### ISSUE TITLE
Conflict with CartFlows plugin on thank you page.

### ISSUE THREAD

**Issue by sarangshahane** [google/site-kit-wp#9276]
## Bug Description

While using the latest version of this plugin with the CartFlows plugin, there is an Fatal/Critical error is getting generated on the thank you page created by CartFlows.
This issue is getting initiated from the WooCommerce action `woocommerce_thankyou` action hook.  In the callback function, there is a check to confirm that the order_key is valid or not. 

Before this check, the $order_key added on line number 94 is returning blank and that what is triggering the Fatal/Critical error.

The code: `$order->key_is_valid( $order_key )`
File location: `includes/Core/Conversion_Tracking/Conversion_Event_Providers/WooCommerce.php`
Line number: `97`

## Steps to reproduce
- Setup a new WordPress plugin
- Install WooCommerce, CartFlows and Google Site Kit
- Import the CSV file of sample products in WooCommerce.
- Activate the CartFlows plugin and Import the ready-made funnel having landing, checkout and thank you page.
- Add a product on the checkout page. [Read more](https://cartflows.com/docs/cartflows-tutorial-video/) to setup the CartFlows.
- Once the flow is setup completely then place an order from the checkout page.
- After placing an order, the user will be redirected to the thank you page where a Fatal/Critical error will be logged in the debug.log file.

1. Go to 'CartFlows Funnels menu'
2. Click on 'The eye icon on the thank you page'
3. Scroll down the page to the end of the page, to see the error.

## Screenshots

- https://bsf.d.pr/i/GcujUP

## Additional Context

 - PHP Version: 8.1.28
 - OS: [e.g. iOS]: Linux
 - Browser: [e.g. chrome, safari]: Chrome
 - Plugin Version: [e.g. 22]: CartFlows: 2.0.10 Google Site Kit: 1.134.0
 - Device: [e.g. iPhone6]: Desktop/Laptop

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Ensure the order key passed to `WC_Order::key_is_valid` is always a string

## Implementation Brief

* [ ] Cast `$order_key` to string https://github.com/google/site-kit-wp/blob/135c0bc8b4640ccaa2f0ff574e785e8217c09698/includes/Core/Conversion_Tracking/Conversion_Event_Providers/WooCommerce.php#L97
* [ ] Merge #9589

### Test Coverage

* No changes necessary

## QA Brief

* This issue should be a harmless change to the WC integration which prevents this notice from being raised
* Basic testing of the WC conversion tracking provider could be done to double check

## Changelog entry

* Prevent a fatal error being raised by the `woocommerce_thankyou` action hook.

**Comment by jamesozzie** [comment]
Thanks for raising this @sarangshahane. With other users also reporting this I'll perform some checks on this and report back to you here with any findings.

**Comment by sahmfz** [comment]
yes, it's happening the same with me.

**Comment by glanglois** [comment]
I have the same issue. Looking forward to a fix release in the future SiteKit plugin updates. Thanks

**Comment by Timbo37** [comment]
Me too!

**Comment by jamesozzie** [comment]
[Another user](https://wordpress.org/support/topic/critical-error-on-thank-you-page-cartflows/) raised this in the support forums.

**Comment by HacMedia** [comment]
We've been having this issue since September. Happy to provide error logs or anything else to help troubleshoot a solution.

**Comment by techanvil** [comment]
Thanks @HacMedia. I'm happy to report we've got a fix in progress which is currently being QA'd. All being well, this should be rolled out in the forthcoming 1.139.0 release.

**Comment by HacMedia** [comment]
Thanks @techanvil - is it possible for us to test that as well?

We've been using a work-around which has not been ideal.

**Comment by kelvinballoo** [comment]
### QA Update ⚠ 

The error is no longer showing. I have 1 question though: ⚠ 


   Referring to the 2nd bullet of the QAB: `Basic testing of the WC conversion tracking provider could be done to double check`
   I am unsure of what to check for the WC conversion tracking. Could we elaborate on this please?


______________________________________________________

Other than that, the main error is no longer showing with the fix on Develop. ✅ 
<Details>

https://github.com/user-attachments/assets/712f3640-f117-4ed8-871e-dba6bd46bd49

</Details>

**Comment by techanvil** [comment]
> Thanks [@techanvil](https://github.com/techanvil) - is it possible for us to test that as well?
> 
> We've been using a work-around which has not been ideal.

Hi @HacMedia, as per the above the issue has been verified in QA and is just undergoing a final related smoke test. The release is due  out today so please bear with us and it will be with you shortly. Thanks for your patience!

**Comment by kelvinballoo** [comment]
### QA Update ✅ 


- The fatal error is no longer happening on develop branch ✅ 

   <Details>

   https://github.com/user-attachments/assets/712f3640-f117-4ed8-871e-dba6bd46bd49

   </Details>

- Regression test on normal WooCommerce `purchase` event tracking done and it's firing accordingly. ✅

   <Details>

  ![Image](https://github.com/user-attachments/assets/e0fce182-b2e2-4bac-ae90-88beb17f5b62)


   </Details>

Moving ticket to approval.
