### ISSUE TITLE
Refactor SetupSuccessSubtleNotification to use the new Notifications datastore

### ISSUE THREAD

**Issue by zutigrm** [google/site-kit-wp#9279]
## Feature Description

This issue should refactor the `SetupSuccessSubtleNotification` so that it uses the new datastore infrastructure to register and queue the notification. It should also incorporate the newly introduced `SubtleNotification` component as a new "layout"

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `SetupSuccessSubtleNotification` component should be refactored so that it is registered and rendered (queued) using the new `core/notifications` datastore. 
* This notification component should not be called directly (i.e. directly in `<SubtleNotifications>`) but only via the generic `getQueuedNotifications` selector.
* The refactored component should not contain any business logic that hides it / prevents it from rendering. This logic should be contained in a callback function defined during registration.
* It should make use of the newly introduced `SubtleNotification` component.

## Implementation Brief

* [x] Update `SetupSuccessSubtleNotification` component
  * Check the `PAXSetupSuccessSubtleNotification` for an example 
  * Include 2 new props - `id` and `Notification`
  * Wrap the component with `Notification` component passed as the prop 
  * Instead of the currently rendered `SubtleNotification` component use the new layout - `assets/js/components/notifications/SubtleNotification.js`, with existing props.
* [x] Update `assets/js/googlesitekit/notifications/register-defaults.js`
  * Register the notification, following the existing patterns already added
  * For `checkRequirements` transfer the existing checks from `SetupSuccessSubtleNotification` component itself - https://github.com/google/site-kit-wp/blob/b6c7c59c9bece36c8b0138d2e3d4f05a2f09479a/assets/js/modules/ads/components/notifications/SetupSuccessSubtleNotification.js#L41
  * For priority, bump it by `10` from the last added subtle notification (not including error ones, which start from `150`).
  * Use `NOTIFICATION_AREAS.BANNERS_BELOW_NAV` for `areaSlug`
  *  Include `isDismissible` property with `true` for value
* [x] Remove `SetupSuccessSubtleNotification` from the `assets/js/components/notifications/SubtleNotifications.js`

### Test Coverage

* Update existing `assets/js/modules/ads/components/notifications/SetupSuccessSubtleNotification.stories.js`

## QA Brief

* Test the Ads Setup Success Notification once thoroughly by really completing the Ads module set up (without PAX enabled).
* For additional retesting, you can use the following URL to trigger the notification: `/wp-admin/admin.php?page=googlesitekit-dashboard&notification=authentication_success&slug=ads`
* Test the dismiss behavior and new GA event being fired on dismissal.
* Also test this notification when the site is in Gathering, Zero data and Unsatisfied Scope alert test. This notification will appear "first" and all others will appear later once this is dismissed.
* Also re-test the PAXSetupSuccessNotification using the following test URL: `/wp-admin/admin.php?page=googlesitekit-dashboard&notification=pax_setup_success_notification&slug=ads`

## Changelog entry

* Refactor Ads notifications to use new notifications infrastructure.

**Comment by eugene-manuilov** [comment]
AC ✔️

**Comment by eugene-manuilov** [comment]
@zutigrm, could you please expand IB to provide more details what exactly needs to be moved to the `checkRequirements` function, what should be deleted from the component, etc.

**Comment by zutigrm** [comment]
@eugene-manuilov This is one is relatively small with one conditional check. I included the line to be transfered, and few minor updates, other than that there is no much to expand

**Comment by eugene-manuilov** [comment]
Ok, thanks, @zutigrm. IB ✔️

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- Tested the Ads Setup Success Notification by completing the Ads module set up (without PAX enabled).
  - Tested the dismiss behavior and new GA event being fired on dismissal.
  - Tested this notification when the site is in Gathering, Zero data and Unsatisfied Scope alert test. This notification appears "first" and all others will appear later once this is dismissed.

- Also re-tested the `PAXSetupSuccessNotification`.  I went through the points above and also made sure that the 'Show me' continued to function and scroll down to the PAX dashboard widget. 


<details>
 <summary>Screencasts</summary>

![image](https://github.com/user-attachments/assets/fdae4347-77b4-405f-9205-1726074ea892)

https://github.com/user-attachments/assets/e82c4c6e-d4c9-4128-b606-fe22ee390edf

https://github.com/user-attachments/assets/2cc7f893-9b42-4982-9020-e9bcf814de8e

https://github.com/user-attachments/assets/3272f7ac-cfe6-4412-b724-5d4a0ab2d47d

https://github.com/user-attachments/assets/4bf61f60-b03d-4d74-9bcd-7fb720f092d8

</details>
