### ISSUE TITLE
GDPR Compatibility

### ISSUE THREAD

**Issue by simea-simea** [google/site-kit-wp#928]
## Feature Description

I would love to see a possibility to be GDPR compliant while using Google's Site Kit. Or at least a clear "How To" Page, where users with no (or small) knowledge of code can follow the steps. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by Zodiac1978** [comment]
Duplicate of #462
