### ISSUE TITLE
Refactor SetupErrorNotification to use the new Notifications datastore

### ISSUE THREAD

**Issue by zutigrm** [google/site-kit-wp#9286]
## Feature Description

This issue is the first issue to refactor an "Error" notification in Site Kit. It should refactor the `SetupErrorNotification` so that it uses the new datastore infrastructure to register and queue the notification. It should also use newer lighter "layout" and "common" components that replace the bloated `BannerNotification` component as per the pattern introduced in #9071.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `SetupErrorNotification` component should be refactored so that it is registered and rendered (queued) using the new `core/notifications` datastore. 
* This notification component should not be called directly (i.e. in `ErrorNotifications`) but only via the generic `getQueuedNotifications` selector.
* The refactored component should not contain any business logic that hides it / prevents it from rendering. This logic should be contained in a callback function defined during registration.
* The component should not use the bloated `BannerNotification` component. Instead, it should be rendered using the new `Notification` component wrapper and a simpler "layout" component that solely encapsulates its structure and design.

## Implementation Brief

* [ ] Update `assets/js/components/notifications/SetupErrorNotification.js`
  * Check the `UnsatisfiedScopesAlert` component for an example 
  * Include 2 new props - `id` and `Notification`
  * Wrap the component with `Notification` component passed as the prop 
  * Remove usage of `BannerNotification` component, and replace it with the new `assets/js/googlesitekit/notifications/components/layout/NotificationError.js` layout using the existing props used to for `BannerNotification`
* [ ] Update `assets/js/googlesitekit/notifications/register-defaults.js`
  * Register the notification, following the existing patterns already added
  * For `checkRequirements` transfer the existing check in `assets/js/components/notifications/SetupErrorNotification.js` - https://github.com/google/site-kit-wp/blob/b6c7c59c9bece36c8b0138d2e3d4f05a2f09479a/assets/js/components/notifications/SetupErrorNotification.js#L51-L54 
  * For priority, bump it by `10 `from the last added error notification (they start from 150)
  * Use `NOTIFICATION_AREAS.ERRORS` for `areaSlug`
* [ ] Remove `SetupErrorNotification` from the `assets/js/components/Header.js` 

### Test Coverage

* There are no stories added for this component, you can include a basic stories coverage following the examples of other error notifications. Some could be extracted from `assets/js/components/notifications/ErrorNotifications.stories.js`

## QA Brief

* When on setup Site Kit page, start the setup, but click `cancel` when on Google OAuth page
* You will be redirected back to the dashboard with error notification. But the first one is not the one that is refactored, to verify that this notification is visible, check it in developer tools:  ![Image](https://github.com/user-attachments/assets/bb5a6fdf-705a-4ebc-86e0-53791875d7a1) The second notification of same type should be there, and should be visible when you delete the first one. Second notification will look like this![Image](https://github.com/user-attachments/assets/8ca4112f-8dcb-41db-91ce-97c3a35de78a)
with title always being `Oops! There was a problem during set up. Please try again.`
* Setup site kit, and start some module setup, like Analaytics, and also cancel the flow, when error is shown on the Dashboard, verify that there is only 1 error notification, the second one should not be shown outside the Splash screen

## Changelog entry

* N/A

**Comment by eugene-manuilov** [comment]
AC ✔️

**Comment by zutigrm** [comment]
@eugene-manuilov thanks. It is relatively small and straightforward component, I expanded a bit where possible.

**Comment by eugene-manuilov** [comment]
Thanks, @zutigrm. IB ✔️

**Comment by zutigrm** [comment]
Moving to MR, since @benbowler you approved CR and it seems you moved it to execution by accident

**Comment by jimmymadon** [comment]
@zutigrm You can keep this in MR since I won't be able to merge this. Instead, I can do a CR for 9283?

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The second notification is visible within developer tools, with title always being `Oops! There was a problem during set up. Please try again.`. When I setup site kit, and setup Analytics, and also cancel the flow, when error is shown on the Dashboard,  and there is only 1 error notification, the second one is not be shown outside the Splash screen. 

<details>
 <summary>Screenshots</summary>

![Image](https://github.com/user-attachments/assets/3b3d554f-3c1a-4f51-bdb0-4bbc75561e59)

![Image](https://github.com/user-attachments/assets/1a20bb47-a815-4834-bfac-6073ca0c25b8)


</details>
