### ISSUE TITLE
AdSense chart number formatting

### ISSUE THREAD

**Issue by OisinOConnor** [google/site-kit-wp#93]
## Bug Description

Numbers on AdSense chart are not formatted for currency on main "Dashboard" tab.

## Steps to reproduce
An Adsense account with a small bit of traffic. Go to main "Dashboard".

## Expected behavior

$, £ etc.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Changelog entry

* Ensure numbers in AdSense charts are properly formatted including their currency.

## Acceptance criteria

* All earnings related numbers should be formatted with correct currency symbols. 

## Implementation Brief
The same way we pass in currency retrieved from the headers when calling readableLargeNumber() in AdSenseEstimateEarningsWidget component used in the AdSense page https://github.com/google/site-kit-wp/blob/develop/assets/js/modules/adsense/dashboard/dashboard-widget-estimate-earnings.js#L244
we need to retrieve currency from period headers in AdSenseDashboardMainSummary component, used in Site Kit dashboard, and include it in the earnings DataBlock https://github.com/google/site-kit-wp/blob/develop/assets/js/modules/adsense/dashboard/dashboard-widget-main-summary.js#L149

**Comment by felixarntz** [comment]
Implementation brief looks good.

**Comment by adamsilverstein** [comment]
This works well in my testing. 

I set up my local and connected to my personal AdSense account. Checking the Site Kit Dashboard the AdSense widget properly shows my currency ("$"), testing previously the currency symbol was missing from the dashboard.  I also tested at various screen sizes and everything looked good.

I was surprised the PR didn't break any visual regression tests, when I checked I found that we don't include the AdSense widget in our Dashboard tests. It would be worth adding it to ensure it remains stable.

**Comment by adamsilverstein** [comment]
Screenshot from testing:

![image](https://user-images.githubusercontent.com/2676022/63534707-0ef83c80-c4cd-11e9-8836-6a14cea9d5cd.png)

The $ symbol in my display is quite large and almost touches the headline above it - perhaps we could use a little more whitespace here?
