### ISSUE TITLE
Update Selection Panels to be in-view aware, and use the `useInViewSelect()` hook where applicable

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#9312]
## Feature Description

Update the Audience and Metric Selection Panels to be in-view aware, and update them to use the `useInViewSelect()` hook in place of `useSelect()` for any selectors which use a resolver or result in a resolver firing via another selector.

This is a followup to 8879, see the comments on that issue for more context: https://github.com/google/site-kit-wp/issues/8879#issuecomment-2332401260

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Audience and Metric Selection Panels should wrap their children in an `InViewProvider` whose in-view state is determined by the open state of the panel.
* Components which are rendered as descendents of the panels should be updated to use the `useInViewSelect()` hook in place of `useSelect()` for any selectors which use a resolver or result in a resolver firing via another selector.
* An observable result of this is that the panels should not trigger any API requests upon page load, unless the request is explicitly determined to be required.
* The flicker that PR https://github.com/google/site-kit-wp/pull/7779 fixed in the Metrics Selection Panel should not return as a result of these changes.
* The panels should in general continue to behave as expected.

## Implementation Brief

* [ ] Update `assets/js/components/KeyMetrics/MetricsSelectionPanel/index.js`, refactor the `SelectionPanel` logic into a new component `assets/js/components/KeyMetrics/MetricsSelectionPanel/Panel.js`, leaving only the `isOpen` logic in this component, importing `InViewProvider` wrapping the new `Panel` component, passing `isOpen` to the `value` prop.
* [ ] Update `assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceSelectionPanel/index.js`, refactor the `SelectionPanel` logic into a new component `assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceSelectionPanel/Panel.js`, leaving only the `isOpen` logic in this component, importing `InViewProvider` wrapping the new `Panel` component, passing `isOpen` to the `value` prop.

**Key Metrics Selection Panel**

 * Update the following `useSelect`'s to use `useInViewSelect`: from within this selection panel and it's children:
    * [ ] *Note: this `useSelect` will be refactored into `assets/js/components/KeyMetrics/MetricsSelectionPanel/Panel.js` above.* https://github.com/google/site-kit-wp/blob/79b4417581b1cca3d718f7e55127681e6e05fc6f/assets/js/components/KeyMetrics/MetricsSelectionPanel/index.js#L49-L59
    * [ ] https://github.com/google/site-kit-wp/blob/79b4417581b1cca3d718f7e55127681e6e05fc6f/assets/js/components/KeyMetrics/MetricsSelectionPanel/MetricItems.js#L48-L55
    * [ ] https://github.com/google/site-kit-wp/blob/79b4417581b1cca3d718f7e55127681e6e05fc6f/assets/js/components/KeyMetrics/MetricsSelectionPanel/CustomDimensionsNotice.js#L54-L71
    * [ ] https://github.com/google/site-kit-wp/blob/79b4417581b1cca3d718f7e55127681e6e05fc6f/assets/js/components/KeyMetrics/MetricsSelectionPanel/Footer.js#L70-L72
    * [ ] https://github.com/google/site-kit-wp/blob/79b4417581b1cca3d718f7e55127681e6e05fc6f/assets/js/components/KeyMetrics/MetricsSelectionPanel/Footer.js#L83-L93
    * [ ] https://github.com/google/site-kit-wp/blob/79b4417581b1cca3d718f7e55127681e6e05fc6f/assets/js/components/KeyMetrics/MetricsSelectionPanel/Footer.js#L95-L97

**Audience Segmentation Panel**

 * Update the following `useSelect`'s to use `useInViewSelect`: from within this selection panel and it's children:
    * [ ] *Note: this `useSelect` will be refactored into `assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceSelectionPanel/Panel.js` above.* https://github.com/google/site-kit-wp/blob/79b4417581b1cca3d718f7e55127681e6e05fc6f/assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceSelectionPanel/index.js#L57-L72
    * [ ] https://github.com/google/site-kit-wp/blob/79b4417581b1cca3d718f7e55127681e6e05fc6f/assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceSelectionPanel/AudienceItems.js#L83-L177
    * [ ] https://github.com/google/site-kit-wp/blob/79b4417581b1cca3d718f7e55127681e6e05fc6f/assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceSelectionPanel/AddGroupNotice.js#L51-L53
    * [ ] https://github.com/google/site-kit-wp/blob/79b4417581b1cca3d718f7e55127681e6e05fc6f/assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceSelectionPanel/AudienceCreationNotice.js#L59-L76
    * [ ] https://github.com/google/site-kit-wp/blob/79b4417581b1cca3d718f7e55127681e6e05fc6f/assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceSelectionPanel/AudienceCreationNotice.js#L81-L92
    * [ ] https://github.com/google/site-kit-wp/blob/79b4417581b1cca3d718f7e55127681e6e05fc6f/assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceSelectionPanel/ErrorNotice.js#L43-L46
    * [ ] https://github.com/google/site-kit-wp/blob/79b4417581b1cca3d718f7e55127681e6e05fc6f/assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceSelectionPanel/Footer.js#L51-L53
    * [ ] https://github.com/google/site-kit-wp/blob/79b4417581b1cca3d718f7e55127681e6e05fc6f/assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceSelectionPanel/Footer.js#L65-L72

### Test Coverage

* No additional test coverage required, confirm that existing tests pass.

## QA Brief

* Test that KM panel and Audience Selection panel continue to work as they were previously without any changes in their behaviour and errors.
* Ensure that the flicker that PR https://github.com/google/site-kit-wp/pull/7779 fixed in the Metrics Selection Panel does not return as a result of these changes.

### QA:Eng

* Ensure that the panels do not trigger any API requests upon page load, unless the request is explicitly determined to be required.

## Changelog entry

* Improve selection panels so that they perform actions only when in view.

**Comment by eugene-manuilov** [comment]
> * An observable result of this is that the Selection Panels should not trigger any API requests upon page load, unless the request is explicitly determined to be required.

@techanvil if the goal is to ensure that no API requests are triggered when the selection panel is closed, then why not to just not render children?

**Comment by techanvil** [comment]
@eugene-manuilov it's a fair question, and one I considered myself. However, as discussed [here](https://github.com/google/site-kit-wp/issues/8879#issuecomment-2334522005), I found it would cause a regression for slower machines as the panel would appear empty while it scrolls into view.

**Comment by eugene-manuilov** [comment]
> I found it would cause a regression for slower machines as the panel would appear empty while it scrolls into view

@techanvil, we can show a progress bar/preview block while data is being loaded, can't we? This is the standard pattern that we use for components that depends on data that loads on demand.

**Comment by techanvil** [comment]
@eugene-manuilov, we do already show the Audience Selection Panel in a [loading state](http://localhost:9001/?path=/story/modules-analytics4-components-audiencesegmentation-dashboard-audienceselectionpanel--loading-no-groups), which is dynamic based on the current cached audience list and audience selection.

So, we've already got that aspect covered in the current implementation. We _could_ restructure things so we have an explicitly defined "loading" component which we switch out for the loaded version when the panel is opened, but I think it probably makes more sense to take the proposed in-view approach.

**Comment by eugene-manuilov** [comment]
Ok, thanks, @techanvil. AC ✔️

**Comment by techanvil** [comment]
Hi @benbowler, this IB is mostly looking good. A couple of points:

- The `useSelect()` calls listed in `MetricsSelectionPanel/index.js` and `AudienceSelectionPanel/index.js` are actually outside of the rendered `SelectionPanel` component, so won't have access to the `SelectionPanel`'s in-view state. This is arguably a shortcoming of the AC which are explicit in specifying the `InViewProvider` should be added to `SelectionPanel`, however the intention is clear that we should be avoiding triggering unwanted API requests on page load. We might want to restructure things so that these outer `useSelect()` calls can also fall within the `InViewProvider`. Alternatively it could be the case that these calls are harmless to keep as they are, if all of the data they retrieve is actually present on page load via preloaded API requests and so forth. Please can you take a look into this and see what looks like the most sensible option?
- Also, once the IB is finalised one way or another, please can you add an estimate :)

**Comment by techanvil** [comment]
Thanks @benbowler! That LGTM. I've tweaked the AC to be less prescriptive about where the `InViewProvider` should reside and made a minor tweak to the IB to clarify the notes about the `useSelect`s.

IB ✅

**Comment by techanvil** [comment]
## QA:Eng ✅ 

### Audience Selection Panel

Confirmed that the GA report to retrieve audience user counts for the selection panel that was previously being made on page load is now only triggered when the panel is opened.

_Page load, current release:_
![Image](https://github.com/user-attachments/assets/df4b98cc-6461-41da-bdc6-9798c573009e)

_Page load, `develop`:_
![Image](https://github.com/user-attachments/assets/f98a42f3-7aa5-4eb0-8a53-0a93b5d7dd49)

### Metric Selection Panel

Confirmed that the request to `sync-custom-dimensions` that was previously being made on page load is now only triggered when the panel is opened.

_Page load, current release:_
![Image](https://github.com/user-attachments/assets/a4a0456b-b69c-40b8-81e9-be546d2754b6)

_Page load, `develop`:_
![Image](https://github.com/user-attachments/assets/f597f0fe-9353-4a2f-b433-6e02cffebffe)

**Comment by mohitwp** [comment]
### QA Update ⚠ 

- Tested on main environment.
- Verified KM and Audience  Segmentation selection panel functionality.
- KM selection panel functionality is working fine.

@ankitrox  When opening the Audience Segmentation selection panel, the following error appears in the console:

`googlesitekit-vendor-56e09129c0c5da07a38b.js:7 Uncaught Error: 'initialFocus' as selector refers to no known node.`

I noticed this error while testing another ticket. @techanvil mentioned that it wasn't related to that ticket, so I created a separate issue for it. -https://github.com/google/site-kit-wp/issues/9758 . This error is showing only on the main and dev environments, so I think the changes introduced in this ticket might be causing it. Could you please have a look?

<details>

![Image](https://github.com/user-attachments/assets/91bd2436-1b13-49eb-af52-5896f24a4cf4)

https://github.com/user-attachments/assets/913564ba-92a3-4112-918b-3c1799caf1bc

</details>

**Comment by techanvil** [comment]
Hi @mohitwp, as the error is present on `main` it won't have been this issue that introduced it, as the changes introduced in this issue (or indeed the current release) are not yet in `main`.

**Comment by techanvil** [comment]
Thanks @mohitwp! I'm not sure how to explain my findings the first time around, I might have simply made a mistake there too.

Anyhow, I can also see it's not present on `1.140.0` and have used `git bisect` to track down the commit that introduced the console error: https://github.com/google/site-kit-wp/commit/c17c02d1eea53ef1af6ecce7a5e3fb86d09a226d

This commit _was_ part of the PR for this issue, so, good call there!

**Comment by techanvil** [comment]
I've created a followup PR to fix the above: https://github.com/google/site-kit-wp/pull/9778

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on main environment.
- Tested key metrics selection panel functionality when `'ConversionReporting'` feature flag is not enabled.
- Tested key metrics selection panel functionality when `'ConversionReporting'` feature flag is enabled.
- Verified initial scope console error is not reproducible now when we open Audience segmentation selection panel.
- Verified that the flicker that PR https://github.com/google/site-kit-wp/pull/7779 fixed in the Metrics Selection Panel does not return as a result of these changes.

<details>

Audience segmentation Selection panel

https://github.com/user-attachments/assets/952a0379-7bf7-43d5-b944-d4c1dd184279

Key metrics selection panel

https://github.com/user-attachments/assets/e263ac03-1a8a-4ebb-8952-324e102dc12e

Flicker issue testing

https://github.com/user-attachments/assets/92cec455-c6fd-4ace-8ee0-a9410e7748d6

</details>
