### ISSUE TITLE
Improve navigation to Publisher Center

### ISSUE THREAD

**Issue by nfmohit** [google/site-kit-wp#9313]
## Feature Description

Links to specific publications in the Publisher Center from the Reader Revenue Manager module (via the `getServiceURL` selector) should be improved so that the user lands on the RRM product page for that publication.

For example, this is what a current link looks like: `https://publishercenter.google.com/?publication=PUBLICATION_ID`

This is what the link should look like: `https://publishercenter.google.com/reader-revenue-manager?publication=PUBLICATION_ID`

[Bug bash task](https://app.asana.com/0/1207894970935603/1208074627052260/f)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Link to a specific Publisher Center publication in the Reader Revenue Manager module should navigate the user to the publication's RRM product page. For example:
	* Current link: `https://publishercenter.google.com/?publication=PUBLICATION_ID`
	* New link: `https://publishercenter.google.com/reader-revenue-manager?publication=PUBLICATION_ID`

## Implementation Brief

* [ ] In `assets/js/modules/reader-revenue-manager/components/dashboard/RRMSetupSuccessSubtleNotification.js`:
	* [ ] Update the `serviceURL` variable definition by passing a `path` property with value `/reader-revenue-manager` to the `getServiceURL` selector.
* [ ] In `assets/js/modules/reader-revenue-manager/datastore/service.js`:
	* [ ] It would be nice to remove the abstraction for passing the publication ID to the `getServiceURL` selector, i.e. remove the `publicationID` parameter that it accepts and update all its usages to pass the publication ID using the `query` parameter. I had originally suggested this abstraction in https://github.com/google/site-kit-wp/issues/8848 but now that I see it being used, I feel it causes unnecessary confusion.

### Test Coverage

* If the `getServiceURL` selector is updated as suggested, update tests for it accordingly.
* Fix any other failing tests.

## QA Brief

* Turn the `rrmModule` feature flag on in the tester plugin.
* Set up Site Kit.
* Set up the Reader Revenue Manager module with a publication that does not yet have completed onboarding.
* When you land on the dashboard with the module connection success notification, click on the CTA to go to the Publisher Center.
	* Verify that it takes you to the RRM product page of the publication (according to the ACs).
* Also test navigation to a specific publication's RRM product page in the Publisher Center from other places, such as:
	* The "_Edit in Reader Revenue Manager_" link in RRM settings view screen.
	* The CTA in the publication onboarding state notification in settings edit/view screen.

## Changelog entry

* Update publication links in the Reader Revenue Manager module to navigate to the RRM product page for the publication.

**Comment by kuasha420** [comment]
IB :heavy_check_mark:

**Comment by nfmohit** [comment]
Note: Changed this to a `P0` as discussed [here](https://app.asana.com/0/0/1208074627052260/1208262114583954/f). CC: @ivonac4
