### ISSUE TITLE
Custom setup experience for users whose sites are not yet live

### ISSUE THREAD

**Issue by marrrmarrr** [google/site-kit-wp#932]
## Feature Description

There are a number of cases where users can't proceed with Site Kit setup due to the state of their site, for example: no pages have been published yet, or the site is behind a login/password. 

Let's customise the setup flow to offer the right information at the right moments and help these users successfully configure Site Kit. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Once a user downloads and activates Site Kit, check if their site is live (e.g. run a request against the site's frontend, check if that returns a non-200 response)
* If the site is not live, replace the contents of the plugins page banner and the setup landing page with custom messaging:

Setup banner on Plugins page: 
_Heading: Congratulations, the Site Kit plugin is now activated._
_Text: It looks like your site is not yet live. To show you stats about how your site is doing, you’ll need to have at least one published page that people can find._ 
_Once you’ve published your first page, we’ll remind you to finish setting up Site Kit._ 
(no CTA button, they can't really do anything here; but there should be a way to dismiss this banner in the top right corner)

Setup landing page: 
_Heading: Site Kit is active. Publish your first page, then you can set up Site Kit._
_Text: It looks like your site is not yet live. To show you stats about how your site is doing, you’ll need to have at least one published page that people can find._ 
_Once you’ve published your first page, we’ll remind you to finish setting up Site Kit._
(no CTA button)

* Detect once the user publishes their first page, 
* Show WP pointer to Site Kit menu item in the left nav (this points to the setup landing page). 
* Revert text on the setup landing page to standard contents + CTA button, so the user can get started on the setup process: 
![setup-landing-page](https://user-images.githubusercontent.com/13304791/69826183-4b48e080-1212-11ea-8281-5660e602ca1b.png)
 

## Implementation Brief

* 

## Changelog entry

*

**Comment by felixarntz** [comment]
This will be combined into #933
