### ISSUE TITLE
RRM setup banner image doesn't appear on some breakpoints

### ISSUE THREAD

**Issue by kelvinballoo** [google/site-kit-wp#9329]
## Bug Description

While testing RRM, I noticed that on Desktop Safari, there are some breakpoints that will not show the image at all. 

- Refer to the video below for the desktop safari  
   <Details>
   
   https://github.com/user-attachments/assets/3d7cdd6a-ee78-404b-aca4-dc18fa04c85d

   </Details>

- I went on to test this on smaller breakpoint on an iPhone 15 Pro max (real) on Safari and Chrome browser. I could not see the graphic   
   <Details>
   Safari
   
   ![IMG_9792](https://github.com/user-attachments/assets/7b37203e-f44b-45c0-b4d9-87658776cbc6)
   
   Chrome
   ![IMG_9793](https://github.com/user-attachments/assets/3ec9db0b-7719-4132-8e7a-5b028db588e4)

   </Details>

## Steps to reproduce

1. Enable RRM feature flag
2. Go to SK dashboard on Desktop Safari (or any of the devices mentioned in the description)to spot the RRM setup banner and resize the window to a smaller breakpoint until the image disappears.

## Additional Context

 - PHP Version: 
 - Browser: [e.g. chrome, safari]
 - Plugin Version: [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When viewing the RRM Setup CTA Banner at narrow breakpoints on the devices/browsers listed above, the banner should be displayed with its graphic below the buttons, as seen for example here in Chrome:

![Image](https://github.com/user-attachments/assets/39024113-7865-4413-9737-619376588ea1)

## Implementation Brief

* [ ] Add `flex: 1` to the `.googlesitekit-setup-cta-banner__svg-wrapper svg` rule:
https://github.com/google/site-kit-wp/blob/ffe957da9e63624807f1c8fedce038486b10548e/assets/sass/components/reader-revenue-manager/_googlesitekit-rrm-setup-cta-banner.scss#L65-L68

### Test Coverage

* No new tests needed.

## QA Brief

* Follow the **steps to reproduce** and verify the graphic does appear below the buttons as expected.

## Changelog entry

* Fix a bug that prevented the appearance of the Reader Revenue Manager setup banner graphic.

**Comment by nfmohit** [comment]
IB ✅

**Comment by kelvinballoo** [comment]
### QA Update ✅ 

- Verified on Desktop Safari (on MacOS Sonoma) across a few breakpoints and the image is appearing accordingly.
   <Details>

   ![Image](https://github.com/user-attachments/assets/f7122ab2-3578-451f-91a8-56ab3d686586)

   ![Image](https://github.com/user-attachments/assets/2e994a5c-3273-453a-86bf-8a2bc7b4a79b)

   </Details>

- Verified on iPhone 15 Pro Max (Safari) and the graphic is showing as expected.
   <Details>

   ![Image](https://github.com/user-attachments/assets/1b693c13-850d-4e03-898d-b74acf6f58d2)

   </Details>

- Verified on other browsers to ensure no regression : Chrome, Firefox, Edge. All are showing the graphic as expected.
   <Details>
   Edge:

   ![Image](https://github.com/user-attachments/assets/9707479a-b2d3-4877-813c-cd07b497ec6f)
   
   Firefox:

   ![Image](https://github.com/user-attachments/assets/51c7302e-3179-4271-81ce-c3c0c0042a44)

   Chrome:

   ![Image](https://github.com/user-attachments/assets/0ef6f1c9-8d27-408a-a5cc-c7acc66992fd)


   </Details>

Moving ticket to approval.
