### ISSUE TITLE
Scaffold Sign in With Google Module

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#9332]
## Feature Description

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A module for Sign in With Google should be created with support for settings.
* The module should only appear/function when the `signInWithGoogleModule` feature flag is enabled. (Similar to how the `rrmModule` behaves, see: https://github.com/google/site-kit-wp/blob/cd076ee37999218bd0e06b5e4ab9a1b3f651c8d2/includes/Core/Modules/Modules.php#L181-L183)
* The module should use the Google logo as its icon, see Figma: https://www.figma.com/design/h9yGR15Pg2DUtgERW4AFAv/Sign-in-with-Google?node-id=27-1075&t=IxHiqEfnlAaEGQ1D-4
* The module should be named "Sign in with Google"
* The module should have a "Beta" and "New" badge next to it in the modules list
* The module should have a description that reads "Improve user engagement, trust, and data privacy, while creating a simple, secure, and personalised experience for your visitors"

## Implementation Brief

* [x] Add a new file for the Sign in with Google module `includes/Modules/Sign_In_With_Google.php`
* [x] Scaffold the module with the minimal number of functions to satisfy `Module_With_Assets, Module_With_Deactivation, Module_With_Settings`. See existing modules like PageSpeed or RRM for examples.
* [x] Add the Google icon as its module icon, and the title/description from the ACs

### Test Coverage

* Add basic tests to ensure module is scaffolded/loaded properly (`tests/phpunit/integration/Modules/Sign_In_With_GoogleTest.php`)
* Add tests to ensure the module is only available when the `signInWithGoogleModule` feature flag is enabled

## QA Brief

* Enable the signInWithGoogle feature flag
* Go to the settings page and open the "connect more services" tab
* Ensure that you see the new module in the list of available modules and it matches the requirements in AC.

## Changelog entry

* Add Sign in with Google module.

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by mohitwp** [comment]
### QA Update ❌ 

- Tested on dev environment.
- Verified the module appear/function only when the `signInWithGoogleModule `feature flag is enabled. 
- Verified that the module uses the Google logo as its icon.
- Verified that the module named "Sign in with Google"
- Verified that the module  have a "Beta" and "New" badge next to it in the modules list
- Verified that the module  have a description that reads "Improve user engagement, trust, and data privacy, while creating a simple, secure, and personalised experience for your visitors".


**_Issue 1 > CTA link graphic symbol is getting little cut from bottom._**

<details>

![image](https://github.com/user-attachments/assets/dab18c2f-e360-4826-88c4-ff1dc04fe238)

![image](https://github.com/user-attachments/assets/b12e314b-c758-4284-ae4d-600fbf370ee6)

</details>

**_Issue 2 > 'New' badge background color is different in Figma._**

<details>

![image](https://github.com/user-attachments/assets/cf6425c5-088a-42f1-99df-67192465bac6)

Figma 

![image](https://github.com/user-attachments/assets/21e0648c-e3a8-4013-b58e-3457bd7578d2)

</details>

**Comment by eugene-manuilov** [comment]
> Issue 1 > CTA link graphic symbol is getting little cut from bottom.

@mohitwp that problem is out of scope for this ticket. If you think we should fix it, then please create a new issue for it.

> Issue 2 > 'New' badge background color is different in Figma.

Updated and created a new PR for it. Once approved and merged, it will be fixed.

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on main environment.
- Verified that beta label background color is now updated and it is same as Figma.
- Verified the module appear/function only when the signInWithGoogleModule feature flag is enabled.
- Verified that the module uses the Google logo as its icon.
- Verified that the module named "Sign in with Google"
- Verified that the module have a "Beta" and "New" badge next to it in the modules list
- Verified that the module have a description that reads "Improve user engagement, trust, and data privacy, while creating a simple, secure, and personalised experience for your visitors".

Note : I will create a separate ticket for the issue 1 reported above.

<details>

![image](https://github.com/user-attachments/assets/be394271-a8ae-44af-84db-ddf8a49fcdc9)

![image](https://github.com/user-attachments/assets/a25ef471-bc50-48bd-8eb3-4ad398961a3d)

</details>
