### ISSUE TITLE
Create Sign in With Google module settings in PHP

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#9333]
## Feature Description

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Support for the Sign in with Google settings [shown in the edit view](https://www.figma.com/design/h9yGR15Pg2DUtgERW4AFAv/Sign-in-with-Google?node-id=27-1075&t=IxHiqEfnlAaEGQ1D-4), should be added eg.:
  * Google Client ID (string, default empty)
  * Text (string, one of `"Sign in with Google"`, `"Continue with Google"`, `"Sign up with Google"`, `"Sign in"` default `"Sign in with Google"`)
  * Theme (string, one of `"light"`, `"neutral"`, `"dark"`, default `"light"`)
  * Shape (string, of of `"rectangular"`, `"pill"`, default `"rectangular"`)

## Implementation Brief

* [x] Ensure `Sign_In_With_Google` module extends `Module_Settings` 
* [x] Create `includes/Modules/Sign_In_With_Google/Settings.php` using another module's settings as a baseline.
* [x] Set `const OPTION = 'googlesitekit_sign-in-with-google_settings';`
* [x] Set the settings/defaults in `get_default()` according to the ACs

### Test Coverage

* Add PHP unit tests to ensure defaults are set correctly

## QA Brief

* This ticket is going to be QA-ed as part of the code review process. There is nothing else to check since there is no user facing changes.

## Changelog entry

* Add Sign in with Google module settings.

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by wpdarren** [comment]
Moved to approval because of no QA, done as part of CR.
