### ISSUE TITLE
Create Sign in With Google Settings module edit screen

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#9334]
## Feature Description

The settings screen for Sign in with Google should be created and available after Sign in with Google is connected. See the Figma designs for this UI in view/edit mode: https://www.figma.com/design/h9yGR15Pg2DUtgERW4AFAv/Sign-in-with-Google?node-id=27-1045&node-type=frame&t=pIlj66YsTMINwgVT-0

**This ticket should implement the edit screen only, with the preview screen implemented in #9477**

It should be only visible when the `signInWithGoogleModule` feature flag is enabled.

### Edit
![Screenshot 2024-10-05 at 12 18 24](https://github.com/user-attachments/assets/7f01a765-f187-4603-bdc5-c9a83ecdf23c)

### Disconnection prompt
![Screenshot 2024-10-05 at 12 18 36](https://github.com/user-attachments/assets/7d8319e6-fbc0-4ace-a235-cd8f33fa78f1)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* **All features in this AC should only be visible when the `signInWithGoogleModule` feature flag is enabled.**
* A new settings component for the Sign in with Google module should appear in Site Kit module settings when Sign in with Google is connected.
* The design should follow the Figma design: https://www.figma.com/design/h9yGR15Pg2DUtgERW4AFAv/Sign-in-with-Google?node-id=27-1045&node-type=frame&t=pIlj66YsTMINwgVT-0
* There should be an additional toggle (on/off) for the "Enable One-Tap" option, see: https://www.figma.com/design/h9yGR15Pg2DUtgERW4AFAv?node-id=27-1045#974060128
* The live preview in the mockup/Figma design does not need to be implemented in this issue; that will come later.
* The module disconnection screen should use the text from: https://www.figma.com/design/h9yGR15Pg2DUtgERW4AFAv/Sign-in-with-Google?node-id=247-1364&t=pIlj66YsTMINwgVT-4

## Implementation Brief

* [x] Update `includes/Modules/Sign_In_With_Google/Settings.php`:
   * Add support for a new boolean, settings key `oneTapEnabled`.
   * Set the default for this key to `false`, in the array returned by `get_defaults`.
* [x] Update `assets/js/modules/sign-in-with-google/datastore/base.js`, adding the new key to the `settingsSlugs` array.

* [x] Create a new `assets/js/modules/sign-in-with-google/components/settings/SettingsForm.js`, based on other `SettingsForm` components ([eg.](https://github.com/google/site-kit-wp/blob/db3699f1b5503195665a0e84a976d621bd44f3c7/assets/js/modules/analytics-4/components/settings/SettingsForm.js)):
   * **Client ID**
      * Use the existing `assets/js/modules/sign-in-with-google/components/common/ClientIDTextField.js` component created in #9336 
   * **Button text, Button theme and Button shape**
      * Create new components for each of these fields `{Camel case title}Select` in the modules `common` folder.
      * Within each fields component, wrap a `Select` Material component, getting the options from [these branding options](https://developers.google.com/identity/branding-guidelines#expandable-1)
      * Get the field value using the `get*` selector for each setting.
      * `onChange` update the settings by dispatching the `set*` action for each setting.
   * **Enable One-Tap**
      * Create a new component `enableOneTapToggle` in the modules `common` folder.
      * Wrap a `Switch` component.
      * Get the field value using the `getEnableOneTap` selector.
      * `onChange` update the settings by dispatching the `setEnableOneTap` action.

* [x] Create a new `assets/js/modules/sign-in-with-google/components/settings/SettingsEdit.js`, based on other `SettingsEdit` components ([eg.](https://github.com/google/site-kit-wp/blob/db3699f1b5503195665a0e84a976d621bd44f3c7/assets/js/modules/analytics-4/components/settings/SettingsEdit.js)):
   * Get the `isDoingSubmitChanges` state from the `MODULE_SIGN_IN_WITH_GOOGLE` store, using the `isDoingSubmitChanges` selector.
   * If `isDoingSubmitChanges` is true, return early rendering a `ProgressBar` component.
   * Otherwise, return the new `SettingsForm` component wrapped in a div with the classes `googlesitekit-setup-module googlesitekit-setup-module--sign-in-with-google`.
   * Add a placeholder div for the Preview iframe which will be added in a later ticket but still should be styled as a second column on the settings edit screen.

* [x] Create a new file `assets/sass/components/sing-in-with-google/_googlesitekit-sign-in-with-google-settings-module.scss` and style the settings edit screen [based on the Figma designs](https://www.figma.com/design/h9yGR15Pg2DUtgERW4AFAv/Sign-in-with-Google?node-id=27-1045&node-type=frame&t=Z5mbre5pmZcLC8ns-0)

 * [x] Add `sign-in-with-google` to the `BETA_MODULES` and `NEW_MODULES` array constants to show the Beta and New badges in the module header.
 * [x] Update the module registration:
    * Change the `SettingsEditComponent` prop to return the newly created `SettingsEdit` component.
    * Add the [features list from the Figma designs](https://www.figma.com/design/h9yGR15Pg2DUtgERW4AFAv/Sign-in-with-Google?node-id=247-1364&node-type=frame&t=Z5mbre5pmZcLC8ns-0) to the `features` prop so that they show in the disconnect modal.
    * Wrap the module registration call in a check for the feature flag using `isFeatureEnabled('signInWithGoogleModule')`, so that it is only registered if this feature flag is enabled.

### Test Coverage

* Create new stories for `SettingsForm` and `SettingsEdit` components within this modules.
* Update `tests/phpunit/integration/Modules/Sign_In_With_Google/SettingsTest.php` tests to test new settings key.

## QA Brief

* Enable the `signInWithGoogle` feature flag.
* Setup the new Sign in with Google module.
* Go to the plugin settings and click Edit to view the module settings edit screen.
* Test editing the module settings.

*Note*
 * *The settings view screen will be implemented in another ticket*.
 * *The SiwG button preview frame will be implemented in another ticket*.

## Changelog entry

* Implement the ability to edit Sign in With Google settings.

**Comment by benbowler** [comment]
Adding #9336 as a blocker because it adds a field we will need here.

**Comment by tofumatt** [comment]
The "Enable One-tap" option was added later in the process so it wasn't originally in the Design Doc or Figma mocks; this also means it wasn't in the settings we added so far.

Can you add a bit to the IB about adding that extra setting to SiwG's settings/datastore so it's available? It should just be a binary value with a default of `false` for now.

If you think that'll expand the issue too much we can remove it from the ACs and just add it later in #9484, but if you think it'll be small we can do it here 🙂

**Comment by tofumatt** [comment]
IB ✅ 

I'll remove #9484 in that case 🙂

**Comment by mohitwp** [comment]
### QA Update ❌ 

- Tested on dev environment.
- Verified edit screen with Figma design.

@benbowler 

**_Issue 1: Users can save the Client ID field in the edit settings by simply entering spaces in the client ID field._**

<details>

![Image](https://github.com/user-attachments/assets/548b5e70-bccb-43f9-9f13-b379da67b7b2)

</details>

**_Question: We have the "Anyone can register WP setting" option in the view mode for WP settings, but there is no reference to it in the edit settings mode. Is this expected, considering that this option will be managed on the WP settings page?_**

<details>

![Image](https://github.com/user-attachments/assets/1ea341d4-1aac-4d7c-bc2d-a0d5973518b0)

</details>

**Comment by benbowler** [comment]
Thanks @mohitwp, we didn't plan any validation in the AC/IB here, @tofumatt, what do you think RE validation, we could add validation for the basic structure of the clientID simply.

To your questions @mohit, the "Anyone can register" is a WordPress core setting so the user has to go to the WordPress settings to change this. We explain this in the yellow banner in the screenshot you sent.

**Comment by tofumatt** [comment]
@benbowler Right, we should at least do a regex validation—in fact, I don't think a client ID would ever have spaces in it, so even just "no whitespace" is a good start.

There's no actual spec for what a client ID _should_ look like—there's what is there now, but that could change, so I didn't want to be overly prescriptive about it and have a change in client IDs break things.

But adding some very basic validation here (no whitespace, at least) is a good idea. If you have something more specific in mind go for it and we can discuss it in the PR 👍🏻

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on main environment.
- Verified edit screen with Figma design.
- Verified issue reported above is resolve now and validation for client ID are implemented.
- Verified Sign In With Google module edit screen functionality and design as per AC and Figma.

<details>

https://github.com/user-attachments/assets/983f6086-adcb-436b-8fdd-0bedec398d07

</details>
