### ISSUE TITLE
Add support for rendering Sign in With Google button on WordPress login page

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#9337]
## Feature Description

When Sign in with Google is activated and fully setup, a "Sign in with Google" button should appear on the WordPress login page (eg. `/wp-login.php`).

This button should reflect the styles/options the user has chosen in their Sign in with Google Module settings and allow the user to sign in to their WordPress site using their Google account.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The button should only appear on the WordPress login page when the `signInWithGoogleModule` feature flag is enabled.
* The button should only appear on the WordPress login page when the Sign in with Google module is activated (eg. a Client ID has been provided and the user has completed setup of the module)
* The button should only appear when the site is using HTTPS. If a non-HTTPS url is active, the button should not appear.
* The button should be [styled according to the styling options](https://developers.google.com/identity/branding-guidelines) the user has selected in the [Sign in with Google module settings](https://github.com/google/site-kit-wp/blob/5e4019fe8270bf5735289edcc68367033b26390e/includes/Modules/Sign_In_With_Google/Settings.php#L26-L36).
* Clicking the button should activate the Sign in with Google flow, allowing the user to sign in to the WordPress site using their Google Account (#9338, #9339)
* The Sign in with Google button should be placed either above the username field or below the log in button.

![Image](https://github.com/user-attachments/assets/eb1e76cd-b152-4fbd-9447-3c8106063d53)

## Implementation Brief

* [x] Update `includes/Modules/Sign_In_With_Google.php`:
   * Create a new method `render_signin_button`, in this method:
      * Get the `clientID` and style settings using `$this->get_settings()`.
      * Return early without rendering, if any of these cases are met:
         * The following statement `if ( substr( wp_login_url(), 0, 5) !== 'https') {`.
         * The `clientID` setting is null.
      * Use the redirect URL defined in #9338/#9339 and get the full URL using `site_url()`.
      * Render the [SiwG button code](https://developers.google.com/identity/gsi/web/guides/display-button#html)
         * Wrapping the `clientID` in `esc_attr()`
         * Wrapping the redirect URL in `esc_url`
      * Pass the `clientID`, redirect URL and style settings to the following tag:
      * ```
        <script src="https://accounts.google.com/gsi/client" async></script>
        <div id="g_id_onload"
            data-client_id="YOUR_GOOGLE_CLIENT_ID"
            data-login_uri="https://your.domain/your_login_endpoint"
            data-auto_prompt="false">
        </div>
        <div class="g_id_signin"
            data-type="standard"
            data-size="large"
            data-theme="outline"
            data-text="sign_in_with"
            data-shape="rectangular"
            data-logo_alignment="left">
        </div>
         ```
   * Update the `register` method, adding an action on the `login_form` hook to call the new method above `add_action( 'login_form', array( $this, 'render_signin_button' ) );`

 * [x] Create a new file `assets/sass/components/sign-in-with-google/_googlesitekit-wp-login-button.scss`:
    * Use the flexbox order property to make sure the Sign in with Google button displays above the username field within the signin form.

### Test Coverage

* Update `tests/phpunit/integration/Modules/Sign_In_With_GoogleTest.php` adding tests to cover each case in the AC where the login hook should and should not be registered.

## QA Brief

* Set up SK on https, enable the `signInWithGoogle` feature flag, enable the SiwG module and enter your clientID. Now open the WordPress login page in an incognito window and you will see the following new button:
* ![Image](https://github.com/user-attachments/assets/d1381a89-0293-475d-826e-b16a1cbd0e83)
* Confirm that the button does *not* render in these cases:
   * The site is not on https.
   * The SiwG module is not active or the clientID is not set
* Confirm the style options correctly update the button as it's displayed.

## Changelog entry

* Add the Google sign-in button to the login screen.

**Comment by benbowler** [comment]
@tofumatt this is ready for IBR

**Comment by eugene-manuilov** [comment]
> * Create a new method `register_button_on_login_page`, in this method:

@benbowler, let's better use the `render_signin_button` name.

> ... wrapping the `clientID` in `esc_html()` ...

Use `esc_attr` instead, plus the redirect URL should be escaped using `esc_url`.

> * Wrap the register call in `Feature_Flags::enabled('signInWithGoogleModule')` to confirm it will only show with the feature flag enabled.
> * Wrap the register call in `if ( substr( wp_login_url(), 0, 5) === 'https') {` so that the button will only be registered on secure sites.
> * Wrap the register call in a check, confirming the `clientID` setting is not null.

These checks should be moved to the render button function that should return early if any of these conditions fail.

**Comment by benbowler** [comment]
Good point @eugene-manuilov, updated.

**Comment by eugene-manuilov** [comment]
Thanks, IB ✔

**Comment by mohitwp** [comment]
### QA Update ⚠ 

- Tested on main environment.
- Verified that the button should only appear on the WordPress login page when the `signInWithGoogleModule `feature flag is enabled.
- Verified that the button  only appear on the WordPress login page when the Sign in with Google module is activated (eg. a Client ID has been provided and the user has completed setup of the module)
- Verified The button appear only when the site is using HTTPS. If a non-HTTPS url is active, the button not appear.
- Verified that the button styled according to the styling options the user has selected in the [Sign in with Google module settings]
- Verified The Sign in with Google button  placed above the username field. 

@benbowler 

**_Q-1) 
Clicking the button shows Access blocked : authorisation error . Is it because following PR's are not merged yet ? (https://github.com/google/site-kit-wp/issues/9338, https://github.com/google/site-kit-wp/issues/9339)_**

**_Q-2) If the Client ID is not valid (not as per standard format), should we still be showing the 'Sign In with Google' button on the WordPress login page? Is this expected?_**

<details>

![Image](https://github.com/user-attachments/assets/ece433fe-00c6-4fff-943f-5bb75e7cebde)

![Image](https://github.com/user-attachments/assets/792337f6-5e44-4ce6-9a82-6a63f38b62ea)

</details>


**PASS CASES** 

<details>

https://github.com/user-attachments/assets/0b4e572d-5eb2-4967-818e-0f7bd0cb672d

https://github.com/user-attachments/assets/d26d95ce-3392-4876-85b6-210b30b8192f

https://github.com/user-attachments/assets/5e014dce-5876-4542-bb27-7cc7511fe46d

https://github.com/user-attachments/assets/233c978f-b7b8-413a-ab5a-9adfcc8d4f31

</details>

**Comment by benbowler** [comment]
Hey @mohitwp,

Q-1)
You are correct, this ticket is just to show the button, https://github.com/google/site-kit-wp/issues/9338 and https://github.com/google/site-kit-wp/issues/9339 will make it work.

Q-2)
Our validation is very simple and just prevents invalid characters to be included in client ID. Base on the design doc we're not hand holding the user too much on the client ID, relying on them for it to be correct. Without adding extra checking for a valid client ID via the API it is correct how it works currently.

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on main environment.
- Verified that the button should only appear on the WordPress login page when the `signInWithGoogleModule `feature flag is enabled.
- Verified that the button  only appear on the WordPress login page when the Sign in with Google module is activated (eg. a Client ID has been provided and the user has completed setup of the module)
- Verified The button appear only when the site is using HTTPS. If a non-HTTPS url is active, the button not appear.
- Verified that the button styled according to the styling options the user has selected in the [Sign in with Google module settings]
- Verified The Sign in with Google button  placed above the username field. 

<details>

https://github.com/user-attachments/assets/0b4e572d-5eb2-4967-818e-0f7bd0cb672d

https://github.com/user-attachments/assets/d26d95ce-3392-4876-85b6-210b30b8192f

https://github.com/user-attachments/assets/5e014dce-5876-4542-bb27-7cc7511fe46d

https://github.com/user-attachments/assets/233c978f-b7b8-413a-ab5a-9adfcc8d4f31

</details>
