### ISSUE TITLE
Extend endpoint/PHP logic to create/sign in user with email from token

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#9339]
## Feature Description

The code/endpoint that handles user login from Sign in with Google (#9338) should be extended to actually create/sign in the user.

This endpoint will, in the following order:

* sign in the user if an existing user account with a Google ID exists that matches the sign-in token's Google ID
* sign in the user if a user account with an email address matching their Google-supplied email address exists, and save their Google ID as being associated with their WordPress user ID.
* create + sign in the user if there is no user/email found and the setting to allow new users is enabled (this setting will depend on the “Anyone can register” setting in WordPress). This step should also save their Google ID as being associated with their WordPress user ID.

After initial sign-in or account creation, we will store the user's Google ID https://docs.google.com/document/d/1U-4YRbOUSOeCYJ6von3lw89WMma8r_mDSKN77jkKGj4/edit?resourcekey=0-QTyKs8YzLSz4z89q5fozbw&disco=AAABWwuDKUA and _not_ their email address. Subsequent 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The endpoint that accepts a POST request from the SiwG request in #9338 should be extended to either:
  1. sign in the user if an existing user account with a Google ID exists that matches the sign-in token's Google ID
  2. sign in the user if a user account with an email address matching their Google-supplied email address exists, and save their Google ID as being associated with their WordPress user ID.
  3. create + sign in the user if there is no user/email found and the setting to allow new users is enabled (this setting will depend on the “Anyone can register” setting in WordPress). Their WordPress username/email should match their Google email. This step should also save their Google ID as being associated with their WordPress user ID. The user's role should match the default role used to create a user. Any fields from their Google account that match up to a WordPress user's fields (eg. "name", etc.) should be populated in the WordPress user account.
  4. if none of the above criteria are met: redirect the user back to the WordPress login page and display an error stating "Could not sign in using your Google account."
* If a new user account is created, a randomised, secure/difficult-to-guess password should be supplied so the user account cannot be accessed otherwise. If an existing account is used, no password change should be made.
* A user's Google email should only be used to "link"/"find" their WordPress account or create a new account (if enabled). Afterward, a value should be added to that user's meta attributes using a new Site Kit field that associates that user with a Google ID (found in the token values in #9338). Subsequent logins should rely on the Google ID and not the email address, as the email address can change.

## Implementation Brief

**Update the auth/google route**

* [ ] Update `includes/Modules/Sign_In_With_Google.php`:
   * [x] Add a new constant: `const SIGN_IN_WITH_GOOGLE_USER_ID_OPTION = 'googlesitekitpersistent_sign_in_with_google_user_id';`
   * [x] Create a new protected method `login_user`, implementing the following code, passing a single property `$user`:
   * ```php
      wp_set_current_user( $user->ID, $user->user_login );
      wp_set_auth_cookie( $user->ID ); 
      do_action( 'wp_login', $user->user_login, $user );
      ```
   * [ ] Create a new protected method `login_error_redirect`, implementing the following code:
   * ```php
       wp_safe_redirect( add_query_arg( 'sign_in_with_google_error', true, wp_login_url() );
       exit;
      ```
   * [x] Update the `handle_google_auth` method in `includes/Modules/Sign_In_With_Google.php` implemented in #9338:
      * If `$error` is truthy, return a call to the method `login_error_redirect` created above.
      * Otherwise, take the `$response` and get the user id and email:
         * `$google_user_id = $payload['sub'];`
         * `$google_user_email = $payload['email'];`
      * **Match existing user by Google user_id** 
      * Check for a user who has a matching Google user_id stored in usermeta:
         * ```php
           $existing_users = get_users(
				array(
				 'meta_key' => self::SIGN_IN_WITH_GOOGLE_USER_ID_OPTION,
				 'meta_value' => $google_user_id,
				 'number' => 1
				)
			   )
            ```
         * Check if $existing_users[0] is a valid WP_User with an `ID` and `user_login`, if so, log the user in by returning, calling the new `login_user`, method implemented above, passing `$existing_users[0]`.
      * Otherwise continue:
      * **Match new user by Google/WP email** 
      * Check for a a user matching the Google email in the users table: `$existing_user = get_user_by( 'email', $email );`
         * If a user is returned, store the Google user_id in the usermeta for this user: `add_user_meta( $existing_user->ID, self::SIGN_IN_WITH_GOOGLE_USER_ID_OPTION, $google_user_id, true )` *Note passing true to the forth prop makes sure this key is unique for this user.*
         * Log the user in by returning and calling the new `login_user`, method implemented above, passing `$existing_user`.
      * Otherwise continue:
      * **Create new user** 
      * Check if "Anyone can register" setting is enabled using `$registration_open = get_option( 'users_can_register' )`.
         * If so, create a new user: `$new_user_id = wp_create_user( $google_email, wp_generate_password(), $google_email );`.
         * Store the Google user_id in the usermeta for this user: `add_user_meta( $new_user_id, self::SIGN_IN_WITH_GOOGLE_USER_ID_OPTION, $google_user_id, true )`.
         * Log the user in by returning and calling the new `login_user`, method implemented above, passing `get_user_by( 'id', $new_user_id )`.
      * **Error, redirect to login** 
      * If the code path reaches this point with none of the above conditions met, return a call to the `login_error_redirect` method implemented above.

**Show error on wp-login page**

 * [x] Update `includes/Modules/Sign_In_With_Google.php`:
    * Add a new method `render_sign_in_errors` taking one prop, `$errors`:
       *  If the GET variable `sign_in_with_google_error` is truthy, update the provided WP_Errors instance adding the custom login error `$errors->add('sign_in_with_google_error', 'Could not sign in using your Google account.');`.
    * Update the `register` method, registering the hook on `wp_login_errors`: `add_filter( "wp_login_errors", array($this,"render_sign_in_errors") );`

### Test Coverage

* Update `tests/phpunit/integration/Modules/Sign_In_With_GoogleTest.php`, adding tests for the three new methods added in this ticket as well as the new hook.

## QA Brief

* You can now Sign in with Google!
* To test, make sure your test site has https enabled, enable the `signInWithGoogle` feature flag and connect the Sign in with Google module with a valid client ID.
   * To create a valid client ID, login to the [Google Cloud Console and create an Oauth client ID](https://console.cloud.google.com/apis/credentials), make sure that the full redirect URL is set up as the Authorised Redirect URI:
   * ![Image](https://github.com/user-attachments/assets/8f2f36b5-98ff-4c7b-ac88-223dbde12013)
   * **Important** the `action` shown above should be `googlesitekit_auth`
* Then verify:
  * Test that you can sign in using a google account of existing user.
  * Test that you get redirected to the correct page after signing in if the login url contained the redirect query argument:
    * Add `redirect_to=` argument to the login URL using one of your site pages and ensure that you get redirected to that page after signing in.
  * Test that non-existing users can't register if the "Anyone can register" setting is disabled.
  * Test that non-existing users can register if the "Anyone can register" setting is enabled.
  * Test that non-existing users get redirected to the correct page after registration.
  * Repeat the same using multisite environment and a subsite taking in account the following:
    * If registration is disabled in the network settings, then existing users shouldn't be able to log in into sites that they are not added to. And opposite behavior: if registration is enabled in the network settings, then existing users should be automatically added to other sites after signing in.
    * When a non-existing user registers, they should be automatically added to the current site.
  * When a user is registered, verify that you and the site admin receive emails.

## Changelog entry

* Implement Sign in with Google token response login handling.

**Comment by tofumatt** [comment]
IB ✅

**Comment by mohitwp** [comment]
### QA Update ⚠ 

@eugene-manuilov I have a question related to point mentioned in QAB-

`Add redirect_to= argument to the login URL using one of your site pages and ensure that you get redirected to that page after signing in.`

I manipulated the URL on the WordPress login page by adding an encoded URL of a site page. For example:
https://dynamic-3b4bc0.instawp.xyz/wp-login.php?redirect_to=https%3A%2F%2Fdynamic-3b4bc0.instawp.xyz%2Fhello-world%2F

However, after signing in with SIWG, the user is redirected to the WordPress admin dashboard instead of the page specified in the encoded URL. Could you confirm if my understanding of this behavior is incorrect?

<details>


https://github.com/user-attachments/assets/b87827e6-8661-4f9b-98eb-763d3bb798da

</details>

**Comment by eugene-manuilov** [comment]
@mohitwp, i have just checked on my end and i have been redirected to the correct URL. Can you try again but not in the private mode?

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on main environment.
- Verified all the points mentioned under AC.
- Verified SIWG setup and login functionality on single site setup.
- Verified  that usercan sign in using a google account of existing user.
- Verified that user get redirected to the correct page after signing in if the login url contained the redirect query argument:
- Added redirect_to= argument to the login URL using one of site pages and verified that user get redirected to that page after signing in.
- Verified that non-existing users can't register if the "Anyone can register" setting is disabled.
- Verified that non-existing users can register if the "Anyone can register" setting is enabled.
- Verified that non-existing users get redirected to the correct page after registration.
- Repeated the same test on multisite environment.
   -- Verified If registration is disabled in the network settings, then existing users not be able to log in into sites that they are not added to. 
   --Verified if registration is enabled in the network settings, then existing users  automatically added to other sites after signing in.
Verified When a non-existing user registers, they automatically added to the current site.
Verified when a user is registered, then user and the site admin receive emails.

<details>

_Single site environment_

https://github.com/user-attachments/assets/a49f72bd-94bd-4190-bf3b-840abe568448


_Redirect URL_

https://github.com/user-attachments/assets/17ed632b-84b1-47e4-be15-24822185ec5c


_Multisite environment_


https://github.com/user-attachments/assets/2d305ada-24ca-48b8-a286-e19dfbdce145

</details>
