### ISSUE TITLE
Include detected and lost events endpoints and corresponding datastore actions

### ISSUE THREAD

**Issue by 10upsimon** [google/site-kit-wp#9343]
## Feature Description

`Analytics_4` module should be updated to include new REST endpoints for removing the `googlesitekit_conversion_reporting_detected_events` and `googlesitekit_conversion_reporting_lost_events` transients. Also `conversion-reporting` datastore  should be updated with corresponding actions to invoke these endpoints.

See [Implementation - New Events Detection Following Initial Events Detection](https://docs.google.com/document/d/1JvA3LK5SNfGH2o4OVnwjDdsAFuQMA9ZJj0T09RTqoy8/edit?pli=1&resourcekey=0-e90bcFGzAI6NhNu_D5i6hQ#heading=h.5ujxp9w8p70s) and [Implementation - Datastore Partial ](https://docs.google.com/document/d/1JvA3LK5SNfGH2o4OVnwjDdsAFuQMA9ZJj0T09RTqoy8/edit?pli=1&resourcekey=0-e90bcFGzAI6NhNu_D5i6hQ#heading=h.7e6inft5e4wy) sections of the design doc

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* `Google\Site_Kit\Modules\Analytics_4` class is updated to include 2 new REST endpoints:
  * `POST:clear-conversion-reporting-new-events` 
    * Deletes the `googlesitekit_conversion_reporting_detected_events` transient. 
  * `POST:clear-conversion-reporting-lost-events` 
    * Deletes the `googlesitekit_conversion_reporting_lost_events` transient
* As addition to that `conversion-reporting` datastore partial is updated with 2 new actions
  * `dismissNewConversionReportingEvents` 
    * Invokes `POST:clear-conversion-reporting-new-events` endpoint
  * `dismissLostConversionReportingEvents` 
    * Invokes `POST:clear-conversion-reporting-lost-events` endpoint

## Implementation Brief

* [x] Update `Google\Site_Kit\Modules\Analytics_4` class
  * In `get_datapoint_definitions` method, include the 2 new endpoints listed in the AC if `conversionReporting` feature flag is enabled
    * For `service` leave an empty array, see for example definition of `POST:set-google-tag-id-mismatch`
  * In `create_data_request` method
    * Include the same endpoints, and delete the transient specified in AC for each endpoint
    * You can see similar example in `POST:set-google-tag-id-mismatch` endpoint
* [x] Update `assets/js/modules/analytics-4/datastore/conversion-reporting.js`
  * Add 2 `createFetchStore` for   `dismissNewConversionReportingEvents` and `dismissLostConversionReportingEvents` that will invoke their endpoints as listed in AC. API parameters would be for example: `('modules', 'analytics-4', 'clear-conversion-reporting-new-events')`, and so on for second endpoint
  * Include `dismissLostConversionReportingEvents` and `dismissNewConversionReportingEvents` actions which will invoke their respective fetch stores

### Test Coverage

* Update `tests/phpunit/integration/Modules/Analytics_4Test.php`
  * Expand on datapoints in `test_get_datapoints` and `test_get_datapoints__audienceSegmentation` test cases
* Update `assets/js/modules/analytics-4/datastore/conversion-reporting.js` to include basic coverage for the 2 new actions 

## QA Brief

* Enable the `conversionReporting` feature flag.
* Run the following actions in the developer console, confirming there are no console errors:
   * `googlesitekit.data.dispatch('modules/analytics-4' ).dismissNewConversionReportingEvents()`
   * `googlesitekit.data.dispatch('modules/analytics-4' ).dismissLostConversionReportingEvents()`

## Changelog entry

* Implement the ability to dismiss detected and lost events information in the Analytics module.

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Tested when `conversionReporting `feature flag not enabled.
- Tested when `conversionReporting `feature flag is enabled.
- Run the following actions in the developer console when `conversionReporting `feature flag is enabled and verified that  there are no console errors:
- --`googlesitekit.data.dispatch('modules/analytics-4' ).dismissNewConversionReportingEvents()`
- -- `googlesitekit.data.dispatch('modules/analytics-4' ).dismissLostConversionReportingEvents()`

<details>

**`googlesitekit.data.dispatch('modules/analytics-4' ).dismissNewConversionReportingEvents()`**


![Image](https://github.com/user-attachments/assets/37b1a6ee-6f9b-455f-8df9-67fe897e01b4)


**`googlesitekit.data.dispatch('modules/analytics-4' ).dismissLostConversionReportingEvents()`**

![Image](https://github.com/user-attachments/assets/7a394816-1011-40fd-9518-8113f12c7223)

**_When conversionReporting feature flag not enabled_**

![Image](https://github.com/user-attachments/assets/5a693633-cfb9-4bcb-b240-f92485e07919)

</details>
