### ISSUE TITLE
"Top content” OAuth flow UX experience

### ISSUE THREAD

**Issue by kelvinballoo** [google/site-kit-wp#9350]
## Feature Description

This came up when testing https://github.com/google/site-kit-wp/issues/8154
The QA brief for that issue can be used as steps to reproduce.

**ITEM 1:**
After I click cancel, the OAuth error variant of the Error Modal does not display straightaway. It will not load until I scroll down to the tiles section. 
Refer to as from 1 minute mark in the video in the Details section.

<Details>

https://github.com/user-attachments/assets/f4fccad1-406d-4c92-aae4-5750091c134e

</Details>

I think we possibly need to anchor the scroll to that tile section so that the error modal appears straightaway.

**ITEM 2:**

This is linked to number 1. When I cancelled the flow, I go to the page where I see a 'Success' message. Again, you can refer to the 1 minute mark in the video above. 
This is due to the success message initially but it just feels weird but maybe this will not be a concern if we auto scroll to the tiles section, if we decide to fix it that way for item 1.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* If an OAuth error occurs when attempting to create the custom dimension from the "Top content" metric area in an audience tile, upon returning to Site Kit:
  * The page should scroll down to the Audiences Widget Area.
  * The Error Modal for the OAuth error should appear.

## Implementation Brief

- Once https://github.com/google/site-kit-wp/pull/9327 is merged:
  - [x] Create an `errorRedirectURL` constant, the value of which is `global.location.href` with the query arg `widgetArea` appended. The value of the `widgetArea` arg should be `AREA_MAIN_DASHBOARD_TRAFFIC_AUDIENCE_SEGMENTATION`.
  - [x] Include `errorRedirectURL` in the options passed to `setPermissionScopeError()` in the `AudienceTilePagesMetric` component, at the same level as `redirectURL`:
https://github.com/google/site-kit-wp/blob/10394a12d82f24b0a44ca3358d091a07f6b37873/assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceTilesWidget/AudienceTile/AudienceTilePagesMetric.js#L142-L155

### Test Coverage

* Update/fix any failing tests.

## QA Brief

* Setup your audiences then set up a missing required scope error like so:
   * Remove the `...additional_auth_scopes` row from your wp_usermeta
   * Archive the WordPress Post Type custom dimension from your Analytics property
   * Sync the custom dimensions by running `googlesitekit.data.dispatch( 'modules/analytics-4' ).fetchSyncAvailableCustomDimensions()` in the developer console
 * After refreshing you should now see the "No data to show" error state in the Top content section of the Audience tiles.
 * Click the "Update" button to start the OAuth flow
 * Select your user but click "Cancel" to simulate an OAuth error
 * When you return to the plugin the app should scroll down to the Visitor Groups section and you should immediately see the error modal
*Note: these steps can be seen in the video in this ticket description above.*

## Changelog entry

* Fix OAuth error handling when attempting to create a custom dimension from the "Top content" metric area in an Audience Tile.

**Comment by nfmohit** [comment]
IB ✅

**Comment by kelvinballoo** [comment]
### QA Update ✅ 

Tested and if an OAuth error occurs when attempting to create the custom dimension from the "Top content" metric area in an audience tile, upon returning to Site Kit:

- The page scrolls down to the Audiences Widget Area ✅ 
- The Error Modal for the OAuth error appears accordingly ✅  

Results are as expected.
Moving ticket to Approval.

<Details>

https://github.com/user-attachments/assets/b9f01dd5-94a4-4eed-ac52-b6d6dbe042a3

https://github.com/user-attachments/assets/392b721f-a550-495a-b915-33472130fc74

Test 2:

https://github.com/user-attachments/assets/0af2e99b-4d60-485c-9e44-61a75e1e85cd

</Details>

**Comment by tofumatt** [comment]
Note: this was actually released in `1.137.0`, but was accidentally tagged with the `1.138.0` release, so it will appear in `1.138.0`'s changelog/release notes.

Since it's behind a feature flag that hasn't been rolled out yet, this isn't a big deal, as existing `1.137.0` users won't get this feature anyway, but just noting it here for clarity 🙂
