### ISSUE TITLE
Re-check `registerDefaults` of the notification API if there is any resolver that needs to be resolved

### ISSUE THREAD

**Issue by zutigrm** [google/site-kit-wp#9351]
## Feature Description

Go over the `assets/js/googlesitekit/notifications/register-defaults.js` and check if there are resolvers, or selectors that are using different resolvers (like in the case of `hasZeroData`) in `checkRequirements` that might be missed, and are retrieved using `select` instead of `resolveSelect`. One such example is `isModuleConnected` which is currently not resolved. There might be more

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All the data used in `checkRequirements` property of currently registered notifications should be properly resolved where needed - specifically when retrieving the data from resolvers.
  * One such example is `isModuleConnected` which is currently not resolved

## Implementation Brief

* [x] Update `assets/js/googlesitekit/notifications/register-defaults.js`
  * Data from `isModuleConnected` resolver should be retrieved with `resolveSelect` and awaited
  * There are few selectors, which rely on data from different resolver, which can't guarantee having data available at the point when notifications API is invoked, although there is good chance this data is already resolved and available due to requests for this mandatory data is done very early.
    * `isAuthenticated` and `getUnsatisfiedScopes` selectors are both using `getAuthentication` resolver, which fetches the needed data.
    * `canViewSharedModule` selector, is relying on having data from `getModule` resolver. 
    * Invoke these dependency resolvers and await them before the selectors are called, to ensure data is resolved properly
* Check if there is any other resolver that might be missed, in case new notifications are added after this IB has been written.

### Test Coverage

* No updates are needed

## QA Brief

* The following notifications need to be re-tested:
  * Gathering Data 
  * Zero Data
  * UnsatisfiedScopesAlert
  * UnsatisfiedScopesAlertGTE
  * GA4AdSenseLinked

## Changelog entry

* Update requirement checks for notifications to have all selectors resolved correctly and efficiently.

**Comment by eugene-manuilov** [comment]
AC ✔️

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified that the following notifications showing correctly and associated events getting trigger successfully.
  -  Gathering Data
   - Zero Data
   - UnsatisfiedScopesAlert
   - UnsatisfiedScopesAlertGTE
  - GA4AdSenseLinked

**Zero and Gathering data state notifications**

<details>

SC is in zero data state

![Image](https://github.com/user-attachments/assets/49e1bb41-cd6d-49c5-9bf9-d13140ec5a42)

Analytics is in gathering state but SC is in zero state

![Image](https://github.com/user-attachments/assets/f0baab09-aec8-4b7d-aa9b-4a9132cd5f29)

AC and Analytics both in zero data state

![Image](https://github.com/user-attachments/assets/ff926a8c-59de-46ef-999e-08146f54b979)

SC and analytics both in gathering data state

![Image](https://github.com/user-attachments/assets/f06f1218-bb5d-4b8f-b9e7-3a8ab513cc1c)

Both SC and analytics is in zero data state

![Image](https://github.com/user-attachments/assets/937bd66b-c25c-4bfd-ae66-c2438e567b7f)

SC is in gathering data state and Analytics is in zero data state

![Image](https://github.com/user-attachments/assets/5d979ed3-3a0d-4f4d-b8a9-405d3491cf33)

</details>

**UnsatisfiedScopeAlert**

<details>

![Image](https://github.com/user-attachments/assets/a6951218-696c-4b95-a4c0-3c654be24b12)

![Image](https://github.com/user-attachments/assets/642c75d0-1dc0-4de4-8da6-2bde0e5014a0)

</details>


**UnsatisfiedScopeAlertGTE**

<details>

![Image](https://github.com/user-attachments/assets/72da0187-888c-4763-89f9-103c28a77ab7)

</details>

**GA4AdSenseLinked**

<details>

![Image](https://github.com/user-attachments/assets/cc6efe6c-4491-49b4-8bbc-06e3b489afdd)

</details>
