### ISSUE TITLE
Move on-demand onboarding state synchronization to server side

### ISSUE THREAD

**Issue by nfmohit** [google/site-kit-wp#9363]
## Feature Description

As pointed out [here](https://github.com/google/site-kit-wp/issues/9262#issuecomment-2352543664), we should look into moving the on-demand synchronization of publication onboarding state from the client-side to the server for a better UX, like we did for the periodic synchronization.

Ideally, we should add a `POST:sync-publication-onboarding-state` endpoint so we handle the sync on the backend, and then call `fetchGetSettings()` after this to update the saved settings state.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* On the RRM setup and settings edit screens, having clicked on the CTA to visit the Publisher Center from one of the notifications that indicate the publication's onboarding state, and having then returned to the Site Kit tab after 15 seconds have elapsed (see #9262), the onboarding state and corresponding CTA should be updated without showing the respective screen in a loading state.
* Additionally, for the settings edit case, the **Save** button should not momentarily change to **Confirm changes** during the onboarding state update.

### Server side

- [x] Create a `POST:sync-publication-onboarding-state` endpoint as a new datapoint in the [`Reader_Revenue_Manager`](https://github.com/google/site-kit-wp/blob/d17f5bd1335a2580594d9f051e1ba83a05586e8f/includes/Modules/Reader_Revenue_Manager.php) class:
  - Require `$publicationID` and `$publicationOnboardingState` parameters to be passed in `$data`. We need to pass these in, rather than simply use the current values in settings, because the client may be requesting a sync for an unsaved setting in the case where a new publication has been selected from the dropdown.
  - Retrieve the list of `$publications` via a call to `$this->get_data( 'publications' )`.
  - Find the `$publication` in the list where `$publication->getPublicationId()` matches `$publicationID`.
  - If `$publication` is not found, return a `WP_Error` with a message that the publication was not found.
  - Retrieve `$newOnboardingState` from `$publication->getOnboardingState()`.
  - If `$newOnboardingState` is already `$publicationOnboardingState`, return an empty object, indicating that the state has not changed.
  - Retrieve the current module `$settings` from `$this->get_settings()->get()`.
  - If the `$publicationID` parameter matches `$settings['publicationID']`, indicating that we are syncing the currently saved publication:
    - Merge `publicationOnboardingState => $newOnboardingState` into `$settings`.
    - Return an object with the following values:
      ```
        {
          publicationOnboardingState: $newOnboardingState
          isSavedSetting: true
        }
      ```
  - Otherwise, return an object with the following values:
    ```
      {
        publicationOnboardingState: $newOnboardingState,
      }
    ```
  - The endpoint does not need to be shareable.

### Client side

- In the [`publications` datastore](assets/js/modules/reader-revenue-manager/datastore/publications.js):
  - [x] Create a new `fetchGetSyncPublicationOnboardingStateStore` store with `baseName: getSyncPublicationOnboardingState` via `createFetchStore()` that calls the new `POST:sync-publication-onboarding-state` endpoint.
    - If `publicationOnboardingState` is set in the response:
      - The reducer should update `settings.publicationOnboardingState` in state.
      - It should also should update `savedSettings.publicationOnboardingState` if `isSavedSetting` is `true`.
  - [x] Update the `*syncPublicationOnboardingState()` action:
    - Replace the [current block from the call to `resetPublications()` to the call that retrieves `currentOnboardingState`](https://github.com/google/site-kit-wp/blob/d17f5bd1335a2580594d9f051e1ba83a05586e8f/assets/js/modules/reader-revenue-manager/datastore/publications.js#L86-L123) with a call to `return yield fetchGetSyncPublicationOnboardingStateStore.actions.fetchGetSyncPublicationOnboardingState()`;
    - Update the early `return` statements with `return {}` to ensure an object is always returned from the action.
- Update the `syncPublication()` callback in the [`RRMSetupSuccessSubtleNotification`](https://github.com/google/site-kit-wp/blob/d17f5bd1335a2580594d9f051e1ba83a05586e8f/assets/js/modules/reader-revenue-manager/components/dashboard/RRMSetupSuccessSubtleNotification.js) component:
  - Prior to the call to `syncPublicationOnboardingState()`, retrieve `currentOnboardingState` via the `getPublicationOnboardingState()` selector.
  - Await `syncPublicationOnboardingState()` to retrieve the result, which is of the shape `{ response, error }`.
  - If `response?.publicationOnboardingState` is truthy, execute the following block of code which can be moved from `syncPublicationOnboardingState()`. The value of `response.publicationOnboardingState` should be used for `newOnboardingState`:
https://github.com/google/site-kit-wp/blob/d17f5bd1335a2580594d9f051e1ba83a05586e8f/assets/js/modules/reader-revenue-manager/datastore/publications.js#L125-L139

### Test Coverage

- Add PHPUnit test coverage for the server side changes.
- Update the JS test coverage for the `syncPublicationOnboardingState()` action and `RRMSetupSuccessSubtleNotification` component.

#### On Site Kit Dashboard

1. Make sure you have at least one publication setup in RRM publication center with the status `ONBOARDING_COMPLETE`.

2. In tester plugin, `RRM > Force Reader Revenue Manager publication onboarding state`, set it to `ONBOARDING_ACTION_REQUIRED`.

3. Enable RRM feature and module. Make sure publications are setup for the site and they are available in settings screen.

4. Select the publication with `complete` state in publication center and complete the setup. This will setup the publication state as `ONBOARDING_ACTION_REQUIRED` in database.

5. Visit the Site Kit dashboard. You will be able to see the publication onboarding state notification with the `Complete publication setup` CTA.

6. Click on CTA which will open the publisher center. Stay on that page (away from Site Kit dashboard tab) for more than 15 seconds.

7. Return to the tab, ensure that notification has been changed to setup success [notification](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-readerrevenuemanager-components-dashboard-rrmsetupsuccesssubtlenotification--onboarding-complete) and the Publication Approved Overlay [notification](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-readerrevenuemanager-components-publicationapprovedoverlaynotification--default) is also visible.

#### On Settings Screen

1. Make sure you have at least one publication setup in RRM publication center with the status `ONBOARDING_COMPLETE`.

2. In tester plugin, `RRM > Force Reader Revenue Manager publication onboarding state`, set it to `ONBOARDING_ACTION_REQUIRED`.

3. Enable RRM feature and module. Make sure publications are setup for the site and they are available in settings screen.

4. Select the publication with `complete` state in publication center. 

5. You will be able to see the publication onboarding state notification with the `Complete publication setup` CTA on settings screen.

6. Click on CTA which will open the publisher center. Stay on that page (away from Site Kit dashboard tab) for more than 15 seconds.

7. Return to the tab on settings edit screen, the publication onboarding state notification should disappear.

## Changelog entry

* Move on-demand onboarding state synchronization to the server side, avoiding the need to reload the full list of publications.

**Comment by nfmohit** [comment]
AC ✅

**Comment by nfmohit** [comment]
IB ✅, thanks @techanvil!

Just a note that I made an edit to correct the selector name from `getOnboardingState()` to `getPublicationOnboardingState()`. @techanvil Please let me know if you think that's not correct. Thank you!

**Comment by techanvil** [comment]
That's spot on @nfmohit, thanks for fixing the typo!

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified that on SK dashboard ensure that notification has been changed to setup success [notification](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-readerrevenuemanager-components-dashboard-rrmsetupsuccesssubtlenotification--onboarding-complete) and the Publication Approved Overlay [notification](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-readerrevenuemanager-components-publicationapprovedoverlaynotification--default) is also visible.
- Verified that on settings edit screen, the publication onboarding state notification gets disappear.
- Verified that on settings edit page s, the Save button not momentarily change to Confirm changes during the onboarding state update.
- 

<details>

Settings screen

https://github.com/user-attachments/assets/306854fa-a5ba-41a6-a2fa-2614ad308608

Main dashboard

https://github.com/user-attachments/assets/1919e0e5-bd85-4b9c-beb6-dcaa9dbccca3

Edit case

https://github.com/user-attachments/assets/f533e6f0-e82c-4f1c-892d-e2a09cae287b


</details>
