### ISSUE TITLE
Filter out ACR metric items from saved ones if feature flag is disabled

### ISSUE THREAD

**Issue by zutigrm** [google/site-kit-wp#9364]
## Feature Description

We should prevent metric tiles from still appearing in the widget area after the `conversionReporting` feature flag is disabled.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* After `conversionReporting` feature flag is disabled key metric tiles that have been already saved and added to the widget area, should not appear, and instead a ghost card should be shown

## Implementation Brief

* [ ] Update `assets/js/googlesitekit/datastore/user/key-metrics.js`
  * Edit `getKeyMetrics` selector
    * `userPickedMetrics` and `answerBasedMetrics` should be filtered out for any saved ACR items, only if  `conversionReporting` feature flag is disabled.
    * You can add a new constant in `assets/js/googlesitekit/datastore/user/constants.js` for example and map all non-ACR widget slugs in an array, so it can be used for checking against saved metrics for filtering purpose.
    * NON-ACR widgets that can be used to filter out ACR metrics are as follows:
      * `KM_ANALYTICS_ADSENSE_TOP_EARNING_CONTENT`
      * `KM_ANALYTICS_ENGAGED_TRAFFIC_SOURCE`
      * `KM_ANALYTICS_LEAST_ENGAGING_PAGES`
      * `KM_ANALYTICS_NEW_VISITORS`
      * `KM_ANALYTICS_POPULAR_AUTHORS`
      * `KM_ANALYTICS_POPULAR_CONTENT`
      * `KM_ANALYTICS_POPULAR_PRODUCTS`
      * `KM_ANALYTICS_RETURNING_VISITORS`
      * `KM_ANALYTICS_TOP_CATEGORIES`
      * `KM_ANALYTICS_TOP_CITIES`
      * `KM_ANALYTICS_TOP_CONVERTING_TRAFFIC_SOURCE`
      * `KM_ANALYTICS_TOP_COUNTRIES`
      * `KM_ANALYTICS_TOP_RECENT_TRENDING_PAGES`
      * `KM_ANALYTICS_TOP_TRAFFIC_SOURCE`
      * `KM_ANALYTICS_PAGES_PER_VISIT`
      * `KM_ANALYTICS_VISIT_LENGTH`
      * `KM_ANALYTICS_TOP_RETURNING_VISITOR_PAGES`
      * `KM_ANALYTICS_VISITS_PER_VISITOR`
      * `KM_ANALYTICS_MOST_ENGAGING_PAGES`
      * `KM_ANALYTICS_TOP_CATEGORIES`
      * `KM_SEARCH_CONSOLE_POPULAR_KEYWORDS`

### Test Coverage

* Update `assets/js/googlesitekit/datastore/user/key-metrics.test.js` to include this new scenario, where saved ACR widget slug, would not be included in the final array when metrics are retrieved using `getKeyMetrics` selector, and when feature flag is disabled, and they are included when it is enabled

## QA Brief

* Set up Google Site Kit with the Analytics module enabled / active
* Reach out to @zutigrm for access to the ACR test site data
* Set up KMW manually, choose 2 random ones, and save
* Enable the `conversionReporting` feature flag
* Go back to the manual KMW selection panel and choose any of the now present ACR widgets, such as "top cities driving leads", and save the selection
* Verify that the ACR KMW is showing in the widget rendering area of KMW
* Now, disable/uncheck the `conversionReporting` feature flag
* Navigate back to the main Site Kit dashboard and observe the KMW rendering area
* The ACR widget(s) should no longer appear, but all others should
* Re-enable the `conversionReporting` feature flag and validate that the ACR metric(s) is shown again

## Changelog entry

* Only show Analytics Conversion Reporting items in the dashboard when the feature flag is enabled.

**Comment by zutigrm** [comment]
Since AC is very straightforward, I added both AC and IB and moved it to the IBR

**Comment by eugene-manuilov** [comment]
> * `userPickedMetrics` and `answerBasedMetrics` should be filtered out for any saved ACR items, only if  `conversionReporting` feature flag is disabled.

@zutigrm let's make it clear which items should be filtered out exactly. Could you please list them in IB?

**Comment by zutigrm** [comment]
@eugene-manuilov Sure, I added the list, and expanded the IB

**Comment by eugene-manuilov** [comment]
Thanks, IB ✔️

**Comment by 10upsimon** [comment]
@zutigrm and I chatted about this via DM, and it made more sense to define a constant that holds non ACR metrics only, and filter against this list. This saves having to add metrics to the array as they become available in code, thus reducing the chance for oversight thereof.

I'll update the IB shortly to reflect this change, cc @eugene-manuilov

**Comment by 10upsimon** [comment]
@zutigrm @eugene-manuilov the IB has been updated accordingly.

**Comment by 10upsimon** [comment]
@zutigrm :

Noting that we are not able to add test cases to `assets/js/googlesitekit/datastore/user/key-metrics.test.js` until such time that we have the mapping defined, as these tests rely on the real values returned by `registry.select( CORE_USER ).getAnswerBasedMetrics()`. 

We should make the addition of this test as part of the GH issue that maps ACR metrics to site purpose answers, once that task is defined.

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on main environment.
- Verified after `conversionReporting` feature flag is disabled key metric tiles that have been already saved and added to the widget area, do not appear, and instead a ghost card shown there.
- Also, done some additional testing around key metrics widget selection.

<details>


https://github.com/user-attachments/assets/0da6da13-5420-435d-baeb-5b03dd7becd1

</details>
