### ISSUE TITLE
Standardize GA events for RRM Setup Success Subtle Notification

### ISSUE THREAD

**Issue by jimmymadon** [google/site-kit-wp#9368]
## Bug Description

The GA events fired when viewing, clicking on the CTA and dismissing the RRM Setup Success Subtle Notification has an event category `mainDashboard_rrm-setup-success-notification`. This is slightly different to the notification events that we have created already for Ads and PAX which are `mainDashboard_setup-success-notification-pax` and `mainDashboard_setup-success-notification-ads`. 

## Steps to reproduce

1. Complete RRM setup and see the setup success subtle notification.
2. The GA events for view, CTA click and dismiss button click are `mainDashboard_rrm-setup-success-notification`. They should be `mainDashboard_setup-success-notification-rrm` just to maintain consistency with other modules.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The GA event categories for the View, CTA Click and Dismiss button click should be modified for the RRM Setup Success Subtle Notification from `<view-context>_rrm-setup-success-notification` to `<view-context>_setup-success-notification-rrm`.

## Implementation Brief

* [x] In `assets/js/modules/reader-revenue-manager/components/dashboard/RRMSetupSuccessSubtleNotification.js`, replace the event category as per the AC.

### Test Coverage

* No new tests required but update existing tests.

## QA Brief

* Ensure user analytics for Site Kit usage are enabled.
* Complete RRM setup and test all the three GA events being fired on view, dismiss and CTA click.

## Changelog entry

* Update RRM notification event names in Analytics.

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified the GA event categories for the View, CTA Click and Dismiss button click now modified for the RRM Setup Success Subtle Notification from <view-context>_rrm-setup-success-notification to <view-context>_setup-success-notification-rrm.
- Verified view_notifcation, dismiss_notification and confirm_notification (CTA click) events.
- Verified when RRM setup get complete and status is onboard complete.
- Verified when RRM setup get complete and status is pending verification.

<details>

**View_Notiification** 

![image](https://github.com/user-attachments/assets/08deb586-8dea-4ed2-8e23-1fcb39fcc2d1)

![image](https://github.com/user-attachments/assets/af1bc573-81e3-46bf-b119-9f24919f3546)


**Confirm_Notification (CTA Click)**

![image](https://github.com/user-attachments/assets/5d11368a-92e4-4824-b449-c5a4bd9ab5b3)

**dismiss_notification** 

![image](https://github.com/user-attachments/assets/e372a1d7-53d2-4f4c-b569-b9d4b8e57e97)

</details>
