### ISSUE TITLE
Notice: Trying to get property 'impressions' of non-object in google-site-kit/includes/Modules/Search_Console.php

### ISSUE THREAD

**Issue by opicron** [google/site-kit-wp#937]
## Bug Description

PHP notice on staging site

Notice: Trying to get property 'impressions' of non-object in google-site-kit/includes/Modules/Search_Console.php on line 415

## Steps to reproduce

1. Activate plugin in Wordpress
2. Set error reporting to ALL

## Additional Context

 - PHP Version: 7.2
 - OS: Ubuntu 19.04
 - Plugin Version: 1.1.1

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by ernee** [comment]
@opicron Site Kit support has now moved to the [WordPress Support Forums](https://wordpress.org/support/plugin/google-site-kit/). Please report your issue there in a new topic with details and screenshots if you have them. We'd be happy to take a look!
