### ISSUE TITLE
Expand the logic of the `ACRNotificationCTAWidget` component for existing KMW users that already have ACR tiles set up 

### ISSUE THREAD

**Issue by zutigrm** [google/site-kit-wp#9373]
## Feature Description

The `ConversionReportingSettingsSubtleNotification ` component logic should be expanded so it surfaces in the dashboard within key metrics widget area for the users who have setup KMW, either manually or using tailored metrics, once new ACR events are detected. This scenario covers only the use case, where ACR metrics were already detected initially, and now new events were detected. CTA should open selection panel with new metrics highlighted with new badge

FIgma design can be seen [here](https://www.figma.com/design/S2CNc1toIzC7UrGMgs79S6/Conversions?node-id=1965-16637&node-type=frame&t=Jv59rveRss6eCqpE-0)

Refer to the [Subtle banner notification for detected events](https://docs.google.com/document/d/1JvA3LK5SNfGH2o4OVnwjDdsAFuQMA9ZJj0T09RTqoy8/edit?pli=1&resourcekey=0-e90bcFGzAI6NhNu_D5i6hQ#heading=h.4vc3htg11p6z) and [New Events Detection Following Initial Events Detection](https://docs.google.com/document/d/1JvA3LK5SNfGH2o4OVnwjDdsAFuQMA9ZJj0T09RTqoy8/edit?pli=1&resourcekey=0-e90bcFGzAI6NhNu_D5i6hQ#heading=h.5ujxp9w8p70s) sections of the design doc

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* `ConversionReportingSettingsSubtleNotification` component is updated to show/surface:
  * If conversion event were already detected, and
  * If key metrics were setup (either using manual selection or getting tailored metrics), and
  * New conversion events have been detected (check implementation in [9379](https://github.com/google/site-kit-wp/issues/9379) that adds needed infrastructure)
* Banner should re-surface every time new events are detected following the initial events detection. If it gets dismissed, it will not show until next time new events are detected, when it should re-surface again
* Said component should match the [figma design](https://www.figma.com/design/S2CNc1toIzC7UrGMgs79S6/Conversions?node-id=1965-16637&node-type=frame&t=Jv59rveRss6eCqpE-0)
* Clicking the `Maybe later` CTA should dismiss the banner
* Clicking the `Select metrics` CTA should open the selection panel
* Check the [Subtle banner notification for detected events](https://docs.google.com/document/d/1JvA3LK5SNfGH2o4OVnwjDdsAFuQMA9ZJj0T09RTqoy8/edit?pli=1&resourcekey=0-e90bcFGzAI6NhNu_D5i6hQ#heading=h.4vc3htg11p6z) and [New Events Detection Following Initial Events Detection](https://docs.google.com/document/d/1JvA3LK5SNfGH2o4OVnwjDdsAFuQMA9ZJj0T09RTqoy8/edit?pli=1&resourcekey=0-e90bcFGzAI6NhNu_D5i6hQ#heading=h.5ujxp9w8p70s) sections of the design doc

## Implementation Brief

* [ ] Update `ConversionReportingNotificationCTAWidget` component
  * Banner should render if:
    * There are new events that are not included already
    * And `isKeyMetricsSetupCompleted` is `true`
    * And `hasNewConversionReportingEvents` selector from analytics datastore is true, and value of `newEvents` returned from `getConversionReportingEventsChange` selector of analytics datastore, is not matching the value from `getDetectedEvents` Analytics setting, marking that these are new events, after initial events were detected. 
  * Note that detected events should not be specific to the existing site purpose, as this is general notification just notifying the user about new KMW being available, as long as the new events have been detected.
  * Following above conditions, include the CTA variation/callback:
    * `Maybe later` CTA callback should behave in a same way as implementation in [9371](https://github.com/google/site-kit-wp/issues/9371)
    * `View metrics` CTA callback should open the selection panel https://github.com/google/site-kit-wp/blob/79b4417581b1cca3d718f7e55127681e6e05fc6f/assets/js/components/KeyMetrics/ChangeMetricsLink.js#L48

### Test Coverage

* Update tests for `ConversionReportingNotificationCTAWidget` (basic coverage added in [9344](https://github.com/google/site-kit-wp/issues/9344)), to verify that banner is showing when conditions are met, and not showing otherwise for example. Also test for new CTA's variation and verifying that it updates the UI state which will trigger the opening of selection panel

## QA Brief

* Set up Site Kit with Analytics module with `conversionReporting` feature flag
* Force detection of the events, say `contact` and setup the KMW using tailored metrics
* Force detection of new events - something unrelated to the leads, say `purchase`. So `Analytics detected events` will have `contact` and `purchase` selected, and `Force Analytics to detect new events` will have `purchase` only selected.
* Verify that callout is showing with `View metrics` CTA, and clicking it will open the selection panel
* Also, for manual selection
  * Start manual setup of KMW with some events detected. For example with `contact` saved as `Analytics detected events`
  * Add all 3 leads metrics. 
  * Then set `contact` and `purchase` for detected events (`Analytics detected events` tester setting), and `purchase` as newly detected event (`Force Analytics to detect new events` tester setting). 
  * Banner should surface with `View metrics` CTA.
*  While testing this one, you can see #9371 for initial detection of events which should be still working as intended on initial events detection, so to ensure there is no regression.
* Combination with lost events is also possible, both banners would be shown in right circumstance (pretty much edge case, but possible), where lost events banner will be on the top of newly detected one

#### Notes

* Ping @zutigrm for modified Tester Plugin to be able to enforce detected and lost events
* To provide a clarification, under the hood detected events are synced via cron, once events are detected, let's say `contact` it will be stored in detected events, and can be mimicked with `Analytics detected events`. At the same time `new events` will be updated with same value if it is initial detection, otherwise every next time it will contain only the event difference (mimicked with `Force Analytics to detect new events`). So if `purchase` event is detected later on, detected events will look like [`contact`, `purchase`], but new events will now contain only the latest detected event, which will be [`purchase`]. This difference is what will trigger the callout in this issue.
* Few things specific for manual selection. When you set `contact` as initial detected event, and then simulate another leads related metric being detected it will not show banner. So `contact`, `generate_lead` and `submit_lead_form` are considered leads events, and bring same 3 metrics. So having `contact` and `submit_lead` in detected events, and `submit_lead` in new events - simulating that later event was detected after contact was detected initially, banner should not surface since no new events would be brought.
* Also, selecting manually 2 leads metrics, or 1 add to cart metric (there 2 in total), leaving partially some metrics unselected from same event, and then showing that event as detected will still surface banner, but only if some events were unelected for detected metric, otherwise banner will not show. This simulates the edge case for manual selection where user might have lost events after selecting them initially. In this case unselected metric will not be avaialble in selection panel, detecting that event later on will bring it back, and it will be considered `new` again
* A note to test ITEM 1 and 3 from https://github.com/google/site-kit-wp/issues/9578

## Changelog entry

* Update Analytics Conversion Report notifications to be more context-aware.

**Comment by 10upsimon** [comment]
@zutigrm the AC says the following:

- either using manual selection or getting tailored metrics

And then goes on to say the following for clicking the primary CTA:

- Clicking the Select metrics CTA should open the selection panel

However, the selection panel would not be applicable for tailored metric users. Please expand on this a little for tailored vs manual setups, thanks!

**Comment by zutigrm** [comment]
@10upsimon Yes the explained steps are correct and expected behaviour. After new events are detected following initial detection, this banner is shown with same CTA regardless of how KMW was setup, it will open the selection panel showing to list the "New" events. CTA which will automatically add the tailored metrics for users who previously set up KMW using tailored metrics, happens only on initial detection, afterwards it is only [one banner variation](https://www.figma.com/design/S2CNc1toIzC7UrGMgs79S6/Conversions?node-id=1965-16635&node-type=frame&t=8Ig235wDCG7UbFxT-0)

**Comment by zutigrm** [comment]
@10upsimon Yes the explained steps are correct and expected behaviour. After new events are detected following initial detection, this banner is shown with same CTA regardless of how KMW was setup, it will open the selection panel showing to list the "New" events. CTA which will automatically add the tailored metrics for users who previously set up KMW using tailored metrics, happens only on initial detection, afterwards it is only [one banner variation](https://www.figma.com/design/S2CNc1toIzC7UrGMgs79S6/Conversions?node-id=1965-16635&node-type=frame&t=8Ig235wDCG7UbFxT-0)

**Comment by 10upsimon** [comment]
@zutigrm AC ✅ thanks for clariyfing

**Comment by zutigrm** [comment]
I increased estimate for a point since this issue will require interacting with existing conditionals for 2 previous banner variations, and during testing it should be monitored that this variation does not cause regression to previous ones implemented

**Comment by eugene-manuilov** [comment]
@zutigrm, we need to update IB to account for changes in #9371. Now we need to adjust logic in the widget component instead of in the notification.

**Comment by zutigrm** [comment]
@eugene-manuilov thanks, IB updated

**Comment by eugene-manuilov** [comment]
> * Following above conditions, include the content variation matching this banner in [Figma](https://www.figma.com/design/S2CNc1toIzC7UrGMgs79S6/Conversions?node-id=1965-16637&node-type=frame&t=Jv59rveRss6eCqpE-0)

@zutigrm, the same here, see https://github.com/google/site-kit-wp/issues/9372#issuecomment-2422824731

**Comment by zutigrm** [comment]
@eugene-manuilov Thanks, IB updated

**Comment by eugene-manuilov** [comment]
Thanks, IB ✔

**Comment by kelvinballoo** [comment]
### QA Update ⚠ 

Hi @zutigrm , there is quite a bit of scenarios to unpack and here are some observations I made.

**ITEM 1:**
Testing on the first scenario of the QAB, where I set up through tailored metrics, withou

<Details>

https://github.com/user-attachments/assets/3b8f830c-caa4-4cb3-aff1-a07304f989c9


</Details>

____________________________________________________________

**ITEM 2:**
I was executing the steps for the manual selection scenario and noticed a lost in event banner that appears.
Refer to the attached video at 2:15. There was no 'lost event' forced in the tester plugin. Is there any reason why this showed up?

<Details>

https://github.com/user-attachments/assets/0ecc9214-1335-432c-b0e9-262c7abce407

</Details>

____________________________________________________________

**ITEM 3:**

I was trying to test a lost event scenario. The add metrics/view metrics banner will not show up.
However, in the selection panel, I was expecting the unselected metrics related to the lost event to disappear.
I assume that's how it should work. Can you confirm?

Video is attached for reference.

<Details>

https://github.com/user-attachments/assets/f425a1fa-d44a-4593-aa87-a34e4f5da252

</Details>

**Comment by zutigrm** [comment]
> ITEM 1:
Testing on the first scenario of the QAB, where I set up through tailored metrics, withou

You are correct, we should still show Add metrics CTA in this case, for tailored metrics if they had not previously had that event, even if othe events were initially detected. I will take it back to EX to improve this.

> ITEM 2:
I was executing the steps for the manual selection scenario and noticed a lost in event banner that appears.
Refer to the attached video at 2:15. There was no 'lost event' forced in the tester plugin. Is there any reason why this showed up?

In events clear scenario, it can't be replicated
https://github.com/user-attachments/assets/11a3e474-5789-4c9f-9200-f8a129df14eb

This can happen only when lost events are detected. Now in the backend, events are detected as lost once detected events setting on next sync had events that are not detected now. What can happened is that perhaps you had some event force as detected, and did a site kit reset, in this scenario it can happen that since setting for detected events is forced, during the check it will be saved in the DB. And if you do not force any lost event, it is automatically calculated as lost if it is not selected in detected events.
So best to test on a fresh data - select do not force on all 3 ACR tester settings, reset the site kit, than start forcing events needed

> ITEM 3:
I was trying to test a lost event scenario. The add metrics/view metrics banner will not show up.
However, in the selection panel, I was expecting the unselected metrics related to the lost event to disappear.
I assume that's how it should work. Can you confirm?

When events are lost, they are going to disappear from the detected events setting, in your case `purchase` as detected event is still forced, as long as it is detected in the setting it will be shown in selection panel. To simulate this, you should remove `purchase` from forced detected events, and select it in forced lost events. This case once you unselect purchase events, and save the selection, next time you open the selection panel they will not be there

**Comment by kelvinballoo** [comment]
### QA Update ⚠ 

Hi @zutigrm ,
I've had a retest.

**ITEM 1:** ⚠ 
Unfortunately, I still see the 'View metrics' CTA even after I reset site kit.
I tested on main branch and dev branch but both yield similar results.

I was expecting 'Add metrics' banner.
Video is attached.

<Details>

https://github.com/user-attachments/assets/4955f15e-fd6e-4936-93b7-90b6d96d8b36

</Details>

____________________________________________________________

**ITEM 2:**  ✅ 
Tested good after properly resetting the settings.

<Details>

https://github.com/user-attachments/assets/56a2ff57-d336-41da-82bf-4cb62244105b

</Details>
____________________________________________________________

**ITEM 3:** ⚠ 
This might be a little tricky.
If I remove from the 'Detect events', even the selected ACRs would disappear.
I have a feeling it's more to the way the tester plugin works.
You can refer to the attached video. Let me know if my scenario makes sense. I was expected the 'Add to card' selected event to remain even though there is a loss in event.

That said, this could be treated as a separate ticket in my opinion.
<Details>

https://github.com/user-attachments/assets/9dd62ef5-6fbd-4b7a-86c9-1c1e5e1d9984

</Details>

____________________________________________________________

**ITEM 4:** -> NEW ITEM ⚠ 
I tested Scenario 5 from https://github.com/google/site-kit-wp/issues/9371 and it's not working as expected.
I was expecting no banner to show up but there was. 

This could be a regression and maybe it's best to tackle it in another ticket to avoid making this a long one.

https://github.com/user-attachments/assets/591782d6-1ee1-4f0a-a178-d49caa470e2d

**Comment by zutigrm** [comment]
@kelvinballoo 

> ITEM 1: ⚠
Unfortunately, I still see the 'View metrics' CTA even after I reset site kit.
I tested on main branch and dev branch but both yield similar results.

> I was expecting 'Add metrics' banner.

From the scenario in the video, this is correct. When you have `contact` event with `publish_blog` as a purpose and detect non site purpose related metrics, like `add_to_cart` it will show banner with `View metrics` CTA

The scenario that was improved, and previously discussed is if you have started off with `sell_products` as a site purpose instead with a `contact` and then detect `add_to_cart` it will show `Add metrics`

> ITEM 3: ⚠
This might be a little tricky.
If I remove from the 'Detect events', even the selected ACRs would disappear.
I have a feeling it's more to the way the tester plugin works.
You can refer to the attached video. Let me know if my scenario makes sense. I was expected the 'Add to card' selected event to remain even though there is a loss in event.

Your observation is correct, the ACR related groups like `Selling products` are connected to the new events detection at the moment, hence when event is not present it will disappear, this will be fixed as part of #9798 

> ITEM 4: -> NEW ITEM ⚠
I tested Scenario 5 from https://github.com/google/site-kit-wp/issues/9371 and it's not working as expected.
I was expecting no banner to show up but there was.

This is correct behaviour. The point from QAB is covering the scenario for Tailored metrics, it is correct `Add metrics` banner variation is not showing, but at that point Manual selection logic was not implemented yet, as it came with the next issue. Now it has been implemented, so the scenario you are testing, it falls correctly for manually selected users, which is showing `Select metrics` CTA for initial events detection

**Comment by kelvinballoo** [comment]
### QA Update ✅ 

Retested ITEM 1 as per correct scenario and it's working as expected.
<Details>

https://github.com/user-attachments/assets/62c6a87e-27b8-4078-a069-86383bcb155c

</Details>

Noted on item 2 (to be fixed in https://github.com/google/site-kit-wp/issues/9798) and that for item 4, it's behaving as expected per the latest fixes available.

_________________________________________________________________

The following for this QAB were tested good:

- Add metrics shows up accordingly per above.
- Loss event scenario works
   <Details>

   https://github.com/user-attachments/assets/56a2ff57-d336-41da-82bf-4cb62244105b

   </Details>
- Maybe later/Dismiss works
   <Details>
   
   https://github.com/user-attachments/assets/5da315f7-3bfa-4072-9e3a-f2c24537106d

   </Details>
_________________________________________________________________

Scenarios from #9371 were verified good as well:
- Scenario 1
   <Details>
   Banner doesn't appear.

   <img width="1287" alt="Image" src="https://github.com/user-attachments/assets/2714f93b-d100-4a5f-ae62-6366b97b01c7" />

   </Details>
- Scenario 2
   <Details>
   Banner doesn't appear.

   <img width="1287" alt="Image" src="https://github.com/user-attachments/assets/526d5099-ac4a-4c18-9f4b-f3e0e0421c9c" />

   </Details>
- Scenario 3
   <Details>
   'Add metrics' variation is working.

   <img width="1285" alt="Image" src="https://github.com/user-attachments/assets/23badf5a-a1ef-4f2c-99f6-99cae3a770bc" />

   <img width="1286" alt="Image" src="https://github.com/user-attachments/assets/589c9ca8-2368-4b2a-a556-d9b28ef8f906" />

   <img width="1259" alt="Image" src="https://github.com/user-attachments/assets/b5b9eae9-f36d-4229-a9f5-c21664523385" />

   </Details>

- Scenario 4
   <Details>
   No banner shows up.

   <img width="1287" alt="Image" src="https://github.com/user-attachments/assets/6e58b967-d06b-45d5-be8a-99a9941938c3" />

   </Details>
- Scenario 5
   <Details>
   Banner shows up and it's in accordance with the latest fixes available.

   https://github.com/user-attachments/assets/7f47b764-9665-4aab-a8e7-6905790e7c06


   </Details>
