### ISSUE TITLE
Update existing ACR tiles to allow for dashboard sharing

### ISSUE THREAD

**Issue by zutigrm** [google/site-kit-wp#9377]
## Feature Description

Some of the new ACR metrics are using metrics and dimensions that are not listed within shareable metrics and dimensions. This issue should update it.

See [Dashboard Sharing](https://docs.google.com/document/d/1JvA3LK5SNfGH2o4OVnwjDdsAFuQMA9ZJj0T09RTqoy8/edit?pli=1&resourcekey=0-e90bcFGzAI6NhNu_D5i6hQ#heading=h.w0br3nfp3mbe) section of the design doc

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* List of shareable metrics is expanded so they can be viewed in view only dashboard. Following new metrics are added:
  * `addToCarts`
  * `eventCount`
  * `ecommercePurchases`
* List of shareable dimensions is also expanded, by following dimension:
  * `eventName`
* Existing ACR KMW are accessible in shared dashboard and data can be read properly.

## Implementation Brief

* [x] Update `includes/Modules/Analytics_4/Report/RequestHelpers.php`
  * Expand array in `validate_shared_metrics` method to include metrics listed in the AC
  * Expand array in `validate_shared_dimensions` method to include dimension listed in the AC
* Verify that ACR KMW are working in view only access. List of ACR widgets:
  * `kmAnalyticsTopPagesDrivingLeads`
  * `kmAnalyticsTopCitiesDrivingLeads`
  * `kmAnalyticsTopTrafficSourceDrivingLeads`
  * `kmAnalyticsTopCitiesDrivingAddToCart`
  * `kmAnalyticsTopTrafficSourceDrivingAddToCart`
  * `kmAnalyticsTopCitiesDrivingPurchases`
  * `kmAnalyticsTopDeviceDrivingPurchases`
  * `kmAnalyticsTopTrafficSourceDrivingPurchases`

### Test Coverage

* No updates needed

## QA Brief

* In the tester plugin, use the `https://brainiest-quetzal-9a3cf6.instawp.xyz` site as the custom URL. Also, enable `conversionReporting` feature flag. 
* Connect Analytics as an Admin. Use the above account (ask @zutigrm or @jimmymadon for access). 
* Enable the key metrics plugin.
* Share the analytics module to other users.
* Now login as a view only user and select all the metrics in the AC from the selection panel and ensure they all work normally without any errors.

## Changelog entry

* Add Dashboard Sharing support to Analytics Conversion Reporting tiles.

**Comment by eugene-manuilov** [comment]
AC looks good.

**Comment by 10upsimon** [comment]
IB ✅ Moving to EB

**Comment by mohitwp** [comment]
### QA Update ⚠ 

- Tested on dev environment.
- Tested using `https://brainiest-quetzal-9a3cf6.instawp.xyz` site.
- Tested after enabling `'conversionReporting' `Feature flag.
- Compared metrics data for all dates on main and view only dashboard.
- Verified ACR tiles on both main and view only dashboard.
- I verified that below listed ACR KMW are working in view only access. (Listed in IB) List of ACR widgets:

   - `kmAnalyticsTopPagesDrivingLeads`
   - `kmAnalyticsTopCitiesDrivingLeads`
   -` kmAnalyticsTopTrafficSourceDrivingLeads`
   - `kmAnalyticsTopCitiesDrivingAddToCart`
   - kmAnalyticsTopTrafficSourceDrivingAddToCart
   - `kmAnalyticsTopCitiesDrivingPurchases`
   - `kmAnalyticsTopDeviceDrivingPurchases`
   - `kmAnalyticsTopTrafficSourceDrivingPurchases`


@jimmymadon 

_**Q-1:** I am unable to find the ACR KMW widgets mentioned under AC. Are there any widgets with the same name, or are they referring to the same widgets listed under IB?

**Q-2:** I have verified all ACR KMW widgets except for kmAnalyticsTopDeviceDrivingPurchases. This widget is not listed under the Metrics list. Can you please confirm if the name of this widget is correct?_


**Main Dashboard**

<details>

![Image](https://github.com/user-attachments/assets/6ff5073f-f994-4f57-99e7-7e130f6ed82f)


![Image](https://github.com/user-attachments/assets/8b081a22-00fd-4f95-a570-843cf0d474ba)


![Image](https://github.com/user-attachments/assets/25e774d1-4d6d-416e-9329-9d153bcb3b06)

![Image](https://github.com/user-attachments/assets/d27ce810-6061-49ee-98d3-2402213499ab)

</details>

**View only Dashboard**

<details>

![Image](https://github.com/user-attachments/assets/9225183d-35d4-4245-ac1d-13dea5186a28)

![Image](https://github.com/user-attachments/assets/0e76ec5a-ddd6-4920-843f-728f0688fb34)


![Image](https://github.com/user-attachments/assets/1fe2dd25-48e3-47ed-94c4-7a4f099f4b7e)

![Image](https://github.com/user-attachments/assets/4c73ebcf-9ed4-48de-b40f-84c515ee3360)

![Image](https://github.com/user-attachments/assets/084c7374-9643-470c-8f16-822643c996f7)

![Image](https://github.com/user-attachments/assets/ef85b7c9-9e64-40fc-8a14-64d8ada2630d)

</details>

**Comment by jimmymadon** [comment]
> _**Q-1:** I am unable to find the ACR KMW widgets mentioned under AC. Are there any widgets with the same name, or are they referring to the same widgets listed under IB?

The names in the ACs are that of the metrics and dimensions and not actual widgets. So the widgets within the IB are the ACR widgets that are being displayed.

> **Q-2:** I have verified all ACR KMW widgets except for kmAnalyticsTopDeviceDrivingPurchases. This widget is not listed under the Metrics list. Can you please confirm if the name of this widget is correct?

That is correct - #9162 will add this tile.

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Tested using `https://brainiest-quetzal-9a3cf6.instawp.xyz` site.
- Tested after enabling `'conversionReporting' `Feature flag.
- Compared metrics data for all dates on main and view only dashboard.
- Verified ACR tiles on both main and view only dashboard.
- I verified that below listed ACR KMW are working in view only access. (Listed in IB) List of ACR widgets:

   - `kmAnalyticsTopPagesDrivingLeads`
   - `kmAnalyticsTopCitiesDrivingLeads`
   -` kmAnalyticsTopTrafficSourceDrivingLeads`
   - `kmAnalyticsTopCitiesDrivingAddToCart`
   - `kmAnalyticsTopTrafficSourceDrivingAddToCart`
   - `kmAnalyticsTopCitiesDrivingPurchases`
   - `kmAnalyticsTopTrafficSourceDrivingPurchases`


**Main Dashboard**

<details>

![Image](https://github.com/user-attachments/assets/6ff5073f-f994-4f57-99e7-7e130f6ed82f)


![Image](https://github.com/user-attachments/assets/8b081a22-00fd-4f95-a570-843cf0d474ba)


![Image](https://github.com/user-attachments/assets/25e774d1-4d6d-416e-9329-9d153bcb3b06)

![Image](https://github.com/user-attachments/assets/d27ce810-6061-49ee-98d3-2402213499ab)

</details>

**View only Dashboard**

<details>

![Image](https://github.com/user-attachments/assets/9225183d-35d4-4245-ac1d-13dea5186a28)

![Image](https://github.com/user-attachments/assets/0e76ec5a-ddd6-4920-843f-728f0688fb34)


![Image](https://github.com/user-attachments/assets/1fe2dd25-48e3-47ed-94c4-7a4f099f4b7e)

![Image](https://github.com/user-attachments/assets/4c73ebcf-9ed4-48de-b40f-84c515ee3360)

![Image](https://github.com/user-attachments/assets/084c7374-9643-470c-8f16-822643c996f7)

![Image](https://github.com/user-attachments/assets/ef85b7c9-9e64-40fc-8a14-64d8ada2630d)

</details>
