### ISSUE TITLE
Allow programmatic removal of Site Kit's meta tag

### ISSUE THREAD

**Issue by ernee** [google/site-kit-wp#938]
Currently the meta tag placed by Site Kit in a website's source code cannot be accessed for removal by `remove_action` due to an [anonymous function](https://github.com/google/site-kit-wp/blob/84af0971ad44feed44dc93fe0f5e04a00dabf99d/includes/Plugin.php#L90-L94). Per a [request in the forums](https://wordpress.org/support/topic/meta-generator-tag/), there are use cases/ preferences to not have it. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* It should be possible to programmatically prevent Site Kit from outputting its `generator` meta tag in the head.

## Implementation Brief

* Allow altering (or removing) the Site Kit generator tag output by introducing a new filter `googlesitekit_generator` in the `$display_site_kit_meta` closure in the `Plugin` class.
* Put the entire meta tag as the initial value of the filter. As such, by definition, if passing an empty string to it the meta tag won't be rendered.

## QA Brief

* With the following code (e.g. in a mini plugin), the Site Kit generator tag should not be displayed:
```php
add_filter( 'googlesitekit_generator', '__return_empty_string' );
```

## Changelog entry

* Allow programmatic modification of the Site Kit generator meta tag.

**Comment by WebFactoryLtd** [comment]
Please move it to a "normal" function so we can `remove_action`. Thank you.

**Comment by avegao** [comment]
I find it absurd to see the version of the plugins in a meta tag. Why give clues to the enemy?

**Comment by ingeniumdesign** [comment]
the remove part dont work:
remove_action( 'wp_head', 'display_site_kit_meta' );

**Comment by herbie4** [comment]
How to taget the site kit metatag in a remove action? 

I tried this, but it doesn't work. 
`remove_action('wp_head', array( \Google\Site_Kit\Plugin::get_instance(), 'display_site_kit_meta' ) );`

Any ideas...?

**Comment by laurentdebricon** [comment]
Why give clues to the enemy? !!!

**Comment by L-X-T** [comment]
Yeah, please fix this!

**Comment by KeesCBakker** [comment]
Any updates on this?

**Comment by herbie4** [comment]
As this is still not resolved...
Here is a temporary fix to mask the version number. Just add this to wp-config.php

`// temp fix to hide Google site kit version number
define('GOOGLESITEKIT_VERSION', 'none');`

**Comment by grzegorz-janoszka** [comment]
Can we please have it fixed?

**Comment by L-X-T** [comment]
Hello, is anybody reading this issues at all? 11 months since we reported this issue and still not fixed?

Come on Googlers, what's up?

**Comment by aaemnnosttv** [comment]
@felixarntz how about we extract it to its own class with two public static methods: `register` and `render`?

Then `Plugin` would only need to `Generator_Tag::register()` and anyone who wants to unhook it can call:
```php
remove_action( 'wp_head', array( Generator_Tag::class, 'render' ) );
remove_action( 'login_head', array( Generator_Tag::class, 'render' ) );
```

If you would prefer to keep it in `Plugin`, I think we can simplify it slightly by making it a static method. Users shouldn't need to `get_instance` to unhook it IMO.

**Comment by felixarntz** [comment]
@aaemnnosttv Hmm, not sure. What's the problem of calling `get_instance`? I'd rather not introduce "static classes" just to make it more straightforward to unhook a method. Unhooking methods on a main "instance" is a practice I've seen in other object-oriented plugins as well.

**Comment by aaemnnosttv** [comment]
@felixarntz to recap our other conversation:

- We can expose a `googlesitekit_generator` filter on the output like WP does giving users full control of the output
- Did we agree to move the tag outside of the Plugin class? I would still opt for that, but not a requirement of this issue. We could keep it in place and just add the filter for now if you want. The added filter decouples how/where it is rendered so we're free to move this.

**Comment by felixarntz** [comment]
@aaemnnosttv I think we should keep the output in the class for now. Since we go with the simple filter approach, it won't be necessary to make access simpler in 3P code. It might generally make sense to outsource the code into a separate class, but I don't think it's really worth it, and we can keep this quite straightforward as is. I've updated the ACs and IB accordingly.

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by asvinb** [comment]
Before adding filter:
`<meta name="generator" content="Site Kit by Google 1.31.0" />` outputted in the page markup.

After adding filter:
Meta tag not outputted.

### QA: ✅
