### ISSUE TITLE
Add support for disconnecting Sign in With Google from user account page in WordPress admin

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#9380]
## Feature Description

It should be possible for users to disconnect their profile from their Google account in the account management screen in the WordPress admin (eg. `/wp-admin/profile.php`). It should also be possible for an admin to disconnect another user's Google account.

![Image](https://github.com/user-attachments/assets/8c3958f7-a213-4196-8a9a-cfa560f4838b)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A section under/near "Account Management" in the WordPress user profile screen (eg. `/wp-admin/profile.php`) should appear titled "Sign in with Google" should appear for a user with an associated Google account (eg. `googlesitekitpersistent_sign_in_with_google_user_id` value in user meta, see #9339).
  * There should be text explaining that the user can sign in with their Google account (showing the Google account ID/email address), along with a button labelled "Disconnect Google Account"
  * The "Disconnect Google Account" should remove the `googlesitekitpersistent_sign_in_with_google_user_id` user meta value, disconnecting this user's WordPress account from their Google account on the WordPress side.
* The proposed functionality should only appear on the WordPress user profile edit screen when the `signInWithGoogleModule` feature flag is enabled.
* The proposed functionality should only appear on the WordPress user profile edit screen when the Sign in with Google module is activated (eg. a Client ID has been provided and the user has completed setup of the module) and the user has a Google ID set

## Implementation Brief

* [x] Edit `includes/Modules/Sign_In_With_Google.php`:
   * Create a new public static function called `disconnect_url`, modelled on the following method, adding the key `googlesitekit-sign-in-with-google-disconnect-user`:
      * https://github.com/google/site-kit-wp/blob/cf9aebaffd4a1c7b72b44ee7a05c26842706e7b6/includes/Core/Util/Reset.php#L61-L69
   * Create a new public method `handle_disconnect_user`:
      * Remove the usermeta storing the Google user ID for this user using `delete_user_meta( get_current_user_id(), self::SIGN_IN_WITH_GOOGLE_USER_ID_OPTION );`
      * Redirect back to the Site Kit dashboard using `wp_safe_redirect`.
   * Create a new private method `render_disconnect_profile` method:
      * Check if the current user has a Google user ID saved using `get_user_meta( get_current_user_id(), self::SIGN_IN_WITH_GOOGLE_USER_ID_OPTION, true )`, if this usermeta value does not exist return early.
      * Otherwise, continue to render a header and button matching the copy in the AC, following the pattern used for the "Reset Site Kit" button:
      * https://github.com/google/site-kit-wp/blob/cf9aebaffd4a1c7b72b44ee7a05c26842706e7b6/includes/Core/Admin/Available_Tools.php#L46-L64
      * The button should link to a url returned by calling the static method `disconnect_url` implemented above.
   * Within the `register` method:
      * Call the new method to call the `handle_disconnect_user` method when the query disconnect query argument is present:
         * https://github.com/google/site-kit-wp/blob/cf9aebaffd4a1c7b72b44ee7a05c26842706e7b6/includes/Core/Util/Reset.php#L96-L103
      * Call the new method on the `edit_user_profile` hook using the `Method_Proxy_Trait`: `add_action( 'edit_user_profile',  $this->get_method_proxy( 'render_disconnect_profile' )  ) );`

### Test Coverage

* Update `tests/phpunit/integration/Modules/Sign_In_With_GoogleTest.php` confirming the usermeta value is removed during disconnection.

## QA Brief

* Users can disconnect their Google user_id from their user in WordPress. _Note: even if the user disconnects their user id, if the SiwG module is still connected and active, they will still be able to login with Google again and this ID re-added if their Google email still matches their Google user_id. Further if "Anyone can register" WP setting is enabled, then this setting does not stop the user from signing in again and re-connecting the user._
   * <img width="980" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHlRQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ae216de0811307ad41b7178b14d9147e754fc842/Screenshot%202024-11-04%20at%2016.25.59.png" alt="Screenshot 2024-11-04 at 16.25.59.png" />
   * This new settings panel is available on the edit profile page:
      * For admins, on their own profile edit page, and the edit page of other users on the site.
      * For users of all roles on their own profile edit page only.
   * The panel will only show if there is a Google user_id for the user (ie. if they have a connected Google account).
   * Once the user clicks disconnect, the user meta row which stores the Google user_id for this user will be deleted, the user will be redirected to the same profile edit page and will no longer see the Sign in with Google settings section. _Note: we don't show a success or error state for this action. It's unlikely to be a common actions so this should be ok for this setting._

## Changelog entry

* Add support for disconnecting associated Google account for sign in from WordPress user edit screen.

**Comment by tofumatt** [comment]
Looks good to me, IB ✅

**Comment by benbowler** [comment]
Vacation handover; this ticket is blocked by #9339, it's worth waiting for that one before picking this up as [my work here is ready for CR](https://github.com/google/site-kit-wp/pull/9616), but it will need to be updated with develop once the blocker is merged.

**Comment by kelvinballoo** [comment]
### QA Update ⚠ 

This is working well overall.
I do have one main query:

The AC screenshot shows a Google account ID in bracket.
Currently, on the implementation, this is not seen.
Should we be showing the ID there? ⚠ 

<Details>
AC:

![Image](https://github.com/user-attachments/assets/0d5151a5-7c1d-462a-88da-630e2a75ea47)

Current implementation:

![Image](https://github.com/user-attachments/assets/58074e01-419c-44a0-9a29-86bd57617c89)


</Details>
____________________________________________________________

Other than that, the other things are verified good ✅ 
- Users can disconnect their Google user_id from their user in WordPress. Even if the user disconnects their user id, if the SiwG module is still connected and active, they are still able to login with Google again and the SiwG section appears accordingly.
   <Details>
   
   https://github.com/user-attachments/assets/43abfe86-3da8-4230-8b89-1e935434d517

   </Details>

- This new settings panel is available on the edit profile page:
   - For admins, on their own profile edit page, and the edit page of other users on the site.
   - For users of all roles on their own profile edit page only. (Tested for subscriber and editor roles)
- The panel will only show if there is a Google user_id for the user (ie. if they have a connected Google account).
- Once the user clicks disconnect, the user meta row which stores the Google user_id for this user is deleted, the user is redirected to the same profile edit page and no longer sees the Sign in with Google settings section. 

   <Details>
   Editor profile:

   ![Image](https://github.com/user-attachments/assets/3231be21-5acb-4b39-8ec3-7ba3fac51bbe)

   Admin profile:
   https://github.com/user-attachments/assets/7b352fa2-e871-4a67-8e0c-e3ae30cbcfe5
   </Details>

**Comment by tofumatt** [comment]
> The AC screenshot shows a Google account ID in bracket.
Currently, on the implementation, this is not seen.
Should we be showing the ID there? ⚠

No, we've decided not to show the account ID in parenthesis; it's a bit ugly and not very useful as it's not a generally-exposed value for the Google Account in Google Account settings.

We thought about showing the email, but if they change their address that might be odd too, so we just left it blank 🙂
