### ISSUE TITLE
Add `signInWithGoogleModule` feature flag

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#9382]
## Feature Description

For the Sign in With Google epic/feature, we'll want a new feature flag: `signInWithGoogleModule`.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new feature flag (`signInWithGoogleModule`) should be available in the list of feature flags.
* It should be possible to toggle this feature on/off from the Tester Plugin.

## Implementation Brief

* [x] Add `signInWithGoogleModule` to the list of feature flags in `feature-flags.json`.
* [ ] Merge #9383

### Test Coverage

* No tests needed.

## QA Brief

* The `signInWithGoogleModule` should appear in the list of feature flags in the Tester plugin.
* Enabling the feature flag should not cause errors.
* Disabling the feature flag should not cause errors.

## Changelog entry

* Add the `signInWithGoogleModule` feature flag for Sign in With Google.

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified `signInWithGoogleModule` feature flag added.
- Verified enabling and disabling feature flag not cause any errors.

![image](https://github.com/user-attachments/assets/9792ac99-15c7-4f65-8823-cdb13c7f3a68)
