### ISSUE TITLE
Enfold theme prevents data from displaying on dashboard and other module pages

### ISSUE THREAD

**Issue by ernee** [google/site-kit-wp#939]
As reported in [this forum topic](https://wordpress.org/support/topic/charts-graphs-not-displaying/), when the[ Enfold theme](https://themeforest.net/item/enfold-responsive-multipurpose-theme/4519990) is activated the dashboard and module pages data does not load (but appears to be attempting retrieval). 

[Video of the issue](https://recordit.co/yqhWdPE9Kr)

Theme support advised user of [this resolution](https://kriesi.at/support/topic/google-site-kit-compatibility-issue/) to prevent Enfold's scripts from loading on Site Kit's admin pages , however is there anything that can be done on Site Kit's side to prevent this? 

## Steps to reproduce

1. Install and activate the [Enfold theme](https://themeforest.net/item/enfold-responsive-multipurpose-theme/4519990)
2. Go to the dashboard or module pages 
3. See data not displaying and attempting to load

## Screenshots

<img width="1269" alt="Enfold theme prevents data loading" src="https://user-images.githubusercontent.com/8108643/70085718-afc6bf80-15c5-11ea-9418-5012282112af.png">

## Additional Context

 - PHP Version: 7.1.33
 - OS: MacOS
 - Browser: Chrome
 - Plugin Version: 1.1.1
 - Device: MacBook Air

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Plugins or themes that load Google libraries should not conflict with those loaded by Site Kit

## Implementation Brief

The main problem is with this conditional
https://github.com/google/site-kit-wp/blob/9aef263e74be80c9023f32fbdf8d9644a73737d5/assets/js/components/google-chart.js#L49-L51

This causes the chart loader script to not be injected if `global.google` is already set. This was probably intended to be a logical `OR` but because it is an `AND` the chart library isn't loaded if `global.google` is set and so the chart stays in a permanent loading state.

In `assets/js/components/google-chart.js`
* Ensure that charts are loaded any time `global.google.charts` is not set
* Replace global `global.googleChartLoaded` loaded flag with a private local variable which defaults to whether or not `global.google.charts` is set to support charts already being loaded as well
* Merge #1096 

## Changelog entry

* Ensure that Google Charts JS library is loaded as expected even when a `window.google` global already exists because of another library.

**Comment by ibushong** [comment]
I just installed this plugin today and I'm experiencing the same issue (we also are using Enfold). Great timing :p

No errors are reported in the JS console. My experience is the same as in the video (though no "Unchecked runtime.last_error", which I believe is unrelated).

Very excited about this plugin! Mainly posting to raise awareness on this issue (as this is a very popular theme) and subscribe to updates. But I can potentially also help with debug/verification.

**Comment by cole10up** [comment]
**Tested**

I tried 2 different sessions:
One on my local with latest develop. Installed and activated SK, Installed and Activated Enfold and navigated to the dashboard.

My local:
![image](https://user-images.githubusercontent.com/57115907/72170207-56506e00-3385-11ea-9b1b-f9ab8a09e237.png)

Jurassic Ninja:
![image](https://user-images.githubusercontent.com/57115907/72170264-6a946b00-3385-11ea-839a-a73cef2c5c04.png)

This doesn't look to be an issue with the latest develop 1.2.0

**Comment by aaemnnosttv** [comment]
After looking at this with @cole10up, there's clearly a conflict here. I'm fairly certain that #993 will resolve this as it appears to be a JS issue with a shared dependency. Since that work is already in progress, we should circle back to test this once that issue is in QA or beyond.

**Comment by cole10up** [comment]
Retested this one just now after running regression on #993 

Still seeing this issue after activating Analytics. Notice: Infinite loading bar.

![image](https://user-images.githubusercontent.com/57115907/73818501-5edc6e80-47a2-11ea-8e69-4d06cf9972b2.png)

**Comment by felixarntz** [comment]
IB ✅

**Comment by cole10up** [comment]
This is verified fixed.

![image](https://user-images.githubusercontent.com/57115907/73855525-0d0b0700-47e9-11ea-9f78-a9598bf48a8e.png)

Passed QA ✅
