### ISSUE TITLE
Link to "Sites" after AdSense set-up needs reformatting

### ISSUE THREAD

**Issue by OisinOConnor** [google/site-kit-wp#94]
## Bug Description

Link from "Sites" after setting up an AdSense account is incorrect. 
## Steps to reproduce
Set-up AdSense on Site Kit with an existing account. After setup, click "Sites" link.

## Expected behavior
the "Sites" link should redirect you to the "Sites status" page for that url, if url already added.
Needed:
Change link to “Sites” in the post-setup screen from:
https://www.google.com/adsense/new/sites?url=http://example.com/&source=site-kit
to
https://www.google.com/adsense/new/sites?url=example.com&source=site-kit
i.e. remove http:// and trailing / from the url

## Screenshots

![fy1L0NB5YHu](https://user-images.githubusercontent.com/6488453/60444847-e7e06580-9c15-11e9-856b-e0dffa9b9d32.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Changelog entry

* Update external Adsense URLs to use local site's hostname rather than full URL.

## Acceptance criteria

* Sites link should point to the correct destination within AdSense FE. 

## Implementation Brief

Use hostname instead of `siteURL` in this line:
https://github.com/google/site-kit-wp/blob/9a262cd18c33995ce5ec81bc300ff055dff2a153/assets/js/modules/adsense/dashboard/adsense-in-process-status.js#L39

**Comment by ThierryA** [comment]
@OisinOConnor could you review this one and advise whether the URL is incorrect as reported in this issue?

**Comment by ivankristianto** [comment]
@OisinOConnor / @marrrmarrr 
what if the site url has subdomain or www? should we only use the root domain?

**Comment by OisinOConnor** [comment]
The best thing would be to only use the root domain. 2 scenarios:
1. User has already added domain. They will land on a page that has an "add subdomain" button.
2. User has not added the root domain yet (prerequisite for adding subdomain). They will land on the page to add the root domain. After they've added and verified, they'll have an option to add a subdomain after.

**Comment by felixarntz** [comment]
Implementation brief looks good!

**Comment by adamsilverstein** [comment]
QA passed.

I tested this and verified the URL is now correct and includes only the domain name, not the full URL:

 
![image](https://cl.ly/4fcc2ad0ba10/Site_Kit_by_Google_AdSense_9_Site_Kit_for_WordPress__WordPress_2019-07-17_08-25-04.jpg)

To test, set up AdSense, then change the filtered domain to a domain without any data, clear session storage and refresh AdSense page.

**Comment by aaron13223** [comment]
Hmmmm, my site is already approved yet it still shows "Getting you site ready for ads". So i can't seem to enable ads at all. Have to do it manually. The url of the website has www and adsense is approved for hostname. Though I already added www in subdomain

**Comment by aaemnnosttv** [comment]
Hi there 👋 Your issue sounds different than the one targeted for the focus of this particular issue. Please open a new issue for support! Thank you 😄
