### ISSUE TITLE
Backport existing AdSense logic into E2E tests

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#940]
Right now we don't have a good sense of the AdSense flow because:

1. AdSense is difficult to manually test
2. we lack E2E tests that verify our AdSense module's behaviour

This means we aren't sure that it's not clear if commits have changed important functionality in AdSense handling. The plan here is to implement a set of E2E tests that verify the current AdSense flow s, _even when incorrect_. This will at least codify our approach.

After these are implemented, we can find flows that are wrong, tweak the tests to be correct, and then get the code passing the tests.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Have E2E tests that verify the _existing_ behaviour of the AdSense code, even if that code is incorrect.

## Implementation Brief

* Implement an E2E test that runs through each account status as found in https://github.com/google/site-kit-wp/blob/84af0971ad44feed44dc93fe0f5e04a00dabf99d/assets/js/modules/adsense/dashboard/adsense-module-status.js#L40

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
@felixarntz should we close the existing E2E issues for AdSense (#269, #271, #347) in favor of this?

**Comment by felixarntz** [comment]
@aaemnnosttv That sounds good to me, I'll close them.

@tofumatt IB ✅ Please upload a first draft PR as soon as you have one or two initial e2e tests, so we can start reviewing early. Especially since the whole thing might take a while.

**Comment by tofumatt** [comment]
Moving this to blocked now as we're looking to quite significantly refactor the AdSense code and modules, and the amount of tests I wrote were minimal and unfinished. As stated before I'll try to push what I have if there's nothing else to work on, but as other things have been higher priority I've always pushed this one aside, so might as well move it out of the "in progress" column for now.

**Comment by felixarntz** [comment]
Not feasible for 1.2.0, so removing this.

**Comment by felixarntz** [comment]
No longer a focus; closing
