### ISSUE TITLE
De-emphasise/remove "subscriptions" in RRM setup CTA widget

### ISSUE THREAD

**Issue by nfmohit** [google/site-kit-wp#9402]
## Feature Description

![image](https://github.com/user-attachments/assets/0b058090-6882-4feb-9994-1b0a61bfbbdd)

The RRM setup CTA widget includes a mention of "subscriptions" which should be removed, as we do not support this feature as part of Phase 1 of the integration.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The description text of the RRM setup CTA widget should be updated according to the following:
	* Current: _Turn casual visitors into loyal readers and earn more from your content with subscriptions, contributions, ad optimization and reader insight tools._
	* New: _Turn casual visitors into loyal readers and earn more from your content with contributions, surveys, newsletter sign-ups and reader insight tools._

## Implementation Brief

* [ ] In `assets/js/modules/reader-revenue-manager/components/dashboard/ReaderRevenueManagerSetupCTABanner.js`:
	* [ ] Locate the paragraph tag containing the current text referenced in the ACs and replace that with the new text.

### Test Coverage

* Fix any failing tests.
* Update any failing VRT references.

## QA Brief

* Verify that the [ReaderRevenueManagerSetupCTABanner](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-readerrevenuemanager-components-dashboard-readerrevenuemanagersetupctabanner--default) story reflects the updated copy as outlined in the AC.

## Changelog entry

* N/A

**Comment by techanvil** [comment]
IB :white_check_mark:

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Tested RRM CTA widget under storybook and on site.
- Verified that RRM CTA widget copy updated as per AC-

_New: Turn casual visitors into loyal readers and earn more from your content with contributions, surveys, newsletter sign-ups and reader insight tools._

<details>

![image](https://github.com/user-attachments/assets/63d52127-eb60-4f6c-a396-aa688df9f07e)

![image](https://github.com/user-attachments/assets/aa0fba8d-8914-44b1-86a0-4c49da95f7f3)
