### ISSUE TITLE
Fix remaining issue where VRT test fails in CI when launching Chromium

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#9406]
## Bug Description

The fix applied via https://github.com/google/site-kit-wp/issues/9211 has improved the reliability of our VRT workflow, however it is still failing with some regularity with the following error:

```sh
      COMMAND | Command "test" ended with an error after [679.315s]
      COMMAND | Error: Failed to launch the browser process!
```

It does however look like a potentially different permutation of the error - in the example occurrences it's surrounded by "Unmatched GET" log messages which were not evident in previous iterations.

## Steps to reproduce

- Watch for failing VRT test runs in CI.
- They will intermittently fail with the above error.
- See these example test runs:
  - https://github.com/google/site-kit-wp/actions/runs/10890467296/job/30219259053
  - https://github.com/google/site-kit-wp/actions/runs/10881165268/job/30194143374

## Screenshots

![image](https://github.com/user-attachments/assets/67853eeb-11a4-4178-8669-76ba879a79fa)

## Additional Context

See the **Additional Context** section on https://github.com/google/site-kit-wp/issues/9211 for some relevant avenues that remain to be explored for the fix.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* VRT test runs should not fail with an error before all the screenshots are captured and the test has run to completion.

Note, additional issues should be raised if needed to follow up on separate avenues of investigation.

## Implementation Brief

*This IB is based on debug work in the PR #9412.*

* [ ] Update `docker/backstopjs/Dockerfile` to install chromium and it's requirements in a separate step and pass the `PUPPETEER_EXECUTABLE_PATH` constant like so:
   https://github.com/google/site-kit-wp/blob/60f81f1e226ea256864933a2d2ae938a28a0cd46/docker/backstopjs/Dockerfile#L7-L25
   *Why? This was based on [notes in puppeteers troubleshooting docs](https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#running-on-alpine). Alpine is not officially supported by chromium, so installing the required packages along with the install is vital.*

 * This new version of chromium will render many components slightly differently, so you need to run and update the VRT images once. After this is done future VRT runs will pass consistently ([eg.](https://github.com/google/site-kit-wp/pull/9412/files#diff-50b6e1f0011ce187192d67bf80e0a5c7f7ffa3f6ff36ac7e9955f00c4fc0a20a)).

 * Also this change highlights some new failing tests:

 * `AudienceSegmentation_Dashboard_AudienceSelectionPanel_Audience_creation_notice` and `Views/WPDashboardApp/WPDashboardWidgets/ReadyWithActivateAnalyticsCTA` for unknown reasons:
    * [ ] Add a delay of 1500ms to the `Modules/Analytics4/Components/AudienceSegmentation/Dashboard/AudienceSelectionPanel/AudienceCreationNoticeOneAdded` story allows this test to pass reliably.
    * [ ] Increase the delay to 6000ms for the `Views/WPDashboardApp/WPDashboardWidgets/ReadyWithActivateAnalyticsCTA` story.
 * `AdSense_Module_Overview_Widget` which was another case of the `DataBlockGroup` component causing issues (just like #9101)
    * [ ] [Update the dates in `stories/module-adsense-components.stories.js` to all be in the year 2021](https://github.com/google/site-kit-wp/pull/9412/files#diff-171c39270c4c8d22272d10b6b7c5ad530a4e39b40656444da2c7bcad6104876d).
    *Why?: The goal here is to update the faker seed so that we get smaller numbers which prevent the DataBlockGroup from iterating too much over the font size. By changing these years the data is smaller and the VRTs pass reliably. We will fix this more robustly in #9419.*

### Test Coverage

* Approve any changes to VRT images based on the chromium version change. They will compare consistently from now on.

## QA Brief

* View the VRTs `Visual Regression Testing / Run VR Tests` check on this ticket and confirm it complete successfully.

## Changelog entry

* Fix VRT test failures in CI when launching Chromium, ensuring tests run to completion without errors.

**Comment by aaemnnosttv** [comment]
IB ✅ !

**Comment by benbowler** [comment]
Adding a note here from chatting to @hussain-t about the CR of this ticket. I marked it blocked by #9101 (which is with @tofumatt as of 1 hour ago) because the VRTs listed in that ticket will fail here until fixed there. We should merge that ticket ASAP then continue to review this ticket and merge ASAP because every new test added before we merge this ticket requires the VRTs to be re-run for this PR. That's because the update version of Chromium renders most components slightly differently so any previously captured images are invalid.

**Comment by techanvil** [comment]
## QA ✅ 

Confirmed the VRT tests passed in the [test run for the PR](https://github.com/google/site-kit-wp/actions/runs/11218798294/job/31183377471?pr=9412):

![Image](https://github.com/user-attachments/assets/86a5ddb3-a889-424b-8533-cba3bc0cd634)

![Image](https://github.com/user-attachments/assets/642d119d-d3c2-4533-bd5e-9cb55dea81fe)
