### ISSUE TITLE
Missing parameter(s): nonce, site_id, site_secret

### ISSUE THREAD

**Issue by jaybayron** [google/site-kit-wp#941]
## Bug Description
It was working before. I transfer the site to my local xampp for update and reupload it back to my hosting server.
This error occurs every time I try setting up site kit

An error occurred: We were unable to send credentials to your WordPress site. Please go back to your site and restart the setup. The following error was returned: Missing parameter(s): nonce, site_id, site_secret

## Steps to reproduce

- Uninstall/reinstall site kit.
- remove other security plugin like wordfence, siteaudit and deactivate wprocket.
- same error

## Screenshots

![image](https://user-images.githubusercontent.com/56905129/70211669-9d3cb980-1770-11ea-96d6-5e7c8dcbe208.png)

## Additional Context

 - PHP Version: 7.3
 - OS:
 - Browser chrome
 - Plugin Version 1.1.1
 - Device: Desktop

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
@jaybayron We've moved Site Kit support to the WordPress support forums. If you're still encountering any issues during setup please open a [support topic](https://wordpress.org/support/plugin/google-site-kit/#new-post) there we'd be happy to assist.
