### ISSUE TITLE
Insufficient permission error showing for Audience widget on secondary admin main dashboard.

### ISSUE THREAD

**Issue by mohitwp** [google/site-kit-wp#9411]
## Bug Description

I noticed that if I log in as a secondary admin and go directly to the main dashboard without visiting the 'View Only Dashboard,' I receive an insufficient permission error for the Audience widget. However, if I either disconnect and visit the 'View Only Dashboard' first or access the 'View Only Dashboard' before signing in, I don’t encounter the insufficient permission error.

Note: All admins have view-only access to Analytics.

## Steps to reproduce

1. Set up SK as primary admin and share Analytics with Admin users
2. Create secondary admin.
3. Login as Secondary admin and sign in.
4. See insufficient permission error for the Audience widget on main dashboard.
5. Disconnect the site kit.
6. Visit 'View only dashboard'.
7. Login again as secondary admin.
8. Now insufficient permission error will not appear for Audience widget on main only dashboard.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Given that Audience Segmentation has been setup by a primary admin, the Analytics module has been shared, and a secondary admin who _doesn't_ have view access to the connected property signs into Site Kit:
   * When Audience Segmentation is set up for the secondary admin, they should not see an "insufficient permissions" error.
   * The `sync-audiences` endpoint should be requested successfully for the secondary admin using the credentials of the primary admin and the Audience Segmentation setup should proceed as usual.
* If the `sync-audiences` endpoint is requested by a view-only user it should return a 403 Forbidden response.

## Implementation Brief

* [x] Make the `sync-audiences` endpoint shareable.
* [x] In the `sync-audiences` request handler, check if the user is authenticated via `$this->authentication->is_authenticated()`. If not, return a `WP_Error` with status `403`, code `forbidden`, and the error message `User must be authenticated to sync audiences`.

### Test Coverage

* Add PHPUnit test coverage for the above changes.

## QA Brief

* Follow the first three steps in the "Steps to reproduce" section.
* Verify that the secondary admin does not see an "Insufficient permissions" error in the Audience widget area.
* Verify that the Audience widgets are displayed correctly for the secondary admin.

## Changelog entry

* Improve the availability of the audience widget for secondary administrators.

**Comment by techanvil** [comment]
Hi @mohitwp, I'm unable to reproduce the issue. When I login as a secondary admin with view access to the property and sign in, I see the audience tiles as expected without an insufficient permissions error:

![image](https://github.com/user-attachments/assets/5e147dc6-67ac-49d4-93a6-399a3840c9a2)

The video you mentioned didn't upload properly, please can you re-upload it so I can take a closer look? I'd suggest that you also try reproducing the issue again yourself to verify whether it's still occurring for you.

**Comment by techanvil** [comment]
Thanks @mohitwp. Are you sure your secondary admin has view access to the property?

When the user has view access to the property, I am not seeing the error:

https://github.com/user-attachments/assets/1f46dc52-56a5-4f48-b34f-5338c34d0ad4

It's only when I remove the view access and try again that I do see the error:

https://github.com/user-attachments/assets/5e89e6ad-ca17-466d-b5c5-2779bcbfd790

Please double check your user's permissions for the property. If you are still able to reproduce the error having confirmed the view access is present, let's jump on a call to figure this one out.

**Comment by hussain-t** [comment]
Hi @mohitwp, I’ve verified the issue with the second admin, who doesn’t have permissions for the connected property, which is expected behavior. However, the second admin with the necessary permissions can successfully set up the audiences and view the widget tiles without any issues.

Please ensure the second admin user has the necessary permissions to access the connected property.

https://github.com/user-attachments/assets/45ef7bb6-c63a-4360-b71c-bf6184bdf4c8


https://github.com/user-attachments/assets/8c6e6f20-aed4-4ae7-9fb5-e803e6dad8b6

cc: @techanvil

**Comment by mohitwp** [comment]
@techanvil 

I discussed this with @hussain-t as well. It seems like an issue, but I would like to know your thoughts.

The 'Insufficient permission' error stops appearing on the main dashboard if the admin user visits the view-only dashboard once. After visiting the view-only dashboard, the 'Insufficient permission' errors do not appear.

Note: The second admin only has view-only access to Analytics provided through dashboard sharing. I have not given any additional access to the secondary admin through the analytics console.

**Steps:**

1. Admin A sets up SK and enables groups.
2. Shares analytics or any other module with all users, including admin.
3. Logs in as Admin B.
4. Signs into SK and visits the main dashboard.
5. Sees the 'Insufficient permission' error on the main dashboard under AS widgets.
6. Disconnects SK.
7. Visits the view-only dashboard.
8. Logs in again as Admin B and reconnects SK.
9. Now the 'Insufficient permission' error will not appear on the main dashboard.

As per my understanding, if we have not provided any additional access to the secondary admin through the analytics console, the error appearance should be consistent. Currently, the error disappears if the second admin visits the view-only dashboard once.

https://github.com/user-attachments/assets/a6e3c183-1c7e-4db1-ba2c-fad95806621b

**Comment by techanvil** [comment]
Hi @mohitwp, thanks for your patience and spelling this out for me. I now understand the issue and it is indeed something we need to fix.

Essentially, we should not expect to see the insufficient permission error when the secondary admin signs in once Analytics has been shared by the primary admin. What's happening is the `sync-audiences` endpoint is currently not shareable, so when the secondary admin makes the request they are doing so with their own credentials.

We chose to _not_ make the endpoint shareable so avoid exposing it to the view-only user, but didn't take this scenario into account. To fix this we can make the endpoint shareable but only allow authenticated users to call it. A view-only user already skips calling the endpoint during setup so it's an easy change to make. I've drafted the AC and IB. Thanks for spotting this one!

**Comment by nfmohit** [comment]
IB ✅

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified that 'Insufficient permission error not showing for Audience widget on secondary admin main dashboard when Analytics is shared by primary admin.
- Verified that the sync-audiences endpoint  requested successfully for the secondary admin.
- Verified that the sync-audiences endpoint  not requested for the secondary admin if analytics is not shared with admin.
- Verified that the sync-audiences endpoint not requested on view only dashboard.
- Note : Console error related to Audience widgets showing on secondary admin main dashboard and view only dashboard. This error will be address under https://github.com/google/site-kit-wp/issues/9445


<details>

Sync Audience endpoint successfully requested on main dashboard of secondary admin

![Image](https://github.com/user-attachments/assets/420bbe33-84a0-4b6d-8d37-5ad4e62504a9)

View only dashboard

![Image](https://github.com/user-attachments/assets/799f1524-9ad4-4104-b40c-2524e4f31fb7)


Screencast 

https://github.com/user-attachments/assets/c54bb9d7-ea16-4f29-b9a2-e92608787354

</details>
