### ISSUE TITLE
Optimize how we generate authentication proxy setup/permissions URLs

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#942]
We should improve a bit how we generate URLs to the `/site-management/setup/` and `/site-management/permissions/` URLs on the authentication proxy.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `OAuth_Client::get_application_name()` method should become a public method on `Google_Proxy`, since that application name is purely related to the proxy. The call to `$client->setApplicationName` in `OAuth_Client::setup_client` should only happen if the proxy is being used (i.e. on the `Google_Site_Kit_Proxy_Client`).
* The `OAuth_Client::get_proxy_setup_supports()` method should become a private method `Google_Proxy::get_supports()`.
* A new method `Google_Proxy::setup_url( Credentials $credentials, $query_params = array() )` should be introduced as a replacement for `OAuth_Client::get_proxy_setup_url()`:
    * The method should basically be a copy of the existing method and automatically set some query parameters following the same logic as present in the current method, with the difference that the parameters set should amend the provided object. All parameters set in the current method should be set in the new one as well, except for `code` and `scope`.
        * `site_id` should be based on the passed `Credentials` instance.
        * `application_name` and `supports` should be based on the above new methods in `Google_Proxy`.
    * The `googlesitekit_proxy_setup_url_params` filter should be maintained in the new method, but its extra parameters `$access_code` and `$error_code` should be removed.
* The `OAuth_Client::get_proxy_setup_url()` method should for now become a wrapper around the new `Google_Proxy::setup_url()`. It should essentially just call the new method, passing the `Credentials` instance, as well as setting the `scope` and `code` query parameters so that the behavior is not altered from today's.
* A new method `Google_Proxy::permissions_url( Credentials $credentials, $query_params = array() )` should be introduced as a replacement for `OAuth_Client::get_proxy_permissions_url()`:
    * The method should basically be a copy of the existing method and automatically set some query parameters following the same logic as present in the current method, with the difference that the parameters set should amend the provided object. All parameters set in the current method should be set in the new one as well, except for `token`.
        * `site_id` should be based on the passed `Credentials` instance.
        * `application_name` and `supports` should be based on the above new methods in `Google_Proxy`.
* The `OAuth_Client::get_proxy_permissions_url()` method should for now become a wrapper around the new `Google_Proxy::permissions_url()`. It should essentially just call the new method, passing the `Credentials` instance, as well as setting the `token` query parameter so that the behavior is not altered from today's.

#### includes/Core/Authentication/Google_Proxy.php

* Move the `OAuth_Client::get_application_name()` method as a public static method to the `Google_Proxy` class;
* Merge `OAuth_Client::get_proxy_setup_supports` and `OAuth_Client::supports_file_verification` methods into one new `Google_Proxy::get_supports()` method;
* Add a new public method `Google_Proxy::setup_url( Credentials $credentials, $query_params = array() )`. It should replicate functionality from the `OAuth_Client::get_proxy_setup_url()` method except setting `code` and `scope` query arguments and except using `$access_code` and `$error_code` in the `googlesitekit_proxy_setup_url_params` filter.
* Add a new public method `Google_Proxy::permissions_url( Credentials $credentials, $query_params = array() )`. It should replicate functionality from the `OAuth_Client::get_proxy_permissions_url()` method except setting the `token` query argument.

#### includes/Core/Authentication/Clients/Google_Site_Kit_Proxy_Client.php

* Update the constructor of the `Google_Site_Kit_Proxy_Client` class to call `$this->setApplicationName( Google_Proxy::get_application_name() )` after calling the parent constructor;

#### includes/Core/Authentication/Clients/OAuth_Client.php

* Update the `OAuth_Client::get_proxy_setup_url()` method to call the `Google_Proxy::setup_url` method providing credentials and an array with `code` and `scope` query arguments;
* Update the `OAuth_Client::get_proxy_permissions_url()` method to call the `Google_Proxy::permissions_url` method providing credentials and an array with the token query argument;
* Remove `$client->setApplicationName( $application_name );` call from the `OAuth_Client::setup_client` method;
* Remove `get_application_name`, `get_proxy_setup_supports` and `supports_file_verification` methods.

### Test Coverage

* Update existing tests if any is failing due to the aforementioned changes.

### Visual Regression Changes

* N/A

## QA Brief

* Make sure that the described functionality has been correctly transitioned to the Google_Proxy class.

## Changelog entry

* N/A

**Comment by aaemnnosttv** [comment]
@felixarntz just want to confirm that this issue and its ACs are still relevant in light of some related changes coming in #1857 and #1985 ?

**Comment by felixarntz** [comment]
@aaemnnosttv That's a fair point. I'll move this back to AC for now, so we can revisit once those two are in.

**Comment by felixarntz** [comment]
@aaemnnosttv Added ACs for this one. I've decided to keep the similar `OAuth_Client` methods for now, as wrappers. We can remove them as a follow-up issue and then rewrite the related calls. I'm also thinking we should try to find a way to get rid of that `googlesitekit_proxy_setup_url_params` filter - would be more straightforward to have the method purely arguments-driven.

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by aaemnnosttv** [comment]
## QA ⚠️

* Both new methods on `Google_Proxy` work as expected, but are named differently than in ACs.
* The ACs also mention the presence of a `supports` query parameter to the URL returned by `Google_Proxy::permissions_url` however this is not present in the current `OAuthClient::get_proxy_permissions_url` method. This is likely a mistake in the original definition, but raising for completeness.

<details>
    <summary>AC checklist</summary>

* [x] The `OAuth_Client::get_application_name()` method should become a public method on `Google_Proxy`, since that application name is purely related to the proxy. The call to `$client->setApplicationName` in `OAuth_Client::setup_client` should only happen if the proxy is being used (i.e. on the `Google_Site_Kit_Proxy_Client`).
* [x] The `OAuth_Client::get_proxy_setup_supports()` method should become a private method `Google_Proxy::get_supports()`.
* ⚠️ A new method `Google_Proxy::setup_url( Credentials $credentials, $query_params = array() )` should be introduced as a replacement for `OAuth_Client::get_proxy_setup_url()`:  
    **The implemented method is `Google_Proxy::get_setup_url` rather than `Google_Proxy::setup_url`**
    * [x] The method should basically be a copy of the existing method and automatically set some query parameters following the same logic as present in the current method, with the difference that the parameters set should amend the provided object. All parameters set in the current method should be set in the new one as well, except for `code` and `scope`.
        * [x] `site_id` should be based on the passed `Credentials` instance.
        * [x] `application_name` and `supports` should be based on the above new methods in `Google_Proxy`.
    * [x] The `googlesitekit_proxy_setup_url_params` filter should be maintained in the new method, but its extra parameters `$access_code` and `$error_code` should be removed.
* [x] The `OAuth_Client::get_proxy_setup_url()` method should for now become a wrapper around the new `Google_Proxy::setup_url()`. It should essentially just call the new method, passing the `Credentials` instance, as well as setting the `scope` and `code` query parameters so that the behavior is not altered from today's.
* ⚠️ A new method `Google_Proxy::permissions_url( Credentials $credentials, $query_params = array() )` should be introduced as a replacement for `OAuth_Client::get_proxy_permissions_url()`:  
    **The implemented method is `Google_Proxy::get_permissions_url` rather than `Google_Proxy::permissions_url`**
    * [x] The method should basically be a copy of the existing method and automatically set some query parameters following the same logic as present in the current method, with the difference that the parameters set should amend the provided object. All parameters set in the current method should be set in the new one as well, except for `token`.
        * [x] `site_id` should be based on the passed `Credentials` instance.
        * [ ] `application_name` and `supports` should be based on the above new methods in `Google_Proxy`.  
        **⚠️ `supports` is not included, but was not included in previous `OAuthClient::get_proxy_permissions_url` either**
* [x] The `OAuth_Client::get_proxy_permissions_url()` method should for now become a wrapper around the new `Google_Proxy::permissions_url()`. It should essentially just call the new method, passing the `Credentials` instance, as well as setting the `token` query parameter so that the behavior is not altered from today's.

</details>

**Comment by aaemnnosttv** [comment]
@felixarntz – I've opened a quick follow-up PR to address the above if needed. If not, we can simply close it, and this is good to go 👍

**Comment by felixarntz** [comment]
@aaemnnosttv Good catch - merged that PR!
