### ISSUE TITLE
Temporarily Hidden badge UX issues

### ISSUE THREAD

**Issue by kelvinballoo** [google/site-kit-wp#9421]
## Bug Description

2 Issues to highlight:
- When we click on the 'i' for the 'Temporarily hidden' badge, it will check on and off the corresponding checkbox and also bring up the tooltip. It's a bad UX.
   <Details>
   
   https://github.com/user-attachments/assets/cbf8027a-4438-41c4-94df-e60236b87da6

   </Details>

- On mobile, the experience is a bit odd as well. It seems like when we tap and lift off our finger, the tooltip will appear and disappear. It seems like for the tooltip to stay, we need to keep our finger there.
   <Details>

   https://github.com/user-attachments/assets/9f348dd6-9261-4a3b-a51f-6ae33f0b14af

   </Details>

## Steps to reproduce

1. Enable audience segmentation feature and enable the visitor groups. Add the non Site Kit created audience to audience tile like "All visitors" and also a SK created audience "New Visitors"

2. In the tester plugin, set Analytics >  Force Analytics report data to Zero. Also, set Analytics Partial Data >  Force Analytics audience partial data state to last-28-days. Save changes.

3. Go to Site Kit dashboard and to audience tile section. You will see the tile in collecting data status with the link to hide the tile temporarily ( "Temporarily hide" ).

4. Click on the "Temporarily hide" link for "All Visitors", that will hide the tile.

5. Open the audience selection panel. There should be a "Temporarily Hidden" badge with a tooltip.

Click on the 'i' icon for the "Temporarily Hidden" badge and you will notice it will check on and off the checkbox.
Also, when tapping on mobile, the UX is weird. The tooltip only appears as long as we press the tooltip. If we lift the finger, it's gone.

## Additional Context

 - PHP Version: 
 - Browser: [e.g. chrome, safari]
 - Plugin Version: [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Clicking on a badge in the Audience Selection Panel should not toggle the item's checkbox.
* Clicking on the information icon in the "Temporarily hidden" badge should show the tooltip for the icon. It should not be necessary to hold the touch on a mobile device as per the bug description.

## Implementation Brief

* [ ] Move the rendering of the badge from the `SelectionBox` to the `Checkbox` component, ensuring it's rendered outside the label.
* [ ] Finish off PR https://github.com/google/site-kit-wp/pull/9422 - it should just need tests & stories.

Note, this issue only needs to tackle the GM2 version of `Checkbox` - we can port the changes across to the GM3 version to keep them aligned in a separate issue, https://github.com/google/site-kit-wp/issues/9423.

### Test Coverage

* Add test cases for the badge rendering to the `Checkbox` test suite.
* Add instances of checkboxes with badges to the `Checkbox` story.
* Fix any failing tests.

## QA Brief

* Follow the steps to reproduce and verify that the reported issues no longer exist.

## Changelog entry

* Fix UX issues with the "Temporarily hidden" badge in the Audience Selection panel by ensuring the info icon only shows the tooltip without toggling the checkbox and improving tooltip behavior on mobile.

**Comment by nfmohit** [comment]
IB ✅

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on main environment.
- Verified Temporarily badge UX on both desktop and mobile devices.
- Verified that clicking on  'i' icon for the "Temporarily Hidden" badge do not check on and off the checkbox.

<details>

Desktop -


https://github.com/user-attachments/assets/edcdca51-d080-4a76-b39f-fa144691fa07

Mobile -


https://github.com/user-attachments/assets/f7a7a980-0b23-4b3f-bbcc-3033f5fc1d41

</details>
