### ISSUE TITLE
Ads PAX Beta - Update Ads Setup Text on Connect More Services Screen

### ISSUE THREAD

**Issue by 10upsimon** [google/site-kit-wp#9425]
## Feature Description

For users enrolled in the Beta phase of the Ads PAX integration (those using the mini plugin), the Ads module setup text appearing on the "Connect More Services" screen is required to be updated to be more reflective of a scenario where users do not have an existing Ads account. 

The new setup text should read as follows:

`Grow sales, leads or awareness for your business by advertising with Google Ads`

![Site Kit by Google Settings ‹ sitekit 10uplabs com — WordPress 2024-09-27 at 11 19 35 AM](https://github.com/user-attachments/assets/e2952d62-814d-446f-a294-71f78691d25d)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* For users enrolled in the Beta phase of the Ads PAX integration (those making use of the mini plugin), the text within the Ads module setup card in the "Connect More Services" tab of `Google Site Kit > Settings` should be amended to read as follows: "Grow sales, leads or awareness for your business by advertising with Google Ads"
    * This change of text should only be applied when the `adsPAX` feature flag is detected.

## Implementation Brief

* [x] Within `includes/Modules/Ads.php`
    * [x] Within the `setup_info()` method:
        * [x] Conditionally alter the string value of the `description` array key based on whether the result of `Feature_Flags::enabled( 'adsPax' )` is `true` or not.

### Test Coverage

* N/A

## QA Brief

* Go to Settings -> Connect More Services, check the Ads module copy:
   * With the adsPAX feature flag disabled the copy should be: "Track conversions for your existing Google Ads campaigns"
   * With the adsPAX feature flag enabled the copy should be: "Grow sales, leads or awareness for your business by advertising with Google Ads"

## Changelog entry

* Update copy text in Google Ads module when Partner Ads Experience is enabled.

**Comment by 10upsimon** [comment]
> @10upsimon Perhaps it will be more straightforward to change it directly in the backend when feature flag is enabled, in `Google\Site_Kit\Modules\Ads::setup_info`?

@zutigrm ya, good shout, let me update.

**Comment by zutigrm** [comment]
Thanks @10upsimon IB ✅
