### ISSUE TITLE
Respect Analytics tracking exclusions when implemented via Tag Manager

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#944]
## Feature Description

Currently the settings for excluding subsets of users from Analytics tracking is limited to the implementation by the Analytics module itself. However, many users implement Analytics via Tag Manager and lose this granularity in their collected metrics as a result.

We can do this by opting out of tracking on a per-UA code basis, or for ALL tracking altogether.

#### Opt out of tracking for `UA-XXXXX-Y`

```js
window['ga-disable-UA-XXXXX-Y'] = true;
```

The challenge with this approach is we may not know what UA code the user is using via Tag Manager.

#### Opt out of ALL tracking

```js
window._gaUserPrefs = { ioo: () => true };
```

See https://developers.google.com/analytics/devguides/collection/analyticsjs/user-opt-out

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Based on whether tracking the current user is disabled:
    * Instead of not rendering our GA snippet, include `window._gaUserPrefs = { ioo: () => true };` in the page to disable GA tracking for this request altogether.

## Implementation Brief

* Add a new private function: `Analytics::print_tracking_opt_out` to output the following
    ```html
    <script type="text/javascript">window["_gaUserPrefs"] = { ioo : function() { return true; } }</script>
    ```  
    This is the exact code added by the [official Chrome extension](https://chrome.google.com/webstore/detail/google-analytics-opt-out/fllaojicojecljbmefodhfapmkghcbnh?hl=en)
* Add an action on `wp_head` in `Analytics::register` to conditionally call `print_tracking_opt_out` if `$this->is_tracking_disabled()`
* Remove existing guards to output snippet using `is_tracking_disabled`
    - `enqueue_gtag_js`
    - `print_amp_gtag`
    - `print_amp_client_id_optin` (Removed in #1160)

## QA Brief

We need to test that when the Analytics module is configured and set to exclude logged-in users that the tracking opt-out is added (on the front-end only).

1. Install [Tag Assistant](https://chrome.google.com/webstore/detail/tag-assistant-by-google/kejbdjndbnbjgmefkgdddjlbokphdefk) Chrome extension  
Note that when opt-out is added as a result of tracking being **disabled**, Tag Assistant will turn yellow/orange and show it in "Where to optimize"  
![image](https://user-images.githubusercontent.com/1621608/76338917-14e72b00-6302-11ea-82b4-fb1326a62dd8.png)
1. Set up Site Kit and the Analytics module with default settings (logged in users should be excluded from tracking)
1. Ensure Site Kit screens **do not** show the orange opt-out enabled in Tag Assistant
1. Go to the frontend while logged-in
1. Ensure the orange opt-out **is shown** in Tag Assistant
1. Go to the frontend while NOT logged-in
1. Ensure the orange opt-out **is NOT shown** in Tag Assistant

Now we need to make sure that the opt-out code is not added when tracking is not disabled

1. Edit Settings for Analytics and toggle off "Logged-in users" under "Exclude from Analytics"
1. Ensure Site Kit screens **do not** show the orange opt-out enabled in Tag Assistant
1. Go to the frontend while logged-in
1. Ensure the orange opt-out **is NOT shown** in Tag Assistant
1. Go to the frontend while NOT logged-in
1. Ensure the orange opt-out **is NOT shown** in Tag Assistant

**To test with Tag Manager**
1. Edit settings for Analytics and **choose "Remove snippet"** to prevent the module from outputting the Analytics tracking code (since we're going to implement it from Tag Manager instead)
1. Go to https://tagmanager.google.com with your Google Account
1. Create a new web container in your Tag Manager account
1. Create a new tag in your new container  
  Type: Analytics, provide a tracking ID to use (can be same as in Analytics module), and set Trigger to All Pages  
![image](https://user-images.githubusercontent.com/1621608/76341234-6c3aca80-6305-11ea-94fe-612e8191c8c7.png)
1. Create another tag: Custom HTML to simply log something in the console to know that it's loaded  
![image](https://user-images.githubusercontent.com/1621608/76341521-d8b5c980-6305-11ea-84c9-3943dd5b5175.png)  
Set trigger to also run on all pages
1. Configure Tag Manager module to use the new container
1. With Analytics module configured to exclude logged-in users, go to the frontend while logged-in
1. Ensure the console log is shown in the console to check that the container is loaded
1. Ensure the orange opt-out **is shown** in Tag Assistant and no page views are recorded for Google Analytics
1. Go to the frontend while NOT logged-in
1. Ensure the console log is shown in the console to check that the container is loaded
1. Ensure the orange opt-out **is NOT shown** in Tag Assistant and page view is recorded in Google Analytics for the configured property (shown in Tag Assistant)

## Changelog entry

* Respect Analytics tracking exclusion of logged-in WordPress users also if Tag Manager is used.

**Comment by felixarntz** [comment]
@aaemnnosttv Since this is for GTM, we need to think about how we would determine whether to disable tracking. We shouldn't have duplicate settings. At the moment, we could rely on GA settings in GTM because it is a dependency, but in the future when it's decoupled, GA might not be active.

As you mentioned already, #859 would come in handy. I think we should look at that one sooner than later.

**Comment by marrrmarrr** [comment]
@felixarntz where would you say we stand on this one, now that #859 is finished?

**Comment by aaemnnosttv** [comment]
@felixarntz this is rather trivial to implement if Analytics is active (see current IB). If we want to think farther ahead to something which isn't coupled to Analytics being active, that means we would need to add the same settings UI for Tag Manager as we have for Analytics for tracking exclusions.

We should also allow this to be filtered the way it is in Analytics now
https://github.com/google/site-kit-wp/blob/8b75b993eb01666fe1ce90cf87935fabd6145cd3/includes/Modules/Analytics.php#L124-L136

I feel like this warrants a new standalone setting which is controlled from both modules (regardless of which is active). Essentially a global version of `trackingDisabled` (above), but one that stores exclusions. The return value should also pass through the same filter as above.

Let me know if this sounds like the right direction. The alternative of keeping the value in the analytics setting and manipulating it or referencing it when Analytics itself may not be active seems wrong.

**Comment by felixarntz** [comment]
@aaemnnosttv I've discussed this with @marrrmarrr before and we decided to keep this within Analytics for now. The main reason is that tracking may mean different things for different services. For this case, it is both related to Analytics, and furthermore GTM depends on Analytics for being active anyway, so it should be kept in the Analytics module.

Let's keep this issue only focused on the implementation fix to support Analytics via GTM by placing the opt-out snippet (rather than only placing our GA snippet only when needed).

**Comment by aaemnnosttv** [comment]
Okay, that makes things easier for sure. I thought the plan was to decouple these modules in the future so we would need a shared setting for this kind of thing. I'll update the IB now 👍

**Comment by felixarntz** [comment]
There is that plan, but it's still very vague and actually quite complex to scope out. We can deal with that when we get there.

**Comment by felixarntz** [comment]
IB ✅

**Comment by aaemnnosttv** [comment]
Bringing this back to execution due to a bug I found causing the opt-out script to be output in wp-admin.

**Comment by cole10up** [comment]
**Tested**

Enabled Tag Manager after installing latest develop and Analytics Module

**Analytics**

**Navigating around Admin on the BE doesn't show any tags:**
![image](https://user-images.githubusercontent.com/57115907/76488796-c1e5a480-63e3-11ea-9276-95f85e4b54ce.png)

![image](https://user-images.githubusercontent.com/57115907/76488805-ca3ddf80-63e3-11ea-9413-db12e9df9969.png)

Navigated to FE while logged in checked Tag Assistant:
![image](https://user-images.githubusercontent.com/57115907/76488819-d7f36500-63e3-11ea-8b9e-d54e3d280c5b.png)

Navigated to FE while not logged in and checked Tag Assistant:
![image](https://user-images.githubusercontent.com/57115907/76488851-f48f9d00-63e3-11ea-9b7b-43f93c057bb3.png)

Toggled off "Logged-in users" under "Exclude from Analytics"
![image](https://user-images.githubusercontent.com/57115907/76488929-328cc100-63e4-11ea-990b-97ee0dd49986.png)

![image](https://user-images.githubusercontent.com/57115907/76488962-4df7cc00-63e4-11ea-8bc1-2bbcf93a32bd.png)

Navigated to FE while logged in checked Tag Assistant:
![image](https://user-images.githubusercontent.com/57115907/76489002-623bc900-63e4-11ea-8912-175b6c5cfb39.png)

Navigated to FE while not logged in and checked Tag Assistant:
![image](https://user-images.githubusercontent.com/57115907/76489753-8d271c80-63e6-11ea-8b1c-69bb11f0c01a.png)

**Tag Manager**

Removed Analytics Snippet
![image](https://user-images.githubusercontent.com/57115907/76489791-a29c4680-63e6-11ea-9e9e-edf4ff7686be.png)

![image](https://user-images.githubusercontent.com/57115907/76489791-a29c4680-63e6-11ea-9e9e-edf4ff7686be.png)

Created a tag in Tag Manager:
![image](https://user-images.githubusercontent.com/57115907/76490176-a381a800-63e7-11ea-904c-4e7108112b93.png)

Created second tag in Tag Manager
![image](https://user-images.githubusercontent.com/57115907/76490327-13902e00-63e8-11ea-9b65-3b5a79cda8a1.png)

Configured Tag Manager in SK selecting my container
![image](https://user-images.githubusercontent.com/57115907/76491421-dbd6b580-63ea-11ea-80ce-296bd5b8d655.png)

Flipped logged in users exclusion toggle and saved
![image](https://user-images.githubusercontent.com/57115907/76491487-09bbfa00-63eb-11ea-8bde-e135264eacb5.png)

![image](https://user-images.githubusercontent.com/57115907/76491541-3708a800-63eb-11ea-8a1c-24cba15d7eaa.png)

**Console is showing a 404 error per my script tag**
![image](https://user-images.githubusercontent.com/57115907/76491722-9f578980-63eb-11ea-9069-9fa96a37ee6a.png)

![image](https://user-images.githubusercontent.com/57115907/76491757-af6f6900-63eb-11ea-8ab0-37566e4e77dc.png)

Navigated to FE while logged in checked Tag Assistant:
![image](https://user-images.githubusercontent.com/57115907/76491612-60293880-63eb-11ea-96ac-156dc40065f8.png)

**Console is showing a 404 error per my script tag**

Navigated to FE while not logged in and checked Tag Assistant:
![image](https://user-images.githubusercontent.com/57115907/76491938-29075700-63ec-11ea-82bf-9fa432775e7e.png)

@aaemnnosttv - I followed the QA steps properly except when creating Tag variables, I tried a few things but it wasn't clear what to place for the tracking ID setting I tried Page URL, Page Path and Page Hostname still seeing an error in tag assistant

![image](https://user-images.githubusercontent.com/57115907/76492103-a0d58180-63ec-11ea-992f-e3773dbdf505.png)

**Comment by cole10up** [comment]
Update:

Seems my container wasn't published. 

**Retesting**
Navigated to FE while logged in checked Tag Assistant:
![image](https://user-images.githubusercontent.com/57115907/76492646-f8c0b800-63ed-11ea-8d8e-1adaa2997ed2.png)

Checked console
![image](https://user-images.githubusercontent.com/57115907/76492701-155cf000-63ee-11ea-94d0-319097a06f23.png)

Navigated to FE while not logged in and checked Tag Assistant:
![image](https://user-images.githubusercontent.com/57115907/76492811-5b19b880-63ee-11ea-99c3-741c4ace9204.png)

Not seeing orange message but showing an error for property ID.

**Comment by cole10up** [comment]
Checking page views while logged in:
![image](https://user-images.githubusercontent.com/57115907/76493949-16dbe780-63f1-11ea-9237-7cf0e7c88aa1.png)

**Checking page views while not logged in still showing 0...**
![image](https://user-images.githubusercontent.com/57115907/76494053-4f7bc100-63f1-11ea-8883-4fd87eb60110.png)

**Comment by cole10up** [comment]
Adjusting my Tag to target my property ID for the variable fixed things. Seeing a positive test now.

Signed out and navigating to FE

![image](https://user-images.githubusercontent.com/57115907/76495426-142ec180-63f4-11ea-877e-61633eb7b94b.png)

Also seeing tracking in GA
![image](https://user-images.githubusercontent.com/57115907/76495450-21e44700-63f4-11ea-940e-67101414da84.png)

Passed QA ✅
