### ISSUE TITLE
Update `subtitle` in the widget area API to accept component or text as parameter and use it for KMW area

### ISSUE THREAD

**Issue by zutigrm** [google/site-kit-wp#9444]
## Feature Description

Following the implementation of [8895](https://github.com/google/site-kit-wp/issues/8895), we need to expand on Widget area API, to allow passing the component for `subtitle`. As in this issue, subtitle of the KMW widget area should be conditionally hidden if key metrics is not setup yet per new [figma design](https://www.figma.com/design/S2CNc1toIzC7UrGMgs79S6/Conversions?node-id=1773-21199&node-type=frame&t=oPFL0ZkvfhuGdErZ-0)

Initial implementation idea can be found in these commits: [here](https://github.com/google/site-kit-wp/pull/9105/commits/6a9ba8ac99f8e46be46b5d9bfdcff2ec813622d0), [here](https://github.com/google/site-kit-wp/pull/9105/commits/5f98335ec0cd16083cf5e62be815100729e5a34d) and [here](https://github.com/google/site-kit-wp/pull/9105/commits/67b6cabc1aa376e23d8fcd5541d5f1f82f6e2f57), as starting point perhaps

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The subtitle property of the widget area object can be either text or component
* KMW area subtitle should be shown only when KM has been setup as per new [figma design](https://www.figma.com/design/S2CNc1toIzC7UrGMgs79S6/Conversions?node-id=1773-21199&node-type=frame&t=oPFL0ZkvfhuGdErZ-0)

## Implementation Brief

* [x] Create a new component `assets/js/components/KeyMetrics/MetricsWidgetSubtitle.js`:
   * Get the value of the `isKeyMetricsSetupCompleted` selector.
   * Return null if `isKeyMetricsSetupCompleted` is not true.
   * If `isKeyMetricsSetupCompleted` is true, return the copy [in the Figma designs](https://www.figma.com/design/S2CNc1toIzC7UrGMgs79S6/Conversions?node-id=1773-18090&node-type=frame&t=tjJ7wY3jZKXcdLxf-0) wrapped in the `__` translation function, and further wrapped in a `Fragment`.
* [x] Update `assets/js/googlesitekit/widgets/components/WidgetAreaRenderer.js`:
   * Extract the header into a new component `assets/js/googlesitekit/widgets/components/WidgetAreaHeader.js`, *Without this, the `WidgetAreaRenderer` will exceed the `complexity` threshold.*
   https://github.com/google/site-kit-wp/blob/dd45c1411110d1b995f59a534732ac8f15dbdb1f/assets/js/googlesitekit/widgets/components/WidgetAreaRenderer.js#L200-L233
   * Update the `subtitle` prop rendering code, in the new `WidgetAreaHeader` component, to the following. This will render a component if passed in the subtitle prop:
   https://github.com/google/site-kit-wp/blob/5f98335ec0cd16083cf5e62be815100729e5a34d/assets/js/googlesitekit/widgets/components/WidgetAreaRenderer.js#L217-L228
* [x] Update [`assets/js/googlesitekit/widgets/register-defaults.js`](https://github.com/google/site-kit-wp/pull/9105/commits/67b6cabc1aa376e23d8fcd5541d5f1f82f6e2f57), passing the new `MetricsWidgetSubtitle` component as the subtitle.

### Test Coverage

* Update the widget rendering tests to confirm both subtitle types work as expected.

## QA Brief 

* Set up Google Site Kit with KMW 
* Ensure that the subtitle for the KMW area on the dashboard matches that of the code update: `Track progress towards your goals with tailored metrics and important user interaction metrics`
* Set up Google Site Kit without KMW enabled
* Ensure that the sub title is no longer displayed in this area

## Changelog entry

* Update the widget area renderer to accept React components for subtitles.

**Comment by zutigrm** [comment]
Thanks @eugene-manuilov AC updated

**Comment by eugene-manuilov** [comment]
Thanks, AC ✔

**Comment by eugene-manuilov** [comment]
@benbowler, could you please expand IB to have explicit instructions of what needs to be done? Also, if you want to reference a block of code, then please use permalinks that get converted into embeds instead of just regular links that hard to use.

**Comment by benbowler** [comment]
Writing the IB I also considered simply conditionally returning the subtitle within `register-defaults` or adding a new widget registration prop function such as `showTitle`, because the main purpose of this ticket is to conditionally render the subtitle. However I think these solutions would either add irrelevant logic into the `register-defaults` file, and the implementation in the IB allows for more complex rendering logic for subtitles in the future as well as matching the way the title prop works more closely.

**Comment by eugene-manuilov** [comment]
Thanks, IB ✔

**Comment by aaemnnosttv** [comment]
Picking up the CR here to restore E2E which is also broken by changes in another issue

**Comment by kelvinballoo** [comment]
### QA Update ✅ 

QAB is met. Moving ticket to approval.

- When Google Site Kit is set up with KMW, the subtitle for the KMW area is as expected: 
   `Track progress towards your goals with tailored metrics and important user interaction metrics`
   <Details>

   ![Image](https://github.com/user-attachments/assets/1619813a-7743-41f4-94d6-942754223a1a)

   </Details>

- When Google Site Kit is set up without KMW enabled, the sub title is no longer displayed in this area.
   <Details>

   ![Image](https://github.com/user-attachments/assets/a24b1ede-dc72-4ef0-91be-add2d38a8daa)

   </Details>
