### ISSUE TITLE
Add a survey trigger for Reader Revenue Manager CTA

### ISSUE THREAD

**Issue by nfmohit** [google/site-kit-wp#9447]
## Feature Description

A survey trigger should be added for the Reader Revenue Manager CTA. The SK Service does not need to actually trigger a survey for this yet, which can be done later. For now, this would only be helpful to track use of the CTA.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When the Reader Revenue Manager CTA banner is viewed, a survey should be triggered.
* The survey `triggerID` should be: `view_reader_revenue_manager_cta`.

Note: This is a stub survey (at least for now) that will help us track use of this banner, so Site Kit doesn't have to display an actual survey.

## Implementation Brief

* [ ] In `assets/js/modules/reader-revenue-manager/components/dashboard/ReaderRevenueManagerSetupCTABanner.js`:
	* [ ] Update the `useEffect` that calls `trackEvent` for the `view_notification` event.
	* [ ] After the above call, dispatch a call to `triggerSurvey()` passing the trigger ID according to the ACs.

### Test Coverage

* No new tests needed.

## QA Brief

* Set up Site Kit with the `rrmModule` feature flag enabled.
* Visit the dashboard and ensure the Reader Revenue Manager CTA banner is displayed.
* Verify that the survey trigger is correctly dispatched when viewing the banner.
* Ensure that the `triggerID` is set to `view_reader_revenue_manager_cta`.
* To verify the survey trigger, open the network tab in the browser's developer tools and ensure a `POST` request is made to the `wp-json/google-site-kit/v1/core/user/data/survey-trigger` endpoint with the correct `triggerID`:
    ```json
    {
        "data": {
            "triggerID": "view_reader_revenue_manager_cta"
        }
    }
    ```

## Changelog entry

* Add a stub survey trigger that is called when viewing the Reader Revenue Manager Setup CTA.

**Comment by techanvil** [comment]
IB ✅

**Comment by kelvinballoo** [comment]
### QA Update ✅ 

Tested this and it's working as expected.
Moving ticket to approval.

When the Reader Revenue Manager CTA banner is viewed, a survey with triggerID `view_reader_revenue_manager_cta` and POST request is triggered to `wp-json/google-site-kit/v1/core/user/data/survey-trigger`

<Details>

![Image](https://github.com/user-attachments/assets/93a5fac7-5aa9-4ecc-99f1-c174b55e0a0a)

![Image](https://github.com/user-attachments/assets/cfe0545c-9fa6-41b8-be47-e68bda445ca6)

</Details>
