### ISSUE TITLE
Update Travis config for PHP 7.4

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#945]
PHP 7.4 was [recently released](https://www.php.net/ChangeLog-7.php#7.4.0) and is now the new stable version of PHP. As such, we should update the Travis job definition to no longer allow failures with PHP 7.4.

The version itself can probably change from `7.4snapshot` to `7.4` as well.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Ensure our "latest PHP version" tests run against PHP 7.4, the new latest PHP version.

## Implementation Brief

* See #946 

## Changelog entry

* N/A

**Comment by cole10up** [comment]
Checking Travis's prior build here, we have passes for PHP 7.3
https://travis-ci.com/google/site-kit-wp/builds/139657848

![image](https://user-images.githubusercontent.com/57115907/70541148-5a396800-1b1b-11ea-8e6a-9537813b0dd2.png)

Latest develop run passes for PHP 7.4
https://travis-ci.com/google/site-kit-wp/builds/140425697

![image](https://user-images.githubusercontent.com/57115907/70541213-79d09080-1b1b-11ea-86d0-26d0ed974548.png)

Passed QA ✅
