### ISSUE TITLE
Change support documentation slug to be `visitor-groups`.

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#9455]
## Feature Description

As discussed on [Asana](https://app.asana.com/0/0/1207778067149895/1208434892314023), the user facing copy refers to "visitor groups" rather than "audience segmentation".

We should accordingly update the slug for the support documentation page to be `visitor-groups` rather than `audience-segmentation`.

There's only one instance of this URL in the feature: the "learn more" link in the tooltip for an audience:

![image](https://github.com/user-attachments/assets/9c807962-ccd0-435a-9b83-57c72b41eaf5)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The tooltip for an audience should link to the following URL: https://sitekit.withgoogle.com/support?doc=visitor-groups

## Implementation Brief

* [ ] Pass `'visitor-groups'` as the argument to `getDocumentationLinkURL()` in the `AudienceTooltipMessage` component.

https://github.com/google/site-kit-wp/blob/0525c3b6f74dd88d924de35ef7658ad67ce4e774/assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceTilesWidget/AudienceTooltipMessage.js#L41-L44

### Test Coverage

* Fix any failing tests.

## QA Brief

* Set up the Analytics module and enable the Audience Segmentation.
* Hover over the tooltip for an audience in the Audience Tiles widget.
* Hover the "Learn more" link in the tooltip and verify that it links to https://sitekit.withgoogle.com/support?doc=visitor-groups.
* Click the link and verify that the support documentation page is displayed.
* **Note:** The support documentation page is not expected to exist yet, you will see default [documentation page](https://sitekit.withgoogle.com/documentation/) instead.

## Changelog entry

* Update the Audience Segmentation support documentation "learn more" link in the tooltip for an Audience Tile.

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by jamesozzie** [comment]
Just a note that I added this slug to the [Support Redirects sheet](https://docs.google.com/spreadsheets/d/12x39d7j0GNqha0m7s4-Y3P5SwK9wwgxxxDnWp3svSKg/edit?resourcekey=0-IngulwDvPmI4SEq2g-f4rA&gid=1590434109#gid=1590434109). 

I didn't remove `audience-segmentation` at this time, but any links do point to the intended location for this documentation on the plugin website. 

cc @eugene-manuilov

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified that Learn more" link in the tooltip links to https://sitekit.withgoogle.com/support?doc=visitor-groups.
- Verified when click the support documentation page is displayed.
- Note: The support documentation page is not expected to exist yet, you will see default [documentation page](https://sitekit.withgoogle.com/documentation/) instead.

<details>

![Image](https://github.com/user-attachments/assets/607a14a3-60fd-4241-bb2b-42fbfa86d2f9)

https://github.com/user-attachments/assets/4c335e43-c943-4f0c-8084-ac5052154a79

</details>
