### ISSUE TITLE
E2E nightly fails to install WP

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#9464]
## Bug Description

Recently, our E2E nightly job started failing during the setup due to a lack of memory.

```
STATUS: Downloading WordPress version nightly...
[04-Oct-2024 15:53:05 UTC] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 12288 bytes) in phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Extractor.php on line 51
```

## Screenshots

<img width="1229" alt="image" src="https://github.com/user-attachments/assets/8d673c8f-e00b-44e6-b5cd-2180f4f734ec">

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* E2E setup should be repaired to continue running successfully

## Implementation Brief

* [ ] Update service definition for the `cli` service in Docker to set a higher `memory_limit` for PHP. It's currently failing with a limit of 128M so we can bump it to something higher as suggested in https://make.wordpress.org/cli/handbook/guides/common-issues/#php-fatal-error-allowed-memory-size-of-999999-bytes-exhausted-tried-to-allocate-99-bytes
* [ ] Merge https://github.com/google/site-kit-wp/pull/9465

### Test Coverage

* No changes (this is about restoring the function of a job)

## QA Brief

* None required, this can be verified during CR

## Changelog entry

* N/A

**Comment by tofumatt** [comment]
Moving directly to approval as no QA is needed here.
