### ISSUE TITLE
Temporarily hidden tiles reappear and the “Temporarily hidden” badge is still visible after deselecting an active tile

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#9472]
## Bug Description

Reported during the Bug bash. [Asana ticket here](https://app.asana.com/0/1208235052195562/1208487132526724/f) 

This issue occurs when three audience tiles are visible on the dashboard. After hiding audience tiles in the dashboard, unselecting a tile that displays data causes one of the previously hidden tiles to reappear. The Audience selection panel also continues to display the “Temporarily hidden” badge for the tile, even though it is now visible.

<details>
 <summary>Screenshots</summary>

![image](https://github.com/user-attachments/assets/694438df-909c-4587-8176-77c256304b58)

https://github.com/user-attachments/assets/6ef6473a-5c18-4d50-bb19-22e5e3dabc3c

</details>

## Steps to reproduce

1. Enable Audience Segmentation.
2. Select three audience tiles to be displayed in the dashboard.
3. Ensure two tiles are in zero and partial data state so the Audience Tile Collecting Data tile is displayed with the "Temporarily hide" CTA.
4. Click "Temporarily hide" for both tiles to hide them.
5. Open the Audience selection panel and confirm that the "Temporarily hidden" badge is displayed.
6. Unselect the tile that displays data and save the selection.
7. Observe that one of the previously hidden tiles is displayed again.
8. Observe that the Audience selection panel still displays the "Temporarily hidden" badge for the reappeared tile.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- When following the **steps to reproduce**, the "temporarily hidden" audience whose zero-data state tile becomes re-shown should have its "Temporarily hidden" badge removed in the Selection Panel.
- The underlying "temporarily hidden" state for the audience should be cleared, so the tile does not automatically re-hide and have its badge restored if the tile with data is re-added to the selection.

## Implementation Brief

- Amend the `saveSettings()` callback in the [`AudienceSelectionPanel/Footer`](https://github.com/google/site-kit-wp/blob/fbcf92fbcedd4e71b158282692cf13ce780ed863/assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceSelectionPanel/Footer.js) component.
  - In the conditional block that runs when `saveAudienceSettings()` has run without error:
    - Determine the list of configured audiences that are also hidden (i.e. have a corresponding entry in `hiddenTileDismissedItems`).
    - Compare the length of this list to the length of `configuredAudiences`.
    - If the lengths match, add the first configured audience's dismissed item key to the list of items that is passed to `removeDismissedItems()`.

### Test Coverage

- Add coverage for the above changes to the tests for `AudienceSelectionPanel`.

## QA Brief

- Follow the **steps to reproduce** and verify the "temporarily hidden" audience whose zero-data state tile becomes re-shown has its "Temporarily hidden" badge removed in the Selection Panel.
- Re-add the tile with data to the selection, save the selection, and verify the "Temporarily hidden" badge is not re-added to the above audience.

## Changelog entry

* Remove the “Temporarily hidden” badge when temporarily hidden tiles reappear with only a single tile visible.

**Comment by nfmohit** [comment]
Thank you for drafting the IB, @ankitrox . However, I don't think the approach you've outlined matches the expectations in the ACs.

Reading the ACs, it sounds like a temporarily hidden audience tile re-appearing when there are no other audience tiles to display is an expected behaviour, and we should clear its temporarily hidden state in this case. @techanvil please let me know if my statement is not correct.

@ankitrox Could you re-consider the ACs and update the IB accordingly? Let's wait for a confirmation from @techanvil if required so that we're all on the same page. Thank you!

**Comment by techanvil** [comment]
Thanks @nfmohit, your read of the ACs is correct and it is indeed expected that a hidden audience will reappear when there are no other tiles to display.

The IB should take the approach whereby, while saving the selection, we check to see if there are only hidden audiences remaining in the selection. If so, we should clear the hidden state for one of them.

**Comment by ankitrox** [comment]
@ivonac4 @techanvil Unassigning myself as I am not resourced for SK this and next week.

**Comment by nfmohit** [comment]
IB ✅

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Tested on latest environment and I'm able to reproduce issue.
- Verified on dev environment issue is resolved.

<details>

**Latest environment**

https://github.com/user-attachments/assets/48947a24-9f45-46d4-88a3-f32d022ee265

**Dev environment**

https://github.com/user-attachments/assets/99380cd1-90fe-422f-a8c8-e579fd589dd7

</details>
