### ISSUE TITLE
Audience Selection Panel rendered before the feature has been set up

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#9475]
## Bug Description

Issue discovered during bug bash.  [Asana task here](https://app.asana.com/0/1208235052195562/1208489517112450/f)

The Audiences Selection Panel component is rendered into the DOM before the feature has been set up.

I spotted this when I noticed that a request to sync-audiences is made when landing on the dashboard prior to the Audience Segmentation Setup CTA Banner being displayed and actioned.

We should not be rendering the selection panel at all prior to the feature being set up.

<details>
 <summary>Screenshots</summary>

<img width="1009" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK010Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--addc6f629d9ceb9c5c71ff597546d6990c36572b/image.png" alt="image.png" />

<img width="1128" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1F0Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--66cdc65f3b79153519efd29c2d42622c350f7881/image.png" alt="image.png" />

</details>

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- If the Audience Segmentation feature has not yet been set up for the current user, the Audience Selection Panel should not be rendered into the DOM.

## Implementation Brief

* [ ] In the `DashboardMainApp` component, retrieve `configuredAudiences` via the `getConfiguredAudiences()` selector. Extend the condition for rendering `AudienceSelectionPanel` to include a check for `configuredAudiences` being truthy.

https://github.com/google/site-kit-wp/blob/3ff3c69cce3f17ec310f57e0a3cfe8aebe2e2759/assets/js/components/DashboardMainApp.js#L297

### Test Coverage

* No new tests needed.

## QA Brief

* Set up Site Kit with the `audienceSegmentation` feature flag enabled, and Analytics connected to a property that is out of the gathering data state.
* Verify that the Audience Selection Panel is not rendered into the DOM. Check for the presence of an element with the class `.googlesitekit-audience-selection-panel` as seen in the screenshot in the Feature Description. This should _not_ be present.
* Click on **Enable groups** to set up the Audience Segmentation feature.
* Verify that the Audience Selection Panel is now rendered into the DOM.

## Changelog entry

* Prevent rendering of the Audience Selection Panel before the feature is set up, ensuring it only renders after setup is complete.

**Comment by nfmohit** [comment]
Thank you for drafting the IB, @techanvil !

> * In the `DashboardMainApp` component, retrieve `configuredAudiences` via the `getConfigurableAudiences()` selector. Extend the condition for rendering `AudienceSelectionPanel` to include a check for `configuredAudiences` being truthy.

Just to confirm, did you mean the `core/user` `getConfiguredAudiences` selector instead?

**Comment by techanvil** [comment]
Thanks for spotting that, @nfmohit! It was indeed a typo, which I've fixed. Back to you for another pass :)

**Comment by nfmohit** [comment]
IB ✅

**Comment by kelvinballoo** [comment]
### QA Update ✅ 

Verified good as per below.
Moving ticket to approval.

- Before the audience tiles were set up, the class .googlesitekit-audience-selection-panel appeared under the 'latest release' branch.
   <Details>

   ![Image](https://github.com/user-attachments/assets/0bb7800a-039d-4d7a-b134-1c1630c59d84)

   </Details>

- When switched to 'develop' Branch, the class .googlesitekit-audience-selection-panel disappeared.
   <Details>

   ![Image](https://github.com/user-attachments/assets/3fe170ba-a759-4fda-a918-83a1c4d9256a)

   </Details>

- Under develop Branch, after the audience tiles were set up, the class .googlesitekit-audience-selection-panel now appeared.
   <Details>

   https://github.com/user-attachments/assets/e0b67570-f1ab-4272-9038-f878fe29a1d7
 
  </Details>
