### ISSUE TITLE
Create Sign in With Google Settings module settings view screen

### ISSUE THREAD

**Issue by benbowler** [google/site-kit-wp#9477]
## Feature Description

The settings screen for Sign in with Google should be created and available after Sign in with Google is connected. See the Figma designs for this UI in view/edit mode: https://www.figma.com/design/h9yGR15Pg2DUtgERW4AFAv/Sign-in-with-Google?node-id=27-1045&node-type=frame&t=pIlj66YsTMINwgVT-0

**This ticket should implement the view screen only, with the edit screen implemented in #9334**

It should be only visible when the `signInWithGoogleModule` feature flag is enabled.

### View
![Screenshot 2024-10-05 at 12 18 10](https://github.com/user-attachments/assets/11dbee73-945a-4d55-8371-ab8c47d8095f)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* **All features in this AC should only be visible when the `signInWithGoogleModule` feature flag is enabled.**
* A new settings component for the Sign in with Google module should appear in Site Kit module settings when Sign in with Google is connected.
* The design should follow the Figma design: https://www.figma.com/design/h9yGR15Pg2DUtgERW4AFAv/Sign-in-with-Google?node-id=20-1129&node-type=frame&t=xGrDkU14DU9FcenS-0

## Implementation Brief

**SettingsView component**
* [x] Create a new `assets/js/modules/sign-in-with-google/components/settings/SettingsView.js`, based on other `SettingsView` components ([eg.](https://github.com/google/site-kit-wp/blob/db3699f1b5503195665a0e84a976d621bd44f3c7/assets/js/modules/analytics-4/components/settings/SettingsView.js)):
   * Get each settings using the relevant selectors and render then using the following format:
   https://github.com/google/site-kit-wp/blob/ed5ebdde53f445730245c879e533692b291d9ed0/assets/js/modules/analytics-4/components/settings/SettingsView.js#L79-L87
   * TODO: "Anyone can register" notice.

* [x] Update `assets/sass/components/sing-in-with-google/_googlesitekit-sign-in-with-google-settings-module.scss`, styling the settings view screen [based on the Figma designs](https://www.figma.com/design/h9yGR15Pg2DUtgERW4AFAv/Sign-in-with-Google?node-id=20-1129&node-type=frame&t=xGrDkU14DU9FcenS-0)

 * [x] Update the module registration:
    * Change the `SettingsViewComponent` prop to return the newly created `SettingsView` component.

**"Anyone can register" notice**

 * [x] Update `includes/Modules/Sign_In_With_Google.php`:
    * Set up a REST infrastructure for this module by implementing `get_datapoint_definitions` and `create_data_request` methods [modelled on other modules](https://github.com/google/site-kit-wp/blob/dfcc37f37c0672470309e63f6f0d02b7598e4e86/includes/Modules/Analytics_4.php).
    * Create a new REST GET endpoint `anyone-can-register`, this API should return the value of `wp_options` `users_can_register` setting.

 * [x] creating a new fetch store `assets/js/modules/sign-in-with-google/datastore/anyone-can-register.js`:
    * Use the control callback `API.get( 'modules', 'sign-in-with-google', 'anyone-can-regsiter', {} )`
    * Create a base resolver and selector `getAnyoneCanRegister`,  [modelled on other modules stores](https://github.com/google/site-kit-wp/blob/dfcc37f37c0672470309e63f6f0d02b7598e4e86/assets/js/modules/analytics-4/datastore/conversion-events.js#L42-L72).
 * [x] Update `assets/js/modules/sign-in-with-google/datastore/base.js`, include this new fetch store in the `combineStores` call.

 * [x] Update `assets/js/modules/sign-in-with-google/components/settings/SettingsView.js`:
    *  If `getAnyoneCanRegister` resolves to false, render the [banner design in Figma](https://www.figma.com/design/h9yGR15Pg2DUtgERW4AFAv/Sign-in-with-Google?node-id=248-1515&node-type=frame&t=Y2gQYhYwb258yiA6-0) adapting the `Notices` component to match the designs.
    * Use the dismissed items infrastructure to dismiss this notice if the user clicks "Got It" with the key `SIGN_IN_WITH_GOOGLE_ANYONE_CAN_REGISTER_NOTICE = 'sign-in-with-google-anyone-can-register-notice'`

### Test Coverage

* Create new stories for `SettingsView` components within this module, including a state showing the "Anyone can register" notice.
* Create simple test for the new fetch store `assets/js/modules/sign-in-with-google/datastore/anyone-can-register.test.js`

## QA Brief

* Set up Site Kit with the `signInWithGoogleModule` feature flag enabled
* Ensure WordPress' "Anyone can register" setting in Settings > General is **enabled**.
* Set up Sign in with Google module, then visit the Site Kit Settings screen and open the "Sign in with Google" module settings.
* You should see all settings displayed
* You _should not_ see a notice under the "Anyone can register" section

Additional testing of notice:

* Set up Site Kit with the `signInWithGoogleModule` feature flag enabled
* Ensure WordPress' "Anyone can register" setting in Settings > General is disabled.
* Set up Sign in with Google module, then visit the Site Kit Settings screen and open the "Sign in with Google" module settings.
* You should see all settings displayed
* You _should_ see a notice under the "Anyone can register" section. Dismissing this notice using the "Okay, got it" CTA should cause it never to appear again.

Note that I've adjusted some of the headings from the Figma mocks and used existing components with slightly different icons, so the UI should match this style:

![Image](https://github.com/user-attachments/assets/c045d7f1-a3f4-4d99-9de9-f58f2d805968)

## Changelog entry

* Implement settings view for Sign in with Google.

**Comment by benbowler** [comment]
@tofumatt should I spec the "Anyone can register" banner and it's related REST endpoint and store as part of this ticket?

**Comment by benbowler** [comment]
Increasing the estimate to account for implementing the "Anyone can register" banner.

**Comment by tofumatt** [comment]
IB ✅

**Comment by tofumatt** [comment]
Leaving this assigned to myself as I accidentally started this one, not realising it wasn't in the sprint 😅

**Comment by mohitwp** [comment]
### QA Update ❌ 

- Tested on dev environment.
- Verified SIWG settings view when "Anyone can register" setting in Settings > General is disabled.
- Verified SIWG settings view when "Anyone can register" setting in Settings > General is enabled.
- Verified that clicking on 'Got It' permanently dismiss the notice.

@benbowler 

**Issue**

I notice that "Anyone can register" disable notice is full width in Figma where as under actual implementation it is not full width. 

<details>

Figma 

![Image](https://github.com/user-attachments/assets/970efbf7-590b-4037-90fd-9a70403d0020)


![Image](https://github.com/user-attachments/assets/6778acbb-821f-4550-a058-546fbbcf533c)

</details>

**Comment by mohitwp** [comment]
### QA Update ⚠ 

Tested on dev environment.

@benbowler The notice now looks good on mobile and tablet devices. However, on dashboard and laptop viewports, the content is not breaking which causing the notice content to appear misaligned with the icon and the 'Got It' button. I think we should break and show `Visit WordPress Settings to manage this setting` in next line. This should be a small fix, but let me know if you’d like me to create a separate ticket for it. 

**Dashboard view**

<details>

![Image](https://github.com/user-attachments/assets/380320ac-f20d-4db2-af8d-b731b566fe1b)

![Image](https://github.com/user-attachments/assets/a2334f1e-2e53-4907-b533-0d94fc72547d)

</details>


**Mobile and tablet view**

<details>

![Image](https://github.com/user-attachments/assets/2502d96f-3b96-46ee-ade4-7addb98d919d)

![Image](https://github.com/user-attachments/assets/44581eb7-6f81-4f4b-a36b-3b140fbe10e9)

</detail>

**Comment by mohitwp** [comment]
### QA Update ✅ 


- Tested on main environment.
- Tested when SIWG feature flag is enabled.
- Also, tested when SIWG feature flag is not enabled.
- Verified SIWG settings view when "Anyone can register" setting in Settings > General is disabled.
- Verified SIWG settings view when "Anyone can register" setting in Settings > General is enabled.
- Verified that clicking on 'Got It' permanently dismiss the notice.
- Verified SIWG module settings view screen is looking same as Figma design.
- Verified functionality of SIWG module settings view screen.
- Verified issue related to notice described above is now resolved.


<details>


**Desktop view**

![Image](https://github.com/user-attachments/assets/a3695c73-b4b8-4472-b103-94266e57f29c)

**Tablet View**

![Image](https://github.com/user-attachments/assets/b41daf17-0d4f-42ca-b53c-a885221ba2b0)

**Mobile view**

![Image](https://github.com/user-attachments/assets/1254b906-d521-44ac-bbb0-8c0ec8f1eabc)

</details>
