### ISSUE TITLE
As a second admin, the setup subtle notification is displayed

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#9482]
## Bug Description

Created from the bug bash.  [Asana ticket can be found here](https://app.asana.com/0/1208235052195562/1208436150537165/f). 

After setting up Audience Segmentation with a primary admin, if you login as a second admin you see the subtle success notification.

![Image](https://github.com/user-attachments/assets/214d9a69-2b3e-4537-85ed-3d548c461312)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- The [Setup Success Banner](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-analytics4-components-audiencesegmentation-dashboard-audiencesegmentationsetupsuccesssubtlenotification--default) should only appear upon successfully setting up the feature as a primary admin, and should not appear for a secondary user.

## Implementation Brief

* [ ] 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by ankitrox** [comment]
Hi @wpdarren ,

I am trying to reproduce the issue, but cannot see the subtle notification for the secondaty admin.

Can you please provide the `Steps to reproduce` the problem?

**Comment by wpdarren** [comment]
@ankitrox actually, I am unable to recreate this issue too. I am wondering if the refactoring of the subtle success notification, which was recently [merged](https://github.com/google/site-kit-wp/issues/9281) has fixed this issue.  I feel that this can be closed.  Tagging in @techanvil here to confirm.

**Comment by techanvil** [comment]
Thanks @ankitrox @wpdarren, I can confirm the refactoring of the notification has indeed resolved this issue.

The relevant logic is here, it's currently necessary to invalidate the resolution for `getQueuedNotifications()` in order for the notification queue to be re-evaluated in order for the setup success notification to be eligible for display, and this is only happening for the initial setup and not for a secondary user's setup.

https://github.com/google/site-kit-wp/blob/3ff3c69cce3f17ec310f57e0a3cfe8aebe2e2759/assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceSegmentationSetupCTAWidget.js#L118-L122

Anyhow, good to see this one is no longer an issue! I'll go ahead and close it now.
