### ISSUE TITLE
Refactor datapoint handlers with alternate switch

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#949]
## Feature Description

Currently datapoint handlers in module classes have several levels of indentation, within if statements and switches. This could be greatly simplified with a single switch that would be easier to parse by using a compound value in the switch rather than nesting.

i.e.
```php
if ( 'GET' === $method ) {
    switch ( $datapoint ) {
        case 'foo':
            // do GET foo
            break;
    }
} elseif ( 'POST' === $method ) {
    switch ( $datapoint ) {
        case 'foo':
            // do POST foo
            break;
    }
}
```
becomes

```php
switch ( "$method:$datapoint" ) {
    case 'GET:foo':
        // do GET foo
        break;
    case 'POST:foo':
        // do POST foo
        break;
}
```

This would make it easier to group datapoints together rather than spreading them apart because they use a different method. It also makes it easier to jump to the specific handler when searching in the code.

This is the same pattern used in the `FakeModule` class for tests but it isn't as obvious how much cleaner it would be since it's just a single datapoint 😄 

https://github.com/google/site-kit-wp/blob/7f000bb4e68b3fec04e59cab463766381e6a8b80/tests/phpunit/includes/Core/Modules/FakeModule.php#L129-L135

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* For all datapoint handlers, combine the `method` and the `datapoint` into a colon-separated string so that only a single `switch` clause is required.
* Group datapoints with the same name together (first `GET`, then `POST`).

## Implementation Brief

* Update existing datapoint handler methods (`create_data_request` and `parse_data_request`) to use a single switch using a compound `"$method:$datapoint"` key for each case.
* Reorder the handlers to using alpha sort (a-z) by datapoint, `GET` before `POST` (but kept adjacent to one another) 

## Changelog entry

* N/A

**Comment by felixarntz** [comment]
@aaemnnosttv I like this suggestion. Let's do it!

We need to get this done at the right time though, to minimize the chance of conflicts or regressions. We haven't been touching datapoints recently in other PRs, so maybe now is a good time. A PR for this definitely shouldn't be around for too long :)

**Comment by felixarntz** [comment]
IB ✅

**Comment by aaemnnosttv** [comment]
@felixarntz This PR is ready with the exception of changes to the Analytics module. I'm waiting for #967 to be merged before doing this to avoid conflicts. Moving to blocked for now.

**Comment by tofumatt** [comment]
QA'd and everything works fine as it did before despite the datapoints being changed. Seems good to me! ✅
