### ISSUE TITLE
Add GA event tracking for the Intro Popup/Banner

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#9498]
## Feature Description

GA events should be added to keep track of interaction with the Intro Popup/Banner.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

The following GA events should be tracked for the given actions. See the [GA events sheet](https://docs.google.com/spreadsheets/d/1eEuJ2ppVZuai1_hL77RA2vL7DUidM_qCnvTsjxZ_S4k/edit?gid=925918307#gid=925918307&range=450:452).

Event Name | Category | Trigger | Condition
-- | -- | -- | --
view_notification | {viewContext}_audiences-secondary-user-intro | Element visibility | User views the [Intro Popup/Banner](https://www.figma.com/design/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?node-id=1395-20664&node-type=frame&t=PNTGwXm0OYTItlYB-0) shown to a user after the feature has been setup by another user																					
confirm_notification | {viewContext}_audiences-secondary-user-intro | Click | User clicks "Show me" on the popup/banner																					
dismiss_notification | {viewContext}_audiences-secondary-user-intro | Click | User clicks "Got it" on the popup/banner																					

## Implementation Brief

- [x] In the `AudienceSegmentationIntroductoryOverlayNotification` component:
  - Add an `onShow` callback prop to the rendered `OverlayNotification`. In the callback, call `trackEvent( '${viewContext}_audiences-secondary-user-intro', 'view_notification' )`.
  - Lift the contents of `dismissNotification()` to a new `dismissNotice()` function.
  - In `scrollToWidgetAndDismissNotification()`, replace the call to `dismissNotification()` with a call to `trackEvent( '${viewContext}_audiences-secondary-user-intro', 'confirm_notification' )` followed by `dismissNotice()`. Chain the two calls using `.finally()`.
  - In `dismissNotification()`, call `trackEvent( '${viewContext}_audiences-secondary-user-intro', 'dismiss_notification' )` followed by `dismissNotice()`. Again, chain the two calls using `.finally()`.
- See the [`PublicationApprovedOverlayNotification`](https://github.com/google/site-kit-wp/blob/5a7a405fd007450fd0276df307a68f13c6e4d798/assets/js/modules/reader-revenue-manager/components/dashboard/PublicationApprovedOverlayNotification.js) component for an example to follow.

### Test Coverage

- Add coverage for the above changes to the tests for `AudienceSegmentationIntroductoryOverlayNotification`.

## QA Brief

* Set up Site Kit with the `audienceSegmentation` feature flag enabled, and tracking enabled.
* Visit the dashboard as a secondary user (a secondary admin and a view-only user).
* Follow the QAB from #8172 to view the Intro Popup/Banner as a secondary user.
* Verify that the GA events are tracked correctly when interacting with the Intro Popup/Banner as per the AC.

## Changelog entry

* Add opt-in event tracking for the Audience Segmentation introductory popup/banner.

**Comment by nfmohit** [comment]
IB ✅

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Tested GA events on view only dashboard.
- Tested GA events for secondary admin main dashboard.
- Verified `view_notification`, `confirm_notification` and `dismiss_notification` GA events triggered successfully for seconday user on view only dashboard and main dashboard.
- Verified that the GA events are tracked correctly when interacting with the Intro Popup/Banner as per the AC.


**View Only Dashboard** 

<details>

**_1. View Notification_**

![Image](https://github.com/user-attachments/assets/cb97a84e-eede-4f74-ab19-07797f6ee38c)

![Image](https://github.com/user-attachments/assets/70f2d060-34af-4eab-b3be-9ef584289426)


**_2. Confirm Notification ( When user clicks on 'Show me' on the popup )_**

![Image](https://github.com/user-attachments/assets/a34eef97-bdc1-459d-95c0-ae18ea8dfbe5)

![Image](https://github.com/user-attachments/assets/d0e8f9df-2c21-4195-8a53-d3ace0d17a59)

**_3. Dismiss Notification ( When user clicks on 'Got it' on the popup )_**

![Image](https://github.com/user-attachments/assets/6f5ccad8-ddd3-4d33-bf6e-432964d5e981)

![Image](https://github.com/user-attachments/assets/36055eca-2282-43f0-b67f-b512cf131ec2)

_**Screencast**_

https://github.com/user-attachments/assets/9ba85bfa-917f-4f68-a60b-6b470f640879


</details>

**Secondary Admin Dashboard**


<details>

**_1. View Notification_**


![Image](https://github.com/user-attachments/assets/89b8be21-bbe4-4ccf-99dd-75fe0c0ec8f6)

![Image](https://github.com/user-attachments/assets/7644aecd-9ba3-4764-9532-691b522ebe3d)


**_2. Confirm Notification ( When user clicks on 'Show me' on the popup )_**

![Image](https://github.com/user-attachments/assets/2ad11dd0-e8cd-4362-923e-c199df8cbcbb)

![Image](https://github.com/user-attachments/assets/a9669b20-4f8b-48ec-a6a6-006aa98d8a26)

**_3. Dismiss Notification ( When user clicks on 'Got it' on the popup )_**


![Image](https://github.com/user-attachments/assets/1930b71d-4b13-456c-9288-86ce2269ef2a)

![Image](https://github.com/user-attachments/assets/de3894c1-2633-4a0e-992b-3b030316cc8d)

</details>
