### ISSUE TITLE
Looks like isnt possible to use the function ga() for tracking events

### ISSUE THREAD

**Issue by drcrow** [google/site-kit-wp#950]
I need to use ga('send', 'event', bla bla bla); but I get the error "Uncaught ReferenceError: ga is not defined"

**Comment by jamesozzie** [comment]
@drcrow Support for Site Kit has moved to the WordPress support forum. If you want to create a [new support thread](https://wordpress.org/support/plugin/google-site-kit/) we can assist from there. 

When submitting add as much information to your issue as is required to assist. From looking at your reported issue you are looking to add events, which can be done via [Tag Manager](https://support.google.com/tagmanager/answer/6106716), after setting up Analytics. But share your site and we can hopefully assist.
