### ISSUE TITLE
Problem on Activating Analytics Services

### ISSUE THREAD

**Issue by hugomartinez** [google/site-kit-wp#951]
![Capture d’écran 2019-12-08 à 22 04 35](https://user-images.githubusercontent.com/3845667/70396201-02114180-1a07-11ea-8bd1-cd2d985cdb44.png)
![Capture d’écran 2019-12-08 à 22 04 44](https://user-images.githubusercontent.com/3845667/70396202-03426e80-1a07-11ea-814f-82633e7d7226.png)

## Bug Description

When I try to activate Analytics Service (by Setup Flow or after Setup Flow), I can't proceed because window open a blank page with this text : _'redirect_uri' mismatch_

## Steps to reproduce

1. Go to Site Kit Dashboard
2. Click on 'Complete Activation' for Analytics activation
3. See error on blank page

## Additional Context

 - PHP Version: 7.3
 - OS: [e.g. iOS] macOS Mojave 10.14.6
 - Browser [e.g. chrome, safari] chrome
 - Plugin Version [e.g. 22] 1.1.2
 - Device: [e.g. iPhone6] MacBook Air 13inch 2017

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by hugomartinez** [comment]
@felixarntz

**Comment by felixarntz** [comment]
@hugomartinez This may be happening because the API sent to the authentication service is different from the one set in your DB. Often times this is caused by e.g. your site using HTTPS, but the "WordPress site URL" (in Settings) is still set to HTTP. If you're willing to do so, let me know the domain of your website, maybe I can see what's wrong then.

**Comment by hugomartinez** [comment]
I've just checking that but site url and WP Site url are same.

**Comment by jamesozzie** [comment]
@hugomartinez Support for Site Kit has moved to the WordPress support forum. Can you open a [new support topic](https://wordpress.org/support/plugin/google-site-kit/) from there and we can hopefully assist. You might also check that you have all non HTTPS traffic redirected and the correct protocol set from within your Analytics account.
