### ISSUE TITLE
Add new inline banner in key metrics settings for existing users who saved "Sell products or services" legacy site purpose answer

### ISSUE THREAD

**Issue by zutigrm** [google/site-kit-wp#9518]
## Feature Description

As part of the work carried on in #9489 the now legacy site purpose answer "Sell products or services" was split into "Sell products" and "Provide services" answers. This issue should implement the new inline banner that will be surfaced in the key metrics admin settings section for existing users who previously saved legacy "" answer.

Figma design can be found [here](https://www.figma.com/design/S2CNc1toIzC7UrGMgs79S6/Conversions?node-id=2770-52119&node-type=frame&t=gejNlcLG8c8JhLme-0)

Check [Splitting “Sell products or services” site purpose answer](https://docs.google.com/document/d/1JvA3LK5SNfGH2o4OVnwjDdsAFuQMA9ZJj0T09RTqoy8/edit?pli=1&resourcekey=0-e90bcFGzAI6NhNu_D5i6hQ#heading=h.tobctwt5ojmh) section of the design doc

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Existing users that have previously saved "Sell products or services" answer for site purpose are shown the new inline banner in the Key metrics section of the admin settings
* Banner should match the content and design from [Figma](https://www.figma.com/design/S2CNc1toIzC7UrGMgs79S6/Conversions?node-id=2770-52119&node-type=frame&t=gejNlcLG8c8JhLme-0)
* It should stay visible in both `Preview` and `Edit` mode, above the selected answer/answers list
* Clicking the `Got it` CTA dismisses the banner
* Check [Splitting “Sell products or services” site purpose answer](https://docs.google.com/document/d/1JvA3LK5SNfGH2o4OVnwjDdsAFuQMA9ZJj0T09RTqoy8/edit?pli=1&resourcekey=0-e90bcFGzAI6NhNu_D5i6hQ#heading=h.tobctwt5ojmh) section of the design doc

## Implementation Brief

* [x] Updates `assets/js/components/user-input/util/constants.js`, add a new constant: `export const USER_INPUT_LEGACY_SITE_PURPOSE_DISMISSED_ITEM_KEY = 'user-input-legacy-site-purpose-dismissed-item';`

* [x] Update `assets/js/components/user-input/UserInputPreviewGroup.js`:
   * Add a new prop `subtitle` which accepts a component.
   * When passed, render the subtitle here:
   * https://github.com/google/site-kit-wp/blob/cc981876c3b654437e965cb66f8a09c9d110dba1/assets/js/components/user-input/UserInputPreviewGroup.js#L176-L178

* [x] Update `assets/js/components/user-input/UserInputPreview.js`:
   * https://github.com/google/site-kit-wp/blob/cc981876c3b654437e965cb66f8a09c9d110dba1/assets/js/components/user-input/UserInputPreview.js#L145-L155
   * If the `settings?.purpose?.values` includes the `sell_products_or_service`, pass a `SubtleNotification` to the new `subtitle` prop, with `type` set to `warning`, the copy should match [Figma design](https://www.figma.com/design/S2CNc1toIzC7UrGMgs79S6/Conversions?node-id=2770-52119&node-type=frame&t=91kYQwExSZBvYrG8-0) and should be dismissed using the dismissed item infrastructure using the `USER_INPUT_LEGACY_SITE_PURPOSE_DISMISSED_ITEM_KEY` key.

### Test Coverage

* No additional test coverage required.

## QA Brief

* Set up Site Kit on a branch/tag/version prior to this body of work, such as release 1.140.0
* Enable Key Metrics Widgets using the tailored method, choosing "Sell products or service" as a site purpose 
* Switch to the branch containing this body of work, i.e `develop`
* Navigate to `Google Site Kit > Settings > Admin` and scroll to the `Key Metrics` settings group
* Validate that the notification appears within the site purpose preview group as per below
![Image](https://github.com/user-attachments/assets/eab75ef3-fe71-4a9a-b13b-b8cc8203822d)
* Edit the answer and save the value using the new shortened purpose, "Sell products"
* Reload the page and confirm that the banner no longer appears
* Reset Site Kit and repeat all the above steps, _except_ for updating the answer to "Sell products"
* Dismiss the notification 
* Reload the page and confirm the notification no longer appears

## Changelog entry

* Add notice for users who used a legacy answer in Key Metrics settings.

**Comment by eugene-manuilov** [comment]
AC ✔

**Comment by benbowler** [comment]
Reducing the estimate here as it's a relatively simple implementation.

**Comment by eugene-manuilov** [comment]
> * If `slug` is `purpose` and `values` includes `sell_products_or_service` using the `Array` `includes` prototype, render the banner after the title:

@benbowler, which banner? Do we need to use an existing one or create a new one? If the new one, how should it be implemented?

**Comment by eugene-manuilov** [comment]
@benbowler 

> * If `slug` is `purpose` and `values` includes `sell_products_or_service` using the `Array` `includes` prototype, render the new `UserInputLegacySitePurposeNotice` banner after the title:

After thinking about it a bit more, I think it would be better to add a new prop `subtitle` to the `UserInputPreviewGroup` component and update `UserInputPreview` to pass the notification to the right group when the condition is met. This will let us avoid having checks in the `UserInputPreviewGroup` component that is intended only for rendering of what is passed via props.

> * Use the `WarningNotice` component to wrap the `warning-icon.svg`, copy from the AC, and `Button`.
> * Use the dismissed item infrastructure to allow the button to dismiss the notice using the `USER_INPUT_LEGACY_SITE_PURPOSE_DISMISSED_ITEM_KEY` key.
> * Update styles if required in `assets/sass/components/user-input/googlesitekit-user-input-preview.scss` to match [Figma design](https://www.figma.com/design/S2CNc1toIzC7UrGMgs79S6/Conversions?node-id=2770-52119&node-type=frame&t=91kYQwExSZBvYrG8-0).

I think we can use the subtle notification for the required banner instead of using the warning notice, can't we?

**Comment by eugene-manuilov** [comment]
IB ✔

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified Existing users that have previously saved "Sell products or services" answer for site purpose are shown the new inline banner in the Key metrics section of the admin settings
- Verified Banner match the content and design from [Figma](https://www.figma.com/design/S2CNc1toIzC7UrGMgs79S6/Conversions?node-id=2770-52119&node-type=frame&t=gejNlcLG8c8JhLme-0)
- Verified It  stay visible in both Preview and Edit mode, above the selected answer/answers list
- Verified Clicking the Got it CTA dismisses the banner
- Verified notification is implemented as mentioned under  [Splitting “Sell products or services” site purpose answer](https://docs.google.com/document/d/1JvA3LK5SNfGH2o4OVnwjDdsAFuQMA9ZJj0T09RTqoy8/edit?pli=1&resourcekey=0-e90bcFGzAI6NhNu_D5i6hQ#heading=h.tobctwt5ojmh) section of the design doc


<details>

![Image](https://github.com/user-attachments/assets/5a2ac7a0-6af9-4a32-928f-e5b15ea98866)

![Image](https://github.com/user-attachments/assets/71552e6d-667d-4b52-ab87-82a0760150c3)

![Image](https://github.com/user-attachments/assets/b546009b-d360-4ccb-a8fa-4e3725a28498)

![Image](https://github.com/user-attachments/assets/fc3e916b-e6b5-4264-b287-8aff489f4469)

![Image](https://github.com/user-attachments/assets/dad0adb2-1f6a-4e18-831e-473e271a6a6e)

https://github.com/user-attachments/assets/de70eb86-8731-4c7c-bd9b-9526105efdb3

</details>
