### ISSUE TITLE
Unable to use Site Kit by Google Dev Settings

### ISSUE THREAD

**Issue by hugomartinez** [google/site-kit-wp#952]
## Bug Description

I try to use Site Kit on a staging environment (url : dev.domainName.com) so I use plugin Dev Settings but there are an error on step 2 : "La réponse n’est pas une réponse JSON valide." (on English : "Response is not a JSON valid response").

## Steps to reproduce

1. I upload Site Kit by Google Dev Settings on plugin folder (Site Kit prod is already on folder and activated but SetUp flow is not started)
2. I activate plugin Site Kit by Google Dev Settings
3. I fill form on Developers Settings (prod url and GCP credentials API)
4. I go to SetUp flow page of Site Kit and start to proceed
5. I log in on my google account on login page and I approve authorization
6. Go back to WordPress and the page show in screenshot

## Screenshots

![Capture d’écran 2019-12-08 à 22 17 12](https://user-images.githubusercontent.com/3845667/70396362-95974200-1a08-11ea-8083-e1fa770784b4.png)

## Additional Context

- PHP Version: 7.3
- OS: [e.g. iOS] macOS Mojave 10.14.6
- Browser [e.g. chrome, safari] chrome
- Plugin Version [e.g. 22] 1.1.2
- Device: [e.g. iPhone6] MacBook Air 13inch 2017

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by hugomartinez** [comment]
@felixarntz

**Comment by felixarntz** [comment]
Thanks for the report @hugomartinez! I wonder if the REST API request included some unexpected output that made the JSON invalid. Can you open your browser's developer tools, and then the `Network` tab? If you use Chrome, you can also filter by `XHR` requests. Try to do this again, it would be helpful if you could see what response that XHR request returns.

**Comment by hugomartinez** [comment]
I don't how it's possible but I was trying to do same process to check XHR requests as you ask for this. And now, it's work fine !

Do you have done something during this time ?

**Comment by felixarntz** [comment]
No I haven't changed anything. Maybe there was a temporary issue on your site that was causing this to break. Glad it works now!
