### ISSUE TITLE
Update RRM setup CTA copy

### ISSUE THREAD

**Issue by nfmohit** [google/site-kit-wp#9524]
## Feature Description

The RRM setup CTA copy should be updated to explicitly mention that "subscriptions" aren't available yet as part of the integration.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

The description text of the RRM setup CTA widget should be updated according to the following:

> Turn casual visitors into loyal readers and earn more from your content with voluntary contributions, surveys, newsletter sign-ups and reader insight tools. Learn more.
> 
> \* Support for subscriptions coming soon

## Implementation Brief

_Note for IB Reviewer: The following IB has already been covered in the PR [#9526](https://github.com/google/site-kit-wp/pull/9526). If the IB looks good to you, please feel free to review the PR and merge it if that looks good, as we're in a slight time-crunch with this one._

<hr>

* [ ] In `assets/js/modules/reader-revenue-manager/components/dashboard/ReaderRevenueManagerSetupCTABanner.js`:
	* [ ] Locate the paragraph tag containing the current CTA copy and replace that with the new text mentioned in the ACs.

### Test Coverage

* Fix any failing tests.
* Update any failing VRT references.

## QA Brief

* Set up Site Kit and turn on the `rrmModule` feature flag in the tester plugin.
* Observe the RRM setup CTA and verify that the description copy has changed according to the ACs.

## Changelog entry

* Update the RRM setup CTA copy to explicitly mention that subscriptions aren't available yet as part of the integration.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

The change to copy as per the AC is now appearing on the RRM setup CTA on the dashboard. 

> Turn casual visitors into loyal readers and earn more from your content with voluntary contributions, surveys, newsletter sign-ups and reader insight tools. Learn more.

> * Support for subscriptions coming soon

![Image](https://github.com/user-attachments/assets/8b7fc2ba-06bd-449f-a60f-91ed517bfa32)
