### ISSUE TITLE
Extra modal 'Failed to enable metric' appearing and non-responsive when cancelled

### ISSUE THREAD

**Issue by kelvinballoo** [google/site-kit-wp#9563]
## Bug Description

When we have the **Update** button in the 'Top Content' metric area for an audience tile, if we follow the below sequence, we will get two popups:
- Click on **Update**
- During the OAuth flow, click on **Cancel**
- Click on **Retry**
- Again click **Cancel** during the OAuth flow
- Click on **Cancel**

Another modal 'Failed to enable metric' appears and when you click **Cancel** there, nothing happens.
Video is attached further down for reference.

## Steps to reproduce

- Set up Site Kit with the `audienceSegmentation` feature flag enabled, tracking enabled, and Analytics connected using a property which is out of the gathering data state.
- Click on **Enable groups** to set up Audience Segmentation.
- Archive the `googlesitekit_post_type` custom dimension in Analytics.
- Back on Site Kit, clear session storage and refresh the page. Verify the **Update** CTA appears in the "Top content" metric area for the audience tile(s).
- Delete the `{db_prefix}_googlesitekit_additional_auth_scopes` entry from the `{db_prefix}_usermeta table` and refresh the page to ensure the edit scope is needed.
- Click on an **Update** CTA to enter the OAuth flow. Cancel out of the OAuth flow to return to Site Kit with an OAuth error.
- Click **Retry** on the 'Analytics Update Failed' error modal
- Cancel out of the OAuth flow to return to Site Kit
- Click **Cancel** on the 'Analytics Update Failed' modal, this will close the modal.

Another modal titled 'Failed to enable metric' appears and when you click **Cancel** there, nothing happens.

## Screenshots

<Details>

https://github.com/user-attachments/assets/cd63b574-e717-45da-811b-d26ae55c1659

</Details>

## Additional Context

 - PHP Version: 
 - Browser: [e.g. chrome, safari]
 - Plugin Version: [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When following the **steps to reproduce**, the second modal titled 'Failed to enable metric' should not appear.

## Implementation Brief

* [x] In the `AudienceTilePagesMetric` component, amend the `onCancel()` callback:
  * Include the property `isRetrying: false` in the object that is set for the `AUDIENCE_TILE_CUSTOM_DIMENSION_CREATE` value:
https://github.com/google/site-kit-wp/blob/6fd266fe7da3ad038e31c28373e8793a62937609/assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceTilesWidget/AudienceTile/AudienceTilePagesMetric.js#L180-L182

### Test Coverage

* No new tests needed.

## QA Brief

* Run through the **steps to reproduce** and verify the "Failed to enable metric" modal does not appear.

## Changelog entry

* Fix the issue where an extra "Failed to enable metric" modal appears when canceled in the Audience Segmentation "Top Content" custom dimension creation flow.

**Comment by nfmohit** [comment]
IB ✅

**Comment by kelvinballoo** [comment]
### QA Update ✅ 

When following the steps to reproduce, the second modal titled 'Failed to enable metric' no longer appears.

<Details>

https://github.com/user-attachments/assets/031d8edc-638e-486d-be3c-cfde1e06597e

</Details>
