### ISSUE TITLE
Improve rendering time of newly added "Setup CTA" SiWG notification

### ISSUE THREAD

**Issue by jimmymadon** [google/site-kit-wp#9568]
## Feature Description

In #9335, we have used the existing notifications infrastructure to render the Sign in With Google Setup CTA banner notification. Since the entire notifications queue is "checked", this banner takes a couple of seconds to load, similar to the newly refactored Setup Success subtle notifications (see issue #9488). We need to come up with a solution to perhaps split the queue into different groups of notifications and load them simultaneously, without necessarily showing them all at the same time. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `Sign in With Google` setup CTA banner notification created in #9335 should render as quickly as other existing Setup Banner CTAs such as the Audience Segmentation, Consent Mode or RRM Setup CTAs. Currently, the SiWG banner loads about 2-5 seconds slower than the rest. 

## Implementation Brief

* In `assets/js/googlesitekit/notifications/datastore/notifications.js`:
  * [x] Create an enum of different `notificationGroupID`s: `default`, and `setup-ctas` are good starting candidates.
  * [x] In the `registerNotification` action, a new `groupID` settings property should be added with the default value.
  * [x] The `getQueuedNotifications` selector and resolver (or control if #9488 is already merged) should now accept `groupID` as another optional parameter (default: `default`). It should now add another filter that only processes notifications that have the `groupID` that is passed.
  * [x] The `receiveQueuedNotifications` action should now accept the `groupID` along with the `queuedNotifications`. 
  * [x] The `RECEIVE_QUEUED_NOTIFICATIONS` reducer should store `queuedNotifications` keyed by the `groupID`.

* In `assets/js/components/notifications/Notifications.js`:
  * [x] Add a new `groupID` prop and pass it to `getQueuedNotifications()`. 

* In `assets/js/components/DashboardMainApp.js`:
  * [x] Call the `<Notifications>` component passing in the `groupID` as `setup-ctas`.

### Test Coverage

* Update jest tests to cover the new behaviour of `getQueuedNotifications`.

## QA Brief

* This issue does affect Banner Notifications, Error Notifications, Subtle Notifications and the SiwG Setup CTA Banner. So the following should be tested using the following QABs:
  * [Sign in With Google banner notification](https://github.com/google/site-kit-wp/issues/9335) - Verify that this now loads quickly  
  * GatheringDataNotification or ZeroDataNotification (simply ensure that they are triggered in any scenario - don't have to retest all possible scenarios here)
  * [UnsatisfiedScopesAlert notification](https://github.com/google/site-kit-wp/issues/8978)
  * [AudienceSegmentationSetupSuccessSubtleNotification](https://github.com/google/site-kit-wp/issues/9281)

## Changelog entry

* Introduce grouping of notification queues.

**Comment by aaemnnosttv** [comment]
> * Create an enum of different `notificationGroupIds`: `info-and-errors`, and `setup-ctas` are good starting candidates.

@jimmymadon let's use `default` for the default as we discussed since there is only one exception to this currently and most things should use the default.

Also, `ID` needs to be capitalized per our coding style (ESLint will require it anyways 😄 )

> * [ ]  The `getQueuedNotifications` selector and resolver (or control if [Improve rendering time of newly refactored "Setup Success" subtle notifications #9488](https://github.com/google/site-kit-wp/issues/9488) is already merged) should now accept the `groupId` as another parameter. It should now add another filter that only processes notifications that have the `groupId` that is passed.

Maybe this is covered in the other issue, but it's important that the queue for each group is stored separately, otherwise they'll compete for the same key and cause problems when they should be independent. We spoke about this too but probably worth making explicit.

**Comment by jimmymadon** [comment]
@aaemnnosttv Thanks for the feedback - all good points. Have updated the IB and made a few clarifications as suggested.

**Comment by aaemnnosttv** [comment]
Thanks @jimmymadon – I made one tweak to clarify that the new parameter should be optional as well and corrected the last instance of the old case 👍 

IB ✅

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified SIWG notification now loads quickly
- Verified GatheringDataNotification or ZeroDataNotification.
- Verified UnsatisfiedScopesAlert Notification.
- Verified AudienceSegmentationSetupSuccessSubtleNotification.

_SIWG banner notice_

<details>

https://github.com/user-attachments/assets/8a29afa2-2bf1-41a7-8fc5-dc0545608886

https://github.com/user-attachments/assets/10471cf7-6a72-4a6a-9a46-c33b84c81ee1

</details>

_Gathering notification_

<details>

![Image](https://github.com/user-attachments/assets/7fe6f89e-fc76-48a6-b24a-f1c3ac438e8b)

![Image](https://github.com/user-attachments/assets/0c4b0741-36f5-4bf8-b277-e58b278ec8fd)

</details>

_Zero data notifications_

<details>

![Image](https://github.com/user-attachments/assets/debd7382-65f7-46b5-9af0-0f7a73a9a84a)

</details>


_Audience segmentation subtle notification_

<details>

![Image](https://github.com/user-attachments/assets/caa8c245-8c0f-4f19-b6a6-70b0b748e130)

</details>

_Unsatisfied Scope Alert_

<details>

![Image](https://github.com/user-attachments/assets/adcc93f1-4ad7-4aa0-82dd-4b20df38d181)

</details>
