### ISSUE TITLE
Update Sign in with Google setup illustration

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#9576]
## Feature Description

After a discussion with @sigal-teller and @wpdarren, we're going to update the illustration used in the setup screen for Sign in with Google, see: https://www.figma.com/design/h9yGR15Pg2DUtgERW4AFAv/Sign-in-with-Google?node-id=600-1513&t=cf9I4eYhdUYKy9bh-4

### Before

![Image](https://github.com/user-attachments/assets/1564ac83-b79c-4b7e-b7da-203b5854f319)

### After

![Image](https://github.com/user-attachments/assets/2d2199af-f530-4958-9489-1fd10c45ac85)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The illustration used during the Sign in with Google module setup should be replaced with the version in this Figma design: https://www.figma.com/design/h9yGR15Pg2DUtgERW4AFAv/Sign-in-with-Google?node-id=600-1513&t=cf9I4eYhdUYKy9bh-4

## Implementation Brief

* [ ] In `assets/js/modules/sign-in-with-google/components/setup/SetupForm.js`
  * Replace the existing SVG graphic with the one from Figma linked in the AC

### Test Coverage

* Update VRT images

## QA Brief

* Test the SiWG setup form and verify the new illustration as per the AC.

## Changelog entry

* N/A

**Comment by tofumatt** [comment]
IB ✅

**Comment by tofumatt** [comment]
(This was missing an estimate, but I marked it as a 3 since it's very straightforward.)

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Tested the SiWG setup form and verified that the new illustration as per the AC.

<details>

![Image](https://github.com/user-attachments/assets/8f1ea17a-3f39-4870-a583-9d2be1fcf41a)

![Image](https://github.com/user-attachments/assets/f014241a-a349-4530-8022-7fede2120ac7)

![Image](https://github.com/user-attachments/assets/d9ec7179-2eec-4d88-b4ba-f6c84e8815d1)

![Image](https://github.com/user-attachments/assets/6fc208bd-e06f-4ad7-b9d2-df7193dc9479)

![Image](https://github.com/user-attachments/assets/5883afe4-3ded-47fe-8d06-d60d51a2c883)

![Image](https://github.com/user-attachments/assets/a9b52c5b-610b-4ed3-9f2d-7442bae2758d)

![Image](https://github.com/user-attachments/assets/0bf1c50c-036d-4b92-908e-fb8c8821955e)

</details>
