### ISSUE TITLE
ACF Wysiwyg Editor Visual Tab Not Clickable With Site Kit Activated

### ISSUE THREAD

**Issue by RamseyV** [google/site-kit-wp#958]
## Bug Description

When making a new post or page, the "Visual" tab of an acf wysiwyg editor is not clickable. All of the clickable options at the top of the editor are no longer there. This only happens when Site Kit is activated. 

## Steps to reproduce

1. Activate advanced custom fields and site kit (On a WordPress 4.9 or below install)
2. Create a new post and add an acf wysiwyg editor to the page. 
3. The "Visual" tab will not be clickable. The "Text" tab is selected (which isn't default) and it cannot be changed. 

## Screenshots
Here is what it looks like when Site Kit is not activated: 
![Screen Shot 2019-12-09 at 12 59 56 PM](https://user-images.githubusercontent.com/24296532/70460343-1182a000-1a84-11ea-846e-fac59244084e.png)
![Screen Shot 2019-12-09 at 12 59 50 PM](https://user-images.githubusercontent.com/24296532/70460349-13e4fa00-1a84-11ea-88ba-1f566a4e5018.png)

Here is what it looks like when Site Kit is activated: 
![Screen Shot 2019-12-09 at 12 57 23 PM](https://user-images.githubusercontent.com/24296532/70460367-219a7f80-1a84-11ea-967e-edd3c30e07de.png)

## Additional Context
This has been tested on multiple different devices and operating systems, all with the same result. It has been isolate by removing all plugins except for ACF and Site Kit. 

Wordpress Version: tested on 4.9.9 and 5.3
ACF Version: Advanced Custom Fields Pro 5.5.14

 - PHP Version: affected on multiple version of 7.1.* and 7.2.*
 - OS: [e.g. iOS] served OSX 10.14.6 and Linux (Amazon Linux 2), tested with OSX and Windows 7 & 10
 - Browser [e.g. chrome, safari] Chrome, Safari, Firefox
 - Plugin Version [e.g. 22] multiple versions from 1.0.4-beta to 1.1.2
 - Device: [e.g. iPhone6] Macbook Pro, Windows 7 & 10 machines

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
@RamseyV I am unable to recreate the same issue after [testing](https://recordit.co/dxr2mYNEjL) on 2 different sites. Can you check with another site and minimal plugins active and from a browser incognito window?

**Comment by RamseyV** [comment]
I just tried with a new install of wordpress 4.9.9, connected to a fresh database, no other plugins activated, and the Twenty Seventeen theme activated (Askimet Anti-Spam and Hello Dolly are installed but not activated). The only plugins activated are Site Kit 1.1.12 and Advanced Custom Fields PRO 5.5.14 and I am still getting the same bug. 

<img width="831" alt="Screen Shot 2019-12-11 at 1 39 16 PM" src="https://user-images.githubusercontent.com/24296532/70649725-b84d7480-1c1b-11ea-9622-0c4b7ec6dda1.png">

System Specs:
OSX 10.14.6 
PHP 7.2.1 
MySQL 5.6.38 
PHP and MySQL hosted by MAMP 4.5

Note: I used composer to install the plugins before, this time I just uploaded the zip files from the wordpress admin console.

**Comment by RamseyV** [comment]
I just tested in WordPress 5.3 and it is working. This seems to only be an issue in WordPress 4.9, but I have not tested this in any other versions.

**Comment by jamesozzie** [comment]
@RamseyV Thanks for the update and additional checks. For WordPress 4.9 or previous versions I will check with the team or install the Gutenberg plugin and check for compatibility.

**Comment by jamesozzie** [comment]
@RamseyV Just following up with you on this issue. I've tried to recreate the same issue using WordPress 4.8 and the ACF wysiwyg visual button is working as expected using the free version. Are you still using and post 5.0 version of WordPress which you can test with?

**Comment by jamesozzie** [comment]
@RamseyV Just checking if this issue persists from your side. If so can you please share any console errors you encounter in order to share with the team?

**Comment by RamseyV** [comment]
I am no longer getting this issue. Thanks!

**Comment by martin-levai99** [comment]
I encountered a similar issue using the Wysiwig editor and Gutenberg. 
It seems that the TinyMCE assets are not being loaded correctly or too late. 

I fixed it using this code: 
```
function enqueue_tinymce_assets() {
    // Check if we are in the admin area and ensure ACF is active
    if (is_admin() && function_exists("acf")) {
        // Enqueue the core WordPress TinyMCE scripts
        wp_enqueue_script("wp-tinymce");
        wp_enqueue_script("editor");
        wp_enqueue_script("quicktags");

        // Enqueue TinyMCE style (if needed for customizations)
        wp_enqueue_style("editor-buttons");
    }
}
add_action('admin_enqueue_scripts', 'enqueue_tinymce_assets', 0);
