### ISSUE TITLE
Remove title borders from Admin Setting Sections

### ISSUE THREAD

**Issue by zutigrm** [google/site-kit-wp#9580]
## Feature Description

Borders should be removed from bellow the section titles in the admin settings, and any other edits if needed - like spacing, etc. Figma design can be found [here](https://www.figma.com/design/S2CNc1toIzC7UrGMgs79S6/Conversions?node-id=2771-60053&node-type=frame&t=vQeH1P2OKGqFJqeG-0)

Currently, boxes with borders:
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXVDQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--88cf42b3096b93015d7745c6ca505b1a8fefc861/image.png" alt="image.png" />

New design without borders:
![Image](https://github.com/user-attachments/assets/b0b27ec0-27c5-4bed-9000-205505c02436)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Borders from bellow the admin settings section titles are removed and spacing is adjusted if needed and settings sections are matching the new [Figma design](https://www.figma.com/design/S2CNc1toIzC7UrGMgs79S6/Conversions?node-id=2771-60053&node-type=frame&t=vQeH1P2OKGqFJqeG-0)

## Implementation Brief

* [ ] Create a new SASS file for targeting admin settings base, at `assets/sass/components/settings/_googlesitekit-settings-admin.scss`
    * [ ] Import this file into the base `admin.scss` file at `assets/sass/admin.scss`, within the `// Settings` import group.
    * [ ] Target the settings page selector: `.googlesitekit-plugin #js-googlesitekit-settings` and within it:
        * [ ] Target `.googlesitekit-layout__header` and remove the boarder, and within it:
            * [ ] Target `.mdc-layout-grid` and remove the bottom padding, and within it:
                * [ ] Target `h3.googlesitekit-layout__header-title` and set the following CSS properties:
                    * [ ] `font-family: $f-primary;`
                    * [ ] `font-weight: $fw-medium;`
                    * [ ] `font-size: $fs-title-lg;`
* [ ] Validate the changes against the [Figma Design](https://www.figma.com/design/S2CNc1toIzC7UrGMgs79S6/Conversions?node-id=2771-60053&node-type=frame&t=LXqh7M54xXddOKTr-0). 

### Test Coverage

* [ ] Update VRT tests as required following the style changes. 

## QA Brief

* Set up Site Kit
* Navigate to `Site Kit > Settings > Admin Settings`
* Validate the setting group header styles against the issue requirements
* The Figma design can be found [here](https://www.figma.com/design/S2CNc1toIzC7UrGMgs79S6/Conversions?node-id=2771-60053&node-type=frame&t=9X23zprz3EeNKqKH-0)

## Changelog entry

* Update styles for the admin settings.

**Comment by 10upsimon** [comment]
Thanks @zutigrm AC ✅ Moving to IB and I'll pick this up.

**Comment by Aditya-PS-05** [comment]
Can you assign me this issue?

**Comment by kelvinballoo** [comment]
### QA Update ⚠ 

Did a check and here are my observations:

**ITEM 1:**
There was an extra 24px spacing for the Plugin Status section: between the text description and the 'Reset Sitekit' CTA.
Based on figma, it's only 24px.
<Details>
Implementation: 48px

![Image](https://github.com/user-attachments/assets/911364a1-20c8-41b7-8b9e-a67bb8f50ae4)

Figma: 24px:

![Image](https://github.com/user-attachments/assets/5bc14c91-ae10-41c4-bae4-5e1fb2135346)


</Details>

____________________________________________________________________

**ITEM 2:**
This feels out of scope and might not even be an issue but on Figma, for the 'Plugin Settings' involves a toggle.
However in our current implementation, it's a checkbox.
Let me know if this needs a separate ticket.

<Details>
Implementation:

![Image](https://github.com/user-attachments/assets/47757170-101a-4bd1-8c77-586921123737)


Figma:

![Image](https://github.com/user-attachments/assets/c258f9fd-4351-4124-82d4-887aff25f03d)

</Details>

____________________________________________________________

Other than that, the borders are not appearing, which is as expected.
<Details>

![Image](https://github.com/user-attachments/assets/37720f7a-ed40-43a8-9fa5-111e2ac4aa8a)

</Details>

**Comment by 10upsimon** [comment]
@kelvinballoo thank you. I have just pushed a PR that addresses the margin on the Reset Site Kit CTA text. The checkbox vs radio controls can be ignored as part of this issue.

**Comment by kelvinballoo** [comment]
### QA Update ✅ 
Thanks @10upsimon .

This was verified good. 

- Borders from below the admin settings section titles are removed and it's matching Figma.
- Verified across Chrome, Safari, Edge, Firefox desktop browsers
- Verified on mobile and tablet breakpoints

<Details>

![Image](https://github.com/user-attachments/assets/31a4d502-6330-4b3b-9b05-2ccf4af2b78d)

![Image](https://github.com/user-attachments/assets/f65bfd4b-78d1-421f-bb47-3918d7768c36)

</Details>
