### ISSUE TITLE
`TypeError: Invalid attempt to spread non-iterable instance` error when setting up Analytics

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#9590]
## Bug Description

Users have reported a continuous loading screen when trying to set up Google Analytics. These reports have occurred since the latest plugin release (1.138.0), and likely as a result of changes added as per https://github.com/google/site-kit-wp/issues/9348. 

`googlesitekit-vendor-cca22bcdeb2e1252b20a.js:7 Uncaught (in promise) TypeError: Invalid attempt to spread non-iterable instance.
`

Full error below:

<details><summary> Uncaught (in promise) TypeError: Invalid attempt to spread non-iterable instance</summary>

```
googlesitekit-vendor-cca22bcdeb2e1252b20a.js:7 Uncaught (in promise) TypeError: Invalid attempt to spread non-iterable instance.
In order to be iterable, non-array objects must have a [Symbol.iterator]() method.
at _nonIterableSpread (googlesitekit-vendor-cca22bcdeb2e1252b20a.js:7:654709)
at googlesitekit-vendor-cca22bcdeb2e1252b20a.js:1:77348
at reducerCallback (googlesitekit-modules-analytics-4-c82d34b549c6c79ba517.js:126:41700)
at reducer (googlesitekit-datastore-site-a25b86aff61d95d576a3.js:1:33952)
at googlesitekit-data-3b542d543c8681a7a9e3.js:1:4154
at Array.reduce ()
at googlesitekit-data-3b542d543c8681a7a9e3.js:1:4125
at googlesitekit-data-3b542d543c8681a7a9e3.js:1:4154
at Array.reduce ()
at Object.root (googlesitekit-data-3b542d543c8681a7a9e3.js:1:4125)
```

</details>

Reports below (most recent occurrence first):
- https://wordpress.org/support/topic/site-kit-cant-connect-to-analytics/ | **Open** | SH info
- https://wordpress.org/support/topic/install-site-kit-by-google-but-analytics-keeps-showing-connect-with-service/ | **Open** | SH info
- https://wordpress.org/support/topic/analytics-59/  | **Open** | No SH info

Potential workaround: 
For those impacted, please revert to Site Kit 1.137.0 to be able to complete Google Analytics connection. After set up is complete, you can switch back to the latest plugin version.

## Steps to reproduce

Unreproducible in support so far. For those that are impacted, the continuous loading screen occurs at soon as GA start starts, before selecting any GA account or property

## Screenshots

![Image](https://github.com/user-attachments/assets/f3a4ab86-696e-442f-b7e4-fb5661a7632f)

## Additional Context

 - SH 1.138.0
 - While we're awaiting users sharing their SH info, a couple of the support topics above does include their site URL

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Analytics setup flow should work regardless of whether or not the user has any Analytics accounts

## Implementation Brief

* This error is raised when the response from the Admin API returns nothing for `accountSummaries`, in which case it errors when attempting to spread `undefined` resulting in a TypeError
* Merge https://github.com/google/site-kit-wp/pull/9592

### Test Coverage

* Add coverage of the fetch action which covers the same case here ![Image](https://github.com/user-attachments/assets/b5e45749-4759-46ed-b485-cf9aedd127a2)

## QA Brief

* This issue was reproduced on [a test site owned by @jamesozzie](https://lethalwealth.s2-tastewp.com/)
* We can use the same site to confirm it is fixed
* This is a fix to an issue introduced in #9348 so the QA for that issue could also be revisited here as well

## Changelog entry

* Fix a bug that prevented the Analytics setup screen from loading if the connected Google account had no pre-existing Analytics accounts.

**Comment by jamesozzie** [comment]
Assigning this to you @nfmohit as discussed earlier today. I'll keep you updated on a [related testing task](https://app.asana.com/0/1185360131189553/1208669429040864/f) with any findings. 

cc @aaemnnosttv

**Comment by kelvinballoo** [comment]
### QA Update ✅ 

I was able to replicate the issue under the 1.138.0 version.
Then I tested the same under the develop branch and it was able to load properly without the error reported.

<Details>

https://github.com/user-attachments/assets/cd75542f-2012-4b8d-bccc-06d0c8d573ff

</Details>
