### ISSUE TITLE
Success banners remain present when the Audience Segmentation feature is disabled

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#9596]
## Feature Description

Both the [setup success banner on the dashboard](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-analytics4-components-audiencesegmentation-dashboard-audiencesegmentationsetupsuccesssubtlenotification--default) and the [setup success banner on the Settings screen](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-analytics4-components-audiencesegmentation-settings-settingscardvisitorgroups--with-setup-success-notification) will remain present when the Audience Segmentation feature has been disabled by toggling the **Display visitor groups in dashboard** switch off in Settings.

Toggling this switch off should dismiss both of the setup success banners.

See the related [Asana task](https://app.asana.com/0/1208235052195562/1208499973020585).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Having set up Audience Segmentation from the **Enable groups** CTA on the dashboard, and toggled **Display visitor groups in dashboard** off on the Settings screen:
  * The [setup success banner on the dashboard](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-analytics4-components-audiencesegmentation-dashboard-audiencesegmentationsetupsuccesssubtlenotification--default) should be dismissed.
* Having set up Audience Segmentation from the **Enable groups** CTA on the Settings screen, and toggled **Display visitor groups in dashboard** off:
  * The [setup success banner on the Settings screen](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-analytics4-components-audiencesegmentation-settings-settingscardvisitorgroups--with-setup-success-notification) should be dismissed.

## Implementation Brief

- [x] In `assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceSegmentationSetupSuccessSubtleNotification.js`
  - Use `isAudienceSegmentationWidgetHidden` selector to check if visitor groups have been disabled.
  - If it is disabled, then use `useEffect` to call `dismissNotification` and pass `AUDIENCE_SEGMENTATION_SETUP_SUCCESS_NOTIFICATION`.

- [x] In `assets/js/modules/analytics-4/components/audience-segmentation/settings/SettingsCardVisitorGroups/SetupSuccess/index.js`
  - Use `isAudienceSegmentationWidgetHidden` selector to check if visitor groups have been disabled.
  - If it is disabled, and the notification is not already dismissed (i.e. the existing `isDismissed` value is false), then use `useEffect` to call `dismissItem` action from `CORE_USER` store and pass `SETTINGS_VISITOR_GROUPS_SETUP_SUCCESS_NOTIFICATION` slug to it.

### Test Coverage

- Add tests for both the components where Display visitor groups setting is disabled such that these notifications should not display.

#### Setup success banner on the dashboard

1. Enable the audience segmentation feature from the setup banner using `Enable Groups` CTA.
2. Once the feature has been setup successfully, you will see the setup success banner on dashboard.
3. In a new tab, go to Site Kit settings and turn the `Visitor Groups` toggle off.
4. Refresh the dashboard and you shall not be able to see the setup success banner anymore.
5. Turn `Visitor Groups` toggle on again and refresh the dashboard, there should no longer be setup success banner.

#### Setup success banner on the Settings screen 

1. Enable the audience segmentation feature using the `Enable groups` link.
2. Once the feature has been setup successfully, you will see the setup success notification on settings screen.
3. Turn the `Visitor Groups` toggle off.
4. setup success banner should go away immediately.
5. Turn `Visitor Groups` toggle on again and refresh the dashboard, there should no longer be setup success banner on settings screen.

## Changelog entry

* Remove visitor groups setup success notifications when the user chooses not to display visitor groups in dashboard.

**Comment by ankitrox** [comment]
Thanks @techanvil, sorry I just missed about dismissing the notification pointer.

I have updated the IB which so that we make use of side effect to dismiss the notification/item.

**Comment by techanvil** [comment]
Thanks @ankitrox! That's looking good, there's just one small detail we might as well include, we should also check for `isDismissed` being false in the `useEffect()` call in `SettingsCardVisitorGroups/SetupSuccess` to avoid dismissing the item on every page load.

I've amended the IB accordingly to save a round trip.

IB ✅

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- Having set up Audience Segmentation from the Enable groups CTA on the dashboard, and toggled Display visitor groups in dashboard off on the Settings screen: the [setup success banner on the dashboard](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-analytics4-components-audiencesegmentation-dashboard-audiencesegmentationsetupsuccesssubtlenotification--default) is dismissed.

- Having set up Audience Segmentation from the Enable groups CTA on the Settings screen, and toggled Display visitor groups in dashboard off: the [setup success banner on the Settings screen](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-analytics4-components-audiencesegmentation-settings-settingscardvisitorgroups--with-setup-success-notification) is dismissed.

![Image](https://github.com/user-attachments/assets/3bbe65ed-a805-4ff2-be80-8d5d97d8cf08)
