### ISSUE TITLE
Custom Dimension not synced and created after enabling Audience Segmentation without dashboard refresh

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#9597]
## Bug Description

The `googlesitekit_post_type` custom dimension is not synced or created when Audience Segmentation is enabled from the dashboard setup CTA without refreshing the Site Kit dashboard after archiving the custom dimension. This also happens from the settings CTA if we don't refresh the page.

See the related [Asana task](https://app.asana.com/0/1208235052195562/1208487132526716).

## Steps to reproduce

1. Set up Site Kit with Analytics connected, and set up the Audience Segmentation feature to ensure the `googlesitekit_post_type` custom dimension is created for the connected property.
2. Reset Site Kit and connect the same Analytics property.
3. Ensure the list of available custom dimensions is synced - this could be through setting up Key Metrics with a tile that depends on a custom dimension, or running the following snippet in the JS console: `googlesitekit.data.dispatch( 'modules/analytics-4' ).fetchSyncAvailableCustomDimensions()`.
4. Go to the Site Kit dashboard and ensure the setup CTA banner is displayed (alternatively, navigate to the Settings screen and ensure the setup CTA is displayed there).
5. In a separate tab, go to the Analytics console and archive the `googlesitekit_post_type` custom dimension.
6. Back on Site Kit, enable Audience Segmentation from the setup CTA without refreshing page.
7. Observe that the custom dimension is not synced or created as expected.

## Screenshots

https://github.com/user-attachments/assets/37126deb-7b0c-46e8-988d-e7cc44a3e592

## Additional Context

 - PHP Version: any
 - OS: any
 - Browser: any
 - Plugin Version: 1.138.0
 - Device: any

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When setting up Audience Segmentation for the initial admin, the list of available custom dimensions should always be resynced, with the `googlesitekit_post_type` custom dimension being created if it doesn't currently exist.
* When running through the **steps to reproduce**, the `googlesitekit_post_type` custom dimension should be created.

## Implementation Brief

- [ ] In `assets/js/modules/analytics-4/datastore/audiences.js`  
  * In `enableAudienceGroupMain` action, call `fetchSyncAvailableCustomDimensionsStore.actions.fetchSyncAvailableCustomDimensions` around this place: https://github.com/google/site-kit-wp/blob/9a919e78e856ee0f7625e47200bd888288955c85/assets/js/modules/analytics-4/datastore/audiences.js#L385-L392

  * If any error is occurred, it should return it the same way like it is for the `syncAvailableAudiences` currently in `enableAudienceGroupMain` so that it can be handled if error is returned by the call to sync the custom dimensions.

### Test Coverage

- Add coverage for the above changes to the tests for the `enableAudienceGroup()` action.

## QA Brief

1. Set up Site Kit with Analytics connected, and set up the Audience Segmentation feature to ensure the `googlesitekit_post_type` custom dimension is created for the connected property.
2. Reset Site Kit and connect the same Analytics property.
3. Ensure the list of available custom dimensions is synced - this could be through setting up Key Metrics with a tile that depends on a custom dimension, or running the following snippet in the JS console: `googlesitekit.data.dispatch( 'modules/analytics-4' ).fetchSyncAvailableCustomDimensions()`.
4. Go to the Site Kit dashboard and ensure the setup CTA banner is displayed (alternatively, navigate to the Settings screen and ensure the setup CTA is displayed there).
5. In a separate tab, go to the Analytics console and archive the `googlesitekit_post_type` custom dimension.
6. Back on Site Kit, enable Audience Segmentation from the setup CTA without refreshing page.
7. Confirm in Google analytics console that the `googlesitekit_post_type` is created again.

## Changelog entry

* Fix a bug that caused a custom dimension to not be created while setting up visitor groups.

**Comment by ankitrox** [comment]
Thank you @techanvil . I've updated the IB as per your suggestions.

**Comment by techanvil** [comment]
Thanks @ankitrox, that LGTM. I've amended the **Test Coverage** section as we should include test coverage for the changes similar to how we test for the audiences being synced in the action.

IB ✅

**Comment by kelvinballoo** [comment]
### QA Update ✅ 

Verified the following and it's working as expected in dev environment:
After archiving the googlesitekit_post_type custom dimension, it's recreated again when after completing the 'Enable groups' flow.

Moving ticket to approval.

<Details>

Setting up:

https://github.com/user-attachments/assets/2cce4997-8e60-4d0d-b2ba-0a7d684beb57

Archiving and enabling:

https://github.com/user-attachments/assets/2858356e-c5b8-490c-bdc4-9b8dd4cf331c

googlesitekit_post_type custom dimension is re-created.

https://github.com/user-attachments/assets/1db7bb2c-8c2c-40f0-8517-3b328c20a321

</Details>
