### ISSUE TITLE
External icon not present for Analytics links in Audience Selection Panel and Placeholder Tile

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#9598]
## Feature Description

The Analytics links in the Audience [Selection Panel](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-analytics4-components-audiencesegmentation-dashboard-audienceselectionpanel--default) and [Placeholder Tile](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-analytics4-components-audiencesegmentation-dashboard-placeholdertile--with-configurable-non-default-audiences) don't have icons to indicate they are external links. We should add this icon to both links.

See related [Asana task](https://app.asana.com/0/1208235052195562/1208498359631493).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

The Analytics links in the Audience [Selection Panel](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-analytics4-components-audiencesegmentation-dashboard-audienceselectionpanel--default) and [Placeholder Tile](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-analytics4-components-audiencesegmentation-dashboard-placeholdertile--with-configurable-non-default-audiences) should have the external link icon.

## Implementation Brief

- [x] Remove `hideExternalIndicator` prop from `Link` component in following files.
 1. assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceSelectionPanel/LearnMoreLink.js
 
 2. assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceTilesWidget/PlaceholderTile.js

### Test coverage

No additional tests required.

## QA Brief

Make sure that [Selection Panel](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-analytics4-components-audiencesegmentation-dashboard-audienceselectionpanel--default) and [Placeholder Tile](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-analytics4-components-audiencesegmentation-dashboard-placeholdertile--with-configurable-non-default-audiences) both have external icons available.

## Changelog entry

* Add an external icon to external links in the audience selection panel and placeholder tile.

**Comment by techanvil** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The [Selection Panel](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-analytics4-components-audiencesegmentation-dashboard-audienceselectionpanel--default) and [Placeholder Tile](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-analytics4-components-audiencesegmentation-dashboard-placeholdertile--with-configurable-non-default-audiences) both have external icons.  See screenshots.

<details>
 <summary>Screenshots</summary>

![Image](https://github.com/user-attachments/assets/7dff996b-35d9-44b9-8d62-69036cdbe6fc)
![Image](https://github.com/user-attachments/assets/bf828126-d556-4a2a-b3dc-2986e42325bc)

</details>
