### ISSUE TITLE
Optimize how we disconnect users

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#960]
#809 exposed an issue where our reset used to be a quite expensive operation because we were making far too many DB calls. Furthermore, since this became unmanageable with a high amount of users on the site, it is very likely that the meta query we were using to get all users with Site Kit data was incorrect, returning all users instead and thus making the operation time out in many cases.

While we haven't doubled-down on what exactly went wrong there, let's get rid of a similar query that we use for "bulk-disconnecting", and let's optimize how we disconnect users overall. What we can simply do is delete all Site Kit-specific user options on such users. This also simplifies maintenance, as right now we have to manually add every new option to this process - actually there is already now one of the recently introduced options missing, which affirms how this is problematic.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A single database query should be used to disconnect a user. (The call to revoke that user's token should remain.)
* A single database query should be used to disconnect all users. (This is only needed in our 1.0.0 migration, so revoking the token for every user shouldn't happen here, as it can easily cause the request to time-out - plus it's a special case anyway.)

## Implementation Brief

* Merge #961 

## Changelog entry

* Optimize disconnecting users by only running a single database query.

**Comment by aaemnnosttv** [comment]
IB ✅ 
OK to move this one to code review I think 😄

**Comment by cole10up** [comment]
**Tested**

Ran a series of tests around disconnecting users, signing back in, resetting the plugin, setting the plugin back up. Trying different users.

All looking good.

Passed QA ✅
