### ISSUE TITLE
Inconsistent spacing between primary and secondary CTA in Audience Segmentation Setup CTA Banner

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#9600]
## Feature Description

There is a larger gap between the actions in the AS banner than the KM banner which looks off. (KM looks correct to me). I believe the AdSense setup CTA also has this quirk as well.

![Image](https://github.com/user-attachments/assets/78dd5f53-3eff-4c1f-8a8b-d84e408ba460)

Looking in Figma, the design shows this as 10px where in the plugin it's currently 30px

![Image](https://github.com/user-attachments/assets/fc471459-8d0c-445b-b451-4453d244e9d9)

![Image](https://github.com/user-attachments/assets/cd7d4380-ad82-46ba-bc49-756cef1b5cec)

As raised by @aaemnnosttv, see the related [Asana task](https://app.asana.com/0/1208235052195562/1208490790420472/f).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- The setup banners/widgets listed below should have their primary and secondary CTA gaps aligned. For each component the gaps between the CTAs should be as follows:
  - Phone viewport (up to 600px):
    - Horizontal gap: 4px.
    - Vertical gap: 4px (note, only some of the components will actually stack their CTAs vertically at narrower viewport widths).
  - Tablet and desktop viewports (above 600px):
    - Horizontal gap: 10px.
    - The vertical gap is irrelevant at these viewport widths.
- Setup banners/widgets:
  - [Ads](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-ads-components-dashboard-adsmodulesetupctawidget--default)
  - [AdSense](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-adsense-widgets-adsenseconnectcta--ready)
  - [Audience Segmentation](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-analytics4-components-audiencesegmentation-dashboard-audiencesegmentationsetupctatile--default)
  - [Consent Mode](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/consent-mode-consentmodesetupctawidget--default)
  - [Key Metrics](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/key-metrics--default)
- ~~Additionally, the [Ad Blocking Recovery, step 2 after CTA click](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-adsense-components-setup-adblockingrecoveryapp--step-two-after-cta-click) component should have its **Create message** CTA updated to be a tertiary button, and its CTA gaps aligned with the above.~~

These AC have been determined by reviewing Figma designs for CTA banners at different viewport widths. For example:
- Audience Segmentation:
  - [Phone viewport](https://www.figma.com/design/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?node-id=1655-35687&node-type=frame&t=MxhV3FiN8v9BlCey-0) (horizontally laid out).
  - [Tablet viewport](https://www.figma.com/design/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?node-id=1834-31500&node-type=frame&t=MxhV3FiN8v9BlCey-0)
  - [Desktop viewport](https://www.figma.com/design/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?node-id=1956-17850&node-type=frame&t=MxhV3FiN8v9BlCey-0)
- Reader Revenue Manager:
  - [Phone viewport](https://www.figma.com/design/f2AFGUqfH8rqi9BpJAwhHi/Reader-Revenue-Manager?node-id=545-3043&node-type=frame&t=V8fcFdI50EY2obf5-0) (vertically stacked).
  - [Tablet viewport](https://www.figma.com/design/f2AFGUqfH8rqi9BpJAwhHi/Reader-Revenue-Manager?node-id=545-3393&node-type=frame&t=V8fcFdI50EY2obf5-0)
  - [Desktop viewport](https://www.figma.com/design/f2AFGUqfH8rqi9BpJAwhHi/Reader-Revenue-Manager?node-id=30-908&node-type=frame&t=V8fcFdI50EY2obf5-0)

## Implementation Brief

 * [x] Update `assets/sass/components/adsense/_googlesitekit-adsense-ad-blocking-recovery.scss`, replace the use of `Link` here for a tertiary `Button`:
    https://github.com/google/site-kit-wp/blob/7846c3a2f3b703a5a6921d4870548e30daa7fc32/assets/js/modules/adsense/components/setup/AdBlockingRecoveryApp/steps/CreateMessageStep.js#L192-L199

* [x] Update the following CSS setting the css `gap` responsively based on the values defined in the AC, adding a media query if there isn't already one for the required breakpoint:
   * Ads:
     https://github.com/google/site-kit-wp/blob/7846c3a2f3b703a5a6921d4870548e30daa7fc32/assets/sass/components/ads/_googlesitekit-ads-setup-banner.scss#L56-L65
   * AdSense:
     https://github.com/google/site-kit-wp/blob/7846c3a2f3b703a5a6921d4870548e30daa7fc32/assets/sass/components/setup/_googlesitekit-adsense-connect-cta.scss#L307-L315
   * Audience Segmentation:
     https://github.com/google/site-kit-wp/blob/7846c3a2f3b703a5a6921d4870548e30daa7fc32/assets/sass/components/analytics-4/audience-segmentation/_googlesitekit-audience-segmentation-setup-cta.scss#L58-L72
   * Consent Mode:
     https://github.com/google/site-kit-wp/blob/7846c3a2f3b703a5a6921d4870548e30daa7fc32/assets/sass/components/dashboard/_googlesitekit-setup-cta-banner.scss#L69-L80
   * Key Metrics:
     https://github.com/google/site-kit-wp/blob/7846c3a2f3b703a5a6921d4870548e30daa7fc32/assets/sass/components/key-metrics/_googlesitekit-key-metrics-setup-cta.scss#L163-L166
   * Ad Blocking recovery:
     https://github.com/google/site-kit-wp/blob/7846c3a2f3b703a5a6921d4870548e30daa7fc32/assets/sass/components/adsense/_googlesitekit-adsense-ad-blocking-recovery.scss#L207-L211

### Test Coverage

* Update VRTs which fail due to the spacing changes. No additional tests are required.

## QA Brief

1. Go through following banners:

- Setup banners/widgets and ensure that the spacing between primary and secondary CTA is 4px on mobile screens and 10px on tablets and above.
  - [Ads](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-ads-components-dashboard-adsmodulesetupctawidget--default)
  - [AdSense](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-adsense-widgets-adsenseconnectcta--ready)
  - [Audience Segmentation](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-analytics4-components-audiencesegmentation-dashboard-audiencesegmentationsetupctatile--default)
  - [Consent Mode](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/consent-mode-consentmodesetupctawidget--default)
  - [Key Metrics](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/key-metrics--default)

2. Also, check [Ad Blocking Recovery, step 2 after CTA click](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-adsense-components-setup-adblockingrecoveryapp--step-two-after-cta-click) and ensure that this is appearing and working same as previous with the only difference in updated spacing.

## Changelog entry

* Update spacing between CTA actions for consistency.

**Comment by nfmohit** [comment]
AC ✅

**Comment by eugene-manuilov** [comment]
IB ✔

**Comment by kelvinballoo** [comment]
### QA Update ❌ 

Tested this and there are a couple of issues to highlight:

**ITEM 1:** ⚠ 
I could not get the Ads setup banner to pop up on develop and thus, I checked on storybook itself.
The spacings are fine but just wanted to confirm if we need to double check on the actual implementation itself? 

<Details>

![Image](https://github.com/user-attachments/assets/ebd7595f-fc19-4748-9d68-c2f23250386c)

![Image](https://github.com/user-attachments/assets/8d797101-7a1e-4795-a0ee-bff6c334d7e2)

![Image](https://github.com/user-attachments/assets/4bded687-d174-4c00-b388-19535c8d6caf)

![Image](https://github.com/user-attachments/assets/5575fe0f-1bdf-40a7-b940-25b7cba2f15f)

![Image](https://github.com/user-attachments/assets/18cf6375-2ace-4e42-9243-79b125334b63)

</Details>

________________________________________________________________________________

**ITEM 2:** ❌ 
 
I did a check on RRM banner. 
- At 601 px and above, the gap is only 4px. It's only on larger viewports (maybe 1100px) that it gets updated to 10px.
- Also, on iPhone SE, the buttons are vertically stacked whereas on iPhone 14 Pro Max, they are horizontal. I assume that's fine but raising in case there is any concern.

<Details>
At 601 px and above, the gap is only 4px. It's only on larger viewports (maybe 1100px) that it gets updated to 10px.

![Image](https://github.com/user-attachments/assets/8b662fcc-76c1-415b-8998-2a8843b2c357)

Also, on iPhone SE, the buttons are vertically stacked whereas on iPhone 14 Pro Max, they are horizontal. Do we have a concern for that?

![Image](https://github.com/user-attachments/assets/1643abcb-c149-4de1-b6e9-31dff226865a)

![Image](https://github.com/user-attachments/assets/c099f9d8-4919-499f-bd55-b5dc31816303)


</Details>


________________________________________________________________________________

**ITEM 3:** ⚠ 
For the Ad blocking recovery banner, there is some mismatch.
- First is in the button copy. On storybook it's 'My message is ready' and 'Create message'. On our plugin, it's 'Create message' and 'I published my message'.
- In the AC, it's mentioned that that Create message CTA will be updated to be a tertiary button. Can you clarify what's a tertiary button?
- On mobile, the gap is 26px. THat's not expected.
- Similarly, on desktop, it's 26px gap. Although, that might be fine, depending on the button style.

<Details>
Copy mistmatch:

![Image](https://github.com/user-attachments/assets/175c5c9e-01d6-4dcd-bb33-22e433bbb9b9)

![Image](https://github.com/user-attachments/assets/f66faac8-25be-4fe2-8aa9-f79525229d76)

Mobile: 26px gap:

![Image](https://github.com/user-attachments/assets/c36097ae-9f8b-4d49-8a95-fbcfaa20f9fb)


Desktop: 26px gap: 

![Image](https://github.com/user-attachments/assets/bfba8111-1c6e-4f50-9cd6-b501dcdbe5f8)


</Details>


________________________________________________________________________________

Other than that, the following were tested good: ✅ 
(Tested on actual banner on develop branch)
- AdSense
   <Details>

   ![Image](https://github.com/user-attachments/assets/7ae7ec2a-551f-4e5f-bd65-b12d4ef54155)

   ![Image](https://github.com/user-attachments/assets/dc1ca0a6-fc7d-4d5f-a110-220285d95a05)

   ![Image](https://github.com/user-attachments/assets/2c84ccf0-58f4-4078-84e3-de0e0319d23b)

   ![Image](https://github.com/user-attachments/assets/fb9a8dee-9621-44b7-a064-80bc006673c3)

   ![Image](https://github.com/user-attachments/assets/7ba01f86-fbdd-4d50-b07d-f79eee5e1867)

   ![Image](https://github.com/user-attachments/assets/34721018-de84-45eb-ae2a-4ad5b907307f)

   </Details>
- Audience Segmentation
   <Details>

   ![Image](https://github.com/user-attachments/assets/c5615c69-49d5-4915-8199-e7e3c1716c6d)

   ![Image](https://github.com/user-attachments/assets/622c7d6b-1d5f-4eb1-b972-777bfb520d59)

   ![Image](https://github.com/user-attachments/assets/fb739b18-57cb-464f-a8d5-2e9d14b04cb5)

   ![Image](https://github.com/user-attachments/assets/2a4fe271-26fa-4973-944d-7f9b81d16356)

   </Details>

- Consent Mode
   <Details>

   ![Image](https://github.com/user-attachments/assets/c90f9edd-e8e7-4f44-9b14-394db5b728db)

   ![Image](https://github.com/user-attachments/assets/4b726894-814e-4995-836e-d205e656d45a)

   ![Image](https://github.com/user-attachments/assets/8db9cb35-0f08-4567-810a-e4953c4b5f2a)

   ![Image](https://github.com/user-attachments/assets/6924f2b7-f439-4f09-81ec-4dfbb0f5dc56)

   ![Image](https://github.com/user-attachments/assets/ef36aec1-8ebc-44f7-aeb6-df8ede976274)

   </Details>

- Key Metrics
   <Details>

   ![Image](https://github.com/user-attachments/assets/11350e35-ac60-4cf1-9b4e-e324995315dd)

   ![Image](https://github.com/user-attachments/assets/6b9c8368-7ecd-4b05-b2de-f016fc4d0a97)

   ![Image](https://github.com/user-attachments/assets/a408fafc-81e8-47a3-823a-56de1ecea206)

   ![Image](https://github.com/user-attachments/assets/fea367b4-3d08-47ef-8b6c-52217fd58b88)

   </Details>

- Did a test on SiwG as well
   <Details>

   ![Image](https://github.com/user-attachments/assets/a5a64150-5c74-4b67-969e-481bef9f43e3). 

   ![Image](https://github.com/user-attachments/assets/1436ee5f-531c-43fa-89b2-978bc49ca28b)

   ![Image](https://github.com/user-attachments/assets/fc4063dd-b691-4015-94bf-89dffcea990a)

   ![Image](https://github.com/user-attachments/assets/146a7744-454f-414d-bd1b-5d87d8cef505). 

   </Details>

**Comment by nfmohit** [comment]
The follow-up PR has been merged. @kelvinballoo this is back with you for another pass, thank you!

CC: @wpdarren

**Comment by kelvinballoo** [comment]
### QA Update ⚠ 

Thanks @ankitrox for the contexts. Noted on ITEM 1.

Retested as follows:
**ITEM 2:**
RRM banner is now following the same spacing standards as the others.

<Details>

<img width="1306" alt="Image" src="https://github.com/user-attachments/assets/cfb890e2-674c-46e3-9881-ef250732a2ff" />

<img width="1301" alt="Image" src="https://github.com/user-attachments/assets/fe25a549-2022-4243-bbf6-d0750bbea539" />

<img width="1312" alt="Image" src="https://github.com/user-attachments/assets/9dc5f378-416e-42a4-893c-8c8ef4f3dba4" />

<img width="1312" alt="Image" src="https://github.com/user-attachments/assets/cc317dd6-7c0c-48b8-8e3a-2fff7268b9bf" />

</Details>

____________________________________________________________

*ITEM 3:*
Tested this and I noticed the Create message does not fully follow the tertiary button when it comes to the radius.

<Details>
Border radius currently is 4px:

<img width="1056" alt="Image" src="https://github.com/user-attachments/assets/6c7a2459-b5b3-465c-9173-436ead30576b" />

On Figma, it's 100px:

<img width="1216" alt="Image" src="https://github.com/user-attachments/assets/a1b568b2-111e-4428-a4b4-aa8fe628a8b0" />


</Details>

_______________________________________________________________________________

Other than that, the following were tested good: ✅ 
(Tested on actual banner on develop branch)
- AdSense
   <Details>

   ![Image](https://github.com/user-attachments/assets/7ae7ec2a-551f-4e5f-bd65-b12d4ef54155)

   ![Image](https://github.com/user-attachments/assets/dc1ca0a6-fc7d-4d5f-a110-220285d95a05)

   ![Image](https://github.com/user-attachments/assets/2c84ccf0-58f4-4078-84e3-de0e0319d23b)

   ![Image](https://github.com/user-attachments/assets/fb9a8dee-9621-44b7-a064-80bc006673c3)

   ![Image](https://github.com/user-attachments/assets/7ba01f86-fbdd-4d50-b07d-f79eee5e1867)

   ![Image](https://github.com/user-attachments/assets/34721018-de84-45eb-ae2a-4ad5b907307f)

   </Details>
- Audience Segmentation
   <Details>

   ![Image](https://github.com/user-attachments/assets/c5615c69-49d5-4915-8199-e7e3c1716c6d)

   ![Image](https://github.com/user-attachments/assets/622c7d6b-1d5f-4eb1-b972-777bfb520d59)

   ![Image](https://github.com/user-attachments/assets/fb739b18-57cb-464f-a8d5-2e9d14b04cb5)

   ![Image](https://github.com/user-attachments/assets/2a4fe271-26fa-4973-944d-7f9b81d16356)

   </Details>

- Consent Mode
   <Details>

   ![Image](https://github.com/user-attachments/assets/c90f9edd-e8e7-4f44-9b14-394db5b728db)

   ![Image](https://github.com/user-attachments/assets/4b726894-814e-4995-836e-d205e656d45a)

   ![Image](https://github.com/user-attachments/assets/8db9cb35-0f08-4567-810a-e4953c4b5f2a)

   ![Image](https://github.com/user-attachments/assets/6924f2b7-f439-4f09-81ec-4dfbb0f5dc56)

   ![Image](https://github.com/user-attachments/assets/ef36aec1-8ebc-44f7-aeb6-df8ede976274)

   </Details>

- Key Metrics
   <Details>

   ![Image](https://github.com/user-attachments/assets/11350e35-ac60-4cf1-9b4e-e324995315dd)

   ![Image](https://github.com/user-attachments/assets/6b9c8368-7ecd-4b05-b2de-f016fc4d0a97)

   ![Image](https://github.com/user-attachments/assets/a408fafc-81e8-47a3-823a-56de1ecea206)

   ![Image](https://github.com/user-attachments/assets/fea367b4-3d08-47ef-8b6c-52217fd58b88)

   </Details>

- Did a test on SiwG as well
   <Details>

   ![Image](https://github.com/user-attachments/assets/a5a64150-5c74-4b67-969e-481bef9f43e3). 

   ![Image](https://github.com/user-attachments/assets/1436ee5f-531c-43fa-89b2-978bc49ca28b)

   ![Image](https://github.com/user-attachments/assets/fc4063dd-b691-4015-94bf-89dffcea990a)

   ![Image](https://github.com/user-attachments/assets/146a7744-454f-414d-bd1b-5d87d8cef505). 

   </Details>

**Comment by techanvil** [comment]
> **ITEM 3:** ⚠ 
Tested this and I noticed the Create message does not fully follow the tertiary button when it comes to the radius.

Hi @kelvinballoo, thanks for flagging this issue. I've reviewed the Ad Blocking Recovery component and have realised that in fact I made an oversight while drafting the AC.

The "Create message" and "I published my message" CTAs are in fact external links, and so they are rendered as semantic links using an `a` anchor tag even when using the `Button` component.

This being the case, we should not be attempting to render them as buttons and the previous implementation was correct. I've struck out the relevant AC point.

@ankitrox, would you mind creating a followup PR to back out the changes you made to Ad Blocking Recovery component? Please target `main` for the PR as this is a release issue. Sorry for the inconvenience.

**Comment by techanvil** [comment]
Back to you for another look, @kelvinballoo.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

Verified:  Tested this and the Create message fully follows the tertiary button when it comes to the radius.

![Image](https://github.com/user-attachments/assets/db62d138-1802-4312-888a-ae850e496d68)
