### ISSUE TITLE
Console warning from Selection Panel when audience has no description

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#9602]
## Feature Description

If an audience has been created without setting a description, a required proptype console warning appears for the `AudienceItem` component in the Selection Panel.

![Image](https://github.com/user-attachments/assets/5b9a08f4-7f18-4f87-a359-cb7ac2a2a6d5)

See the related [Asana task](https://app.asana.com/0/1208235052195562/1208489517112458).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* If an audience has been created without setting a description, the above console warning should not appear when opening the Audience Selection Panel.

## Implementation Brief

* [x] Remove `isRequired` from the `description` proptype definition for the `AudienceItem` component.

### Test Coverage

* 

## QA Brief

* Add an audience in GA-4 without adding the description.
* Setup the audience segmentation feature in Site Kit dashboard and open Audience Selection panel.
* There should not be any warning in console stating
```
Failed prop type: The prop `subtitle` is marked as required in `AudienceItem`, but its value is `null`.
```

## Changelog entry

* Improve visitor groups selection panel to prevent a console warning.

**Comment by techanvil** [comment]
Thanks @wpdarren. I've had a look and I do see the error as reported on `main`, while as you've noted it's not on `develop`.

As for the `initialFocus` error, this is a new defect and out of scope for this issue. It is however present on `main` so it's not a regression for the current release. It doesn't seem to cause a usability problem, thankfully.

Please can you or @mohitwp create an issue for the above error, while this issue can be moved to Approval.

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Tested by creating audience without description
- Verified that on dev environment  reported console error is not appearing.
Note : I created https://github.com/google/site-kit-wp/issues/9758 for initial scope console  error on dev environment.

<details>

![Image](https://github.com/user-attachments/assets/8a9c6287-7c6c-4254-bf0d-3cfd5f3b14ac)

</details>
