### ISSUE TITLE
Key metrics banner issues

### ISSUE THREAD

**Issue by kelvinballoo** [google/site-kit-wp#9614]
## Bug Description

The key metrics banner as 2 issues:
**ISSUE 1 :** 
It's written Intereseted in specific metrics?
There is a typo. It should have been 'Interested'
<Details>

![Image](https://github.com/user-attachments/assets/c2f59a87-8274-453a-9f18-bc6802c33e1b)

</Details>

**ISSUE 2:** 
For RTL language, the banner is haywire. Image attached.
Also, the 'Get tailored metrics' button isn't functional then.
<Details>

![Image](https://github.com/user-attachments/assets/33a9049d-6ed6-42f7-8886-17c95b8e047b)

</Details>

## Steps to reproduce

1. Set up Site Kit
2. Review the banner on the SK Dashboard

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* In key metrics setup banner, `Intereseted in specific metrics?` should be corrected to say `Interested in specific metrics?` (`Intereseted` has a typo)
* In RTL mode, the graphic should be mirrored to the left side of the banner
  * Graphic should be flipped horizontally

## Implementation Brief

* [x] Update `assets/sass/components/key-metrics/_googlesitekit-key-metrics-setup-cta.scss`
  * Add new small group, under `html[dir="rtl"]` selector, and target:
    * `html[dir="rtl"] .googlesitekit-plugin .googlesitekit-setup__wrapper--key-metrics-setup-cta .googlesitekit-preview-block ` - it should have `left: 0; right: unset;` on media queries with `min-width: 800px`
    * `html[dir="rtl"] .googlesitekit-plugin .googlesitekit-setup__wrapper--key-metrics-setup-cta div.googlesitekit-widget-key-metrics-svg__wrapper svg`
      * On `min-width: $bp-desktop` it should have `left: 0; right: unset;`, and flip it horizontally with `transform: scaleX(-1)`
      * On `min-width: $bp-wpdb4` it should have `left: -15px;`
* [ ] Update `assets/js/components/KeyMetrics/KeyMetricsCTAFooter.js`
  * In `Intereseted in specific metrics?` replace `Intereseted` with  `Interested`

### Test Coverage

* Update any failing VRT 

## QA Brief

* Set up Site Kit
* Review the KMW setup CTA banner on the dashboard screen
    * Confirm that the spelling error of "Interested" has been corrected
    * Confirm that when using RTL language, the banner image and copy are no longer incorrect, image should be on the left and text and cta's on the right 

## Changelog entry

* Fix typo in Key Metrics Widget.

**Comment by zutigrm** [comment]
Since AC is small and straightforward for fixing a bug, I added an IB as well to get it moving. If AC is good, it can be moved to the IBR

**Comment by 10upsimon** [comment]
@zutigrm AC and IB ✅ Moving to EB, I will pick this up

**Comment by kelvinballoo** [comment]
### QA Update ✅ 
Moving ticket to approval.
- The spelling error of "Interested" has been corrected
   <Details>

   ![Image](https://github.com/user-attachments/assets/581662cb-3341-4375-8648-875b79ee9e6f)

   </Details>
- When using RTL language, the banner image and copy are no longer incorrect, image is on the left and text and cta's on the right

   <Details>

   ![Image](https://github.com/user-attachments/assets/e7bd9e3b-4060-4100-9d64-12ec6778fecb)

   </Details>
