### ISSUE TITLE
Authentification redirecting to home page (

### ISSUE THREAD

**Issue by fredetco** [google/site-kit-wp#962]
## Bug Description

I have installed Site Kit on multiple sites flawlessly, for some reason, Site kit setup doesn't fully complete or complete at all after activating plugin.

It's always the same behaviour:

Installed Plugin
Activate Plugin
Start Setup (I have Reset Site Kit multiple times ...)
Sign in with Google
Choose my Google Account
Click Allow
After a while the page refresh and goes back to the homepage (with Wp-Admin toolbar ontop)

I have tried multiple reset kit option
I have tried Google (both normal and incognito) and Firefox, no luck, same thing.

Thank you!

## Steps to reproduce

1. Go to '...' **/wp-admin/**
2. Click on '....' **Site Kit / Dashboard**
3. Scroll down to '....' **Start Setup**
4. See error **The Site Kit plugin is active but requires setup**

## Additional Context

 - PHP Version: 
 - Plugin Version [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
@fredetco Thanks for reporting. We have moved Site Kit support over to the [WordPress support forum](https://wordpress.org/support/plugin/google-site-kit/). If you wish to open a support topic there we can hopefully assist. Please share as much information as possible, including your domain is possible or [Site Health information](https://i.imgur.com/Rtkmsba.png) on the site you are reporting on.
