### ISSUE TITLE
Add `firstPartyMode` Feature Flag

### ISSUE THREAD

**Issue by hussain-t** [google/site-kit-wp#9623]
## Feature Description

Implement the `firstPartyMode` feature flag to control the availability of First-party mode functionality during development. This flag will enable or disable First-party mode features through the tester plugin, facilitating testing and phased rollout.

For more details, see the [Feature Flag](https://docs.google.com/document/d/1PHptJ1Js_1OZrk5kRwoB3zPB2KQrXLJV7-3izi-bB30/edit?tab=t.0#heading=h.u26gj5vc0mo9) section in the design doc.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new feature flag, `firstPartyMode` should be added to the list of available feature flags.
* It should be possible to toggle this feature on/off using the Site Kit Tester Plugin.

## Implementation Brief

* [ ] Add the `firstPartyMode` feature flag to the list of feature flags in `feature-flags.json`.

### Test Coverage

* No new tests needed.

## QA Brief

* Verify the `firstPartyMode` feature flag can be toggled in the Tester plugin.

## Changelog entry

* N/A

**Comment by techanvil** [comment]
IB ✅

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified that A new feature flag, `firstPartyMode` added to the list of available feature flags.
- Verified that it is possible to enable/disable feature flag using the Site Kit Tester Plugin.

<details>


![Image](https://github.com/user-attachments/assets/ec40b0a2-e547-4283-9697-f577cb0e39eb)

![Image](https://github.com/user-attachments/assets/f726b072-79e4-4abb-83d5-91da5ab60dfe)

![Image](https://github.com/user-attachments/assets/aa0faffc-a935-438d-b57f-5c171dfd3e54)

</details>
