### ISSUE TITLE
Create First-party mode base class, settings, and REST API controller

### ISSUE THREAD

**Issue by hussain-t** [google/site-kit-wp#9625]
## Feature Description

Develop the foundational structure for First-party mode by implementing a base class, settings class, and REST API controller.

This includes:

A `First_Party_Mode_Settings` class to define and manage the First-party mode settings.
A `REST_First_Party_Mode_Settings_Controller` class to handle REST API endpoints.
A `First_Party_Mode` base class that will serve as the main entry point, registering and instantiating the settings and REST controller classes.

See the [design doc for more details](https://docs.google.com/document/d/1PHptJ1Js_1OZrk5kRwoB3zPB2KQrXLJV7-3izi-bB30/edit?tab=t.0#heading=h.kvmx5h32gtz1).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* **Namespace:** The infrastructure for handling First-party mode should be organized within the `Google\Site_Kit\Core\Tags\First_Party_Mode` namespace.
* A `First_Party_Mode_Settings` class should be created to define the `googlesitekit_first_party_mode` settings object, including:
    * An `isEnabled` boolean property to indicate if First-party mode is on or off.
    * An `isFPMHealthy` boolean property to track the status of the FPFE health check.
    * An `isScriptAccessEnabled` boolean property to track whether direct script access is blocked.
    * Default values and sanitization callbacks for each setting should be defined.
* A `REST_First_Party_Mode_Settings_Controller` class should be created to handle REST API requests for First-party mode settings with the following endpoints under `core/site/data`:
    * `GET fpm-settings`: Retrieves the current First-party mode settings.
    * `POST fpm-settings`: Updates the First-party mode settings, allowing users to enable/disable the mode.
    * **Note:** The `fpm-server-requirement-status` endpoint will be implemented in a separate issue.
* A `First_Party_Mode` base class should be created and used to instantiate and register the `First_Party_Mode_Settings` and `REST_First_Party_Mode_Settings_Controller` classes, ensuring they are loaded properly within Site Kit.
    * The `First_Party_Mode` base class should handle any additional setup or hooks necessary for managing First-party mode.
* The base class should be instantiated and registered in the main Site Kit plugin file only if the `firstPartyMode` feature flag is enabled.

## Implementation Brief

- The PHP classes defined in the AC should be implemented following Site Kit's standard patterns and conventions.
- The Consent Mode classes can serve as a reference:
  - [`Core\Consent_Mode\Consent_Mode_Settings`](https://github.com/google/site-kit-wp/blob/dcc8d100cf95dffe7564727a5fbc6395c73bc1a5/includes/Core/Consent_Mode/Consent_Mode_Settings.php)
    - The `enabled` setting can be used as an example for the boolean settings `isEnabled`, `isFPMHealthy` and `isScriptAccessEnabled`.
    - It's not necessary to add individual accessors for the settings at this point, as they may not be needed. They can be added in a subsequent issue if it turns out they will be useful.
  - [`Core\Consent_Mode\REST_Consent_Mode_Controller`](https://github.com/google/site-kit-wp/blob/dcc8d100cf95dffe7564727a5fbc6395c73bc1a5/includes/Core/Consent_Mode/REST_Consent_Mode_Controller.php)
    - The `core/site/data/consent-mode` route can be used as an example for the `core/site/data/fpm-settings` route.
    - The `GET core/site/data/fpm-settings` endpoint should be preloaded using `googlesitekit_apifetch_preload_paths`.
  - [`Core\Consent_Mode\Consent_Mode`](https://github.com/google/site-kit-wp/blob/dcc8d100cf95dffe7564727a5fbc6395c73bc1a5/includes/Core/Consent_Mode/Consent_Mode.php)
    - The code [up to and inclusive of the REST controller registration](https://github.com/google/site-kit-wp/blob/dcc8d100cf95dffe7564727a5fbc6395c73bc1a5/includes/Core/Consent_Mode/Consent_Mode.php#L1-L76) can serve as an example. The rest is not relevant for this issue.
- For the instantiation and registration of the `First_Party_Mode` class, see that of the `Consent_Mode` class for an [example](https://github.com/google/site-kit-wp/blob/dcc8d100cf95dffe7564727a5fbc6395c73bc1a5/includes/Plugin.php#L226). It should however be wrapped in a check for the `firstPartyMode` feature flag being set. To retrieve the state of the feature flag, use `Feature_Flags::enabled( 'firstPartyMode' )`.

### Test Coverage

- Add PHPUnit test coverage for the `First_Party_Mode_Settings` and `REST_First_Party_Mode_Settings_Controller` classes.

## QA Brief

* Enable the `firstPartyMode` feature flag.
* To verify the `fpm-settings` endpoint is preloaded, open the browser console and execute `_googlesitekitAPIFetchData.preloadedData`.
* Verify it contains `/google-site-kit/v1/core/site/data/fpm-settings` in the object.
* To execute the `fpm-settings` REST API endpoints, go to the Analytics settings page and open the browser developer tools "Network" tab.
* Refresh the page if you don't see a request to `conversion-tracking` in the network tab.
* Right-click on the `conversion-tracking` request and select "Copy->Copy as fetch":
![Image](https://github.com/user-attachments/assets/1d7c2d74-a3f7-44a4-8c95-0a6ecaacfb79)
* Open the browser console and paste the copied fetch command.
* Replace the `conversion-tracking` part of the URL with `fpm-settings` and execute the command:
    ```json
    "http://sitekit.10uplabs.com/wp-json/google-site-kit/v1/core/site/data/fpm-settings?_locale=user"
    ```
* Verify that the response contains the default First-party mode settings:
    ```json
    {
        "isEnabled": null,
        "isFPMHealthy": null,
        "isScriptAccessEnabled": null
    }
    ```
* To verify the `POST fpm-settings` endpoint, edit the Analytics settings and enable/disable the "Enable enhanced conversion tracking" toggle, and save the changes.
* Copy the fetch command from the `conversion-tracking` request as described above and replace the URL with `fpm-settings`.
* From the `body` object, change the `enabled` property to `isEnabled` and set it to `true` or `false`:
    ```json
    "body": "{\"data\":{\"settings\":{\"isEnabled\":true}}}",
    ```
* Execute the command and verify that the response contains the updated First-party mode settings.
* Verify that the `googlesitekit_first_party_mode` option is updated with the new settings in the `wp_options` table in the database.
* Disable the `firstPartyMode` feature flag and verify that the First-party mode settings routes are no longer available.

## Changelog entry

* Add REST endpoints for First-Party Mode module settings.

**Comment by techanvil** [comment]
Hey @hussain-t, thanks for drafting the AC. In general I prefer to avoid these IB-like ACs but sometimes it's unavoidable and this seems like one of those times.

Arguably, the IB could simply state "implement as per the AC", but it could also expand on the detail, we can leave that for the IB author to decide.

The only question I have relates to the one I [raised](https://docs.google.com/document/d/1PHptJ1Js_1OZrk5kRwoB3zPB2KQrXLJV7-3izi-bB30/edit?disco=AAABRiTUcrY in the design doc about the `is_fpm_health_check_failed` and `is_script_access_disabled` setting names, I would prefer to invert them to make them a bit easier to comprehend, but it's manageable enough to keep them as they are. Please review my comment on the design doc, and update these AC accordingly if we do make that change.

**Comment by hussain-t** [comment]
Thanks, @techanvil! I agree with avoiding IB-like ACs. In cases like this, though, a bit more specificity helps provide a clear understanding.

**Comment by hussain-t** [comment]
Thanks, @techanvil. The IB almost looks good. However, I'd suggest adding the individual accessors for the settings for completion and bumping the estimate up to 19 to avoid overages.

**Comment by techanvil** [comment]
Thanks for the feedback @hussain-t. I am a bit hesitant though with regard to the accessors, including them just for the sake of completion might result in us maintaining dead code if we don't end up using them. Can you point to where we know they will be used? When I had a browse of the issues for this epic it didn't look like they will end up being needed, although I could be wrong there.

**Comment by hussain-t** [comment]
Thanks, @techanvil, that sounds reasonable. We can add them as needed. Let’s go ahead and bump it to 19.

IB ✅

**Comment by kelvinballoo** [comment]
### QA Update ✅ 

Tested this and results are as expected.
Moving ticket to approval.

-  fpm-settings endpoint is preloaded
   <Details>

   ![Image](https://github.com/user-attachments/assets/6c1aba8e-d283-4371-bc99-47353ebe159c)

   </Details>

- Copy as fetch for the conversion-tracking request was successful and the response contains the default FPM settings

   <Details>

   ![Image](https://github.com/user-attachments/assets/dd0e10ab-6d0e-4492-9a65-758b1c086f66)

   ![Image](https://github.com/user-attachments/assets/d1acf14f-7f9e-4a11-80bb-b37d9fd0c5d2)

   </Details>

- Copy as fetch for POST fpm-settings endpoint was successful and the response contained the updated FPM settings, whether it was True or false.

   <Details>

   ![Image](https://github.com/user-attachments/assets/5d97fc02-6b78-4886-adbd-01374d561598)

   ![Image](https://github.com/user-attachments/assets/4e93f065-f06e-43b4-9567-45c59ddbd649)

   ![Image](https://github.com/user-attachments/assets/05951628-8d02-4bb2-9e5b-9c6749f5b482)

   </Details>

- The googlesitekit_first_party_mode option is updated accordingly in the wp_options table in the database, based on what was set in the command. 
   <Details>

  ![Image](https://github.com/user-attachments/assets/c460dba1-ada3-4abf-b476-0b3d07dd02e0)

  ![Image](https://github.com/user-attachments/assets/dfd6bbc7-3441-4eb2-9b73-21483c41b669)

   </Details>

- When the firstPartyMode feature flag is disabled, the First-party mode settings routes are no longer available and will hit 404 not found error.
   <Details>

   ![Image](https://github.com/user-attachments/assets/799dcf34-c171-487f-ae3b-30fc33edcb33)

   ![Image](https://github.com/user-attachments/assets/bbe8c2cd-bfa6-4f0a-88a5-3d74788de898)


   </Details>
