### ISSUE TITLE
Create First-Party Mode Partial Datastore in Core Site

### ISSUE THREAD

**Issue by hussain-t** [google/site-kit-wp#9628]
## Feature Description

Implement a new partial datastore for First-party mode within the `core/site` datastore. This store will manage actions and selectors specific to First-party mode settings and communicate with the REST API endpoints defined in the backend infrastructure. The datastore will retrieve, set, and persist the First-party mode settings, including its enabled status, FPFE health check status, and script access status.

See the [design doc for more details](https://docs.google.com/document/d/1PHptJ1Js_1OZrk5kRwoB3zPB2KQrXLJV7-3izi-bB30/edit?tab=t.0#heading=h.b7hfno5zm39f).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new partial datastore file, `first-party-mode.js`, should be created in the `assets/js/googlesitekit/datastore/site` directory to manage First-party mode settings.
* The following actions should be implemented in the datastore to interact with the `fpm-settings` REST API endpoints:
    * `fetchGetFirstPartyModeSettings()`: Retrieves the current First-party mode settings from the server by sending a `GET` request to the `fpm-settings` endpoint.
    * `fetchSaveFirstPartyModeSettings( {} )`: Saves the First-party mode settings to the database by sending a `POST` request to the `fpm-settings` endpoint.
    * `setFirstPartyModeEnabled( bool )`: Updates the enabled/disabled state of First-party mode in the store.
* The following selectors should be implemented in the datastore:
    * `getFirstPartyModeSettings()`: Retrieves the First-party mode settings object.
    * `isFirstPartyModeEnabled()`: Returns the enabled state of First-party mode.
    * `isFPMHealthy()`: Retrieves the status of the FPFE health check.
    * `isScriptAccessEnabled()`: Retrieves the status of direct PHP script access.
* Integrate the new `first-party-mode.js` datastore into the main site datastore in `assets/js/googlesitekit/datastore/site/index.js`.

**Note:** The `fpm-settings` REST API endpoints are being implemented in #9625.

## Implementation Brief

Note: This [PR](https://github.com/google/site-kit-wp/pull/9642) can be used as the base for this ticket as it already registers the data store for first party mode.

- [x] Create `assets/js/googlesitekit/datastore/site/first-party-mode.js`.
  - Use `createFetchStore` to get the first party (`fetchGetFirstPartyModeSettings`) mode settings and save the first party mode settings (`fetchSaveFirstPartyModeSettings`). Reference of [conversion tracking datastore](https://github.com/google/site-kit-wp/blob/develop/assets/js/googlesitekit/datastore/site/conversion-tracking.js) can be taken.
  - Initial state of the should settings should be undefined. `{ firstPartyModeSettings: undefined }`
  - Create an action `setFirstPartyModeEnabled` which should return an object with type `SET_FIRST_PARTY_MODE_ENABLED`, this will be identified by the reducer to update the state.
  - In the reducer function, for `SET_FIRST_PARTY_MODE_ENABLED` action type, update `firstPartyModeSettings.isEnabled` to true.
  - Add a resolver `getFirstPartyModeSettings` for retrieving settings. This should call `fetchGetFirstPartyModeSettings.actions.fetchGetFirstPartyModeSettings` to fetch settings.
  - Add following selectors to the store which will return the respective settings.
    - `getFirstPartyModeSettings` - Should return the setting `firstPartyModeSettings`. Note that resolver will be called for the first time.
    - `isFirstPartyModeEnabled` - Should return `firstPartyModeSettings.isEnabled`. This would be a boolean. It should return `undefined` if `firstPartyModeSettings` is not loaded.
    - `isFPMHealthy` - Should return `firstPartyModeSettings.isFPMHealthy`. This would be a boolean, or `undefined` as above.
    - `isScriptAccessEnabled` - Should return `firstPartyModeSettings.isScriptAccessEnabled`. This would be a boolean, or `undefined` as above.
- [x] In `assets/js/googlesitekit/datastore/site/index.js`
  - Import the first party mode datastore and add it to the `combineStores` call, so that it gets registered.

### Test Coverage

- Add the tests for the datastore. Refer conversion tracking datastore tests for reference.

## QA Brief

- Site up Site Kit with the `firstPartyMode` feature flag enabled.
- Exercise the selectors and actions listed in the AC via the JS console. An additional action, `saveFirstPartyModeSettings()`, was added during implementation that should also be tested. E.g.:

```js
// Retrieve the initial settings.
// Note that the first time it's run it will return `undefined`; run it a second time to see the loaded value.
googlesitekit.data.select( "core/site" ).getFirstPartyModeSettings();

// Get the current value of `isEnabled`:
googlesitekit.data.select( "core/site" ).isFirstPartyModeEnabled();

// Set `isEnabled` locally:
googlesitekit.data.dispatch( "core/site" ).setFirstPartyModeEnabled( true );

// Persist the settings. Reload the page and run the above selectors again to see the persisted value.
await googlesitekit.data.dispatch( "core/site" ).saveFirstPartyModeSettings();

// Test the `isFPMHealthy()` and `isScriptAccessEnabled()` selectors. These have no setter equivalents.
googlesitekit.data.select( "core/site" ).isFPMHealthy();
googlesitekit.data.select( "core/site" ).isScriptAccessEnabled();

// Test the `fetchSaveFirstPartyModeSettings()` action.
await googlesitekit.data.dispatch( "core/site" ).fetchSaveFirstPartyModeSettings({
  // At present the underlying REST endpoint only supports setting the `isEnabled` property:
  isEnabled: false,
});

// Verify the settings were persisted.
await googlesitekit.data.dispatch( "core/site" ).fetchGetFirstPartyModeSettings();
```

## Changelog entry

* Add a partial datastore for First-Party Mode in the `core/site` datastore to manage its settings.

**Comment by techanvil** [comment]
Hey @hussain-t, I'd leave effectively the same comment here as my [review of 9625](https://github.com/google/site-kit-wp/issues/9625#issuecomment-2462850044), this looks fine unless we decide to change the setting names in which case we'd want to update the selectors too.

**Comment by hussain-t** [comment]
Thanks, @techanvil. I've updated the selector names 👍

**Comment by techanvil** [comment]
Thanks @hussain-t! The AC LGTM.

AC ✅

**Comment by techanvil** [comment]
Thanks @ankitrox this IB is generally LGTM. A few minor points:

- It's quite standard datastore work that doesn't seem like it should need an up-front PR for the IB. However if you found you needed to flesh it out to understand the implementation that's OK, but I'd hope it can be avoided for this sort of thing as time goes on.
- I've tweaked the IB in a few places to fix a bit of grammar and also specify that the selectors should return `undefined` where the underlying state is not loaded. Please see my edit for details.
- I've added #9625 as a dependency, this will be needed to fully test the issue.

IB ✅

**Comment by hussain-t** [comment]
Thanks, @techanvil. I didn’t set #9625 as a dependency because it’s not technically blocking datastore work, allowing for parallel progress. It’s only a blocker when it comes to testing.

**Comment by hussain-t** [comment]
Thanks, @techanvil, I agree! I suggest bumping the estimate up to 15, considering the unit test, and avoiding overages during the execution.

**Comment by techanvil** [comment]
Thanks @hussain-t, sounds fair. I've bumped the estimate accordingly.

**Comment by techanvil** [comment]
Hi @kelvinballoo, thanks for flagging that. It is indeed expected - if the request to save the settings returned an error, the `error` property would be populated. Having it set to `undefined` just indicates there was no error.
