### ISSUE TITLE
Implement `fetchGetFPMServerRequirementStatus` Action

### ISSUE THREAD

**Issue by hussain-t** [google/site-kit-wp#9634]
## Feature Description

Develop the `fetchGetFPMServerRequirementStatus` action in the First-party mode datastore. This action should call the `fpm-server-requirement-status` API endpoint to verify the server requirements for First-party mode. Based on the server’s response, it will retrieve the updated First-party mode settings and update the relevant properties in the datastore to reflect the current server configuration.

See the [design doc for more details](https://docs.google.com/document/d/1PHptJ1Js_1OZrk5kRwoB3zPB2KQrXLJV7-3izi-bB30/edit?tab=t.0#heading=h.b7hfno5zm39f).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A `fetchGetFPMServerRequirementStatus` action should be added to the First-party mode datastore.
* This action should:
    * Send a `GET` request to the `fpm-server-requirement-status` endpoint.
    * Upon a successful response, update the First-party mode settings properties in the datastore based on the API response.

## Implementation Brief

- [ ] In the `first-party-mode` store created via https://github.com/google/site-kit-wp/issues/9628:
  - Use `createFetchStore()` to create a store called `fetchFPMServerRequirementStatus` with basename `getFPMServerRequirementStatus`.
    - Call `API.get()` in the control callback to request the `core/site/data/fpm-server-requirement-status` endpoint added via https://github.com/google/site-kit-wp/issues/9632. The `useCache` option should be `false` for the request.
    -  Update `state.settings` and `state.savedSettings` in the fetch store's reducer with the `isFPMHealthy` and `isScriptAccessEnabled` properties returned by the endpoint.
  - Add `fetchFPMServerRequirementStatus` to the call to `combineStores()` at the end of the file.

### Test Coverage

* Add JS test coverage for the above changes.

## QA Brief

* Set up Site Kit with the `firstPartyMode` feature flag enabled.
* Execute the following snippet in the browser console to make a request to the `fpm-server-requirement-status` endpoint using the `fetchGetFPMServerRequirementStatus` action:
```js
await googlesitekit.data.dispatch( "core/site" ).fetchGetFPMServerRequirementStatus();
```
* Verify that the `fetchGetFPMServerRequirementStatus` action sends a `GET` request to the `fpm-server-requirement-status` endpoint.
* Verify that the First-party mode settings in the datastore are updated based on the response from the server by running the following snippet in the browser console:
```js
googlesitekit.data.select( "core/site" ).getFirstPartyModeSettings()
```
* Verify the `googlesitekit_first_party_mode` option is set in the DB with the properties defined as above.
* Unhappy paths are covered in #9632.
## Changelog entry

* Implement the `fetchGetFPMServerRequirementStatus()` Redux action used to retrieve the FPM server requirement status.

**Comment by hussain-t** [comment]
Thanks, @techanvil. Updated 👍

**Comment by techanvil** [comment]
Thanks @hussain-t! The AC LGTM.

AC ✅

**Comment by nfmohit** [comment]
IB ✅

**Comment by kelvinballoo** [comment]
### QA Update ✅ 

- The snippet to make a request to the fpm-server-requirement-status endpoint using the fetchGetFPMServerRequirementStatus action was successful.
   <Details>

   ![Image](https://github.com/user-attachments/assets/e2d3f4d5-bde9-4e5b-b433-33e36026a710)

   </Details>

- The fetchGetFPMServerRequirementStatus action sends a GET request to the fpm-server-requirement-status endpoint as expected.
   <Details>

   ![Image](https://github.com/user-attachments/assets/531a847f-89ef-42b4-91b3-def889faab04)

   </Details>

- The First-party mode settings in the datastore are updated based on the response from the server 
   <Details> 
   
   ![Image](https://github.com/user-attachments/assets/7c177955-0e5a-4aca-8b9a-e55d562ed80a)

   </Details>

- The googlesitekit_first_party_mode option is set in the DB with the correct values (true)
   <Details>

   ![Image](https://github.com/user-attachments/assets/194cb074-dc42-4d40-8385-f1861113a140)

   </Details>
