### ISSUE TITLE
Update "One-tap" toggle to include new copy and "Learn more" link

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#9643]
## Feature Description

The "Enable One-tap" button should be expanded with copy and a "Learn more" link that points to https://developers.google.com/identity/gsi/web/guides/offerings#one_tap

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Text should be added under the "Enable One-tap" toggle in Sign in with Google: "One Tap allows users to sign in or sign up with one click offering smooth user entry points without redirecting to a dedicated sign in and sign up page. Learn more"
* The "Learn more" link should point to https://developers.google.com/identity/gsi/web/guides/offerings#one_tap
* The format of the text + "Learn more" link should follow this example: https://www.figma.com/design/h9yGR15Pg2DUtgERW4AFAv/Sign-in-with-Google?node-id=27-1045&t=O7yiMZwvAt5ZuVIk-1

## Implementation Brief

* [ ] In `assets/js/modules/sign-in-with-google/components/common/OneTapToggle.js`
  * Bellow the `Switch` component, include `<HelperText>` component, with `persistent` prop included
    *  Use `createInterpolateElement` to add text and learn more link from the AC. `Link` component should have `external` prop included
    * The new content should match Figma design referenced in the AC
  * If additional spacing tweaks are needed, you can apply additional class on `.googlesitekit-settings-module__fields-group` wrapper and target the `p` child in `assets/sass/components/sign-in-with-google/_googlesitekit-sign-in-with-google-settings-module.scss`

### Test Coverage

* VRTs may need updating; no other tests required.

## QA Brief

* Setup Site Kit with `signInWithGoogleModule` feature flag enabled
* Setup Sign in with Google module, and go to connected modules and edit Sign in with Google settings
* Verify that learn more link and helper text are added and match Figma design referenced in AC

## Changelog entry

* Add info to the "One-tap" option in Sign in with Google settings.

**Comment by eugene-manuilov** [comment]
@tofumatt let's point exactly where those changes should be made and what we need to use to add that learn more link.

**Comment by eugene-manuilov** [comment]
IB ✔

**Comment by wpdarren** [comment]
### QA Update: ✅ 

- Text under the "Enable One-tap" toggle in Sign in with Google reads: `One Tap allows users to sign in or sign up with one click offering smooth user entry points without redirecting to a dedicated sign in and sign up page. Learn more`
- The `Learn more` link points to `https://developers.google.com/identity/gsi/web/guides/offerings#one_tap`
- The format of the text + Learn more link follows [the Figma](https://www.figma.com/design/h9yGR15Pg2DUtgERW4AFAv/Sign-in-with-Google?node-id=27-1045&t=O7yiMZwvAt5ZuVIk-1) example.

![Image](https://github.com/user-attachments/assets/640b0416-408e-480f-89b9-fbd5f5cd6f1b)
