### ISSUE TITLE
How to enable Features rrmModule signInWithGoogleModule?

### ISSUE THREAD

**Issue by ycycxz** [google/site-kit-wp#9646]
![](https://raw.githubusercontent.com/ycycxz/pic/refs/heads/main/Screenshot_20241111_085059_Chrome.png)

How to enable Features rrmModule signInWithGoogleModule?

**Comment by adamdunnage** [comment]
@ycycxz I can see that you have opened a support topic regarding this so we will get back to you about this in the support forum and I will close this issue as we don't provide support via GitHub, thanks!
