### ISSUE TITLE
Implement First-Party Mode Toggle Component with Error Handling and Synchronization Across Modules

### ISSUE THREAD

**Issue by hussain-t** [google/site-kit-wp#9649]
## Feature Description

Develop the `<FirstPartyModeToggle />` component to provide a toggle switch that enables or disables the First-party mode. This component should interact with the datastore to manage the First-party mode state, including automatic disabling when server restrictions are detected. Display an error notice if server configuration prevents enabling First-party mode. The toggle will be placed within Ads and GA4 settings, with synchronized state control across both modules.

For more details, refer to the [Design Doc](https://docs.google.com/document/d/1PHptJ1Js_1OZrk5kRwoB3zPB2KQrXLJV7-3izi-bB30/edit?tab=t.0#heading=h.ihyr1dbxg95e) and the [Figma design](https://www.figma.com/design/udlPW35VZ0EDnSbRxYOGMj/First-party-mode?node-id=27-2097&m=dev).

**FPM Toggle on**:

![Image](https://github.com/user-attachments/assets/6c479246-b95a-441e-a922-9520a098a3b6)

**FPM Toggle off**:

![Image](https://github.com/user-attachments/assets/177af619-b36f-4e1d-94d7-0c74e1cbd52a)

**Error Notice**:

![Image](https://github.com/user-attachments/assets/a8c04acf-3904-4ee9-bd62-9917b53c0a25)

**Note:** The "Beta" badge and the toggle placement in the Ads and GA4 settings will be implemented in separate issues.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Component Functionality:
    * Develop a First-Party Mode Toggle component to allow users to enable or disable First-party mode.
	* The toggle should interact with the datastore to manage the First-party mode state.
* Display and Behavior:
    * The toggle should validate server requirements for enabling First-party mode on every mount:
        * The check should determine whether both the FPFE health check and script access are enabled.
        * If either the FPFE (First-Party Front-End) health check or script access check fails:
            * The toggle should be disabled (grayed out) to prevent users from enabling First-party mode.
            * Display an error notice with the following message:
            >"Your server’s current settings prevent first-party mode from working. To enable it, please contact your hosting provider and request access to external resources and plugin files. Learn more"
* UI Enhancements:
	* Styling and content should align with the specifications outlined in the [Figma design](https://www.figma.com/design/udlPW35VZ0EDnSbRxYOGMj/First-party-mode?node-id=27-2097&m=dev).

---
 
Note that the following aspects of the design don't need to be covered here, and will be implemented in subsequent issues:
* A "Beta" badge should appear next to the toggle label (implemented in #9650).
* The "Learn more" links for the description and the error notice will be implemented in #9699.
* The First-party mode setup banner should be dismissed when the toggle is enabled (implemented in #9698).
* Saving the First-party mode settings will be implemented in #9654 and #9655.

## Implementation Brief

- [ ] Create a component `FirstPartyModeToggle` in `assets/js/components/first-party-mode`.
  - Use the `isFirstPartyModeEnabled` selector to check if the FPM feature is already enabled. Save this in a constant, example `firstPartyModeEnabled`.
  - The component should return a `Fragment` wrapped around `Switch` component, `<p>` element which will contain the description for the toggle and the `SettingsNotice` component to conditionally display the warning. 
    - Take the reference of `EnhancedMeasurementSwitch` component in `assets/js/modules/analytics-4/components/common` or `ConsentModeSwitch` component in `assets/js/components/`.
  - Use the `useMount` hook (from `react-use`) to fetch the current status of server requirements. This effect needs to be run on every mount.
    - Use `fetchGetFPMServerRequirementStatus` action from `core/site`. It will update the state in the datastore.
    - Use `isFetchingGetFPMServerRequirementStatus` selector to check if the server requirement check is still in progress.
    - Render the `<ProgressBar>` component if the server requirement check is in progress. For example, see the [EnhancedMeasurementSwitch](https://github.com/google/site-kit-wp/blob/3e28b1c35733c5a719c943ea090719e6d29447d3/assets/js/modules/analytics-4/components/common/EnhancedMeasurementSwitch.js#L104-L109) component.
  - Use `isFPMHealthy` and `isScriptAccessEnabled` selectors and store their values in a variable.
  - Create a constant `metServerRequirements`. It should be `true` if neither `isFPMHealthy` nor `isScriptAccessEnabled` is `false`. If either value is explicitly `false`, the constant should be `false`.
  - Following props needs to be passed to `Switch` component.
    - `label` would be `First-party mode`.
    - `checked` should be the result of the expression `firstPartyModeEnabled && metServerRequirements`. 
    - `disabled` should be true if `metServerRequirements` is falsy.
    - `onClick` prop should be a function which calls `setFirstPartyModeEnabled` action and toggles the value of `firstPartyModeEnabled` in the state. Note that the value won't be saved in settings, it will only be changed in datastore. The save settings will be performed in #9654 and #9655
    - `hideLabel` should be false.
  - Add the decription of the component in following `p` element as can be seen [here](https://github.com/google/site-kit-wp/blob/8913261d60a8593fe7bff01fac23086f7b5c6e71/assets/js/modules/analytics-4/components/common/EnhancedMeasurementSwitch.js#L127-L142) for `EnhancedMeasurementSwitch` component. Note that `Learn more` link will be implemented separately in #9699
  - A warning notice following the description must be shown as per the [figma design](https://www.figma.com/design/udlPW35VZ0EDnSbRxYOGMj/First-party-mode?node-id=97-2033&node-type=instance&m=dev) only when `metServerRequirements` is falsy.
    - Use `SettingsNotice` component to display the warning.
      - Pass `notice` prop as the text given in figma design.
      - The icon needs to be styles as per the figma.
- [ ] Styles for the component should be added in `assets/sass/components/first-party-mode/_googlesitekit-first-party-mode.scss`.

### Test Coverage

* Add JS tests for the `FirstPartyModeToggle` component.
* Add Storybook stories for the `FirstPartyModeToggle` component.

## QA Brief

* Verify the _Components -> First Party Mode -> FirstPartyModeToggle_ stories in Storybook.

## Changelog entry

* Implement the First-party mode toggle as a component which is presented in Storybook.

**Comment by techanvil** [comment]
Hi @hussain-t, the AC here are looking good. A couple of minor points:

>    * The toggle should be synchronized across both modules, ensuring consistent state control. For example, enabling First-party mode in Ads should automatically enable it in Analytics and vice versa.

This is OK, but it does overcomplicate things a bit. The component is module-agnostic, it simply toggles a site-wide value and there's no module specific work involved in this issue. So, specifying the sync across modules could suggest a bit more work than there actually is. I think it's ultimately fine as whoever is drafting the IB should get the intention, but I figured it's worth a mention.

>    * An effect hook should validate server requirements for enabling First-party mode:

This is getting a bit too into the implementation details, there's no need to specify using an effect hook in the AC here.

**Comment by techanvil** [comment]
Thanks @hussain-t, that's great. Please note, I made a tweak to the AC to make the related dependencies aspect clearer and more distinct from the requirements.

AC ✅

**Comment by hussain-t** [comment]
Thanks, @techanvil 👍

**Comment by hussain-t** [comment]
Hi @ankitrox, we want to validate the server requirements on every mount of the component, regardless of whether First-party mode is enabled or disabled. I’ve made a slight update to the AC and included the following adjustment in the design doc:

>The `fetchGetFPMServerRequirementStatus` action should be called on every mount to validate server requirements.

Could you please update the IB accordingly?

**Comment by ankitrox** [comment]
Thank you @hussain-t for reviewing the IB and providing the feedback.

I think using the `useMount` hook would be suitable in this case as we want to check the requirement when the component mounts. 

Please let me know if this looks fine.

**Comment by hussain-t** [comment]
Thanks for drafting the IB, @ankitrox. The overall structure looks good. However, I’ve updated a few points for clarity and alignment with requirements:

>Use `isFetchingGetFPMServerRequirementStatus` selector to check if the server requirement check is still in progress, do not render the component till it is finished.

Instead of not rendering the component, we should display a `ProgressBar` while the request is in progress. You can refer to the [EnhancedMeasurementSwitch](https://github.com/google/site-kit-wp/blob/3e28b1c35733c5a719c943ea090719e6d29447d3/assets/js/modules/analytics-4/components/common/EnhancedMeasurementSwitch.js#L104-L109) component for an example.

>Create a constant `metServerRequirements`, it should be `true` if `isFPMHealthy` and `isScriptAccessEnabled` both are truthy, else `false`.

We should explicitly check that both `isFPMHealthy` and `isScriptAccessEnabled` are not `false` (`isFPMHealthy !== false && isScriptAccessEnabled !== false`), as the initial values for these properties will be `null`. This ensures that the toggle isn’t prematurely disabled during the initial state.

We should specify where the styles for the component should be added.

We should also add storybook stories for the toggle component.

I’ve updated the IB to incorporate these changes and avoid further iterations. I’ve also bumped up the estimate to 15 to reflect the additional effort.

---

IB ✅

**Comment by wpdarren** [comment]
### QA Update: ✅ 

- The `Components -> First Party Mode -> FirstPartyModeToggle` stories in Storybook match figma designs.  For the loading animation, I set up a test site now that the FPM settings are engineered and could verify the animation.   

I will do some additional testing around this functionality when working on #9654 and #9655.
