### ISSUE TITLE
Adsense error for AMP non-post pages such as Home Page, Category and Tags

### ISSUE THREAD

**Issue by yogeshbeniwal** [google/site-kit-wp#965]
## Bug Description

While using Site kit, its working for Non-AMP pages, however for AMP pages such as Home Page, Category and Tags its giving below error:

**The extension 'amp-auto-ads' was found on this page, but is unused. Please remove this extension.**

## Steps to reproduce

1. Go to AMP page for Home Page or Category or Tag
2. Use AMP Validator plugin for chrome to validate AMP page
3. Click on AMP Validator plugin to view error

## Screenshots

![Screenshot](https://user-images.githubusercontent.com/7325107/70595624-c5b82e00-1c1e-11ea-9c71-f67718608deb.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
@yogeshbeniwal Thanks for reporting. We have moved general Site Kit support over to the [WordPress support forum](https://wordpress.org/support/plugin/google-site-kit/).  You can submit any support topics over there. 

For your issue specifically it may be down to the theme you are using, please mention the theme and we can investigate further. There are different methods Site Kit uses to place the auto ads body code, you can find out more [here](https://github.com/google/site-kit-wp/blob/3db5ce48f9304067bbe897475c028c7daf7c09ba/includes/Modules/AdSense.php#L223).
