### ISSUE TITLE
Add "Beta" Badge to First-Party Mode Toggle

### ISSUE THREAD

**Issue by hussain-t** [google/site-kit-wp#9650]
## Feature Description

Add a "Beta" badge next to the First-party mode toggle label to indicate the feature is in beta.

For details, refer to the [Design Doc](https://docs.google.com/document/d/1PHptJ1Js_1OZrk5kRwoB3zPB2KQrXLJV7-3izi-bB30/edit?tab=t.0#heading=h.ihyr1dbxg95e) and the [Figma design](https://www.figma.com/design/udlPW35VZ0EDnSbRxYOGMj/First-party-mode?node-id=27-2097&m=dev).

![Image](https://github.com/user-attachments/assets/46be0a01-a5cf-46a1-b2ac-60c0b4f9f3b9)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A "Beta" badge should be displayed next to the First-party mode toggle label to indicate that the feature is in beta.
* The badge should be styled according to the specifications in the [Figma design](https://www.figma.com/design/udlPW35VZ0EDnSbRxYOGMj/First-party-mode?node-id=27-2097&m=dev).
* The badge should be non-interactive and serve as a visual indicator of the feature's beta status.

## Implementation Brief

- [ ] In `FirstPartyModeToggle` component in `assets/js/components/first-party-mode/`
  - Import the `Badge` component from `/assets/js/components`.
  - Add the `Badge` component beside `Switch` component with `label` prop passed as `Beta` and className as `googlesitekit-beta-badge`.
  - Make sure to conform to the style as per the Figma design. Any styling rules should be added in `assets/sass/components/first-party-mode/_googlesitekit-first-party-mode.scss`

### Test Coverage

* Update tests for `FirstPartyModeToggle` component.

## QA Brief

* Open the _Components -> First Party Mode -> FirstPartyModeToggle_ stories in Storybook and verify that the "_Beta_" badge appears as expected in the ACs.

## Changelog entry

* Add a "Beta" badge to the First-party mode toggle.

**Comment by techanvil** [comment]
AC ✅

**Comment by techanvil** [comment]
Hi @ankitrox, thanks for drafting this IB. However, I think it should take a slightly different approach.

We don't tend to interpolate badges into a string like that and in fact there's an [existing component](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/adsense-module--use-snippet-switch-toggled-on-default) with a badge next to a switch and it simply renders it after the switch:

https://github.com/google/site-kit-wp/blob/3fe82ad5b47e2c2a1a0796258f6bba9736cb1250/assets/js/modules/adsense/components/common/UseSnippetSwitch.js#L82-L92

I'd suggest we take the same approach here.

**Comment by ankitrox** [comment]
Thank you @techanvil .

I updated the IB to simply add the `Badge` beside `Switch` component in `FirstPartyModeToggle` component.

**Comment by techanvil** [comment]
Thanks @ankitrox!

IB ✅

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

We're unable to test this on a site right now so as per the QAB, I checked Storybook. 

- A "Beta" badge is displayed next to the First-party mode toggle label to indicate that the feature is in beta.
- The badge is styled according to the specifications in the [Figma design](https://www.figma.com/design/udlPW35VZ0EDnSbRxYOGMj/First-party-mode?node-id=27-2097&m=dev).
- The badge is non-interactive and serve as a visual indicator of the feature's beta status.

I compared the beta badge for SiWG and checked that the font size, style and dimensions were the same. 

![Image](https://github.com/user-attachments/assets/ee422910-ea6f-4e18-a4ec-2ddf2add7a80)
