### ISSUE TITLE
Integrate First-Party Mode Toggle into Analytics Settings Form

### ISSUE THREAD

**Issue by hussain-t** [google/site-kit-wp#9654]
## Feature Description

Add the `<FirstPartyModeToggle />` component to the Analytics settings forms, enabling existing users to opt into First-party mode. The toggle will default to "off" and can be enabled if desired.

If either the FPFE health check or script access check fails, the toggle will be disabled and grayed out, displaying an error message instructing users that additional server configuration is needed to enable First-Party Mode.

For details, refer to the [Design Doc](https://docs.google.com/document/d/1PHptJ1Js_1OZrk5kRwoB3zPB2KQrXLJV7-3izi-bB30/edit?tab=t.0#heading=h.9rs77pvi571d).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The First-Party Mode Toggle component should be integrated into the Analytics module’s settings form.
* The toggle should allow users to enable or disable First-party mode.
* The toggle should default to “off” for existing users.
* If either the FPFE health check or script access check fails, the toggle should be disabled (implemented in #9649).
* Changes made to the toggle state (on/off) should save the First-party mode settings in the datastore and persist them on the server.
* If the toggle is enabled via the settings form, the First-party mode setup banner should be dismissed (implemented in #9698).
* The component’s styling and placement should align with the specifications in the [Figma design](https://www.figma.com/design/udlPW35VZ0EDnSbRxYOGMj/First-party-mode?node-id=97-1818&m=dev).
* UI/UX for grouping the measurement toggles will be implemented in #9651.

## Implementation Brief

* [x] Update `assets/js/modules/analytics-4/components/settings/SettingsForm.js`, import and render the new `FirstPartyModeToggle` if the `firstPartyMode` feature flag is enabled.
* [x] Update `assets/js/modules/analytics-4/datastore/settings.js`:
   * Within the `saveSettings` function, check if the first party mode settings has changed using the `haveFirstPartyModeSettingsChanged ` selector, if so dispatch `saveFirstPartyModeSettings`, returning an error if there is one, similar to how the conversion tracking setting is saved:
  https://github.com/google/site-kit-wp/blob/44e0928b0a835d95e89bbe6225132aca5a4cd1d0/assets/js/modules/analytics-4/datastore/settings.js#L182-L192
   * Within the `rollbackChanges` function, within the `haveSettingsChanged` check block, dispatch the action `resetFirstPartyModeSettings`.
   https://github.com/google/site-kit-wp/blob/44e0928b0a835d95e89bbe6225132aca5a4cd1d0/assets/js/modules/analytics-4/datastore/settings.js#L242

### Test Coverage

* Add new tests in `assets/js/modules/analytics-4/datastore/settings.test.js` to confirm the first-party mode setting is saved and rolled back.

## QA Brief

1.	Activate Site Kit with the `firstPartyMode` feature flag enabled and ensure that the Analytics module is active and connected.
2.	Navigate to `Site Kit > Settings > Analytics` and click the Edit link. Verify that the First-party mode toggle is displayed.
3.	Change the toggle state:
    * Confirm that the submit button text changes from `Save` to `Confirm changes`.
4.	Save the changes:
    * Verify that the new toggle state is persisted after saving.
    * Refresh the settings page to ensure the toggle retains its updated state.
5.	Cancel changes:
    * Change the toggle state and click Cancel.
    * Verify that the toggle reverts to its previous state when reopening the settings edit screen by clicking the Edit link.

**Note:** If your test site fails either of the health checks, you can force local settings to test the toggle functionality using the following action in the console:
```js
googlesitekit.data.dispatch( 'core/site' )
    .receiveGetFirstPartyModeSettings( {
        isEnabled: true,
        isFPMHealthy: true,
        isScriptAccessEnabled: true,
    } );
```

## Changelog entry

* Integrate the First-party mode toggle into the Analytics module’s settings form, allowing users to enable or disable First-party mode.

**Comment by techanvil** [comment]
Hey @hussain-t, this comment applies to these AC too: https://github.com/google/site-kit-wp/issues/9655#issuecomment-2488251549

**Comment by hussain-t** [comment]
Thanks, @techanvil. I've removed specifying the component name, back to you.

**Comment by techanvil** [comment]
Thanks @hussain-t!

AC ✅

**Comment by benbowler** [comment]
@hussain-t I've picked this up for IB as I'm back in squad M next week. Working through this however, I found an issue with rolling back the settings if the user cancels changes in the settings form. Because FPM uses a fetch store instead of a settings store, it doesn't implement rollback and we don't know if the user changed the setting or not.

What do you think about switching the FPM store for the isEnabled setting to be a settings store rather than a fetch store? Do you see issues with this?

https://github.com/google/site-kit-wp/blob/63ca619c73ec538a9b1694e756db9c5f4c9a8ccc/assets/js/googlesitekit/datastore/site/first-party-mode.js#L46-L53

**Comment by hussain-t** [comment]
Hi @benbowler, the reset and rollback changes are being implemented in [#9688](https://github.com/google/site-kit-wp/issues/9688). Let me know if that helps. Thanks!

**Comment by techanvil** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The First-Party Mode Toggle component is integrated into the Analytics module’s settings form.
  - The toggle allows users to enable or disable First-party mode.
  - The toggle is default to `off` for existing users.
  - If either the FPFE health check or script access check fails, the toggle is disabled and a notification appears. 
  - Changes made to the toggle state (on/off) are saved on the First-party mode settings in the datastore and persist them on the server.
  - If the toggle is enabled via the settings form, the First-party mode setup banner is dismissed.
- The component’s styling and placement align with the specifications in the [Figma design](https://www.figma.com/design/udlPW35VZ0EDnSbRxYOGMj/First-party-mode?node-id=97-1818&m=dev).

<details>
 <summary>Screenshots</summary>

![Image](https://github.com/user-attachments/assets/1cfba19c-30ae-452c-80ad-f9ce8e4efa07)
![Image](https://github.com/user-attachments/assets/f7ec9b12-89b4-455a-8e1b-b776c054d6a6)
![Image](https://github.com/user-attachments/assets/34986438-e4d8-4c87-8cc2-0946b51325f9)
![Image](https://github.com/user-attachments/assets/6f8156e6-141b-41e2-826c-f2dd9ec5efb8)

</details>
