### ISSUE TITLE
Integrate First-Party Mode Toggle into Ads Settings Form

### ISSUE THREAD

**Issue by hussain-t** [google/site-kit-wp#9655]
## Feature Description

Add the `<FirstPartyModeToggle />` component to the Ads settings forms, enabling existing users to opt into First-party mode. The toggle will default to "off" and can be enabled if desired.

If either the FPFE health check or script access check fails, the toggle will be disabled and grayed out, displaying an error message instructing users that additional server configuration is needed to enable First-Party Mode.

For details, refer to the [Design Doc](https://docs.google.com/document/d/1PHptJ1Js_1OZrk5kRwoB3zPB2KQrXLJV7-3izi-bB30/edit?tab=t.0#heading=h.9rs77pvi571d).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The First-Party Mode Toggle component should be integrated into the Ads module’s settings form.
* The toggle should allow users to enable or disable First-party mode.
* The toggle should default to “off” for existing users.
* If either the FPFE health check or script access check fails, the toggle should be disabled (implemented in #9649).
* Changes made to the toggle state (on/off) should save the First-party mode settings in the datastore and persist them on the server.
* If the toggle is enabled via the settings form, the First-party mode setup banner should be dismissed (implemented in #9698).
* The component’s styling and placement should align with the specifications in the [Figma design](https://www.figma.com/design/udlPW35VZ0EDnSbRxYOGMj/First-party-mode?node-id=110-1598&m=dev).
* UI/UX for grouping the measurement toggles will be implemented in #9651.

## Implementation Brief

* [x] Update `assets/js/modules/ads/components/settings/SettingsForm.js`, import and render the new `FirstPartyModeToggle` if the `firstPartyMode` feature flag is enabled.
* [x] Update `assets/js/modules/ads/datastore/settings.js`:
   * Within the `saveSettings` function, check if the first party mode settings has changed using the `haveFirstPartyModeSettingsChanged ` selector, if so dispatch `saveFirstPartyModeSettings`, returning an error if there is one, similar to how the conversion tracking setting is saved:
  https://github.com/google/site-kit-wp/blob/44e0928b0a835d95e89bbe6225132aca5a4cd1d0/assets/js/modules/ads/datastore/settings.js#L54-L64
   * Within the `rollbackChanges` function, within the `haveSettingsChanged` check block, dispatch the action `resetFirstPartyModeSettings`.
   https://github.com/google/site-kit-wp/blob/44e0928b0a835d95e89bbe6225132aca5a4cd1d0/assets/js/modules/ads/datastore/settings.js#L93

### Test Coverage

* Add new tests in `assets/js/modules/ads/datastore/settings.test.js` to confirm the first-party mode setting is saved and rolled back.

## QA Brief

1. Activate Site Kit with the `firstPartyMode` feature flag enabled and make sure that the Ads module is active and connected.

2. Go to `Site Kit > Settings > Ads` click Edit link, First-party mode toggle should be available.

3. Change the toggle state and the CTA should be changed from `Save` to `Confirm changes`.

4. Once changes saved, state of the toggle should persist.

5. Change the toggle state and click `Cancel`, it should get back to previous state again when we come back to settings edit screen by clicking `Edit` link.

*Note: if you test site fails either of the health checks you can dispatch the following action to force local settings to test this toggle:*
```
await googlesitekit.data.dispatch( 'core/site' )
					.receiveGetFirstPartyModeSettings( {
						isEnabled: false,
						isFPMHealthy: true,
						isScriptAccessEnabled: true,
					} );
```

## Changelog entry

* Integrate the First-party mode toggle into the Ads module’s settings form, allowing users to enable or disable First-party mode.

**Comment by techanvil** [comment]
Hi @hussain-t, these AC are looking good. A couple of minor points:

> * The `<FirstPartyModeToggle />` component should be integrated into the Ads module’s settings form.

The component name is an implementation detail, and we should aim to write AC from a user's perspective where we can. Tbh, it's a marginal point as it's the only implementation detail in the AC and it's clear enough what it means. I would have just approved it but as I'm sending it back due to the point below I figured I'd mention it.

> * If the toggle is enabled via the settings form, the First-party mode setup banner should be dismissed (implemented in #9698).

As per this comment, https://github.com/google/site-kit-wp/issues/9698#issuecomment-2488224404, we should be able to remove the above AC point.

**Comment by techanvil** [comment]
@hussain-t as per https://github.com/google/site-kit-wp/issues/9698#issuecomment-2488347783 my second point is invalid, please ignore it! Sorry for the mixup.

**Comment by hussain-t** [comment]
Thanks, @techanvil. I've removed specifying the component name, back to you.

**Comment by techanvil** [comment]
Thanks @hussain-t, that's great.

AC ✅

**Comment by techanvil** [comment]
IB ✅

**Comment by hussain-t** [comment]
@ankitrox, I just realized that we should add stories with the FPM toggle in `assets/js/modules/ads/components/settings/SettingsForm.stories.js`. I will send it back in execution. Could you create a follow-up PR and assign it back to me for review?

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The First-Party Mode Toggle component is integrated into the Ads module’s settings form.
  - The toggle allows users to enable or disable First-party mode.
  - The toggle is default to `off` for existing users.
  - If either the FPFE health check or script access check fails, the toggle is disabled and a notification appears. 
  - Changes made to the toggle state (on/off) are saved on the First-party mode settings in the datastore and persist them on the server.
  - If the toggle is enabled via the settings form, the First-party mode setup banner is dismissed.
- The component’s styling and placement align with the specifications in the [Figma design](https://www.figma.com/design/udlPW35VZ0EDnSbRxYOGMj/First-party-mode?node-id=97-1818&m=dev).

<details>
 <summary>Screenshots</summary>

![Image](https://github.com/user-attachments/assets/b59cc0c7-3c90-41d0-a9c0-710d03e9d3fc)
![Image](https://github.com/user-attachments/assets/c7322c84-f9e9-4109-bede-3600ce7469d5)
![Image](https://github.com/user-attachments/assets/6ef04b90-688c-464e-9372-8d7aef59317b)

</details>
