### ISSUE TITLE
Trigger a stub survey when the Audience Segmentation feature is set up.

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#9656]
## Feature Description

We need to trigger a survey when the Audience Segmentation feature is set up by the initial admin. This will be a stub survey for the time being that will help us track usage of the feature.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When the Audience Segmentation feature is successfully set up by the initial admin, a survey should be triggered.
* The survey trigger ID should be `audience_segmentation_setup_completed`.

## Implementation Brief

* [ ] At the [very end of the `*enableAudienceGroupMain()` action](https://github.com/google/site-kit-wp/blob/61e489787fc9b640c2482f4e43dee57108386c6c/assets/js/modules/analytics-4/datastore/audiences.js#L587), after the call to `saveSettings()` has completed successfully, dispatch the `triggerSurvey()` action passing the trigger ID according to the ACs.

### Test Coverage

* Add coverage for the above changes to the tests for the `*enableAudienceGroup()` action.

## QA Brief

- Site up Site Kit with Analytics connected using a property which is out of the gathering data state.
- Click on the **Enable groups** CTA to set up Audience Segmentation.
- Verify that the survey is triggered as per the AC.
- To verify that a survey has been triggered, using the Chrome devtools network inspector or an HTTP proxy like Proxyman, check that an HTTP `POST` request is made to `/wp-json/google-site-kit/v1/core/user/data/survey-trigger` with the body:

```
{
  "data": {
    "triggerID": "audience_segmentation_setup_completed"
  }
}
```

## Changelog entry

* Add a survey to be triggered when audience groups are set up.

**Comment by hussain-t** [comment]
Thanks, @techanvil!

IB ✅

**Comment by kelvinballoo** [comment]
### QA Update ✅ 

After enabling the groups, the survey is triggered as per the AC:
HTTP POST request is made to /wp-json/google-site-kit/v1/core/user/data/survey-trigger with the body:
```
{
  "data": {
    "triggerID": "audience_segmentation_setup_completed"
  }
}
```

Moving ticket to approval.

<Details>

![Image](https://github.com/user-attachments/assets/6af3f1e1-21b2-4018-bce0-35c9b3af3d62)

![Image](https://github.com/user-attachments/assets/3c3a25af-ab9e-4c91-9200-8283982031bd)

</Details>
