### ISSUE TITLE
Display First-Party Mode Status in Analytics Settings View

### ISSUE THREAD

**Issue by hussain-t** [google/site-kit-wp#9658]
## Feature Description

To provide users with clear visibility into the current status of First-party mode, display the enabled/disabled state within the Analytics Settings View.

For details, refer to the [design doc](https://docs.google.com/document/d/1PHptJ1Js_1OZrk5kRwoB3zPB2KQrXLJV7-3izi-bB30/edit?tab=t.0#heading=h.1e2vcvece322) and the [Figma design](https://www.figma.com/design/udlPW35VZ0EDnSbRxYOGMj/First-party-mode?node-id=31-1104&m=dev).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The current state of First-party mode ("Enabled" or "Disabled") should be displayed within the Analytics module’s Settings View.
* A label "First-party mode" should be displayed, along with the current state of First-party mode as "Enabled" or "Disabled", reflecting the saved settings.
* The status should align visually with other settings in the Analytics Settings View, ensuring a consistent user experience.
* The status should be read-only and not interactive.
* The status display should follow the layout shown in the [Figma design](https://www.figma.com/design/udlPW35VZ0EDnSbRxYOGMj/First-party-mode?node-id=31-1104&m=dev). However, the typography and spacing should be consistent with the existing settings page (the Figma design uses different font weights for the title vs value text and so forth when compared to the current implementation).

## Implementation Brief

- [ ] In `assets/js/modules/ads/components/settings/SettingsView.js`
  - Import the `SettingsStatuses` component from `assets/js/components/settings/`.
  - Remove `SettingsEnhancedMeasurementView` component as we will determine whether enhance measurement is enabled in the current component itself. Refer the logic for same inside `SettingsEnhancedMeasurementView` component.
  - Remove [this snippet](https://github.com/google/site-kit-wp/blob/4010667814209e8cad4c58859912e630c98847ee/assets/js/modules/analytics-4/components/settings/OptionalSettingsView.js#L85-L96) from `OptionalSettingsView` component. We will determine whether the enhanced conversion tracking is enabled in the `SettingsView` component itself.
  - For first party mode, use `isFirstPartyModeEnabled` selector from `core/site` store.
  - Pass the array of objects for the following items to `SettingsStatuses` component.
    - Enhanced Measurement
    - Enhanced Conversion Tracking
    - First-party mode

- [ ] Make sure the layout follows the Figma design as described in the AC.

### Test Coverage

* Update VRT for `assets/js/modules/analytics-4/components/settings/SettingsView.stories.js`

## QA Brief

 * View the settings view for the Analytics module:
    * With the `firstPartyMode` feature flag *disabled*, no additional settings should be visible, however they have been re-ordered.
    * With the `firstPartyMode` feature flag *enabled*, the new "First-party mode" enabled status should show and should show if the feature is enabled or not.
    * *Note: while there is not switch to enable FPM you can dispatch the following action in the developer console: `await googlesitekit.data.dispatch( 'core/site' ).setFirstPartyModeEnabled(true)`.*
 * The "Enhance Measurement" value should show a progress bar while the data is resolving form the backend.
 * The Ads settings view should not have any regressions from the ticket #9659.

## Changelog entry

* Display the First-party mode enabled status in the Analytics settings view.

**Comment by techanvil** [comment]
AC ✅

**Comment by techanvil** [comment]
Thanks @ankitrox, this IB is looking good. One small point:

> - [ ] Make sure the styling matches the figma design link for which is provided in AC.

As per my comment on 9659, https://github.com/google/site-kit-wp/issues/9659#issuecomment-2497770318, we don't want to exactly follow the Figma design and want to keep the changes consistent with the current implementation. I've tweaked the AC, and amended this IB point to save a round trip. CC @hussain-t.

IB ✅

**Comment by benbowler** [comment]
I'm actually going to use the `SettingsStatuses` component [added here](https://github.com/google/site-kit-wp/pull/9788/files#diff-3e2f0dc796717138c39335faaeee8fe6dce4dead543a8c2514613b577f013902).

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The current state of First-party mode (`Enabled` or `Disabled`) is displayed within the Analytics module’s Settings View.
  - A label `First-party mode` is displayed, along with the current state of First-party mode.
  - The status aligns visually with other settings in the Analytics settings, ensuring a consistent user experience.
  - The status is read-only and not interactive.
  - The status display follows the layout shown in the [Figma design](https://www.figma.com/design/udlPW35VZ0EDnSbRxYOGMj/First-party-mode?node-id=31-1104&m=dev). 
  - 
![Image](https://github.com/user-attachments/assets/06a1ba7c-e2a2-4204-a06a-7093ed3a6fff)
