### ISSUE TITLE
Display First-Party Mode Status in Ads Settings View

### ISSUE THREAD

**Issue by hussain-t** [google/site-kit-wp#9659]
## Feature Description

To provide users with clear visibility into the current status of First-party mode, display the enabled/disabled state within the Ads module Settings View.

For details, refer to the [design doc](https://docs.google.com/document/d/1PHptJ1Js_1OZrk5kRwoB3zPB2KQrXLJV7-3izi-bB30/edit?tab=t.0#heading=h.1e2vcvece322) and the [Figma design](https://www.figma.com/design/udlPW35VZ0EDnSbRxYOGMj/First-party-mode?node-id=110-1640&m=dev).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The current state of First-party mode ("Enabled" or "Disabled") should be displayed within the Ads module’s Settings View.
* A label "First-party mode" should be displayed, along with the current state of First-party mode as "Enabled" or "Disabled", reflecting the saved settings.
* The status should align visually with other settings in the Ads Settings View, ensuring a consistent user experience.
* The status should be read-only and not interactive.
* The status display should follow the layout shown in the [Figma design](https://www.figma.com/design/udlPW35VZ0EDnSbRxYOGMj/First-party-mode?node-id=110-1640&m=dev). However, the typography and spacing should be consistent with the existing settings page (the Figma design uses different font weights for the title vs value text and so forth when compared to the current implementation).

## Implementation Brief

- [x] Create a component `SettingsStatuses` in `assets/js/components/settings/`.
  - It should accept `statuses` prop which is an Array of objects. Each object will have the properties `label` and `status`.
  - If no `statuses` are supplied i.e. `statuses.length` is zero or undefined, return null from the component.
  - Map over the `statuses` and create a list of settings statuses to form `statusList`. Each list item would be wrapped in a `div` element, we should assign the class to div as `googlesitekit-settings-module__meta-item`.
    - Display the `label` with `h5` within the div element. Assign class name as `googlesitekit-settings-module__meta-item-type`.
    - Display the status in (Enabled/Disabled) in `p` tag. If `status` is true, `Enabled` must be displayed, else `Disabled`. If `status` is `undefined`, a blank space should be rendered with the help of `BLANK_SPACE` constant.
    - Assign unique key prop to each list item. Assign the class name to the `p` as `googlesitekit-settings-module__meta-item-data`.
  - Retun a parent div with class name such as `googlesitekit-settings-module__meta-items` wrapped around `statusList` created above.

- [x] In `assets/js/modules/ads/components/settings/SettingsView.js`
  - Import the `SettingsStatuses` component.
  - Pass the statuses for `Conversion Tracking Status` and `First-party mode` as mentioned above. Those should be array of objects.
  - For first party mode, use `isFirstPartyModeEnabled` selector from `core/site` store.

### Test Coverage

* Write JS tests for `SettingsStatuses` component.
* Update VRT for `assets/js/modules/ads/components/settings/SettingsView.stories.js`

## QA Brief

* Enable the `firstPartyMode` feature flag, then view the Ads Settings view component. You will see the new status "First-Party Mode" enabled status.
* Set the feature to active in the store by dispatching this action in the developer console: `await googlesitekit.data.dispatch( 'core/site' ).setFirstPartyModeEnabled(true)`, see the status change to "Enabled".

## Changelog entry

* Display the First-party mode enabled status in the Ads settings view.

**Comment by techanvil** [comment]
AC ✅

**Comment by techanvil** [comment]
Hi @ankitrox, thanks for drafting this IB. Creating a reusable component for the statuses sounds good. However, there's no need for any new classes and styling.

It wasn't made entirely clear in the AC, but we don't want to exactly follow the Figma design. We want to ensure the additions to the Settings screen are consistent with the current implementation and we can reuse the existing `googlesitekit-settings-module__meta.*` classes, taking the multi-value row in the Analytics section as an [example](https://github.com/google/site-kit-wp/blob/63ca619c73ec538a9b1694e756db9c5f4c9a8ccc/assets/js/modules/analytics-4/components/settings/SettingsView.js#L105-L155). I've updated the AC to be clearer on this point.

![Image](https://github.com/user-attachments/assets/3bc589df-0d9c-4931-b457-ab4b79cdc9f0)

**Comment by ankitrox** [comment]
Thanks for reviewing the IB @techanvil . I have updated the IB so that we use the existing class names and removed the point to create an additional css file.

**Comment by techanvil** [comment]
Thanks @ankitrox! One more minor point:

> `className` Class name for the main parent container which contains all the statuses.

As it doesn't look like we need any new styling, we shouldn't need this `className` prop. I think it can be removed from the IB.

**Comment by ankitrox** [comment]
Thanks @techanvil . You are right, we don't need `className` prop anymore.

**Comment by techanvil** [comment]
Thanks @ankitrox! I don't see we'll need `className` in the list of `statuses` either so I've removed that detail.

IB ✅

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The current state of First-party mode ("Enabled" or "Disabled") is displayed within the Ads module’s Settings View.
  - A label `First-party mode` is displayed, along with the current state of First-party mode as `Enabled` or `Disabled`
  - The status aligns visually with other settings in the Ads Settings View.
  - The status is read-only and not interactive.
  - The status display follows the layout shown in the [Figma design](https://www.figma.com/design/udlPW35VZ0EDnSbRxYOGMj/First-party-mode?node-id=110-1640&m=dev). 


<details>
 <summary>Screenshots</summary>

![Image](https://github.com/user-attachments/assets/fedc7e25-734e-445b-904f-678342c698f9)
![Image](https://github.com/user-attachments/assets/d83a62b0-59b7-4b36-b878-e44a2d815d37)

</details>
