### ISSUE TITLE
Conditionally render the GTag URL based on First-Party Mode setting

### ISSUE THREAD

**Issue by hussain-t** [google/site-kit-wp#9664]
## Feature Description

Update the Site Kit GTag URL to align with the First-party mode setting. When First-party mode is enabled, the URL should point to the first-party proxy script on the WordPress server; otherwise, it should use the standard Google Tag Manager URL.

For additional details, refer to the [Design Doc](https://docs.google.com/document/d/1PHptJ1Js_1OZrk5kRwoB3zPB2KQrXLJV7-3izi-bB30/edit?tab=t.0#heading=h.uwkb1hl9se9y).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The GTag URL used by Site Kit should be dynamically determined based on the First-party mode setting and the health check statuses.
* When First-party mode is enabled and health checks pass:
    * The URL should point to the proxy script hosted on the WordPress server (e.g., `{plugin route}/fpm/measurement.php`).
* When First-party mode is disabled or if health checks fail:
    * The URL should default to the standard Google Tag Manager URL (e.g., https://www.googletagmanager.com/gtag/js).
* The `gtag.js` script should load from the correct URL without causing any errors or warnings in the browser console.
* All events and data tracking should work as expected, regardless of whether the script is loaded through the proxy or directly from Google servers.

## Implementation Brief

- [ ] Update the [`Gtag::get_gtag_src()` method](https://github.com/google/site-kit-wp/blob/b24ac5f614983001b0859fd2264497fd5dd6cdb6/includes/Core/Tags/GTag.php#L198):
  - Retrieve the first-party mode settings, `isEnabled`, `isFPMHealthy` and `isScriptAccessEnabled`.
  - If all three of the above settings are `true`, return the URL to the `measurement.php` proxy script with the correct query params appended.
    - Use `plugins_url( 'fpm/measurement.php', GOOGLESITEKIT_PLUGIN_MAIN_FILE ) ` to retrieve the URL to the script.
    - Append the query params `id` and `s`.
      - `id` should be the tag ID, encoded via `rawurlencode` as it is now.
      - `s` should be the path `/gtag/js`.
  - Otherwise, continue to return the URL as it's currently defined:
  
 https://github.com/google/site-kit-wp/blob/b24ac5f614983001b0859fd2264497fd5dd6cdb6/includes/Core/Tags/GTag.php#L206

### Test Coverage

* Add coverage for the above changes to the tests for the `GTag` class.

## QA Brief

Please note that the current version of the `measurement.php` script does not work when deployed on a TasteWP site, so InstaWP or other sites should be used for testing. See this [Slack thread](https://fueled10up.slack.com/archives/C077DB69US2/p1732038247532169) for more info.

This should be addressed when we update the version of the script in https://github.com/google/site-kit-wp/issues/9710.

#### Verify current, non-FPM behaviour

- Set up Site Kit with the `firstPartyMode` feature flag enabled, and connect Analytics.
- You may wish to toggle the **Exclude Analytics** switches off in the Analytics settings for convenience.
- Navigate to a public page and verify that Analytics events are being tracked as usual:
  - The GTag script should be served from `https://www.googletagmanager.com`:
```html
<!-- Google Analytics snippet added by Site Kit -->
<script src="https://www.googletagmanager.com/gtag/js?id=GT-XXXXXXX" id="google_gtagjs-js" async></script>
<script id="google_gtagjs-js-after">
window.dataLayer = window.dataLayer || [];function gtag(){dataLayer.push(arguments);}
gtag("set","linker",{"domains":["sitekit.10uplabs.com"]});
gtag("js", new Date());
gtag("set", "developer_id.dZTNiMT", true);
gtag("config", "GT-XXXXXXX");
 window._googlesitekit = window._googlesitekit || {}; window._googlesitekit.throttledEvents = []; window._googlesitekit.gtagEvent = (name, data) => { var key = JSON.stringify( { name, data } ); if ( !! window._googlesitekit.throttledEvents[ key ] ) { return; } window._googlesitekit.throttledEvents[ key ] = true; setTimeout( () => { delete window._googlesitekit.throttledEvents[ key ]; }, 5 ); gtag( "event", name, { ...data, event_source: "site-kit" } ); }
</script>
```
  - Events should be tracked via requests to an `analytics.google.com` host:
  ![Image](https://github.com/user-attachments/assets/1de15057-bd6c-4519-ac42-435cd7d099a5)
  - Verify that events appear in the Analytics realtime report for the property.
    - Note that neither Tag Assistant or the GA debugger Chrome extension currently work for first-party mode, so it's best to use the realtime report for verifying that events are being tracked in order to do a like-for-like comparison when running through the FPM behaviour testing steps below.

### Verify FPM behaviour

- On the Site Kit dashboard, use the following snippet in the JS console to update the FPM health check flags:
```js
await googlesitekit.data.dispatch('core/site').fetchGetFPMServerRequirementStatus();
```
- Verify the `isFPMHealthy` and `isScriptAccessEnabled` properties are `true` in the returned `response`.
- Then use the following snippet in the JS console to enable first-party mode:
```js
await googlesitekit.data.dispatch('core/site').setFirstPartyModeEnabled(true);
await googlesitekit.data.dispatch('core/site').saveFirstPartyModeSettings();
```
- Back on a public page, verify that Analytics events are being tracked in first-party mode:
  - The GTag script should be served from the WordPress site via the `measurement.php` proxy script, for example:
```html
<!-- Google Analytics snippet added by Site Kit -->
<script src="http://sitekit.10uplabs.com/wp-content/plugins/google-site-kit/fpm/measurement.php?id=GT-XXXXXX&amp;s=/gtag/js" id="google_gtagjs-js" async></script>
<script id="google_gtagjs-js-after">
window.dataLayer = window.dataLayer || [];function gtag(){dataLayer.push(arguments);}
gtag("set","linker",{"domains":["sitekit.10uplabs.com"]});
gtag("js", new Date());
gtag("set", "developer_id.dZTNiMT", true);
gtag("config", "GT-XXXXXX");
 window._googlesitekit = window._googlesitekit || {}; window._googlesitekit.throttledEvents = []; window._googlesitekit.gtagEvent = (name, data) => { var key = JSON.stringify( { name, data } ); if ( !! window._googlesitekit.throttledEvents[ key ] ) { return; } window._googlesitekit.throttledEvents[ key ] = true; setTimeout( () => { delete window._googlesitekit.throttledEvents[ key ]; }, 5 ); gtag( "event", name, { ...data, event_source: "site-kit" } ); }
</script>
```
  - Events should be tracked via requests to the WordPress site:
![Image](https://github.com/user-attachments/assets/3706fdce-847d-4f17-bf66-50d8646fdaa4)
  - Again, verify that events appear in the Analytics realtime report for the property.

#### QA:Eng

- Refer to the QAB for https://github.com/google/site-kit-wp/issues/9632 for advice on modelling the unhappy path scenarios, resulting in `isFPMHealthy` or `isScriptAccessEnabled` being set to `false`.
- Verify that FPM is _not_ active in either of these cases, and events continue to be tracked via Google's servers.

## Changelog entry

* Add support for gtag to load in first-party mode when enabled.

**Comment by techanvil** [comment]
AC ✅

**Comment by nfmohit** [comment]
IB ✅

**Comment by techanvil** [comment]
Hi @wpdarren, thanks for flagging that. I should have mentioned it in the QAB, but it slipped my mind - the current version of the script doesn't work on TasteWP sites. This is something I raised in [Slack](https://fueled10up.slack.com/archives/C077DB69US2/p1732038247532169) and @aaemnnosttv said it may be fixed by a pending update.

I'm not sure if the version we've deployed is the one he's referring to. I've made a point on the QAB this is not expected to work on TasteWP sites for now, and added a requirement for it to be fixed in the AC for https://github.com/google/site-kit-wp/issues/9710.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- For non-FPM behaviour
  - The GTag script is served from https://www.googletagmanager.com
  - Events are tracked via requests to an analytics.google.com host
  - Events appear in the Analytics realtime report for the property.

- For FPM behaviour
  - The GTag script is served from WordPress
  - Events are tracked via requests to an WordPress URL host
  - Events appear in the Analytics realtime report for the property.

<details>
 <summary>Screenshots</summary>

![Image](https://github.com/user-attachments/assets/970c910f-22cd-420e-832c-1103baaff6ef)
![Image](https://github.com/user-attachments/assets/4576b3fd-6bf3-4279-b992-e2d702cc67ec)
![Image](https://github.com/user-attachments/assets/72acb10f-d595-4ad2-a79e-cb10fca8fae5)
![Image](https://github.com/user-attachments/assets/b0a07e54-d74e-437e-99fa-16a92bf99578)
![Image](https://github.com/user-attachments/assets/3c0af55f-ab15-41a9-9e0e-9d66886fe433)
![Image](https://github.com/user-attachments/assets/ba10da7e-64bb-49ca-aba6-82a34dd037b9)
![Image](https://github.com/user-attachments/assets/22562be4-1f29-46b5-8b3c-3bf1962d8723)

</details>

**Comment by ankitrox** [comment]
I have verified the QA:Eng checks here and unhappy path is working fine.

It sets `isFPMHealthy` and `isScriptAccessEnabled` flags to `false` and serves the gtag via googletagmanager.com domain.

Moving this ticket to approval.

CC: @wpdarren
