### ISSUE TITLE
Integrate First-Party Mode Proxy Script

### ISSUE THREAD

**Issue by hussain-t** [google/site-kit-wp#9665]
## Feature Description

Integrate the Google-provided proxy script library to support the First-party mode feature, enabling Google Analytics and Ads tags to be served directly from the WordPress server. The proxy script will be stored in a new top-level folder within the Site Kit plugin directory for easy access.

For details, refer to the [Design Doc](https://docs.google.com/document/d/1PHptJ1Js_1OZrk5kRwoB3zPB2KQrXLJV7-3izi-bB30/edit?tab=t.0#heading=h.3hjgolso8lt3).

Note that a stub of the script will already be created via https://github.com/google/site-kit-wp/issues/9632 which the Google-provided script can be merged with.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- The `measurement.php` script provided by Google should be merged with the stub of the script at `{plugin route}/fpm/measurement.php` implemented via https://github.com/google/site-kit-wp/issues/9632, such that the script continues to return `ok` if the `healthCheck` query parameter is provided, or otherwise behaves as usual.
  - Include a prominent notice stating that the file has been modified in accordance with its Apache licence.
  >      (b) You must cause any modified files to carry prominent notices
  >          stating that You changed the files
  - Note that we do plan to find an alternative solution in a future iteration which avoids needing to modify the file, however this is likely to come after the initial release.
- Contact @aaemnnosttv or @eugene-manuilov for access to the latest version of the script (see this [Slack](https://fueled10up.slack.com/archives/C077DB69US2/p1731602593260239) thread).
- The `measurement.php` script should correctly serve the GTag script and track Analytics events when requested with the relevant query parameters.

## Implementation Brief

- [x] Merge the current version of the `measurement.php` proxy script with the stub of the script at `{plugin route}/fpm/measurement.php`.
  - The script can be found here in [Slack](https://fueled10up.slack.com/archives/C077DB69US2/p1732037895974219?thread_ts=1732037696.772749&cid=C077DB69US2).
  - Note that we have a separate task #9710 to update to the latest version of the proxy script. Here, the focus is mainly on serving the correct gtag script and tracking Analytics events when requested with the relevant query parameters.

- [x] In the file header, we must add a notice.

  ```
      NOTICE: This file has been modified from its original version in accordance with the Apache License, Version 2.0.
  ```

### Test Coverage

No tests required for this because this is third-party script.

### QA:Eng

1. Visit the URL: https://testsiteurl.xyz/wp-content/plugins/google-site-kit/fpm/measurement.php?id=GT-1234&s=/gtag/js, replace `testsiteurl.xyz` with appropriate site domain. Ensure that the JS code gets loaded on the page.

2. Now, visit the URL https://testsiteurl.xyz/wp-content/plugins/google-site-kit/fpm/measurement.php?healthCheck, it should return the text `ok` on the page.

#### Testing whether events are being captured properly.

1. Update the `includes/Core/Tags/GTag.php` file. In `get_gtag_src` function, replace

```php
  return 'https://www.googletagmanager.com/gtag/js?id=' . rawurlencode( $this->tags[0]['tag_id'] );
```

with

```php
  return plugins_url( 'fpm/measurement.php', GOOGLESITEKIT_PLUGIN_MAIN_FILE ) . '?id=' . rawurlencode( $this->tags[0]['tag_id'] ) . '&s=/gtag/js';
```

Save the file.

2. Load the homepage. Check in the network tab that the request to `https://example.com/wp-content/plugins/google-site-kit/fpm/measurement.php?id=GT-some-tag-id&s=/gtag/js` is being triggered. Domain and `id` will be different in the actual request.

3. Open the Google analytics dashboard for the property for which the Google analytics has been setup in the Site Kit. Go to realtime overview in the GA dashboard.

4. Open homepage of the test website and scroll, click, visit different page and check in GA dashboard that different events are being captured.

## Changelog entry

* Integrate the First-party mode proxy script that will allow Analytics events to be tracked via requests made from the browser to the user's site rather than directly to Google's servers.

**Comment by nfmohit** [comment]
AC ✅

**Comment by techanvil** [comment]
Thanks @ankitrox, the IB looks good. I've made a couple of minor grammatical tweaks which you'll see in the edit history.

IB ✅

**Comment by techanvil** [comment]
## QA ✅ 

- Updated `includes/Core/Tags/GTag.php` to return the `measurement.php` proxy URL:
![Image](https://github.com/user-attachments/assets/4d14339c-6c4b-4597-b0ee-06f347d895c9)
- Confirmed the GTag script is loaded via `measurement.php` as expected:
![Image](https://github.com/user-attachments/assets/40957375-94e9-4da5-b2f7-475bb0c28b80)
- Confirmed that events are tracked via the `measurement.php` script:
![Image](https://github.com/user-attachments/assets/95a5598d-a9b2-4f7d-abef-3e81ca090baf)
- Verified events being tracked E2E via the realtime report:
![Image](https://github.com/user-attachments/assets/be8d95ea-b6c9-407f-904c-6000df373c07)
