### ISSUE TITLE
Display First-Party Mode Status in Site Health

### ISSUE THREAD

**Issue by hussain-t** [google/site-kit-wp#9667]
## Feature Description

Enhance Site Health to show the status of First-party mode, indicating whether it is enabled or disabled.

For details, refer to the [Design Doc](https://docs.google.com/document/d/1PHptJ1Js_1OZrk5kRwoB3zPB2KQrXLJV7-3izi-bB30/edit?tab=t.0#heading=h.qeiw15oj4hsa).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The following entry should be added to Site Kit's Site Health section when the `firstPartyMode` feature flag is enabled:
  * Title: _First-Party Mode: Enabled_
  * Value:
    * _Yes_ if First-party mode is enabled.
    * _No_ if it's not enabled.
* If https://github.com/google/site-kit-wp/issues/9668 has already been implemented it should be ensured that this entry appears above the entries specified in that issue.

## Implementation Brief

* [x] Update `includes/Core/Tags/First_Party_Mode/First_Party_Mode.php`:
   * Inherit the `Module_With_Debug_Fields` trait.
   * Add a new method `get_debug_fields`:
      * Get the module settings with `$settings = $this->get_settings()->get();`, return the value of `isEnabled` in the following format:
         ```
			'first_party_mode_is_enabled' => array(
				'label' => __( 'First-Party Mode: Enabled', 'google-site-kit' ),
				'value' => $settings['isEnabled'] ? __( 'Yes', 'google-site-kit' ) : __( 'No', 'google-site-kit' ),
				'debug' => $settings['isEnabled'] ? 'yes' : 'no',
			),
         ```
          *Note: the module activation is behind a feature flag, and these debug fields will only show when the module is active so I have not added any additional feature flag check.*

### Test Coverage

* No additional test coverage required.

## QA Brief

* Enable either the Ads or Analytics module and the `firstPartyMode` feature flag.
* Visit site health and you will see the new field.
* If the toggle switch has not been merged you should be able to test by manually editing/adding the settings into `googlesitekit_first_party_mode` meta key in the `wp_options` table.

**Update:**

* We don't have to update the settings in the `wp_options` table. Instead we can simply execute the following steps.
* Set the First-Party Mode status and save the settings by running the following commands in the browser console:
```js
// Set `isEnabled` locally:
googlesitekit.data.dispatch( "core/site" ).setFirstPartyModeEnabled( true );

// Persist the settings on the server.
await googlesitekit.data.dispatch( "core/site" ).saveFirstPartyModeSettings();
```

## Changelog entry

* Add First-Party Mode status to Site Kit’s Site Health section, displaying whether the feature is enabled or not when either the Analytics or Ads modules are connected and the `firstPartyMode` feature flag is active.

**Comment by nfmohit** [comment]
AC ✅

**Comment by techanvil** [comment]
>       *Note: I adjusted the titles slightly from the AC to keep them consistent with #9680*

Thanks @benbowler, good shout. I've amended the AC accordingly and removed this note from the IB.

IB ✅

**Comment by hussain-t** [comment]
Hi @benbowler, FYI, we don't have to alter the `wp_options` table to update the FPM settings. We can run the following actions to set and persist the status. I've updated the QAB to avoid a round of iteration.

```js
// Set `isEnabled` locally:
googlesitekit.data.dispatch( "core/site" ).setFirstPartyModeEnabled( true );

// Persist the settings on the server.
await googlesitekit.data.dispatch( "core/site" ).saveFirstPartyModeSettings();
```

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The following entries are added to Site Kit's Site Health section when the `firstPartyMode` feature flag is enabled:
  - Title: First-Party Mode: Enabled
  - Value:
     - Yes when First-party mode is enabled.
     - No when not enabled.

<details>
 <summary>Screenshots</summary>

![Image](https://github.com/user-attachments/assets/df13977f-547c-471f-9296-ec1cc06a2598)

![Image](https://github.com/user-attachments/assets/019dd1c6-d0a3-4aba-9978-161b84fb9121)

</details>
