### ISSUE TITLE
Display FPFE Health Check and Script Access Status in Site Health

### ISSUE THREAD

**Issue by hussain-t** [google/site-kit-wp#9668]
## Feature Description

Add FPFE health check and script access statuses to the Site Health report, displaying whether these checks are enabled or disabled.

For details, refer to the [Design Doc](https://docs.google.com/document/d/1PHptJ1Js_1OZrk5kRwoB3zPB2KQrXLJV7-3izi-bB30/edit?tab=t.0#heading=h.oh47p42srtvl).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The following entries should be added to Site Kit's Site Health section when the `firstPartyMode` feature flag is enabled:
  * Title: _First-Party Mode: Service healthy_
  * Value:
    * _Yes_ if the FPFE service health check has succeeded.
    * _No_ if the health check has failed.
  * Title: _First-Party Mode: Script accessible_
  * Value:
    * _Yes_ if the script access check has succeeded.
    * _No_ if the access check has failed.
* For each entry the value should be a dash, `-`, if the given check hasn't been made yet.
* If https://github.com/google/site-kit-wp/issues/9667 has already been implemented it should be ensured that these Site Health entries appear below the _First-party mode enabled_ entry.

## Implementation Brief

* [x] Update the `get_debug_fields` method, added in #9667, in `includes/Core/Tags/First_Party_Mode/First_Party_Mode.php`:
	* Create two private methods to return the correct values to display for each healthcheck field:
		```
		private function health_check_debug_field_value( $setting_value ) {
			if ( true === $setting_value ) {
				return __( 'Yes', 'google-site-kit' );
			} elseif ( false === $setting_value ) {
				return __( 'No', 'google-site-kit' );
			}
			return '-';
		}
		private function health_check_debug_field_debug( $setting_value ) {
			if ( true === $setting_value ) {
				return 'yes';
			} elseif ( false === $setting_value ) {
				return 'no';
			}
			return '-';
		}
		```

	* Add two new site health fields like so:
		```
		'first_party_mode_is_fpm_healthy' => array(
			'label' => __( 'First-Party Mode: Service healthy', 'google-site-kit' ),
			'value' => $this->health_check_debug_field_value( $settings['isFPMHealthy'] ),
			'debug' => $this->health_check_debug_field_debug( $settings['isFPMHealthy'] )
		),
		'first_party_mode_is_script_access_enabled' => array(
			'label' => __( 'First-Party Mode: Script accessible, 'google-site-kit' ),
			'value' => $this->health_check_debug_field_value( $settings['isScriptAccessEnabled'] ),
			'debug' => $this->health_check_debug_field_debug( $settings['isScriptAccessEnabled'] )
		),
		```

*Note: the module activation is behind a feature flag, and these debug fields will only show when the module is active so I have not added any additional feature flag check.*

### Test Coverage

* No additional test coverage required.

## QA Brief

* Enable either the Ads or Analytics module and the `firstPartyMode` feature flag.
* Visit site health and you will see the new fields.
* You can test setting values of `isFPMHealthy` and `isScriptAccessEnabled` settings by running `  await googlesitekit.api.get('core','site','fpm-server-requirement-status', undefined, { useCache: false });
` in the developer console, then updating values in `googlesitekit_first_party_mode` meta key in the `wp_options` table.

## Changelog entry

* Add FPFE health check and script access statuses to Site Kit’s Site Health section, displaying whether these checks are enabled or disabled.

**Comment by nfmohit** [comment]
AC ✅

**Comment by techanvil** [comment]
>       *Note: I adjusted the titles slightly from the AC to keep them consistent with #9680*

Thanks @benbowler, again, good shout and I've amended the AC accordingly and removed this note from the IB.

IB ✅

**Comment by techanvil** [comment]
Hi @benbowler, thanks for updating the IB.

I'll approve this for the sake of moving it forward, but for future reference please do try to avoid including code snippets like this where they are not necessary, as per our [guidelines](https://docs.google.com/document/d/17eVCooecdDD2s6HluvZA3jBEH7hrGKgudJ3Tyu3JlZA/edit?tab=t.0#heading=h.lp95xtn1qsfo).

IB ✅

**Comment by kelvinballoo** [comment]
### QA Update ⚠ 

I have tested this and I have a couple of queries:

**ITEM 1:**
For the last point in the QAB, I ran  `await googlesitekit.api.get('core','site','fpm-server-requirement-status', undefined, { useCache: false });` in the developer console but there was an error.
Is that script necessary or I can directly update the values to 0 or 1 in the wp-options table? Doing so works fine from my POV.

Video is attached for reference.
<Details>

https://github.com/user-attachments/assets/f442f33e-b376-4f83-940f-d07f2f3a5f3a

</Details>
________________________________________________________________________

ITEM 2:
If let's say I have disconnected Analytics and I reconnected it with an incomplete setup, should the values be '-'? 
Currently, it's showing up as 'Yes' for me. 
Video is attached for reference.

<Details>

https://github.com/user-attachments/assets/79cc6021-0394-47d1-894b-56ddbd9e697a

</Details>

**Comment by hussain-t** [comment]
@kelvinballoo, the following is the Site Kit's code snippet. Hence, it should be executed within the Site Kit dashboard or the settings page.
```js
await googlesitekit.api.get( 'core', 'site', 'fpm-server-requirement-status', undefined, { useCache: false } )
```

**Comment by benbowler** [comment]
Hey @kelvinballoo, as @hussain-t says you can run that snipped on the dashboard or settings page to create the database record. You can then make changes in the database. However, because code that automatically does the checks has now been merged, these steps might be overwritten by the real healthcheck values. There are discussions in Slack around a tester plugin update that will allow you to test these healthcheck states that could help if you can't fully test here.

To your second point, showing these healthcheck values seems good regardless of module state as it can inform the user if they are able to enable this feature at a later point once they finish Analytics module setup.

**Comment by kelvinballoo** [comment]
### QA Update ✅ 

Thanks @benbowler , @hussain-t . Noted on those points.
This ticket is good to move to approval.

Verified the following:
- Tested when either the Ads or Analytics module is connected and even when both are connected.
   Under site health, the new fields appear with values Yes/No:
   - First-Party Mode: Service healthy - Yes/No
   - First-Party Mode: Script accessible - Yes/No
   <Details>

   ![Image](https://github.com/user-attachments/assets/6afc782e-ef8a-448d-b3f7-fe8817d795f7)

   </Details>

- When turning off feature flag, the fields no longer appear.
   <Details>

   ![Image](https://github.com/user-attachments/assets/9a1475bb-5f5f-45ac-a4a4-00a93b50bdb0)

   </Details>

- When disconnecting analytics and ads, the fields are no longer there.
   <Details>

   ![Image](https://github.com/user-attachments/assets/2437d3c2-8157-4809-bf2b-0303b3fa0390)

   </Details>

- When disconnect analytics but connectd ads, the fields appear.
   <Details>

   ![Image](https://github.com/user-attachments/assets/6bb1334e-af60-47f9-9bbf-4e4f713d1384)


   </Details>

- Ran the script `await googlesitekit.api.get('core','site','fpm-server-requirement-status', undefined, { useCache: false });` in the developer console and it works fine. 
   <Details>

   ![Image](https://github.com/user-attachments/assets/64882688-79cc-440c-80b1-05c8ab5a40c5)

   
   </Details>

- Tested different values: 1, 0 or N by updating values in googlesitekit_first_party_mode meta key in the wp_options table and in the Site Health, it will show as Yes, No or '-' respectively.

   <Details>

   ![Image](https://github.com/user-attachments/assets/31d1e634-4bb9-47dd-99f8-a2a08affb05d)
   
   https://github.com/user-attachments/assets/d790f05e-21e0-406c-802c-e59a12d1e7fd

   </Details>
