### ISSUE TITLE
Place RRM snippet only on singular WordPress posts

### ISSUE THREAD

**Issue by nfmohit** [google/site-kit-wp#9670]
## Bug Description

The RRM snippet is currently placed across the entire site. Instead, it should only be placed on singular WordPress posts.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Reader Revenue Manager snippet should only be placed on singular posts of the "post" post type.

## Implementation Brief

* [x] In `includes/Modules/Reader_Revenue_Manager/Web_Tag.php`:
	* [x] Update the `enqueue_swg_script` method:
		* [x] Call the `wp_enqueue_script` function only if it is a singular post of the "post" post type, i.e. `is_singular( 'post' )`.

### Test Coverage

* In `tests/phpunit/integration/Modules/Reader_Revenue_Manager/Web_TagTest.php`:
	* Update tests to assert that the snippet is only added according to ACs.
		* You can take a look at how it was done for Thank with Google [here](https://github.com/google/site-kit-wp/blob/1.89.0/tests/phpunit/integration/Modules/Thank_With_Google/Web_TagTest.php).

## QA Brief

* Turn on the `rrmModule` feature flag.
* Set up Site Kit and the Reader Revenue Manager module.
* Go to the site front-end.
* View page source and verify that the RRM snippet is only added to singular posts and nowhere else.

## Changelog entry

* Only place the Reader Revenue Manager snippet on singular WordPress posts.

**Comment by techanvil** [comment]
IB ✅

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on main environment.
- Tested after setting up RRM module.
- Verified that the RRM snippet is only added to singular posts and nowhere else.
- Verified that if RRM module is disconnect then snippet gets remove from WP posts.

<details>

https://github.com/user-attachments/assets/dfeeeda8-e84c-4800-a371-bf0c5def9ab3

https://github.com/user-attachments/assets/64231842-23e8-4d08-815e-68d877cc87f7

</details>
