### ISSUE TITLE
Reset deletes dev settings option

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#968]
## Bug Description

Resetting Site Kit deletes the `googlesitekitdev_settings` option which should be excluded from the delete queries.

This is because of the way the option prefix is passed to the database query for the reset.

https://github.com/google/site-kit-wp/blob/3db5ce48f9304067bbe897475c028c7daf7c09ba/uninstall.php#L20-L26

According to the [MySQL docs](https://dev.mysql.com/doc/refman/5.7/en/pattern-matching.html):
> SQL pattern matching enables you to use `_` to match any single character and `%` to match an arbitrary number of characters (including zero characters)

This causes the query to match all `googlesitekit*` options instead of `googlesitekit_*` options.

## Steps to reproduce

1. Install and configure the [helper plugin](http://sitekit.withgoogle.com/service/download/google-site-kit-dev-settings.zip)
1. Reset Site Kit
1. Note developer settings are gone

## Additional Context

 - PHP Version: 
 - Plugin Version [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Only options / user options starting in `googlesitekit_` should be wiped on reset or disconnect.
    * Options / user options starting in `googlesitekit{somethingelse}` should not be wiped.

## Implementation Brief

* Ensure underscores are properly escaped in all direct database queries

## Changelog entry

* Ensure that only options and user options starting with `googlesitekit_` (including underscore) are deleted on reset or disconnect.

**Comment by felixarntz** [comment]
IB ✅

**Comment by tofumatt** [comment]
QA failed for me on this one. I tried a few times with the latest `develop` but my Developer Settings are always cleared out:

![2019-12-16 19 56 21](https://user-images.githubusercontent.com/90871/70938547-4bccde00-203e-11ea-8e61-444bd8e8284a.gif)

(Note: this happens with real credentials too but I didn't want to post them in the public GIF 😄)

**Comment by aaemnnosttv** [comment]
@tofumatt it sounds like you aren't on the latest version of the helper plugin. Can you try upgrading to the [latest](http://sitekit.withgoogle.com/service/download/google-site-kit-dev-settings.zip) and try again?

**Comment by tofumatt** [comment]
Ohhh, snap, maybe that's it. I'll give it a go, cheers.

**Comment by tofumatt** [comment]
Huzzah! Indeed, that works.

QA ✅

With the latest version of the developer settings, my settings are intact after a site reset.
