### ISSUE TITLE
SiWG SK Site Health update to descriptions

### ISSUE THREAD

**Issue by kelvinballoo** [google/site-kit-wp#9680]
## Feature Description

This came up while testing https://github.com/google/site-kit-wp/issues/9571 
The AC lists one of the fields to appear under SK's site health as:
'**The absolute number of users who have authenticated using Sign in with Google**'

Current implementation is: 
'**Sign in with Google Number of users who have authenticated using Sign in with Google**'

There are 2 potential options from here.

**OPTION 1:**
Should we change the current implementation to '**The absolute number of users who have authenticated using Sign in with Google**' ?

**OPTION 2:**
Or should we maintain the current implementation and just add a semi-colon after the module name for all the relevant fields in the attached screenshot?
<Details>

![Image](https://github.com/user-attachments/assets/b4860ccb-9af7-4c11-ab75-c2e41cfb0856)

</Details>

Expectation:
Sign in with Google:  Client ID
Sign in with Google: Shape
Sign in with Google: Text
Sign in with Google: Theme
Sign in with Google: One-tap Enabled
Sign in with Google: Number of users who have authenticated using Sign in with Google

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Whenever the module name is prefixed in a Site Health debug field, the prefix should end with a colon sign. Also, prefer capitalising words unless it is a phrase:
  * Search Console Shared Roles --> Search Console: Shared Roles
  * Search Console property --> Search Console: Property
  * Analytics account ID --> Analytics: Account ID
  * Sign in with Google Shape --> Sign in with Google: Shape
  * Ads Conversion Tracking ID --> Ads: Conversion Tracking ID

## Implementation Brief

* [ ] Within the implementation of all `get_debug_fields()` methods within all module classes that implement the `Module_With_Debug_Fields` interface (i.e. `Ads.php`, `AdSense.php`, `Analytics_4.php`, `Reader_Revenue_Manager.php`, `Search_Console.php`, `Sign_In_With_Google.php` and `Tagmanager.php`, if the `label` begins with the module name, add a colon after it as demonstrated in the AC. Also capitalise words within the label unless they form a part of a sentence of phrase.

### Test Coverage

* No new tests required.

## QA Brief

* Visit the Site Health info tab and verify the ACs.

## Changelog entry

* Update Sign in with Google descriptions in Site Health.

**Comment by tofumatt** [comment]
AC 👍🏻 

IB ✅  as well 🙂

**Comment by kelvinballoo** [comment]
### QA Update ✅ 

This was verified good across all the different modules connected.
Moving ticket to approval.

<Details>

Ads: 

![Image](https://github.com/user-attachments/assets/dba48495-56d1-43fd-b49a-d2d39859f38d)

Adsense:

![Image](https://github.com/user-attachments/assets/0732187d-4cc7-4134-ab7a-578857dbad34)

Analytics:

![Image](https://github.com/user-attachments/assets/f63acf90-7273-4214-a43f-6606e001bb40)

PageSpeed Insights:

![Image](https://github.com/user-attachments/assets/e94900c1-7b8c-40d4-aa48-fee3aa075545)

Reader Revenue Manager:

![Image](https://github.com/user-attachments/assets/b4f4325c-5689-481d-be94-b04ae2feae57)

Search Console:

![Image](https://github.com/user-attachments/assets/5a57012a-71dd-4518-947f-9c7606714120)

Sign in with Google:

![Image](https://github.com/user-attachments/assets/60768a79-2ecc-499d-874a-7d84059ec47d)

Tag Manager:

![Image](https://github.com/user-attachments/assets/90da92ea-115e-47d0-9f25-d3b45da4a991)

</Details>
