### ISSUE TITLE
Implement `haveFirstPartyModeSettingsChanged` Selector and `resetFirstPartyModeSettings` Action

### ISSUE THREAD

**Issue by hussain-t** [google/site-kit-wp#9688]
## Feature Description

Develop a selector and action in the First-party mode datastore to handle the settings state:
* `haveFirstPartyModeSettingsChanged()`: A selector to check if current settings differ from saved settings.
* `resetFirstPartyModeSettings()`: An action to revert any changes, restoring settings to their saved state.

These should integrate with existing rollback and validation processes of Analytics and Ads settings.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A `haveFirstPartyModeSettingsChanged` selector should be created to compare the current First-party mode settings with the saved settings, returning `true` if there are unsaved changes and `false` if the current settings match the saved settings.
* A `resetFirstPartyModeSettings` action should be created to reset any unsaved changes in the First-party mode settings, restoring them to the last saved state.
* The `resetFirstPartyModeSettings` action should be called within the `rollbackChanges` process of both Analytics and Ads settings to ensure any unsaved changes are discarded when rolling back.
* The `haveFirstPartyModeSettingsChanged` selector should be used within the `validateHaveSettingsChanged` function of both Analytics and Ads settings to confirm if there are changes that need validation before saving.
* The submit button on both the Analytics and Ads settings screens should update its text to “Confirm changes” when there are validated changes, indicating that the modified settings will be saved.

## Implementation Brief

- [x] In `assets/js/googlesitekit/datastore/site/first-party-mode.js`
  - Add a new property `firstPartyModeSavedSettings ` in `baseInitialState` object.
  - In `settingsReducerCallback` assign `firstPartyModeSettings` to `state.firstPartyModeSavedSettings`.
- [x] Create a new selector `haveFirstPartyModeSettingsChanged`, this will get the `state` as its parameter.
  - Retrieve `firstPartyModeSettings` and `firstPartyModeSavedSettings ` from `state`.
  - Check if `firstPartyModeSettings` and `firstPartyModeSavedSettings ` are equal using `isEqual` method from lodash. If equal, return `false`, else `true`.
- [x] Create a new property `resetFirstPartyModeSettings` in `baseActions` which should dispatch an action of type `RESET_FIRST_PARTY_MODE_SETTINGS`.
  - In `baseReducer`, for `RESET_FIRST_PARTY_MODE_SETTINGS` action, reset `firstPartyModeSettings` to `firstPartyModeSavedSettings ` like  
```js
    state.firstPartyModeSettings = state.firstPartyModeSavedSettings;
```
- [x] In `assets/js/modules/ads/datastore/settings.js`
  - In `validateHaveSettingsChanged`, use `haveFirstPartyModeSettingsChanged` selector from `core/site` store to get whether settings have been changed.
    - Use `haveFirstPartyModeSettingsChanged` along with existing condition to determine whether the settings have been changed.
  - In `rollbackChanges` function, call `resetFirstPartyModeSettings` action from `core/site` store.
- [x] In `assets/js/modules/analytics-4/datastore/settings.js`
  - In `validateHaveSettingsChanged`, use `haveFirstPartyModeSettingsChanged` selector from `core/site` store to get whether settings have been changed.
    - Use `haveFirstPartyModeSettingsChanged` along with existing condition to determine whether the settings have been changed.
  - In `rollbackChanges` function, call `resetFirstPartyModeSettings` action from `core/site` store.

### Test Coverage

1. Add the tests for new selector and action.
2. Update existing tests for `ads` and `analytics-4` settings to accommodate the first party mode settings change.

## QA Brief

1. Connect the Analytics and Ads modules in Site Kit plugin.
2. Go to Site Kit > Settings > Analytics, click `Edit` link, so that Settings Edit screen is opened.

Run following command and note the output as it will be used to comare against the value in step 4 below.

```js
  googlesitekit.data.select('core/site').isFirstPartyModeEnabled();
```

Run following command

```js
  const isFPMEnabled = googlesitekit.data.select('core/site').isFirstPartyModeEnabled();
  googlesitekit.data.dispatch('core/site').setFirstPartyModeEnabled( ! isFPMEnabled );
```

Notice that the `Save` button text will change to `Confirm Changes`.

3. Run the following command

```js
  googlesitekit.data.select('core/site').isFirstPartyModeEnabled();
```

It should output `true`. FPM is enabled in data store.

4. Click `Cancel` button which will switch back to Settings View screen. Run the command from previous step again, it should output the same value as that of in step 1. If the value in step 1 was null, then value in step 4 should also be `null`.

5. Repeat the exact same steps for Ads section in `Site Kit > Settings > Ads`.

## Changelog entry

* Add a selector to detect changes and an action to reset First-party mode settings, integrated with Analytics and Ads rollback and validation processes.

**Comment by techanvil** [comment]
AC ✅

**Comment by techanvil** [comment]
Hi @ankitrox, thanks for drafting this IB. A couple of points:

- The property name `savedSettings` is too generic to use as a top level state value. Remember, the initial state for all of the partial stores are merged into one object. I'd suggest the shape of the state for the FPM store partial should be either:

```typescript
{
  firstPartyModeSettings: object|undefined;
  firstPartyModeSavedSettings: object|undefined;
}
```

Or:

```typescript
{
  firstPartyMode: {
    settings: object|undefined;
    savedSettings: object|undefined;
  }
}
```

- The code snippet for handling `RESET_FIRST_PARTY_MODE_SETTINGS` in the reducer needs a tweak. We shouldn't assign `state.savedSettings` directly to `state.firstPartyModeSettings` as we don't want them to share a reference. We should instead assign a copy, e.g.
```js
    state.firstPartyModeSettings = { ...state.savedSettings };
```

**Comment by ankitrox** [comment]
Thanks @techanvil for reviewing the IB. I've made the couple of suggested changes and assigning it to you to review the same.

Thank you.

**Comment by techanvil** [comment]
Thanks @ankitrox. Actually, while reviewing this again I noticed we do actually take the approach of sharing references in a similar situation in the conversion tracking store partial:

https://github.com/google/site-kit-wp/blob/17f036cec1bd18b2b41b969c8fe635efd7c5d8c0/assets/js/googlesitekit/datastore/site/conversion-tracking.js#L138-L141

Digging in, I've found that despite the references being the same, Immer protects us against mutating the state in both places - a new object is created for `state.settings` in the reducer when setting one of its properties.

https://github.com/google/site-kit-wp/blob/17f036cec1bd18b2b41b969c8fe635efd7c5d8c0/assets/js/googlesitekit/datastore/site/conversion-tracking.js#L135

The upshot of this is we don't actually _need_ to clone the object as per my previous comment. It's debatable which is preferable but I've reverted the IB point to be consistent with the existing code. Sorry to steer you in the "wrong" direction here, although cloning is not an incorrect thing to do there per se.

I've also made a minor correction as there was still a reference to `savedSettings` which needed updating to `firstPartyModeSavedSettings`, and I fixed an odd layout error with the code block appearing above where it should have (this took a few edits to get right). Please review my changes and if you're happy, move this straight to the EB.

I'll give this an IB ✅ in the meantime.

**Comment by ankitrox** [comment]
Thanks @techanvil . No worries, I also overlooked this fact which you shared.

All looks good to me, moving to EB.

**Comment by wpdarren** [comment]
### QA Update: ⚠ 

@ankitrox I have one small observation.  When editing Analytics settings, when I run   `googlesitekit.data.select('core/site').isFirstPartyModeEnabled();` the output is `Undefined` rather than `Null` I suspect thats not the expected behaviour?  I didn't notice this with the Ads module. 

**Verified:**

- The Save button text changes to `Confirm Changes`.
- The output is `true`. FPM is enabled in data store.
- When I click the `Cancel `button, it switches back to Settings View screen. 
- When I run the command, the same value as that of in step 1, i.e. null. 

I ran through the QAB steps for Analytics and Ads modules. 

<details>
 <summary>Screenshots</summary>

![Image](https://github.com/user-attachments/assets/26ade208-4fd7-450b-904b-b5f7a88a749b)
![Image](https://github.com/user-attachments/assets/dccdb206-5e39-43e9-abfa-22a8aeec0e90)
![Image](https://github.com/user-attachments/assets/7beb0d81-5f2d-482d-8b40-aa3445353b19)
![Image](https://github.com/user-attachments/assets/f16b4729-2cc4-41b0-8a21-6a548a139a67)

</details>
