### ISSUE TITLE
Update icon for Optimize

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#969]
## Feature Description

The icon used for [Google Optimize](https://optimize.google.com/optimize/home/) seems to be out-of-date. We should update it to be consistent with the service's homepage.

### Service homepage
![image](https://user-images.githubusercontent.com/1621608/70645527-d9c75400-1c4d-11ea-98de-da34689e1e5f.png)

### Currently in the plugin
![image](https://user-images.githubusercontent.com/1621608/70645539-de8c0800-1c4d-11ea-8cdc-537a5fd06020.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Updated Optimize icon should be displayed in all relevant locations (setup flow, settings, etc).
Hi-res PNG file:
![optimize_96dp](https://user-images.githubusercontent.com/13304791/74742141-626dfc00-525e-11ea-882d-21090aa1adc0.png)
 
## Implementation Brief

* Update `assets/svg/optimize.svg` with official SVG https://www.gstatic.com/analytics-suite/header/suite/v2/ic_optimize.svg

## Changelog entry

* Use latest product icon for the Optimize module.

**Comment by marrrmarrr** [comment]
@aaemnnosttv what size icons do you need? I can find you the source files

**Comment by aaemnnosttv** [comment]
@marrrmarrr I think we can use this one from https://optimize.google.com 🙂 

https://www.gstatic.com/analytics-suite/header/suite/v2/ic_optimize.svg

**Comment by aaemnnosttv** [comment]
@marrrmarrr the AC mentions using PNG but we use SVG for all logos. This is better as it will scale for all screen resolutions 🙂

**Comment by felixarntz** [comment]
IB ✅

**Comment by aaemnnosttv** [comment]
@felixarntz this one ended up being slightly more work than expected due to separate icons used for disabled and active module states. Rather than updating the disabled variant, I opted to remove these and style the normal/active icon as disabled instead (probably what we all thought was happening anyways). This has the benefit of less work needed to add modules in the future or (in this case) update the icon. It turns out that the disabled icon for Tag Manager (the only other module that has a disabled icon) was out of date as well. This prevents such a thing from happening again 👍

**Comment by aaemnnosttv** [comment]
Actually, it turns out that the Tag Manager icon was correct, as the comparison only failed in a single test+viewport. This leads me to think that it may be one of the strange fluke renders that causes VRT to randomly fail sometimes. At any rate, it's still better to only have a single icon per module rather than two, and VRT didn't notice a change between the previous version and the new one using styles, so this is actually a pure refactor in that regard 😄

**Comment by cole10up** [comment]
**Tested**

Checked the following pages:

Connect more services
![image](https://user-images.githubusercontent.com/57115907/76483436-429ca480-63d4-11ea-8278-94ad8aa1f876.png)

Setup Optimize
![image](https://user-images.githubusercontent.com/57115907/76483463-521bed80-63d4-11ea-8292-ea8a551c73ac.png)

Connected Services
![image](https://user-images.githubusercontent.com/57115907/76483594-a6bf6880-63d4-11ea-8f81-48be9ea0d7a4.png)

Settings:
![image](https://user-images.githubusercontent.com/57115907/76483649-ce163580-63d4-11ea-8ca4-edc9491e4f08.png)

Passed QA ✅

**Comment by marrrmarrr** [comment]
Verified icon appears as intended in all UI settings.
