### ISSUE TITLE
Dismiss the First-Party Mode Setup Banner Notification When Toggle Is Enabled from Settings Screen

### ISSUE THREAD

**Issue by hussain-t** [google/site-kit-wp#9698]
## Feature Description

The First-party mode Setup Banner should automatically dismiss itself if the user enables First-party mode directly through the settings screen to ensure a consistent user experience and avoid redundant notifications after the feature has been enabled.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The First-party mode Setup Banner should automatically dismiss itself when the user enables the First-party mode toggle from the settings screen.
* The dismissal should be permanent and ensure the banner does not reappear after the toggle is enabled.
* This behavior should mirror the implementation of the Consent Mode switch dismissal, as seen in the [ConsentModeSwitch](https://github.com/google/site-kit-wp/blob/b94493bb2883b6c91615b05c63629a1b27b70bf7/assets/js/components/consent-mode/ConsentModeSwitch.js#L74-L95) component.
* Ensure this behavior is consistent across both the Ads and Analytics settings screens where the toggle is displayed.

## Implementation Brief

- [ ] Update the Ads `submitChanges()` function. After the call & error handling for `saveFirstPartyModeSettings()` (introduced via https://github.com/google/site-kit-wp/issues/9655):
https://github.com/google/site-kit-wp/blob/c8e73f872b70f928ab60464d97c88f94b0bbed7c/assets/js/modules/ads/datastore/settings.js#L69-L77
  - Retrieve the `isEnabled` FPM setting.
  - Retrieve the dismissed status for the Setup Banner via the `CORE_NOTIFICATIONS` store's `isNotificationDismissed()` selector.
  - If FPM is enabled and the banner isn't dismissed, dispatch the `CORE_NOTIFICATIONS` store's `dismissNotification()` action to dismiss it.
- [ ] Repeat the above for the Analytics `submitChanges()` function (see https://github.com/google/site-kit-wp/issues/9654).

### Test Coverage

* Add coverage for the above changes to the tests for each module.

## QA Brief

* Follow steps 1-3 from the QAB for https://github.com/google/site-kit-wp/issues/9647 and ensure the FPM setup banner is present on the dashboard.
* Navigate to the Analytics or Ads settings screen.
* Toggle the **First-party mode** switch on, save the settings, and verify that the setup banner is dismissed.
* Repeat all of the above steps, starting with a fresh site, but save the settings with the switch in the off position and verify the setup banner is not dismissed. In this scenario, change one of the other module settings in order to show the "Confirm changes" CTA.

## Changelog entry

* Automatically dismiss the First-Party Mode setup banner notification when the toggle is enabled from the settings screen, preventing redundant notifications.

**Comment by techanvil** [comment]
@hussain-t sorry, please ignore my last comment - I got mixed up thinking this issue was referring to the success notification whereas it's actually the setup banner, so it's still relevant.

That being the case, these AC LGTM!

AC ✅

**Comment by nfmohit** [comment]
IB ✅

**Comment by techanvil** [comment]
Hey @nfmohit, I picked this up for execution and realised I'd made a mistake with the IB, we should only dismiss the banner when enabling FPM and saving the settings (this is in line with the CoMo behaviour as per the AC).

I've amended the IB, would you mind re-reviewing it?

**Comment by nfmohit** [comment]
LGTM, thank you @techanvil !

IB ✅

**Comment by techanvil** [comment]
Great, thanks @nfmohit!

**Comment by wpdarren** [comment]
### QA Update: ⚠ 

@techanvil  From this part of the QAB: 

> Repeat the above, but save the switch in the off position and verify the setup banner is not dismissed.

When I go to the Site Kit settings (Analytics in this example) and disable First-party mode, and then go back to the dashboard, the setup banner does not reappear.   I created a screencast of the behaviour.  The AC though does suggest that the dismissal is permanent so I am wondering what should the outcome be in this situation? 

https://github.com/user-attachments/assets/a056cfac-6ae6-4e60-ae96-713c2e20735b

**Comment by techanvil** [comment]
Hi @wpdarren, sorry, I realise the last point of the QAB was a bit unclear. The intention was to repeat the whole process starting with a fresh site to ensure the banner is not dismissed. I've amended it to be clearer, please take another look.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The First-party mode Setup Banner automatically dismisses when the user enables the First-party mode toggle from the settings.
  - The dismissal is permanent and the banner does not reappear after the toggle is enabled.
- This behavior is consistent across both the Ads and Analytics settings screens where the toggle is displayed. 
- Repeated all of the steps, starting with a fresh site, and save the settings with the switch in the off position and the setup banner is not dismissed. In this scenario, I changed one of the other module settings and the`Confirm changes` CTA appeared.

https://github.com/user-attachments/assets/c9a92c1a-9c27-4fcf-8911-fa0be20af7c4
