### ISSUE TITLE
Blank screen on setup 

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#97]
## Bug Description

Blank screen upon visiting Site Kit dashboard. At one stage I did get to the verify stage but it would not proceed when I click on the "Continue" button. 

## Steps to reproduce

1. Install Site Kit via standard upload (with all plugins inactive)
2. Start activation process

## Screenshots

Video below
http://recordit.co/VQoZM3RXsS

And screenshot:
<img width="1645" alt="Screen Shot 2019-07-02 at 9 15 21 AM" src="https://user-images.githubusercontent.com/41326532/60496421-aa79e780-9caa-11e9-9456-b8834d57b8e5.png">

## Additional Context

 - PHP Version: 7.2
 - OS: IOS
 - Browser: Chrome
 - Plugin Version: 1.0.0 Beta 1
 - Plugins installed: Only Site Kit active (AMP was previously installed, but deactivated and deleted prior to Site Kit install
- Theme: Twenty Nineteen
- AMP Plugin status: was installed previously
- 2FA active

I have tried the same process a few times with this domain. I can't get to the verify state. At one point I got to the authentication stage but the verification step keep loading (after I click on verify button) but never proceeded. At that point I did have the AMP plugin active. (it was my first attempt on this domain) See below:

![verify](https://user-images.githubusercontent.com/41326532/60497286-71db0d80-9cac-11e9-9f80-99f9c1eaac2c.gif)

I will delete the app from Google Cloud Console and try the process again 
---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Changelog entry

* 

## Acceptance criteria

*

**Comment by ivankristianto** [comment]
@jamesozzie 
Can you please help me with these:

- What is Wordfence version you are using?
- What is AMP plugin version you are using? When you deactivate the plugin, can you clear your browser cache?
- Do you use any CDN like Cloudflare? If yes, in Cloudflare you might need to turn on development mode for a while. If not but still use other CDN, can you try to Purge all caches.
- Are you using any cache plugin to cache WordPress object cache and rest api cache?
- Can you please try with Site Kit v1.0.0-beta.1.0.1

**Comment by jamesozzie** [comment]
@ivankristianto See notes below:
- Wordfence 7.3.3 (Deactivated)
- Official AMP plugin (1.2)
- No CDN being used
- No caching plugins

Issue no longer occurs with 1.0.0-beta.1, feel free to close, or let me know if you would like me to troubleshoot further.

**Comment by aaemnnosttv** [comment]
> Issue no longer occurs with 1.0.0-beta.1, feel free to close, or let me know if you would like me to troubleshoot further.

@jamesozzie you reported this issue using `1.0.0 Beta 1`. Was it fixed for you with `1.0.0-beta.1.0.1` or the previous version `1.0.0-beta.1` (same as reported version)?

**Comment by jamesozzie** [comment]
@aaemnnosttv I have 1.0.0-beta.1 active at present and the issue no longer appears. At the same time I could not recreate the same issue use during other testings with 1.0.0 Beta 1.

**Comment by aaemnnosttv** [comment]
If this isn't reproducible then let's close it out. We can always re-open it if it comes up again.
