### ISSUE TITLE
AMP Auto Ads Compatibility with AMP for WP plugin

### ISSUE THREAD

**Issue by ernee** [google/site-kit-wp#971]
When using the [AMP for WP plugin ](https://wordpress.org/plugins/accelerated-mobile-pages/)on a site implementing AMP Auto Ads, the following validation error is thrown on AMP pages:

> The extension ‘amp-auto-ads’ was found on this page, but is unused. Please remove this extension.

AMP auto ads are not implemented/ displayed. 

1) Install and activate [AMP for WP plugin ](https://wordpress.org/plugins/accelerated-mobile-pages/)
2) Visit AMP page (typically` /amp ` endpoint) 
3) See the validation error ( in AMP validator or the validation extension)

## Screenshots
<img width="1185" alt="AMP validation extension error" src="https://user-images.githubusercontent.com/8108643/70658711-5db01a80-1c13-11ea-8e11-c685fece7d63.png">
<img width="1277" alt="AMP validator error " src="https://user-images.githubusercontent.com/8108643/70658718-60ab0b00-1c13-11ea-828b-90c3249d41b1.png">

## Additional Context

 - PHP Version: 7.1.33
 - OS: MacOS
 - Browser: Chrome
 - Plugin Version: 1.1.3
 - Device: MacBook Air

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* In AMP reader mode, the `amp-auto-ads` component should only be loaded if an `amp-auto-ads` tag generated by Site Kit is actually present in the post content.

### QA Instructions

1. Activate the AMP plugin and set it to Reader mode.
2. With AdSense module set up and it set up to render the tag, ensure the `amp-auto-ads` tag is still displayed in AMP reader mode content, and that there are no AMP validation errors (i.e. the `amp-auto-ads` component is also loaded).
3. Add a mini plugin with the following: `add_filter( 'the_content', '__return_empty_string', 999 );`, which should make every post render with empty content in the frontend. Go back to AMP reader mode content (where the post content should now as well be empty), and ensure that there are no AMP validation errors (i.e. the `amp-auto-ads` component is _not_ loaded).

## Implementation Brief

* In `AdSense::amp_data_load_auto_ads_component()`:
    * If `! $this->adsense_tag_printed`, return early.
    * If `$data['post_amp_content']` (see https://github.com/ampproject/amp-wp/blob/b86ba30087ea2fcac6f9ddec910fc59428e1ef54/includes/templates/class-amp-post-template.php#L348) does not contain `<amp-auto-ads `, return early.
* Both of these checks are fine since when setting up all this reader mode data the content (`the_content`) is generated before the `amp_post_template_data` filter is run.

## Changelog entry

*

**Comment by felixarntz** [comment]
@westonruter While this is not related to our AMP plugin, would there be any problem if we simply removed adding `amp-auto-ads` to `amp_component_scripts`? Our AMP plugin does that automatically if an `amp-auto-ads` tag exists in the page right?

**Comment by westonruter** [comment]
@felixarntz In Standard/Transitional modes, yes. In Reader mode this is only done for components in the post content. However, this is changing in v1.5, in which the entire Reader mode templates are sent through the post-processor (https://github.com/ampproject/amp-wp/issues/2202). So as of v1.5, filtering `amp_component_scripts` will be truly a thing of the past in the AMP plugin.

**Comment by TB7722** [comment]
@felixarntz What is the targeted release date for this. Thanks

**Comment by felixarntz** [comment]
@TB7722 We don't have a clear timeline yet, but this might make it into the next release scheduled for in 3 weeks from now.

**Comment by aaemnnosttv** [comment]
@felixarntz as long as the implementation is the same across all AMP modes, ✅ IB

**Comment by demiromer** [comment]
Hi is there any workaround about this?
Google stop indexing amp pages due to validation error

**Comment by jamesozzie** [comment]
@ernee While I can't reproduce this validation error I can see the [fallback](https://github.com/ahmedkaludi/accelerated-mobile-pages/blob/5c7e0af1b02ea1e343412c246dd5949310e377fa/templates/template-mode/template-mode.php#L21) hook is used in the AMP for WP templates to place the Site Kit Auto ads for AMP code. Maybe we can take a look at this later if you're free. 

The image below shows the code placements on AMP for WP (via Site Kit). 
![image](https://user-images.githubusercontent.com/41326532/76437378-639fce00-63b1-11ea-8459-e037165c8a32.png)

@demiromer Can you share your site URL and I can see if I notice anything in relation to those errors?

**Comment by demiromer** [comment]
Its been over a month @jamesozzie and I have already replaced the plugin

**Comment by ernee** [comment]
@jamesozzie as discussed, I no longer get the error as well.  I suspect the AMP for WP plugin has added compatibility in version 1.0.7 per [their changelog]( https://plugins.svn.wordpress.org/accelerated-mobile-pages/trunk/changelog.txt).

**Comment by ryanwelcher** [comment]
I am unable to reproduce this either.

**Comment by tofumatt** [comment]
If QA can't reproduce this either I think we can safely close it as fixed upstream 👍

**Comment by cole10up** [comment]
I'm unable to reproduce this one on my end. Looks to be fixed.

Passed QA ✅

**Comment by ernee** [comment]
Closing as it was not reproducible any longer.
