### ISSUE TITLE
Inconsistencies with casing of "Sign in with Google" across the plugin

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#9719]
## Bug Description

From the SiWG bug bash. Asana ticket can be found [here](https://app.asana.com/0/1208661003027471/1208794928746361/f).

When viewing the setup CTA banner, "Sign in with Google" is cased with "in" and "with" in lower case. However, on the connection screen, the description cases it as "Sign in With Google" where "With" is upper cased. 

The official wording is "Sign in with Google" and it should be that way everywhere. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Sign in with Google should be written as "Sign in with Google" everywhere, with no alternative capitalisations.

## Implementation Brief

* [ ] Replace user-facing strings at https://github.com/google/site-kit-wp/blob/440dcd6e8289a8776acc60ecb3c13f99bfd0ac5a/assets/js/modules/sign-in-with-google/index.js#L73 and https://github.com/google/site-kit-wp/blob/440dcd6e8289a8776acc60ecb3c13f99bfd0ac5a/assets/js/modules/sign-in-with-google/components/setup/SetupForm.js#L58 with "Sign in with Google"
* [ ] Update code comments with the same capitalisation at https://github.com/google/site-kit-wp/blob/440dcd6e8289a8776acc60ecb3c13f99bfd0ac5a/includes/Modules/Sign_In_With_Google.php#L41

### Test Coverage

* No new tests needed.

## QA Brief

* Check Sign in with Google is correctly capitalized in:
   * The Setup Form for the module.
   * The module disconnection features list.

## Changelog entry

* N/A

**Comment by eugene-manuilov** [comment]
IB ✔

**Comment by kelvinballoo** [comment]
### QA Update ✅ 

Sign in with Google is written as "Sign in with Google" everywhere, with no alternative capitalisations.
Multiple screens were checked as per details below.

Verified good. Moving ticket to approval.

<Details>

![Image](https://github.com/user-attachments/assets/0d3d099e-74d6-4dc8-8eac-0add93223fa2)

![Image](https://github.com/user-attachments/assets/49024a59-41c4-4a04-ac48-4c1eaa2d9372)

![Image](https://github.com/user-attachments/assets/8ad5fbc8-5041-4e41-96ed-8137922b499e)

![Image](https://github.com/user-attachments/assets/aae11d12-3275-498d-8819-814ed4538692)

![Image](https://github.com/user-attachments/assets/cfa6c05e-c44b-4d1a-9779-f99d5ff537d9)

![Image](https://github.com/user-attachments/assets/9381a0e0-b481-43e1-9eb3-bb26f793675e)

![Image](https://github.com/user-attachments/assets/0b6241a3-55b2-4b59-8680-e119e8b4cda1)

![Image](https://github.com/user-attachments/assets/3997ef1e-976d-4495-87b6-ec85ab18338b)

![Image](https://github.com/user-attachments/assets/4bc003b8-36c7-416f-aff1-f8a3cb9c081d)

![Image](https://github.com/user-attachments/assets/479ba3d0-ed56-4846-bc97-fcea2c7454f3)

![Image](https://github.com/user-attachments/assets/778a9383-296a-4cc4-93aa-c68fd030ada5)

![Image](https://github.com/user-attachments/assets/014dd698-00d2-4cba-9847-1e180af16bc6)

![Image](https://github.com/user-attachments/assets/ce4c6ff6-cd61-43a8-95d3-262038f4e865)

</Details>
