### ISSUE TITLE
Add composer.lock to repo

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#972]
## Feature Description

Similar to how we commit the `package-lock.json` for node modules, we should also include the `composer.lock` file to git for tracking the current installed PHP dependencies.

Composer says "This file locks the dependencies of your project to a known state". This is important both for development and in CI to ensure we're all "on the same page" in terms of dependencies and in reducing potential inconsistencies between environments.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* `composer.lock` should be included in version control.

## Implementation Brief

* Remove `composer.lock` from `.gitignore`
* Add `composer.lock` to the repo 

## Changelog entry

* N/A

**Comment by felixarntz** [comment]
IB ✅

**Comment by tofumatt** [comment]
QA ✅

`composer.lock` works fine and running `composer install` installs the right files with no issues or changes appearing in `composer.lock`'s `git diff` 👍
