### ISSUE TITLE
Console warning messages on the set up and edit settings screens

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#9720]
## Bug Description

From the SiWG bug bash. Asana ticket can be found [here](https://app.asana.com/0/1208661003027471/1208796203239378/f).

When on the SiWG module set up screen, various warnings occur in the browser. 

@jamesozzie also reported it when going to the edit screen for SiWG. 

![Image](https://github.com/user-attachments/assets/a653430a-b16c-428e-815c-05c64ac0473e)

```
googlesitekit-modules-sign-in-with-google-f5adc79d7ec046daf4e6.js:9 Invalid URL: TypeError: Invalid URL: undefined
    at r (googlesitekit-modules-sign-in-with-google-f5adc79d7ec046daf4e6.js:9:27561)
    at SetupMain (googlesitekit-modules-sign-in-with-google-f5adc79d7ec046daf4e6.js:1:3656)
    at Fo (googlesitekit-vendor-53f2bc5cdc475dd3f08e.js:7:721508)
    at Ti (googlesitekit-vendor-53f2bc5cdc475dd3f08e.js:7:767758)
    at Qj (googlesitekit-vendor-53f2bc5cdc475dd3f08e.js:7:760306)
    at Kj (googlesitekit-vendor-53f2bc5cdc475dd3f08e.js:7:760231)
    at wa (googlesitekit-vendor-53f2bc5cdc475dd3f08e.js:7:757261)
    at googlesitekit-vendor-53f2bc5cdc475dd3f08e.js:7:708905
    at t.unstable_runWithPriority (googlesitekit-vendor-53f2bc5cdc475dd3f08e.js:7:784156)
    at Br (googlesitekit-vendor-53f2bc5cdc475dd3f08e.js:7:708614)
```

Ths does not appear to be creating any user-facing issues from our testing but we've reported it as a launch blocker as it should be fixed. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* No console warning messages should appear when going through the SiwG setup and edit settings forms. This should be the case if HTTPS is enabled or disabled for the site.

## Implementation Brief

* [x] In `assets/js/modules/sign-in-with-google/components/setup/SetupMain.js`:
    * [ ] Before calling `isURLUsingHTTPS` (and subsequently `<SetupForm>`), check if homeURL is not undefined.
* [x] In `assets/js/components/notifications/HTTPSWarning.js`:
    * [ ] Similar to the above, if the `homeURL` is undefined, return null before calling the `isURLUsingHTTPS` method.

### Test Coverage

* No new tests required.

## QA Brief

* Follow the steps from bug description
* Verify that there are no console warnings

## Changelog entry

* N/A

**Comment by eugene-manuilov** [comment]
AC ✔

**Comment by eugene-manuilov** [comment]
@jimmymadon, as far as i understand it, those console errors appear because `isURLUsingHTTPS` is called while home URL is not resolved yet. We need to update components that use that function to wait until the home url is resolved and only then call that function. Could you please update IB accordinglyl?

**Comment by jimmymadon** [comment]
@eugene-manuilov The IB indirectly does do what you are saying unless I'm missing something. We can just check if `homeURL` is undefined and not call the `isURLUsingHTTPS ` function in that case. Or do you mean we should use something like `await resolveSelect('getSiteInfo')` which makes sure `homeURL` will be resolved?

**Comment by eugene-manuilov** [comment]
Ah... yes, sorry about that 🤦‍♂, you are right, IB ✔

**Comment by kelvinballoo** [comment]
### QA Update ✅ 

No console warning messages appeared when going through the SiwG setup and edit settings forms.
Moving ticket to approval.

<Details>
Setup form and view form:

https://github.com/user-attachments/assets/789c51a5-cf66-42ad-ae2d-4b288520c75f


Edit form:
![Image](https://github.com/user-attachments/assets/fe54c229-59e8-4136-bb34-93079e7ba365)


</Details>
