### ISSUE TITLE
Success notification is a subtle one in Figma but not on test site

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#9724]
## Bug Description

From the SiWG bug bash. Asana ticket can be found [here](https://app.asana.com/0/1208661003027471/1208774151662907/f).

In the [figma designs](https://www.figma.com/design/h9yGR15Pg2DUtgERW4AFAv/Sign-in-with-Google?node-id=31-1026&node-type=frame&t=OpZbZN67rJ0vYxol-0), the success notice when setting up SiWG is a subtle notification but currently in develop it’s a usual module notification.

![Image](https://github.com/user-attachments/assets/23426bd6-ab22-4025-8a20-b75a0af6a253)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The existing, "default" module connected notification shown after successfully connecting Sign in with Google (see screenshot, above) should _not_ be shown.
* A new subtle notification should be shown as per this [figma design](https://www.figma.com/design/h9yGR15Pg2DUtgERW4AFAv/Sign-in-with-Google?node-id=31-1026&node-type=frame&t=OpZbZN67rJ0vYxol-0) after a user successfully completes the setup for SiWG.
* Clicking on Maybe later should dismiss the notification.
* Clicking on Customize settings should take the user to the Settings Page with the SiWG view settings accordion tab open: `http://sitekit.10uplabs.com/wp-admin/admin.php?page=googlesitekit-settings#/connected-services/sign-in-with-google` 

## Implementation Brief

* The approach here should be similar to rendering the Ads module's simple `SetupSuccessSubtleNotification`.
* In `assets/js/components/notifications/BannerNotifications.js`, add the `sign-in-with-google` slug to the `MODULES_USING_SUBTLE_NOTIFICATIONS` array.
* In `assets/js/modules/sign-in-with-google/index.js`:
  * [x] Similar to the other notification already added, use `notifications.registerNotification()` to add a new notification. The values should be the same as the Ads (not PAX) subtle notification added in `assets/js/modules/ads/index.js` with the following changes:
    * Slug: `setup-success-notification-siwg`
    * Component: A new `SetupSuccessSubtleNotification` component that will be created below.
    * `viewContexts` should only be `VIEW_CONTEXT_MAIN_DASHBOARD`
    * `checkRequirements` should check if the `slug` query argument is `sign-in-with-google`.
* In `assets/js/modules/sign-in-with-google/components/dashboard`:
  * [x] Create a new `SetupSuccessSubtleNotification` component similar to  `assets/js/modules/ads/components/notifications/SetupSuccessSubtleNotification.js`:
    * [x] Change all the strings appropriately matching the Figma design in the AC.
    * [ ] Add a `<CTALinkSubtle>` component to the `additionalCTA` prop of the `SubtleNotification` component. Follow its usage similar to the RRMSetupSuccessSubtleNotification and link the user to the settings URL given in the AC. To get the settingsURL, use the `getAdminURL( 'googlesitekit-settings' )` selector on the `CORE_SITE` datastore and append the `#/connected-services/sign-in-with-google` to it.

### Test Coverage

* Add a storybook story but no new tests required as the logic here is already tested as part of the notifications API.

## QA Brief

* Set up sign in with google and verify the new subtle notification appears as per the figma mock.
* Also verify the standard notification GA events for the view, confirm (when clicking on Customize settings), dismiss (Maybe later) events.

## Changelog entry

* Update Sign in with Google setup success notification UI.

**Comment by jimmymadon** [comment]
@tofumatt Please could you assign me this if the AC and IB reviews go well as I have some stashed code ready to go here as well as some context on these notifications.

**Comment by tofumatt** [comment]
(ACs here are good, moving to IB.)

@jimmymadon The ACs and IB here look good, except the ACs should explicitly mention that the "default" setup notification that appears in the screenshot should _not_ appear.

I've added that to the ACs, which otherwise look good. Does anything need to be updated in the IB for that to work? Or is it good-to-go as-is?

**Comment by jimmymadon** [comment]
@tofumatt Thanks for pointing this out and updating the AC. I would've only found this out when testing and both of these appeared. But I've updated the IB to include the notification to the list of `MODULES_USING_SUBTLE_NOTIFICATIONS` which will prevent the default banner from showing! 😄

**Comment by tofumatt** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The existing, "default" module connected notification shown after successfully connecting Sign in with Google (see screenshot, above) is no longer shown.
- A new subtle notification is shown as per this [figma design](https://www.figma.com/design/h9yGR15Pg2DUtgERW4AFAv/Sign-in-with-Google?node-id=31-1026&node-type=frame&t=OpZbZN67rJ0vYxol-0) after a user successfully completes the setup for SiWG.
- Clicking on Maybe later dismisses the notification.
- Clicking on Customize settings takes the user to the Settings Page with the SiWG view settings accordion tab open
- The standard notification GA events for the view, confirm, dismiss events.


<details>
 <summary>Screenshots</summary>

![Image](https://github.com/user-attachments/assets/aa334799-c3aa-4e0a-a374-330047863b66)
![Image](https://github.com/user-attachments/assets/5e054be5-9644-40ce-9603-c5d3136ebcb2)
![Image](https://github.com/user-attachments/assets/bce6a60a-3b83-4d43-88b6-bec03a2e67e7)

</details>
