### ISSUE TITLE
Grammar error on SiWG set up CTA banner

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#9731]
## Bug Description

From the SiWG bug bash. Asana ticket can be found [here](https://app.asana.com/0/1208661003027471/1208794920366063/f).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* In the Sign in with Google CTA Setup banner:
  * Change "Boost onboarding, security, and trust on your site using Sign in with Google" to "Boost onboarding, security and trust on your site using Sign in with Google" (eg. remove Oxford Comma)
  * Change "Provide your site visitors with a simple, secure, and personalised experience by adding a Sign in with Google button to your login page" to "Provide your site visitors with a simple, secure and personalised experience by adding a Sign in with Google button to your login page" (eg. remove Oxford Comma)

## Implementation Brief

* [ ] Update the text in https://github.com/google/site-kit-wp/blob/c526e1fcfb775995e7dbc41699f2fd507f462cf6/assets/js/modules/sign-in-with-google/components/dashboard/SignInWithGoogleSetupCTABanner.js#L55
* [ ] Merge #9769

### Test Coverage

* No new tests needed.

## QA Brief

* Enable the `signInWithGoogleModule` feature flag and trigger the Sign in with Google CTA banner on the Site Kit dashboard (should appear on a site with data, eg. not showing the gathering data/zero data notifications).
* The text in the banner should not have a trailing comma/match the ACs.

## Changelog entry

* N/A

**Comment by eugene-manuilov** [comment]
IB ✔

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- In the Sign in with Google CTA Setup banner:
  - The title now reads as `Boost onboarding, security and trust on your site using Sign in with Google`
  - The description now reads as `Provide your site visitors with a simple, secure and personalised experience by adding a Sign in with Google button to your login page`

![Image](https://github.com/user-attachments/assets/ad2e4985-ba6d-454e-bb77-45f0d7d91556)
