### ISSUE TITLE
"Anyone can register" notice under settings is not full width

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#9732]
## Bug Description

From the SiWG bug bash. Asana ticket can be found [here](https://app.asana.com/0/1208661003027471/1208814101550413/f).

The "Users can create new accounts" disable notice is not full-width as shown in the Figma design, causing responsiveness issues, especially in smaller viewports.

![Image](https://github.com/user-attachments/assets/ca09e0b9-f34b-4e55-bc73-92a58d15706a)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The "Users can create new accounts" notice should be full-width (eg. stretch to the size of the parent container) on at least mobile/tablet viewports.
  * It's up to the implementer to make it full-width on larger screens as it may be better to limit the width eventually to improve line-length readability.

## Implementation Brief

* [ ] 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by benbowler** [comment]
@tofumatt @wpdarren  [I fixed this as a follow up QA PR here](https://github.com/google/site-kit-wp/pull/9755)
