### ISSUE TITLE
Incorrect redirect when clicking on 'Learn More' link in Connected Services

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#9734]
## Bug Description

From the SiWG bug bash. Asana ticket can be found [here](https://app.asana.com/0/1208661003027471/1208799946825728/f).

On the settings page, when clicking on "learn more" you are redirected to the One Tap section on the Google Developers website, however, you should be redirected to Site Kit's documentation. Site Kit's documentation should include a section on One Tap, which should include a link out to the One Tap Section on Google Developers page.

We'll need to change the in-product link to https://sitekit.withgoogle.com/documentation/using-site-kit/sign-in-with-google#one-tap/

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The learn more link for the One Tap setting is updated to lead to the following page: https://sitekit.withgoogle.com/documentation/using-site-kit/sign-in-with-google/#one-tap
* The URL should be defined as a learn more link with a slug of `sign-in-with-google-one-tap` using common documentation link infrastructure

## Implementation Brief

* [x] Update the learn more link URL in `OneTapToggle.js` 
* [x] Use `getDocumentationLinkURL` to generate the correct link for the slug defined in the AC

### Test Coverage

* N/A

## QA Brief

* Click the learn more link next to the Sign in with Google one tap toggle and confirm it links to the correct URL in the AC.

## Changelog entry

* Update learn more link in Sign in with Google module settings.

**Comment by aaemnnosttv** [comment]
@eugene-manuilov I'm reviewing this one now, but the IB here missed a mention of the infra to use for generating the right link. The AC should also include this detail regarding the doc ID to use/create.

I'll update it now but please be careful to follow the conventions we have for learn more and get help links.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The learn more link for the One Tap setting is updated to lead to the following page: `https://sitekit.withgoogle.com/documentation/using-site-kit/sign-in-with-google/#one-tap`

- The URL is defined as a learn more link with a slug of `sign-in-with-google-one-tap` using common documentation link infrastructure `https://sitekit.withgoogle.com/support?doc=sign-in-with-google-one-tap`
