### ISSUE TITLE
Always display the "Users can create new accounts" / "Anyone can register" status

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#9735]
## Bug Description

From the SiWG bug bash. Asana ticket can be found [here](https://app.asana.com/0/1208661003027471/1208798663755447/f).

While it's very useful to see the "Users can create new accounts" / "Anyone can register" status on the module view settings, it may lead to confusion for users when they try to edit this within SK, as the setting is removed. 

In some cases [a notice will appear ](https://i.imgur.com/Y41UAnS.png)regarding this setting (before clicking on "Edit"), but displaying this setting in the edit page I feel would be an improvement. 

We could do similar to what we do for GA/Google Ads, where the Enhanced Measurement setting is linked.

![Image](https://github.com/user-attachments/assets/23de76e7-d96f-43c0-b6e8-e4d54b77c317)

The below is how Enhance Measurement works within GA when it's configured at Ads level. For SiWG we could display a notice that "<Enabled / Disabled>: The Users can create new accounts" setting is configured from the "Anyone can register" setting". 

![Image](https://github.com/user-attachments/assets/3cd34a51-3073-4526-882d-055abd2b6b89)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The "Users can create new accounts" setting should be visible even when the users are editing Sign in with Google settings.
* The implementation should mirror the GA "Enhanced measurement is enabled" UI:

![Image](https://github.com/user-attachments/assets/37e89db9-446c-447d-8cfc-2ee5a539d7fa)

* The text should read "Users can create new accounts on this site using Sign in with Google" when open sign-ups are enabled
* The text should read "Only existing users can use Sign in with Google to access their accounts" when open sign-ups are disabled

## Implementation Brief

* [x] Update `assets/js/modules/sign-in-with-google/components/settings/SettingsForm.js`:
   * Use the `getAnyoneCanRegister` selector on `CORE_SITE` to get the "Anyone can register" setting value.
   * Add a new full width `Cell` at the bottom of the grid, below the `OneTapToggle`, using the `googlesitekit-settings-module__fields-group` div/class structure to format the text:
      * Within the `h4.googlesitekit-settings-module__fields-group-title`, the title should be "Users can create new accounts".
      * Within the `.googlesitekit-settings-module__meta-item`, wrapped in a `p` tag, return the relevant text in the AC, using the `__` function for translations, based on the value of `getAnyoneCanRegister` once resolved.

### Test Coverage

* Update VRT images for the settings view stories.

## QA Brief

* Set up Site Kit with `signInWithGoogleModule` feature flag enabled
* Setup the SiWG module and go to settings
  * When "Anyone can register" setting is disabled, a notice should show and match the [Figma design](https://www.figma.com/design/h9yGR15Pg2DUtgERW4AFAv/Sign-in-with-Google?node-id=248-1515&node-type=frame&t=aKwh4a4uUzKjrkuP-0)
  * When enabled notice should not show
* Click on edit, to expand the edit settings
  * When "Anyone can register" setting is disabled, it should show `Only existing users can use Sign in with Google to access their accounts.` text and notice should appear as per [figma design](https://www.figma.com/design/h9yGR15Pg2DUtgERW4AFAv/Sign-in-with-Google?node-id=1028-2846&node-type=frame&t=aKwh4a4uUzKjrkuP-0)
  * When enabled notice should not show, and text should be matching the [figma design](https://www.figma.com/design/h9yGR15Pg2DUtgERW4AFAv/Sign-in-with-Google?node-id=1026-2087&node-type=frame&t=aKwh4a4uUzKjrkuP-0)
* WP Settings link should take you to the WordPress general settings page
* When in multisite environment, link should take you to the network settings, and in notice, the mention of "Anyone can register" should be replaced with "Allow new registrations" 

## Changelog entry

* Always display the "Anyone can register" WordPress setting in Sign in with Google settings.

**Comment by benbowler** [comment]
IB written based on the AC, two thoughts:

1. Should this text have a header or other divider to split it from the One Tap toggle?
2. Should we include a [settings link as we do in the notification banner to allow users to easily find and change this setting](https://github.com/google/site-kit-wp/blob/6cba34a3c82b8205ebc2b621e398d8387a1b65fc/assets/js/modules/sign-in-with-google/components/settings/SettingsView.js#L90-L94).

**Comment by eugene-manuilov** [comment]
IB ✔

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- When `Anyone can register` setting is disabled, a notice shows and matches the [Figma design](https://www.figma.com/design/h9yGR15Pg2DUtgERW4AFAv/Sign-in-with-Google?node-id=248-1515&node-type=frame&t=aKwh4a4uUzKjrkuP-0)
- When enabled the notice does not show
- In Edit SIWG settings, when `Anyone can register` setting is disabled, it shows Only existing users can use Sign in with Google to access their accounts. text and notice should appear as per [figma design](https://www.figma.com/design/h9yGR15Pg2DUtgERW4AFAv/Sign-in-with-Google?node-id=1028-2846&node-type=frame&t=aKwh4a4uUzKjrkuP-0)
- When enabled the notice does not show, and text matches the [figma design](https://www.figma.com/design/h9yGR15Pg2DUtgERW4AFAv/Sign-in-with-Google?node-id=1026-2087&node-type=frame&t=aKwh4a4uUzKjrkuP-0)
- WP Settings links take you to the WordPress general settings page
- When in multisite environment, link takes you to the network settings, and in notice, the mention of `Anyone can register`  is replaced with `Allow new registrations`


<details>
 <summary>Screenshots</summary>

![Image](https://github.com/user-attachments/assets/bcdd1de4-1200-4bf8-a358-58f5b76d6613)
![Image](https://github.com/user-attachments/assets/60943436-d17b-4619-b01e-3289d7ea3d33)
![Image](https://github.com/user-attachments/assets/65992bc1-f866-4333-908a-5ad76be4c91b)
![Image](https://github.com/user-attachments/assets/2826b9b9-e172-4f1a-b0b7-254e243bf452)
![Image](https://github.com/user-attachments/assets/0c540873-3bc5-4b43-ba8f-596c783f32f9)
![Image](https://github.com/user-attachments/assets/86c7ac52-e877-4d8b-9aee-2dac08b3aee9)
![Image](https://github.com/user-attachments/assets/4cc511e2-ccb1-4f3c-b3f1-0c1069010914)
![Image](https://github.com/user-attachments/assets/ec20c629-bc28-4643-8675-417ca19471f9)
![Image](https://github.com/user-attachments/assets/109e6446-df7f-480d-94c5-38baebfab02f)

</details>
