### ISSUE TITLE
Learn more link on connect service page should go to SK documentation

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#9736]
## Bug Description

From the SiWG bug bash. Asana ticket can be found [here](https://app.asana.com/0/1208661003027471/1208781779069764/f).

The learn more link points to https://support.google.com/%23?hl=en-US which does not seem user friendly.  We should send the user directly to documentation on the SK side.

From @jamesozzie 

> The slug for this should be sign-in-with-google, which would mean the final URL would be:
https://sitekit.withgoogle.com/documentation/using-site-kit/sign-in-with-google/

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Learn More link on the Connect Service screen for Sign in with Google should point to: `https://sitekit.withgoogle.com/support?doc=sign-in-with-google`
* The link should redirect to `https://sitekit.withgoogle.com/documentation/using-site-kit/sign-in-with-google/` 

## Implementation Brief

The below small change has been made in the PR attached to this issue. So this can be moved straight to CR if the ACs and IB here look good.

* [x] In `assets/js/modules/sign-in-with-google/components/setup/SetupForm.js`, use the `getDocumentationLinkURL` selector with `'sign-in-with-google'` as the slug argument. Instead of using the `<SupportLink>` component, use the `<Link>` component to render the above obtained URL.

### Test Coverage

* No new tests required.

## QA Brief

* On a site with HTTPS enabled, try to Connect the Sign in with Google module from the Settings "Connect more services" tab. Verify the `Learn more` link in the Setup Form is as per the AC.

## Changelog entry

* N/A

**Comment by eugene-manuilov** [comment]
AC + IB ✔

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The Learn More link on the Connect Service screen for Sign in with Google points to: `https://sitekit.withgoogle.com/support?doc=sign-in-with-google`
- The link redirects to `https://sitekit.withgoogle.com/documentation/using-site-kit/sign-in-with-google/`

Note: the URL currently 404s due to us not yet pushing the documentation live to production.  

We will test this as part of our final testing for SiWG. 

![Image](https://github.com/user-attachments/assets/4ffa5359-f854-44e3-b108-a487452767b0)
