### ISSUE TITLE
Inconsistent sizing of beta and new badges

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#9737]
## Bug Description

From the SiWG bug bash. Asana ticket can be found [here](https://app.asana.com/0/1208661003027471/1208768495540765/f).

The beta badge and new badges which SiwG has both of show different sizes, we should make these consistent. 

![Image](https://github.com/user-attachments/assets/fa638a05-1687-4980-847c-3b78a687809b)

![Image](https://github.com/user-attachments/assets/c46c43a1-499e-4301-b592-118172b6c8fd)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The beta and new badges should have consistent styling (padding, line height and font size). 

## Implementation Brief

* [x] Standardise the line heigh and padding on both the badges. 
  * [x] In `assets/sass/components/global/_googlesitekit-badge.scss`, update the line-height to be `$lh-label-sm`
  * [x] In `assets/sass/components/global/_googlesitekit-new-badge.scss`, remove the font-size, padding and line-height properties as these will fall back to the `googlesitekit-badge` styles above.

### Test Coverage

* VRTs will need to be updated.

## QA Brief

* Set up Site Kit with the `signInWithGoogleModule` feature flag enabled
* Validate that the "New" and "Beta" badges are consistent in size in all areas of the plugin related to Sign in With Google

## Changelog entry

* N/A

**Comment by tofumatt** [comment]
ACs and IB here both look good 👍🏻 

(Since this requires a VRT update I'm bumping this to a 7 estimate, but it likely won't take that long.)

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The beta and new badges now have consistent styling (padding, line height and font size).

https://github.com/user-attachments/assets/612e01c9-3c28-44fc-bf2e-1cb862a684f9
