### ISSUE TITLE
Sign in with Google is getting translated

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#9738]
## Bug Description

From the SiWG bug bash. Asana ticket can be found [here](https://app.asana.com/0/1208661003027471/1208796073855878/f).

Like all other modules we shouldn't have Sign in with Google translated within the plugin.  

You can see an example here where it's translated to Spanish 

![Image](https://github.com/user-attachments/assets/1c7369ad-9e69-4e43-8d10-662982961255)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `Sign in with Google` Module name should be consistently translated in the plugin, using `"Service name"` as a comment.

## Implementation Brief

* [ ] Update all standalone `__( 'Sign in with Google', 'google-site-kit' )` instances to use `_x( 'Sign in with Google', 'Service name', 'google-site-kit' )`, eg:
  * [ ] https://github.com/google/site-kit-wp/blob/3fe82ad5b47e2c2a1a0796258f6bba9736cb1250/assets/js/components/legacy-setup/SetupUsingGCP.js#L345
  * [ ] https://github.com/google/site-kit-wp/blob/3fe82ad5b47e2c2a1a0796258f6bba9736cb1250/assets/js/components/legacy-setup/wizard-step-authentication.js#L112
  * [ ] https://github.com/google/site-kit-wp/blob/3fe82ad5b47e2c2a1a0796258f6bba9736cb1250/assets/js/components/setup/SetupUsingProxyWithSignIn.js#L410
  * [ ] https://github.com/google/site-kit-wp/blob/3fe82ad5b47e2c2a1a0796258f6bba9736cb1250/assets/js/components/ViewOnlyMenu/Description.js#L122
* [ ] Update other instances of "Sign in with Google" to be standalone, non-translated `_x()` strings that are interpolated (with `sprintf()` or similar) into strings, like `sprintf( __( '%s failed', 'google-site-kit' ), _x( 'Sign in with Google', 'Service name', 'google-site-kit' ) )`:
  * [ ] https://github.com/google/site-kit-wp/blob/3fe82ad5b47e2c2a1a0796258f6bba9736cb1250/includes/Modules/Sign_In_With_Google.php#L140
  * [ ] https://github.com/google/site-kit-wp/blob/3fe82ad5b47e2c2a1a0796258f6bba9736cb1250/includes/Modules/Sign_In_With_Google.php#L345-L377
  * [ ] https://github.com/google/site-kit-wp/blob/3fe82ad5b47e2c2a1a0796258f6bba9736cb1250/includes/Modules/Sign_In_With_Google.php#L445
  * [ ] https://github.com/google/site-kit-wp/blob/3fe82ad5b47e2c2a1a0796258f6bba9736cb1250/includes/Modules/Sign_In_With_Google.php#L521

### Test Coverage

* No new tests needed, and VRTs should not need updating from this change.

## QA Brief

* Ensure the `signInWithGoogleModule` feature flag is enabled
* Go through Sign in with Google setup and ensure no errors are encountered.

## Changelog entry

* Ensure Sign in with Google translations are consistent.

**Comment by tofumatt** [comment]
ACs are good, moving to IB 🙂

**Comment by eugene-manuilov** [comment]
@tofumatt, looks like your CL contains much more than needed after changing the base branch to main. If we need to merge it into main, then let's probably create a copy of your changes using a new branch based off of main. Could you please check it?

**Comment by tofumatt** [comment]
@eugene-manuilov Whoa, thanks. I'm guessing GitHub pulled `develop` in somehow, I have no clue why, but I'll update the branch or make a new PR. Thanks 😓

**Comment by tofumatt** [comment]
@eugene-manuilov I've opened a new PR at #9873. Sorry about that 😓

**Comment by wpdarren** [comment]
### QA Update: ✅ 

Verified:

- Went through the Sign in with Google setup and ensure no errors are encountered.
- Will do some more thorough testing including with different languages as part of our final testing next week.
