### ISSUE TITLE
Change label for the Anyone can register WP setting

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#9741]
## Bug Description

From the SiWG bug bash. Asana ticket can be found [here](https://app.asana.com/0/1208661003027471/1208809127149606/f).

In figma, there is a field 'Anyone can register WP setting'

In the current implementation, it's "users can create new accounts".

<img width="1732" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNy9ZQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e161680121e537e3cfaafe5b37ec09e1d92183a0/image.png" alt="image.png" />

From @tofumatt 
> "users can create new accounts" is definitely the right label to go with.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* [ ] 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by tofumatt** [comment]
This is already correct in the code; the Figma design is wrong, so closing as a won't fix 🙂
