### ISSUE TITLE
When disconnecting SiWG and re-connecting, a new Client ID is created and the old one remains

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#9744]
## Bug Description

When disconnecting and re-connecting the SiWG module, a new Client ID is created and the old one remains.  

From @tofumatt 
> I guess it could be nice if the service had a way to detect an existing client ID for the site and offer it, but at the same time it's valid to reuse a Client ID. I guess the best option is we persist the client ID between disconnections. In fact, I thought I specified this in the design doc/issue, but maybe not. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When the module is deactivated and then re-activated again, the client ID setting remains the same as it was set before deactivation.

## Implementation Brief

* [x] Update the `Sign_In_With_Google::on_deactivation` method to reset all settings but client ID to its defaults instead of deleting settings. To do that, we need the following:
  * Get the current client ID setting into a temporary variable.
  * Delete settings as it is done now.
  * Then get settings again, it should return default settings.
  * Set client ID in the default values using the aforementioned temporary variable.
  * Merge updated settings back into module settings using the `merge` method. 

### Test Coverage

* Implement a phpunit test that verifies this behavior.

## QA Brief

* Testing when no client ID was set: On a site where SiwG is not setup, go to the setup form but do not enter the client ID / save the form. Exit the setup incomplete. Now go to Settings and disconnect the SiwG module (incomplete module setup for SiwG). Go back to settings and attempt to set up the module again from the Connect More services tab. The setup form should have a blank Client ID since no client ID was saved before the module was disconnected.
* Testing persisting client ID: Now enter a client ID and complete setup. Then disconnect the module. Now try to set up the module. Verify that the old client ID entered was prefilled along with some new helper text. Test the validation by removing the text. Now save a new client ID.
* Once again disconnect the module and go back to setting it up again. Check that the new Client ID that was updated before disconnection was now prefilled.

## Changelog entry

* Update the Sign in with Google module to suggest using the previous client ID when re-connecting the module.

**Comment by jimmymadon** [comment]
@eugene-manuilov @tofumatt After implementing the IB, there is an issue where the Client ID is prefilled on the Setup Form page (which is great), but the `hasSettingsChanged` validation fails not allowing the user to reuse the old client ID. The ACs here might need to be updated to handle the case of an old Client ID being found better? 

I have pushed my small changes and a WIP PHP unit test and I can get back to this issue tomorrow but if someone else wants to pick this up today, please feel free to unassign me. c.c. @binnieshah

**Comment by eugene-manuilov** [comment]
@jimmymadon, good finding, we didn't account for it 🤔. I think in this case, we probably need to introduce a new setting `_clientID` in the settings class that should be set on deactivation and then when user opens the setup form, this value should be used to pre-set the new `clientID` value.

**Comment by wpdarren** [comment]
### QA Update: ⚠ 

@jimmymadon Generally, this is working well but I wanted to highlight weird UX/UI behaviour.   So, I have entered a Client ID and then disconnected the module.  The previous client ID was displayed as expected with the message underneath.  I am unable to delete the client ID though, when I get to the last character the client ID reappears.  I can type over the ID but its a weird experience.  What do you think about this?  Screencast below. 



**Verified:**

Working through the QAB I can confirm the following:
- The setup form has a blank Client ID since no client ID was saved before the module was disconnected.
- When entering a client ID and complete setup, then disconnecting the module, I can confirm that the old client ID entered was pre-filled along with some new helper text. Test the validation by removing the text. I was able to save a new client ID.
- Disconnected the module and went back to setting it up again. Check that the new Client ID that was updated before disconnection was now pre-filled.

**Comment by kelvinballoo** [comment]
### QA Update ✅ 

I can confirm that I can delete the client ID and I don't face the weird UX issues raised earlier.

Other than that, I can still confirm the previously tested items:
- The setup form has a blank Client ID since no client ID was saved before the module was disconnected.
- When entering a client ID and complete setup, then disconnecting the module, I can confirm that the old client ID entered was pre-filled along with some new helper text. Test the validation by removing the text. I was able to save a new client ID.
- Disconnected the module and went back to setting it up again. Check that the new Client ID that was updated before disconnection was now pre-filled.

<Details>
Blank client ID as expected.

https://github.com/user-attachments/assets/cc67e7bc-c43d-4f84-9a17-8e496c9ec71b

Able to save, validation works, can delete the client ID.

https://github.com/user-attachments/assets/07b56c92-0765-410a-8161-ad023698ed4a

Saving new client ID works well.

https://github.com/user-attachments/assets/abe55f87-6af0-4757-9810-35a9b52464bd

</Details>
