### ISSUE TITLE
Add GA Events to SiwG Module

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#9747]
## Feature Description

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Analytics events should be added for actions in the Sign in with Google module outside of the existing events common to all modules in Site Kit.
* Add [events listed in the GA Events document](https://docs.google.com/spreadsheets/d/1eEuJ2ppVZuai1_hL77RA2vL7DUidM_qCnvTsjxZ_S4k/edit?gid=925918307#gid=925918307&range=B458:B462) to the [Sign in with Google CTA setup component](https://github.com/google/site-kit-wp/blob/6bf442a71aa4977156788c6705aa582b7ee1e441/assets/js/modules/sign-in-with-google/components/dashboard/SignInWithGoogleSetupCTABanner.js#L41).
* Add [events listed in the GA Events document](https://docs.google.com/spreadsheets/d/1eEuJ2ppVZuai1_hL77RA2vL7DUidM_qCnvTsjxZ_S4k/edit?gid=925918307#gid=925918307&range=D463:D467) to the components in the [Sign in with Google CTA settings edit](https://github.com/google/site-kit-wp/blob/6bf442a71aa4977156788c6705aa582b7ee1e441/assets/js/modules/sign-in-with-google/components/settings/SettingsForm.js#L33).

## Implementation Brief

**Setup CTA**

* [x] Update `assets/js/modules/sign-in-with-google/index.js#L100`, change the notification id to `sign-in-with-google-setup-cta`, once this is changed, the `useNotificationEvent` hook will handle all analytics events:
   https://github.com/google/site-kit-wp/blob/953c00ebd885d4711f04e26baf99992d6ec4ff4a/assets/js/googlesitekit/notifications/hooks/useNotificationEvents.js#L55-L64

**Settings**

 * [x] Update `assets/js/modules/sign-in-with-google/components/common/ButtonShapeSelect.js`, `https://github.com/google/site-kit-wp/blob/953c00ebd885d4711f04e26baf99992d6ec4ff4a/assets/js/modules/sign-in-with-google/components/common/ButtonThemeSelect.js` and  `assets/js/modules/sign-in-with-google/components/common/ButtonTextSelect.js`:
    * Wrap a call to the `trackEvent` in the `useDebounce` hook with a `500` millisecond delay, track the events `change_button_shape`, `change_button_theme` and `change_button_text` in the respective components to the category `{viewContext}_sign-in-with-google-settings`.
    * Update the onChange callbacks in each of these components to call the debounced track event function *only if the value has changed*.

* [x] Update `assets/js/modules/sign-in-with-google/components/common/OneTapToggle.js`, creating a new callback function which should call `setOneTapEnabled`.
   * If `oneTapEnabled` is `true`, trigger the event `enable_one_tap` to the category `{viewContext}_sign-in-with-google-settings`.
   * If `oneTapEnabled` is `false`, trigger the event `disable_one_tap` to the category `{viewContext}_sign-in-with-google-settings`.

### Test Coverage

* No additional test coverage required.

## QA Brief

* Set up a new instance of Google Site Kit with the `signInWithGoogle` feature flag enabled, ensure internal tracking is enabled during setup
* Install a suitable extension for tracking GTag events, such as [Tag Assistant Companion](https://chromewebstore.google.com/detail/tag-assistant-companion/jmekfmbnaedfebfnmakmokmlfpblbfdm?hl=en&pli=1) and connect the companion to your test site 
* Navigate to the main Site Kit dashboard
* Observe the Sign in with Google setup CTA banner within the main dashboard, and validate that events are tracked for the following instances:
    * The SiWG Setup CTA Banner is viewed
        * A `view_notification` event is fired with category `mainDashboard_sign-in-with-google-setup-cta` 
    * The "Learn more" link is clicked
        * A `click_learn_more_link` event is fired with category `mainDashboard_sign-in-with-google-setup-cta`
    * The "Maybe later" CTA button is clicked
        * A `dismiss_notification` event is fired with category `mainDashboard_sign-in-with-google-setup-cta` 
    * The "Set up Sign in with Google" CTA button is clicked
        * A `confirm_notification` event is fired with category `mainDashboard_sign-in-with-google-setup-cta` 
* Proceed to set up Sign in with Google
* Once set up, navigate to `Site Kit > Settings`, expand the `Sign in with Google` module settings and click `Edit` to expose the edit view
* Perform the following settings changes and validate that the appropriate events are fired:
    * The `Button text` option is changed
        * A `change_button_text` event is fired with category `settings_sign-in-with-google-settings` 
    * The `Button theme` option is changed
        * A `change_button_theme` event is fired with category `settings_sign-in-with-google-settings` 
    * The `Button shape` option is changed
        * A `change_button_shape` event is fired with category `settings_sign-in-with-google-settings` 
    * The `Enable one tap sign in` control is toggled
        * An `enable_one_tap` event is fired with category `settings_sign-in-with-google-settings` when the toggle is active/on
        * A `disable_one_tap` event is fired with category `settings_sign-in-with-google-settings` when the toggle is inactive/off

Following is a series of screenshot showing the various evens as captured by Tag Assistant Companion:

<details>

![Image](https://github.com/user-attachments/assets/f69d5ef5-f9f6-491d-9072-ac8d5ca620d7)

![Image](https://github.com/user-attachments/assets/7f6f9539-e89c-4978-8d2c-3dd556c701e5)

![Image](https://github.com/user-attachments/assets/7ac81c1f-4ee1-4d03-aea8-4976f326d072)

![Image](https://github.com/user-attachments/assets/501d9f08-06f3-44e3-b194-b517e85de238)

![Image](https://github.com/user-attachments/assets/5c1f24e0-f385-430f-88b4-5c082967d452)

![Image](https://github.com/user-attachments/assets/c564fbee-dcb8-4c8e-b16d-2707c9f28180)

![Image](https://github.com/user-attachments/assets/4dd27b5a-27c0-42f2-9f05-f4ef884d5316)

![Image](https://github.com/user-attachments/assets/3f025ee4-f8be-49d2-9054-5d33d2f65e97)

![Image](https://github.com/user-attachments/assets/db8e2f48-0059-4dc7-89ac-4ccbe87e4290)

</details>

## Changelog entry

* Add Analytics events to Sign in with Google.

**Comment by eugene-manuilov** [comment]
> [ ]
> [ ] Update `assets/js/googlesitekit/notifications/components/common/ActionsCTALinkDismiss.js`, adding a new optional callback prop, `onDismissClick`.
> 
> 
> * [ ] 
>   [ ]  Update `assets/js/modules/sign-in-with-google/components/dashboard/SignInWithGoogleSetupCTABanner.js` to track the following events with the `trackEvent` function in the `{viewContext}_sign-in-with-google-cta` category:
>   
>   * Use a `useEffect`, with an empty dependencies array, to call `view_notification`.* Create a new callback function `setupActivate` to call `confirm_notification` and call the `onSetupActivate` function.
>     
>     * Update the `onCTAClick` prop on `ActionsCTALinkDismiss` to call this new callback.* Create a new callback function `setupDismiss` to call `dismiss_notification`.
>     
>     * Use the new `onDismissClick` prop on `ActionsCTALinkDismiss` to call this callback.
> 
> [ ]
> [ ] Update `assets/js/modules/sign-in-with-google/index.js#L100`, change the notification id to `sign-in-with-google-cta`, once this is changed, the `useNotificationEvent` hook will handle trigger the learn more link click event automatically:

@benbowler, isn't it already automatically tracked in the new notification components? See how `useNotificationEvents` is used there. @jimmymadon am i right?

**Comment by jimmymadon** [comment]
@eugene-manuilov Correct, all 4 events for the Setup CTA Banner have already been implemented (automatically as part of the new notifications infrastructure).

@tofumatt Currently, the event category for the SiwG Setup CTA Banner is set to be `view_context_setup-cta-siwg`. This follows the `view_context_notification-id` format. The notification ID here was set to `setup-cta-siwg` only because other "setup success" notifications were set to `setup-success-notification-<module_name>`. However, the [event categories in the spreadsheet](https://docs.google.com/spreadsheets/d/1eEuJ2ppVZuai1_hL77RA2vL7DUidM_qCnvTsjxZ_S4k/edit?gid=925918307#gid=925918307&range=B458:B462) are different to this pattern but are consistent with the other settings event categories for SiwG. So which ones should we go for?

@benbowler Depending on @tofumatt 's answer above, we can simply update the notification ID to `sign-in-with-google-cta` instead of the existing ID:

https://github.com/google/site-kit-wp/blob/673e5effd5369c1fbb474cddd35e5d73844bebb7/assets/js/modules/sign-in-with-google/index.js#L100

**Comment by eugene-manuilov** [comment]
Assigning to @tofumatt to review Jimmy's comment and IB.

**Comment by tofumatt** [comment]
Going with the `view_context_notification-id` format seems more consistent to me, let's go with that.

@benbowler: I don't think there's anything else here that's needed based on the comments from @eugene-manuilov and @jimmymadon, right? 🤔

**Comment by jimmymadon** [comment]
@tofumatt We still have to add the events for the Settings components which is the second part of @benbowler's IB. 

@benbowler After speaking to @tofumatt on Slack, the notification ID should be updated to be consistent with `<module-name>-<component-name>`. So lets change the notification ID on the line below to be `sign-in-with-google-setup-cta`. I have updated the Excel sheet categories to reflect the addition of the word `setup`.

https://github.com/google/site-kit-wp/blob/673e5effd5369c1fbb474cddd35e5d73844bebb7/assets/js/modules/sign-in-with-google/index.js#L100

(Since the SiwG Setup CTA banner is the first of its kind as part of the new notification's infrastructure, there is no real convention for Setup CTA notification IDs as yet. Similar other notifications have a convention of `<component-notification-name>-<module-name>` for the notification ID, but it isn't always consistent. It doesn't really matter what notification ID we use as long as it doesn't change after release.)

**Comment by benbowler** [comment]
Thanks @jimmymadon, I've updated the IB so this should be good to review.

**Comment by jimmymadon** [comment]
@benbowler Assigning @eugene-manuilov back here as he did the original IB review 🙂

**Comment by eugene-manuilov** [comment]
Thanks. IB ✔

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- Analytics events are added for actions in the Sign in with Google module.
- Went through the QAB, and ensured that all events were being fired when action is completed. 

<details>
 <summary>Screenshots</summary>

![Image](https://github.com/user-attachments/assets/726e5224-3635-4ba5-a69a-0770bfbfc72a)
![Image](https://github.com/user-attachments/assets/de82357b-88d1-4817-b885-e5a8efc8a34f)
![Image](https://github.com/user-attachments/assets/6c1e0957-e28e-4e93-9b87-2d3e3ade591b)
![Image](https://github.com/user-attachments/assets/cb5d4378-dcf7-44d7-b7fa-915f946bc399)
![Image](https://github.com/user-attachments/assets/c744cb79-28e4-4288-9d71-ac37af97afef)
![Image](https://github.com/user-attachments/assets/cb7384fd-0bfe-455c-b790-a2b9143983ea)
![Image](https://github.com/user-attachments/assets/9887dacf-a7b6-41b1-83c1-bee74a3b66fd)
![Image](https://github.com/user-attachments/assets/a5f6ecf4-c129-4b59-9db9-03ce55fc70a5)
![Image](https://github.com/user-attachments/assets/29cfde82-d265-462c-ad44-138c75279955)


</details>
