### ISSUE TITLE
Fix fatal error with AMP Plugin versions < 1.2

### ISSUE THREAD

**Issue by ThierryA** [google/site-kit-wp#975]
## Bug Description

Site Kit cause a `Fatal error: Uncaught Error: Call to undefined method AMP_Theme_Support::get_support_mode()` for users with AMP Plugin version lower that 1.2 in which `get_support_mode()` function was added.

## Steps to reproduce

Install AMP plugin version older than 1.2 and activate Site Kit.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Ensure there is not fatal error with AMP Plugin versions < 1.2, for `get_support_mode()` function and other properties we are using from the AMP plugin.

## Implementation Brief

* Merge #977 (see notes on PR).

## Changelog entry

* Fix compatibility issues with older versions of the AMP plugin.

**Comment by aaemnnosttv** [comment]
## QA ✅ 

* Confirmed fatal with AMP 1.1.3 and Site Kit 1.1.3
* Confirmed fatal no longer occurs with AMP 1.1.3 and Site Kit develop
* Confirmed AMP latest works with Site Kit develop
* Confirmed `ampMode` with AMP 1.1.3 and latest:
    - Native/Standard: `primary`
    - Transitional: `secondary`
    - Reader: `secondary`
