### ISSUE TITLE
Enhance Jest stability

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#9760]
## Feature Description

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Jest tests should pass more consistently

## Implementation Brief

* Review & merge https://github.com/google/site-kit-wp/pull/9748
* Revert temporary changes to workflows

### Test Coverage

* No changes

## QA Brief

* No QA needed.

## Changelog entry

* N/A

**Comment by tofumatt** [comment]
Moving directly to Approval as no QA is needed here.
