### ISSUE TITLE
Pagespeed Insights: use newer API endpoint

### ISSUE THREAD

**Issue by adamsilverstein** [google/site-kit-wp#978]
## Feature Description

Site kit should switch to using the newer Pagespeed Insights API URL that fully supports the OAuth authentication used in the plugin.  The PHP client should set the new base URL for PSI requests.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
Hey @adamsilverstein can you elaborate on this one? The PageSpeed Insights module works just fine with the current oAuth authentication; which endpoint are you referring to?

**Comment by adamsilverstein** [comment]
Yes @aaemnnosttv I'll add some details in the AC/IB - long story short is the current endpoint serving PSI data doesn't support OAuth - although our data requests work fine now, to fully switch over to OAuth based authentication for PSI, we need to use the newer API endpoint (which has a different URL prefix).

**Comment by exterkamp** [comment]
Update: we were able to rollout OAuth support to the old endpoint much earlier than we thought. So OAuth should work on the current endpoint (`www.googleapis.com/pagespeedonline/v5/*`) as well as (`pagespeedonline.googleapis.com/pagespeedonline/v5/*`).

Sorry for the back and forth on this! 😄

**Comment by adamsilverstein** [comment]
@exterkamp Excellent, thanks for the update.

Closing this issue as we no longer need to change this URL.
