### ISSUE TITLE
Missing "Top Pages by Returning Visitors" Metric for "Provide Services" Purpose with 'conversionReporting' Feature Flag Enabled

### ISSUE THREAD

**Issue by mohitwp** [google/site-kit-wp#9786]
## Bug Description

I noticed that if the `'conversionReporting' `feature flag is enabled and the user selects the purpose “Provide Services”, only seven metrics are displayed instead of eight. Upon comparing with the AC metrics list, I found that the “Top Pages by Returning Visitors” metric tile is missing. Additionally, this metric tile is also absent from the tailored metric suggestions.

## Steps to reproduce

1. Enable `'conversionReporting' `feature flag.
2. Set up SK with analytics.
3. Setup KM using tailored metrics.
4. Select purpose 'Provide services'
5. Compared metric tiles.

## Screenshots

![Image](https://github.com/user-attachments/assets/b2ce4a83-646a-4ad1-ae54-e0b3650fee03)

![Image](https://github.com/user-attachments/assets/1232c026-6a6f-4d3d-872b-0d258bab82b3)

![Image](https://github.com/user-attachments/assets/11f74984-ca6f-42ea-8b79-672e454a3245)

## Additional Context

 - PHP Version: 
 - Browser: [e.g. chrome, safari]
 - Plugin Version: [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When Key Metrics is setup using the tailored option, and the `conversionReporting` feature flag is enabled, the "op Pages by Returning Visitors" metric should show when the site purpose answer is "Provide Services".

## Implementation Brief

* [ ] Edit the `getConversionTailoredKeyMetricsWidgetIDs` selector within `assets/js/googlesitekit/datastore/user/key-metrics.js`
    * [ ] Within the array attached to property `provide_services`, append the `KM_ANALYTICS_TOP_RETURNING_VISITOR_PAGES` widget to the list of returned items.

### Test Coverage

* Update the datastore tests at `assets/js/googlesitekit/datastore/user/key-metrics.test.js`
    * Correct the expected array of data within the `should return the correct metrics for the %s purpose` test for the `provide_services` ACR metrics case when the value is `provide_services`

## QA Brief

* Set up Site Kit with GA4 connected and the `conversionReporting` feature flag enabled
* Set up tailored Key Metrics using the `Provide services` purpose option, by actioning the tailored metrics CTA from the KMW setup banner in the main dashboard, or by answering the user input questionnaire from `Site Kit > Settings > Admin > Key Metrics`
* Validate that the `Top pages by returning visitors` widget is now present in the list of KMW's as per the image below
![Image](https://github.com/user-attachments/assets/dc567b54-f09d-4afd-98c5-670201fb35e0)
* Note that the 8x metrics may change based on GA4 events detected via your connected account, and you may see less than 8, or a different selection than the above

## Changelog entry

* N/A

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- When Key Metrics is setup using the tailored option, and the `conversionReporting` feature flag is enabled, the `Pages by Returning Visitors` metric shows when the site purpose answer is `Provide Services`.
- Checked that the `Pages by Returning Visitors` metric appears in the selection panel and it can be enabled and disabled. 
- Checked that when the purpose was changed in Site Kit settings from `Selling Products` to `Provide Services` that the `Pages by Returning Visitors` metric appears.

![Image](https://github.com/user-attachments/assets/4216537a-e4eb-42bb-91bd-c602dfe09a0f)
