### ISSUE TITLE
AdSense should use `amp-story-auto-ads` tag for AMP stories

### ISSUE THREAD

**Issue by adamsilverstein** [google/site-kit-wp#979]
## Bug Description

When using the [AMP for WP](https://wordpress.org/plugins/amp/) plugin to create an **AMP Story**, the story shows an AMP validation error (and Auto-ads do not work in AMP)

## Steps to reproduce

1. Create an AMP Story  
2. Safe as a draft
3. Reload the editor or check AMP->Validation to see error:

![image](https://user-images.githubusercontent.com/2676022/70812259-7f7cdf00-1d84-11ea-8350-58ddaa1a5bf8.png)

The issue is the `amp-auto-ads` tag - inside an amp story, this needs to be a `amp-story-auto-ads` tag.

According to @westonruter:

instead of outputting:
```
<amp-auto-ads type="adsense" data-ad-client="ca-pub-5439573510495356">
</amp-auto-ads>
```
on an AMP Story it instead needs to output something like:
```
<amp-story>
  <amp-story-auto-ads>
    <script type="application/json">
      {
         "ad-attributes": {
           "type": "doubleclick",
           "data-slot": "/30497360/a4a/amp_story_dfp_example"
         }
       }
    </script>
  </amp-story-auto-ads>
  ...
</amp-story>
```

## Additional Context

 - PHP Version: 7.3
 - OS: iOS
 - Browser: Chrome
 - Plugin Version 1.1.3
 - Device: Mac

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Site Kit must not output an `amp-auto-ads` tag inside of AMP stories.

## Implementation Brief

* check that `! is_singular( 'amp_story' )` after `Context::is_amp()`, and otherwise bail
    * in `AdSense::output_adsense_script()`
    * in `AdSense::amp_content_add_auto_ads()`

## Changelog entry

* Do not render `amp-auto-ads` element in AMP stories because it is invalid in that context.

**Comment by westonruter** [comment]
> When using the [AMP for WP](https://wordpress.org/plugins/accelerated-mobile-pages/) plugin to create an **AMP Story**

This is not the right plugin. I assume you meant https://wordpress.org/plugins/amp/ ?

**Comment by adamsilverstein** [comment]
Haha! Oops, I mistakenly copied that URL from another issue. Thanks for catching that!

**Comment by felixarntz** [comment]
@westonruter It appears that `amp-story-auto-ads` doesn't work with AdSense yet, only with Ad Manager (DoubleClick). In this case, all we can do here is prevent output of the `amp-auto-ads` tag if in a story I assume?

**Comment by westonruter** [comment]
Yes, I suppose so.

**Comment by aaemnnosttv** [comment]
@felixarntz for `AdSense::is_amp_story()` could we not just use `is_singular( 'amp_story' )` ?

**Comment by felixarntz** [comment]
@aaemnnosttv Good point 😄 I updated the IB.

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by cole10up** [comment]
**Tested**
Setup AMP stories. Set up Adsense auto ads. Created a AMP story, added tags, saved published, deleted.

![Stories ‹ Maximum Osprey — WordPress (1)](https://user-images.githubusercontent.com/57115907/73007193-f3b59400-3dc0-11ea-9e53-1c139d2e53fa.gif)

Passed QA ✅
