### ISSUE TITLE
`ReaderRevenueManagerSetupCTABanner` Incorrect Heading Weight & Inconsistent CTA Button Spacing

### ISSUE THREAD

**Issue by 10upsimon** [google/site-kit-wp#9807]
## Bug Description

The Reader Revenue Manager Setup CTA Banner contains a heading weight that is heavier than other setup banners, and the spacing between the primary and secondary CTA banners is larger than other setup banners. The screenshot that follows shows this banner alongside another (correct) banner:

<img width="1504" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3orQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--438e219d4c3e5f3807daca5a6200964337418260/image.png" alt="image.png" />

## Steps to reproduce

1. Set up a brand new instance of Site Kit
2. Observe the RRM Setup CTA banner alongside the SiWG banner
3. Note the difference in heading weight and CTA button spacing

## Additional Context

 - PHP Version: 
 - Browser: [e.g. chrome, safari]
 - Plugin Version: [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

_Note that the button spacing should be updated as per the AC for https://github.com/google/site-kit-wp/issues/9600_

* 

## Implementation Brief

* [ ] 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jimmymadon** [comment]
This issue should be fixed as part of #9675. As such, I am not going to add ACs here.

**Comment by aaemnnosttv** [comment]
@jimmymadon is this okay to close out now?

**Comment by jimmymadon** [comment]
@aaemnnosttv Yes, closing this in favour of #9675.
