### ISSUE TITLE
AMP E2E tests are having SSL certificate issue

### ISSUE THREAD

**Issue by zutigrm** [google/site-kit-wp#9810]
## Feature Description

AMP E2E tests are having SSL certificate issue in CI 

> Error: Can't find the requested plugin's version 1.5.5 in the [WordPress.org](http://wordpress.org/) plugin repository (cURL error 60: SSL certificate problem: unable to get local issuer certificate).

For example it can be seen here https://github.com/google/site-kit-wp/actions/runs/12138941348/job/33845455830

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* E2E environment provisioning should be updated to install the AMP plugin without SSL certificate verification if it fails to install by default

## Implementation Brief

* Merge #9817

### Test Coverage

* No changes

## QA Brief

* No QA to do – it can be verified in CR

## Changelog entry

* N/A

**Comment by aaemnnosttv** [comment]
Nothing to QA here – moving to Approval.
