### ISSUE TITLE
Sign in with Google CTA notification (needlessly) grows in height on wide screens

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#9824]
## Bug Description

The Sign in with Google CTA notification should not grow in height as the viewport it's being displayed on grows wider.

## Steps to reproduce

1. Set up a site on an HTTPS site
2. Ensure the `signInWithGoogleModule` feature flag in enabled
3. Visit the dashboard and see the Sign in with Google CTA notififcation
4. Use a wide viewport (eg. `1800px` or wider) and observe the notification is needlessly tall

## Screenshots

![Image](https://github.com/user-attachments/assets/93d0af5d-6e2e-4132-ba64-90f926c084b8)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Sign in with Google CTA notification should not grow in height as the viewport it's being displayed on grows wider.
* The notification should be sized to fit all text; the image on the right can be cut off by the bounds of the notification

## Implementation Brief

* [ ] Update `assets/sass/components/sign-in-with-google/_googlesitekit-sign-in-with-google-setup-module.scss`:
   * Add a new block targeting `.googlesitekit-setup-cta-banner__svg-wrapper--sign-in-with-google-setup-cta > svg`.
   * Set the max height like so: `max-height: 274px`.
    *Note: This prevents the SVG growing to fill the ever increasing width of it's wrapper div which causes the height of the banner to continue to increase as the page is resized.*
   * Set `display: block` and `justify-self: center;`
    *Note: This applies to [tablet sizes, to better match designs](https://www.figma.com/design/h9yGR15Pg2DUtgERW4AFAv/Sign-in-with-Google?node-id=112-2849&node-type=frame&t=chpVmHwHvFdgBfhu-0), making sure the reduced size SVG is aligned center in the banner.*

### Test Coverage

* Update VRT images if required. No additional test coverage required.

## QA Brief

* Follow the steps from `Steps to reproduce` section
* Verify that graphic is not increasing in height and fitting within the banner height

## Changelog entry

* N/A

**Comment by benbowler** [comment]
This will also fix the gap at the bottom of the SVG which is not in the designs but currently appears in the implemented banner.

**Comment by eugene-manuilov** [comment]
IB ✔

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The Sign in with Google CTA notification does not grow in height as the viewport it's being displayed, e.g. 1800px or wider) 
- The notification is sized to fit all text; the image on the right can be cut off by the bounds of the notification. 
- Tested with various viewports to ensure the changes haven't affected mobile, tablet, desktop etc. 

<details>
 <summary>Screenshots</summary>

![Image](https://github.com/user-attachments/assets/7fc67427-e1c7-4328-a930-c673eee81cd0)
![Image](https://github.com/user-attachments/assets/6e9c49fe-7083-4b25-8a0d-58b674232bf3)
![Image](https://github.com/user-attachments/assets/b056f80f-336e-4229-8ed6-877263d25de3)
![Image](https://github.com/user-attachments/assets/b8c654dd-df5d-44e0-9558-43e5876ca63d)
![Image](https://github.com/user-attachments/assets/87f1c444-8f0c-4758-8e60-6455b9a6c6c9)
![Image](https://github.com/user-attachments/assets/c83dd82e-f832-4b14-bcc2-eb37cc8a66e5)

</details>
