### ISSUE TITLE
Update Default Value of `isEnabled` Setting to `false` for First-Party Mode

### ISSUE THREAD

**Issue by hussain-t** [google/site-kit-wp#9828]
## Feature Description

Currently, the default value for the `isEnabled` setting of First-Party Mode is set to `null`. When toggling the switch for the first time, if the user turns it "on" and "off" again, the submit CTA text in the Analytics and Ads settings forms remain as "Confirm changes" instead of reverting back to "Save" due to the change being tracked from `null` to `false'.

To resolve this issue and improve the user experience, we need to update the default value of the `isEnabled` setting to `false`.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The default value for the `isEnabled` setting in First-Party Mode should be updated from `null` to `false`.
* When toggling the First-Party Mode switch for the first time in the Analytics and Ads settings forms:
    * If the user toggles the switch "on" and "off" again, the submit CTA text should revert back to "Save" instead of remaining as "Confirm changes".
* This change should be applied consistently across both the Analytics and Ads settings forms.
* **Note:** The First-Party Mode toggle switch component is being integrated into Analytics and Ads settings forms in #9654 and #9655, respectively.

## Implementation Brief

In `includes/Core/Tags/First_Party_Mode/First_Party_Mode_Settings.php`:

* Locate the `First_Party_Mode_Settings::get_default` method.
* Update the default value for the `isEnabled` setting from `null` to `false`.

In `assets/js/googlesitekit/datastore/site/first-party-mode.js`:

* Review and update JSDoc `@return` directives in selectors to reflect the above change.

### Test Coverage

* Update the `First_Party_Mode_SettingsTest` PHP unit test to assert that the default value for the `isEnabled` setting is `false`.
* Fix any failing tests related to the change in the default value.

## QA Brief

* There are no user-facing changes introduced for this update.
* Verify that the default value for the `isEnabled` setting in First-Party Mode is updated to `false`. This can be done during the code review process.
* Perform a smoke test to ensure that all First-Party Mode functionality continues to work as expected, based on the feature's current implementation.

## Changelog entry

* Update the default value of the First-party mode `isEnabled` setting to `false`.

**Comment by techanvil** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- Performed a smoke test to ensure that all First-Party Mode functionality continues to work as expected.
  - Set up the feature via the CTA banner, made sure that the Ads and Analytics module settings reflected that the FPM is enabled. 
  - Checked the source code to make sure measurement.php is appearing in the code when the feature is enabled. 
  - Checked the source code to make sure googletag is appearing in the code when the feature is disabled. 
  - Checked to make sure that the feature can be enabled and disabled within the settings
  - Checked Google Analytics to make sure that visits are getting tracked when FPM is enabled and disabled. 

<details>
 <summary>Screenshots</summary>

![Image](https://github.com/user-attachments/assets/5785e542-05e8-4ba9-bb7f-03ad029f61fc)
![Image](https://github.com/user-attachments/assets/c01b9a17-672c-41fc-a470-042f00dd53eb)
![Image](https://github.com/user-attachments/assets/cf8f86ad-c61e-4054-922a-de5ba771422f)
![Image](https://github.com/user-attachments/assets/f7156976-0ad8-4dcd-a83c-695514fe70a5)

</details>
