### ISSUE TITLE
Update "improve your measurement" section mobile design to match Figma

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#9830]
## Feature Description

We now have a mobile design in [Figma](https://www.figma.com/design/udlPW35VZ0EDnSbRxYOGMj/First-party-mode?node-id=973-1894&node-type=frame&t=kuXCQ5wAqi1S19xW-0) for the **improve your measurement** section. The current implementation should be updated to adhere to this design.

![Image](https://github.com/user-attachments/assets/9d43dadd-958f-4c8a-86d2-9e8ed0ee0454)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The **improve your measurement** section on the Analytics settings edit screen should be updated to follow the mobile [Figma design](https://www.figma.com/design/udlPW35VZ0EDnSbRxYOGMj/First-party-mode?node-id=973-1894&node-type=frame&t=kuXCQ5wAqi1S19xW-0).
* The **improve your measurement** section on the Ads settings edit screen should also be updated to follow the principles of the above design.

## Implementation Brief

- [ ]  Update the `ConversionTrackingToggle`, `FirstPartyModeToggle` and `SettingsGroup` styling to match the Figma design.
  - Finish and merge this [PR](https://github.com/google/site-kit-wp/pull/9832/files?w=1).

### Test Coverage

* Fix any failing tests.

## QA Brief

* View the Ads and Analytics settings edit panels, confirm the new layout matches the designs on all viewports and that the settings still remain functional.

## Changelog entry

* Fix the "improve your measurement" section's layout in mobile viewports.

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by techanvil** [comment]
Hi @benbowler, please can you add a QAB for this one?

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The improve your measurement section on the Analytics settings edit screen is updated to follow the mobile [Figma design](https://www.figma.com/design/udlPW35VZ0EDnSbRxYOGMj/First-party-mode?node-id=973-1894&node-type=frame&t=kuXCQ5wAqi1S19xW-0).
- The improve your measurement section on the Ads settings edit screen is also updated to follow the principles of the above design.
- Completed checked on various mobile, tablet and desktop viewports to ensure no styling issues. 

<details>
 <summary>Screenshots</summary>

![Image](https://github.com/user-attachments/assets/cccfa5ac-9fdc-4608-878a-6f21c5919933)
![Image](https://github.com/user-attachments/assets/293f6ce6-129b-40fa-8f0b-7947942f2c1b)
![Image](https://github.com/user-attachments/assets/5da7c078-1057-4394-9399-c7156955df6d)
![Image](https://github.com/user-attachments/assets/dcedbc89-ac9b-4fc3-ab31-1f211bc2f5f8)
![Image](https://github.com/user-attachments/assets/808dd623-6935-4eac-9ef2-e0da27249bc2)

</details>
