### ISSUE TITLE
Standardize the usage of module slugs across the codebase

### ISSUE THREAD

**Issue by zutigrm** [google/site-kit-wp#9845]
## Feature Description

The current codebase have inconsistencies in how module slugs are used:
* Some modules use a constant (e.g., `MODULES_READER_REVENUE_MANAGER`) for defining their module slug.
* Other modules directly use hardcoded strings (e.g., 'analytics-4', 'ads', etc).

We should define a consistent approach for module slugs, either using the constants, or continue using the hardcoded strings. Either convert other modules to switch to using the constants, or replace the existing usage of constant in RRM module with hardcoded strings.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* [ ] 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
We already have an issue for this 🙂 Closing in favor of https://github.com/google/site-kit-wp/issues/3417
