### ISSUE TITLE
Send surveys trigger request when the SiwG CTA is displayed

### ISSUE THREAD

**Issue by eugene-manuilov** [google/site-kit-wp#9853]
## Feature Description

We need to send the surveys trigger request using the `view_siwg_setup_cta` trigger ID when the `SignInWithGoogleSetupCTABanner` notification is displayed to correctly identify users that activated but not connected the module.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When the SiwG setup CTA is shown, a request to trigger surveys is sent with the `view_siwg_setup_cta` trigger ID.

## Implementation Brief

* [ ] In `assets/js/modules/sign-in-with-google/components/dashboard/SignInWithGoogleSetupCTABanner.js`:
  * Add the `useMount` hook that dispatches the `triggerSurvey` action from the `core/users` datastore using `view_siwg_setup_cta` as parameter.
* Merge #9852

### Test Coverage

* N/A

## QA Brief

* Enable the SiwG feature flag for your site and activate the SiwG module.
* Go to the dashboard and ensure that you see the setup CTA notofication.
* Verify that a request trigger surveys is sent.

## Changelog entry

* N/A

**Comment by kelvinballoo** [comment]
### QA Update ✅ 

I can confirm that when the SiwG setup CTA is shown, a request to trigger surveys is sent with the view_siwg_setup_cta trigger ID.

Video attached for reference.

<Details>

https://github.com/user-attachments/assets/6cbe6cc3-ab6d-422d-8882-bd025f15b8a8

</Details>
