### ISSUE TITLE
Update `healthcheck` Method to Support First-Party Mode Filters for Tester Plugin Integration

### ISSUE THREAD

**Issue by hussain-t** [google/site-kit-wp#9855]
## Feature Description

Update the `healthcheck` method in the `First_Party_Mode` class to support overrides for the health check logic. This enhancement will enable seamless integration with the Site Kit Tester Plugin, allowing developers and testers to simulate various server configurations and validate the behavior of the First-party mode feature.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `healthcheck` method in the `First_Party_Mode` class should support dynamic overrides for FPFE and proxy script access checks.
* The overrides should be implemented using filter hooks to allow testers to simulate different server configurations.
* The default health check logic should remain intact and execute if no overrides are set.

## Implementation Brief

In `includes/Core/Tags/First_Party_Mode/First_Party_Mode.php`:

* [ ] Update the `First_Party_Mode::healthcheck` method to allow dynamic overrides for:
    * FPFE health check result.
	* Proxy script access check result.
* [ ] Implement the following filter hooks to support the overrides:
    * `googlesitekit_is_fpm_healthy`
    * `googlesitekit_is_fpm_script_access_enabled`
* [ ] Add the filter hooks to the respective health check conditions.
* [ ] Finish and merge this [PR](https://github.com/google/site-kit-wp/pull/9857).

### Test Coverage

* No new tests are required for this change.

## QA Brief

- Set up Site Kit with the `firstPartyMode` feature flag enabled.
- Run the following snippet in the JS console. Verify that `isFPMHealthy` and `isScriptAccessEnabled` are `true` in the returned `response`:
```js
await googlesitekit.data.dispatch( "core/site" ).fetchGetFPMServerRequirementStatus()
```
- Create a PHP file in `mu-plugins` with the following content:
```php
<?php

add_filter( 'googlesitekit_is_fpm_healthy', '__return_false' );
add_filter( 'googlesitekit_is_fpm_script_access_enabled', '__return_false' );
```
- Run the JS snippet again. This time, the `isFPMHealthy` and `isScriptAccessEnabled` properties should be `false`.

## Changelog entry

*

**Comment by hussain-t** [comment]
Sure. Go for it, @techanvil 👍

**Comment by techanvil** [comment]
Thanks @hussain-t. I've updated the IB and the PR accordingly.
