### ISSUE TITLE
Dismiss new events banner for manual KMW users after all metrics have been selected

### ISSUE THREAD

**Issue by zutigrm** [google/site-kit-wp#9870]
## Feature Description

As reported by QA in #9372, we should implement the logic that automatically dismisses the new events callout for manual KMW users.

Based on the [discussion with Sigal](https://fueled10up.slack.com/archives/C01CA828ZPZ/p1733932542312609?thread_ts=1733836066.182389&cid=C01CA828ZPZ), we will dismiss the notification once selection panel is opened
 
---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When inline callout for new events is present, with CTA's `View metrics` or `Select metrics`, clicking on `Change metrics` and opening the selection panel should dismiss the notification
* When said callout is present, with CTA `Add metrics` for tailored metrics users, it should be dismissed only if the save button is clicked in selection panel marking the transition to the manual selection
* Adapt existing showing/dismissing logic with changes implemented in #9897

## Implementation Brief

* [ ] In `assets/js/components/KeyMetrics/ConversionReportingNotificationCTAWidget.js`
  * [ ] Add `dismissCallout` callback
    * It should accept one argument - `eventType`
    *  Dispatch `saveConversionReportingSettings` action from `CORE_USER` store implemented in #9897 , checking if `calloutType` is `lostEvents` use `lostEventsCalloutDismissedAt` setting key, otherwise use `newEventsCalloutDismissedAt` setting key. Use current timestamp as a value, eq `Math.round( Date.now() / 1000 )`
  * [ ] Include new `useEffect` hook, and check if `KEY_METRICS_SELECTION_PANEL_OPENED_KEY` key from `CORE_UI` store, is `true`, then
    * If `shouldShowCalloutForNewEvents` or `shouldShowCalloutForUserPickedMetrics` is `true`
    * OR If `isSavingConversionReportingSettings` selector from `CORE_USER` store and `shouldShowInitialCalloutForTailoredMetrics` are both `true`
      * Invoke `dismissCallout` callback
    * If `haveLostConversionEvents` is `true` dispatch `dismissCallout` callback but pass `lostEvents` as argument
  * [ ] Within existing `handleSelectMetricsClick` callback
    * Remove dismiss action https://github.com/google/site-kit-wp/blob/abbb74ff21f98a8779fbab0eeb9a16279a122bc4/assets/js/components/KeyMetrics/ConversionReportingNotificationCTAWidget.js#L139-L145 since it will be handled in the `useEffect` above, no need to make duplicate call   
  * [ ] Retrieve `getNewConversionEventsLastUpdateAt` and `getLostConversionEventsLastUpdateAt` settings from analytics store, and their values as arguments in the respective selectors from `CORE_USER` datastore - `haveNewConversionEventsAfterDismiss` and `haveLostConversionEventsAfterDismiss`
    *  Update conditional checks for `shouldShowInitialCalloutForTailoredMetrics`, `shouldShowCalloutForUserPickedMetrics` and `shouldShowCalloutForNewEvents` to also account if `haveNewConversionEventsAfterDismiss` is `true`, so they are shown only if they are not previously dismissed, or there was new/lost events change more recently than the last dismissal happend.
      * With `shouldShowInitialCalloutForTailoredMetrics` being an exception to also check if current user ID matches the user who completed KMW setup, you can see this check in `assets/js/components/KeyMetrics/SetupCompletedSurveyTrigger.js`.
        * We want to show `Add metrics` CTA variation only to the user who originally setup the tailored metrics
* [ ] Remove `dismissNewConversionReportingEvents` and `dismissLostConversionReportingEvents` actions and their REST endpoints counterparts in `includes/Modules/Analytics_4.php`

### Test Coverage

* In `assets/js/components/KeyMetrics/ConversionReportingNotificationCTAWidget.test.js` add test cases verifying that when callout is showing and `KEY_METRICS_SELECTION_PANEL_OPENED_KEY`, or `isSavingConversionReportingSettings` is happening (by dispatching `saveConversionReportingSettings`), callout will be dismissed
  * Replace the check that existing dismiss endpoint is fetched on dismiss with the new endpoint for conversion reporting settings
  * Existing tests for rendering/not rendering will need `conversionReportingSettings` to be provided. You can use `0` for both sync properties `.receiveGetConversionReportingSettings({newEventsCalloutDismissedAt: 0, lostEventsCalloutDismissedAt: 0})`, which will satisfy the check for showing, and add new test to confirm that it is not rendering when one of the dismissals is more recent then the last sync (`newConversionEventsLastSyncAt` and `lostConversionEventsLastSyncAt` GA4 settings happend earlier then `*CalloutDismissedAt` values).
* Remove `dismissNewConversionReportingEvents` and `dismissLostConversionReportingEvents` related tests

## QA Brief

* 

## Changelog entry

*

**Comment by eugene-manuilov** [comment]
IB ✔

**Comment by 10upsimon** [comment]
@zutigrm IB ✅ Moving to EB

**Comment by zutigrm** [comment]
Closing it as this logic is implemented as part of #9897
