### ISSUE TITLE
Console error when viewing Analytics settings; FPM settings requested without feature flag

### ISSUE THREAD

**Issue by zutigrm** [google/site-kit-wp#9875]
## Bug Description

A console error appears in Site Kit Settings > Analytics (View) when the First-Party Mode feature flag is not enabled.

## Steps to reproduce

Ensure the `firstPartyMode` feature flag is NOT enabled.

1. Setup Site Kit with Analytics module
2. Go to the Site Kit settings
3. Expand the settings for Analytics module
4. Check the console
5. See error

## Screenshots

<img width="1412" alt="Image" src="https://github.com/user-attachments/assets/cbc0f45f-28c5-4e6a-9b65-5bd14fec76d8" />

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* No console errors should appear in Site Kit Settings > Analytics when the First-Party Mode feature flag is not enabled.

## Implementation Brief

* [ ] Add a feature flag check to ensure the `fpm-settings` request is not made when the feature flag is disabled.
* [ ] Merge #9893

### Test Coverage

* No new tests needed.

## QA Brief

* Follow the steps-to-reproduce.
* There should not be a console error in the browser console.

## Changelog entry

* N/A

**Comment by aaemnnosttv** [comment]
IB ✅ 

Moving to CR

**Comment by wpdarren** [comment]
### QA Update: ✅

**Verified:**

No console errors appear in Site Kit Settings > Analytics when the First-Party Mode feature flag is not enabled.

![Image](https://github.com/user-attachments/assets/af9ce3c6-5e11-48e1-b3e4-0a1c93e16336)
