### ISSUE TITLE
Update Site Kit version identification in Google Client requests

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#989]
## Feature Description

Currently Site Kit passes the plugin version along in the query string for all proxy setup URLs. This is unnecessary now that feature support is explicitly declared in the `supports` parameter, which is preferred over inferring support from the version on the proxy. However, the Site Kit version is still valuable information statistically and should be kept.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Site Kit version should not be sent as a query parameter in any proxy URL.
* Platform and version should be sent in the user agent.

## Implementation Brief

* Remove `version` from `OAuth_Client::get_proxy_setup_url`
* Add the Site Kit version to the [user-agent header](https://github.com/googleapis/google-api-php-client/blob/2a652bfaab250ea7b6dfae46a917f2a6d7997f6f/src/Google/Client.php#L808-L816) sent with all Google Client requests by setting the Application Name  
    ```diff
    diff --git a/includes/Core/Authentication/Clients/OAuth_Client.php b/includes/Core/Authentication/Clients/OAuth_Client.php
    index 0ffed71d..4eafdef9 100644
    --- a/includes/Core/Authentication/Clients/OAuth_Client.php
    +++ b/includes/Core/Authentication/Clients/OAuth_Client.php
    @@ -189,6 +189,9 @@ final class OAuth_Client {
            } else {
                $this->google_client = new Google_Client();
            }
    +       $this->google_client->setApplicationName(
    +           sprintf( 'wordpress/google-site-kit/%s', GOOGLESITEKIT_VERSION )
    +       );
     
            // Return unconfigured client if credentials not yet set.
            $client_credentials = $this->get_client_credentials();

    ```

> Application name using lowercase for consistency with the [default user agent suffix](https://github.com/googleapis/google-api-php-client/blob/2a652bfaab250ea7b6dfae46a917f2a6d7997f6f/src/Google/Client.php#L42)

## Changelog entry

* Include platform and plugin version information in API client requests.

**Comment by felixarntz** [comment]
@aaemnnosttv The user agent should also include a platform-specific identifier: How about `WordPress/GoogleSiteKit/$version`?

**Comment by aaemnnosttv** [comment]
Sure that sounds good to me, IB updated!

**Comment by felixarntz** [comment]
IB ✅

**Comment by aaemnnosttv** [comment]
@felixarntz I'm wondering if maybe we should keep the `version` parameter in the setup URLs for statistics/support. The added configuration only affects API requests by the Google Client, but if users have a problem during the initial set up, they may never get to that point. Basically, since the proxy set up is a critical first step, it might be worth keeping that parameter.

Thoughts?

**Comment by felixarntz** [comment]
@aaemnnosttv I noticed that a few days ago too, but I generally think it's cleaner to remove it, as we want to know how the version distribution is overall. It would be useful for support as well, but I think in that case it's still rather trivial to ask the reporter of an issue which version they're using.

**Comment by cole10up** [comment]
I ran through a set of regression around proxy setup, initial install, reinstall, reset. Everything functions properly. Version number exists and is passed through.

![image](https://user-images.githubusercontent.com/57115907/71954966-c9968c00-319b-11ea-85c2-7ccd0db6cd0f.png)

Passed QA ✅
