### ISSUE TITLE
Console error when viewing Ads settings; FPM settings requested without feature flag

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#9895]
## Bug Description

A console error appears in Site Kit Settings > Ads (view) when the First-Party Mode feature flag is not enabled.

![Image](https://github.com/user-attachments/assets/4799a274-fd36-47bc-bae7-a7efed5c0657)

## Steps to reproduce

1. Setup Site Kit with Ads module
2. Go to the Site Kit settings
3. Expand the settings for Ads module
4. Check the console and see error

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* No console errors should appear in Site Kit Settings > Ads when the First-Party Mode feature flag is not enabled.

## Implementation Brief

* [ ] Add a feature flag check to ensure the `fpm-settings` request is not made when the feature flag is disabled.
* [ ] Merge https://github.com/google/site-kit-wp/pull/9896

### Test Coverage

* No changes necessary

## QA Brief

* Follow the steps-to-reproduce.
* There should not be a console error in the browser console.

## Changelog entry

* N/A

**Comment by kelvinballoo** [comment]
### QA Update ✅ 

**Verified**:
No console errors appear in Site Kit Settings > Ads when the First-Party Mode feature flag is not enabled.

<Details>

<img width="1156" alt="Image" src="https://github.com/user-attachments/assets/f77d145b-965a-43dd-a6ce-906d4757bd17" />

</Details>
