### ISSUE TITLE
Optimize / Tag Manager setup. Add notice that Analytics module activation is required

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#99]
## Feature Description

Rather than just greying out the Optimize & Tag Manager services (when Analytics is not yet connected) add a notice to the "Connect more services" tab to make users aware that Analytics must first be added in order to proceed with Optimize or Tag Manager setup. 

## Proposed solution

Add a small notice below the Tag Manager and Optimize connect services options. Something along the lines of "You must have the Analytics module connected before proceeding" would be suitable.  

![6oybJ18Oa3p](https://user-images.githubusercontent.com/41326532/60499499-7d303800-9cb0-11e9-9967-7dc8f471e907.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Changelog entry

* 

## Acceptance criteria

*

**Comment by felixarntz** [comment]
This has been fixed by now during the refactoring, it's now clarified.
