### ISSUE TITLE
Add a toggle to enable/disable the Site Kit admin bar feature

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#990]
## Feature Description

As per [this](https://wordpress.org/support/topic/site-kit-admin-bar/#post-12251754) WordPress support topic some users may want to remove the Site Kit admin bar feature. A toggle to enable the Site Kit admin bar feature may be something to consider. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new Site Kit-wide setting `googlesitekit_admin_bar_menu_enabled` should be registered, which is a boolean with default value of `true`.
* If the setting is `false`, the admin bar menu of Site Kit should not be displayed (under any circumstance, so this should be the first check).
* In the _Admin Settings_ tab on the Site Kit settings page, a new box should be displayed on the right side of the existing _Plugin Status_ box, which should be shrinked to half width on desktop (i.e. the new box should also be half width on desktop).
    * The new box should look similar to the existing _Tracking_ box.
    * It should have the title _Plugin Settings_.
    * It should for now only contain a single toggle _Display relevant page stats in the Admin bar_, which controls the new setting.

## Implementation Brief
* Using `assets/js/components/settings/SettingsAdmin.js`,
    * Update the markup for the `Plugin Status` section to be half width replacing the html markup by the `Grid`, `Row` and `Cell` components.
    * On small screens, the `Plugin Status` should be full width, and then half width on tablet and up.
    * Add another cell adjacent to the `Plugin Status` one, 100% wide on small screens and 50% on tablet and up. The cell will host the `SettingsPlugin` component. More below.
* Create `includes/Core/Admin_Bar/Admin_Bar_Settings.php` which contains the `Admin_Bar_Settings` class that extends the `Setting` class and registers the `googlesitekit_admin_bar_menu_enabled` option name. Default value `true`.
    * Code example: `includes/Core/Authentication/Owner_ID.php`
* Using `includes/Core/Admin_Bar/Admin_Bar.php`,
    * In the `register` method,
        * create a new object from `Admin_Bar_Settings` which will register the new setting.
        * using the `googlesitekit_rest_routes` action, add a filter to add the following REST route `core/site/data/admin_bar`.
            * Code example: `includes/Core/Util/Tracking.php`.
            * In the `WP_REST_Server::CREATABLE` callback, the value for the setting should be toggled.
    * In the `add_menu_button` private method, check if the setting for the admin bar is true. If this is not the case, then return early.
* Using `assets/js/googlesitekit/datastore/site`,
    * Create new file `settings.js` which houses a `createFetchStore` store similar to `assets/js/googlesitekit/datastore/site/connection.js`.
        * It should contain only 1 selector for now, `getShowAdminBar`.
        * It should contain only 1 action for now, `setShowAdminBar`
        * Appropriate resolvers should be added.
* Create `assets/js/components/settings/SettingsPlugin.js` which exports the `SettingsPlugin` functional component. The latter should do the following:
    * Query the `core/site` data store to check whether the admin bar is visible or not via the `getShowAdminBar` selector.
    * Render a title styled similarly as the `Tracking` section, where there is a grey border bottom to the section header.
    * Render a single toggle for now, with the label as per the AC. The state of the toggle, i.e whether it's checked or unchecked should be based on the value of the `getShowAdminBar` selector.
    * Upon checkbox change, the `setShowAdminBar` action should be dispatched to update the setting.
* Update `assets/js/components/settings/SettingsAdmin.js`, to include `SettingsPlugin` component in the newly created cell next to the `Plugin Status` section.

### Test Coverage
* Create test for the new `settings` data store partial.

### Visual Regression Changes
* N/A

## QA Brief

* Go to a post on the frontend and verify that you see the admin bar integration.
* Go to the admin settings and turn off the admin bar.
* Go back to the post page and verify that the admin bar integration is not shown anymore.
* Go back to the admin settings and turn on the admin bar.
* Go back to the post page and make sure that now you see the admin bar again.

## Changelog entry

* Add a toggle to enable/disable the Site Kit admin bar feature.

**Comment by gholm** [comment]
Any news on this one, please? We work on a number of sites with rather busy admin bars and removing some of the items would definitely help.

**Comment by marrrmarrr** [comment]
Let's scope the amount of work on this.

**Comment by marrrmarrr** [comment]
@felixarntz We could handle this as a one-off (as I described in the ACs), but we can also start thinking about the upcoming settings (e.g. the custom modules) and create a section for them, even if it only has one thing now (Admin bar). 
What do you think?

**Comment by tofumatt** [comment]
IB ✅

**Comment by Overbord** [comment]
+1

**Comment by tofumatt** [comment]
(This just needs a QA Brief, then it can be merged 👍🏻 )

**Comment by wpdarren** [comment]
QA Update: ⚠️ 

@eugene-manuilov this is passing the tests in QAB, but an observation on small screen sizes like mobiles. 

The Site Kit admin bar feature does not appear on mobile devices, but the setting is still appears in the settings.  I am wondering if it would cause confusion with the users, so, it might be a thought to hide the setting on smaller screens. [Screenshot](https://user-images.githubusercontent.com/73545194/127669907-039522ae-5ded-40b4-9f84-842049f41d6e.png)

Interested in your thoughts.

**Comment by eugene-manuilov** [comment]
@wpdarren the admin bar feature should appear on mobile devices. Can you make a screencast to show me how it works on small screen sizes on your end?

**Comment by wpdarren** [comment]
@eugene-manuilov you are right! I initially tested this on Chrome console using the device toolbar, and it didn't appear.  When I tested on Browserstack and my own phone, I can see that the admin feature appears and disappears based on the settings. 

### QA Update: Pass ✅ 

**Verified:**

- Verified that you see the admin bar integration. The setting is enabled by default 

![image](https://user-images.githubusercontent.com/73545194/127670520-7add51ad-d214-4d81-a5d3-76b3773744c4.png)

- When the setting is disabled, the admin bar integration is not shown anymore.

![image](https://user-images.githubusercontent.com/73545194/127670644-ef748b59-3757-41ad-b2d6-a63a4aec2afc.png)

- When the setting is enabled, you see the admin bar again.

![image](https://user-images.githubusercontent.com/73545194/127670749-65f264b8-ea1b-4263-b4ba-f10abad40aab.png)

**Comment by abdullah1908** [comment]
IMO a message would be a good addition while we disable/enable settings e.g. like **Settings Saved** or **Admin Bar enabled**.  Right now there is not alert/message.
https://www.loom.com/share/ebd59fe12ec34631be209721f25f8915

**Comment by wpdarren** [comment]
@abdullah1908 that is the same behaviour for the other checkboxes, where no alert appears. Personally, I think it's fine as it is.  If you feel this would be a good UX improvement you can create a ticket and the engineers will discuss it.

**Comment by abdullah1908** [comment]
Thanks @wpdarren I'll put my suggestions by submitting new issue.
