### ISSUE TITLE
PHP_FPM_REPLACE_PATH not replaced causing 404 for requests

### ISSUE THREAD

**Issue by benbowler** [google/site-kit-wp#9903]
## Bug Description

When loading a page with FPM enabled, there are 2x 404 console errors related to tracking. It appears as though the value of `FPS_PATH` constant (which is `PHP_FPM_REPLACE_PATH` by default) is not being replaced in certain cases, here are the GET and POST endpoints in question:

`https://simon-d-fpm-bug-bash.instawp.xyz/PHP_FPM_REPLACE_PATH/g/ccm/collect?en=page_view&dr=simon-d-fpm-bug-bash.instawp.xyz&dl=https%3A%2F%2Fsimon-d-fpm-bug-bash.instawp.xyz%2F&scrsrc=simon-d-fpm-bug-bash.instawp.xyz&frm=0&rnd=881594217.1734338296&dt=heavenly-goosander-92e4c9.instawp.xyz&auid=785249758.1734337691&navt=r&npa=0&did=dZTNiMT&gdid=dZTNiMT&gtm=45892e4cc1za204zb9136159890&gcd=13l3l3l3l1l1&dma=0&tag_exp=101925629~102067555~102067808~102081485~102198178&tft=1734338295774&tfd=6041&apve=1`

`https://simon-d-fpm-bug-bash.instawp.xyz/PHP_FPM_REPLACE_PATH/pagead/viewthroughconversion/12345/?random=1734338295771&cv=11&fst=1734338295771&bg=ffffff&guid=ON&async=1&gtm=45892e4cc1za204zb9136159890&gcd=13l3l3l3l1l1&dma=0&tag_exp=101925629~102067555~102067808~102081485~102198178&u_w=1512&u_h=982&url=https%3A%2F%2Fsimon-d-fpm-bug-bash.instawp.xyz%2F&ref=https%3A%2F%2Fsimon-d-fpm-bug-bash.instawp.xyz%2Fwp-admin%2Fadmin.php%3Fpage%3Dgooglesitekit-dashboard&hn=www.googleadservices.com&frm=0&tiba=heavenly-goosander-92e4c9.instawp.xyz&did=dZTNiMT&gdid=dZTNiMT&npa=0&auid=785249758.1734337691&uaa=arm&uab=64&uafvl=Google%2520Chrome%3B131.0.6778.140%7CChromium%3B131.0.6778.140%7CNot_A%2520Brand%3B24.0.0.0&uamb=0&uam=&uap=macOS&uapv=13.0.0&uaw=0&fledge=1&data=event%3Dgtag.config&rfmt=3&fmt=4`

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* [ ] 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by hussain-t** [comment]
Hi @benbowler, please take a look at this [comment](https://github.com/google/site-kit-wp/issues/9901#issuecomment-2548900681) and close this one.

**Comment by benbowler** [comment]
Thanks @hussain-t, closing.

**Comment by hussain-t** [comment]
@benbowler, we should close it as not planned. Thanks!
