### ISSUE TITLE
Implement activation notice as a React component

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#991]
While the plugin activation notice started as static content and therefore is implemented in PHP, it has over time grown into a more and more Frankenstein-like assembly of various tiny JS-based features. It started with us needing to include a `script` tag in the notification content (which is also related to https://github.com/google/site-kit-wp/pull/900#issuecomment-564530169), but since the introduction of the new proxy it now almost entirely replicates the plugin setup screen in `googlesitekit-splash`.

With #933 as a high priority, the amount of logic that we'd need to re-implement in React vs non-React would grow completely out of proportion. Let's therefore rebuild the existing functionality as-is as a React component with its own JavaScript asset.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The plugin activation notice should be rendered as a React component that handles all of its dynamic functionality.
* The script registered and enqueued in PHP should be `googlesitekit-activation-notice.js`.
* In PHP, only a scaffolded success notice with a loading indicator (e.g. bar or spinner) should be rendered, that the React component replaces once loaded.
* The content and functionality of the activation notice (copy, different buttons, links, tracking checkbox) should remain exactly as it is today.

## Implementation Brief

* Create a new top-level app, available in `assets/js/googlesitekit-activation.js`, similar to `assets/js/googlesitekit-dashboard.js`, that loads a new React app with setup components similar to `DashboardSplashApp`. The component would be new, but share similarities to the setup flow in the `DashboardSplashApp` component.
* Some refactoring of the child components inside `DashboardSplashApp` may need to be done so both the new `ActivationApp` can share them. It's likely the setup code should be refactored into its own component that could be used across the app.
* Add this new React script for the "Activation app", available via `googlesitekit_activation`/`googlesitekit-activation.js` (add to https://github.com/google/site-kit-wp/blob/411fcd008334eafa286990f6523a75cc73816d2b/includes/Core/Assets/Assets.php#L338-L339). Let's call it `ActivationApp`.
* Enqueue the `googlesitekit_activation` script and `'googlesitekit_modules'` to https://github.com/google/site-kit-wp/blob/411fcd008334eafa286990f6523a75cc73816d2b/includes/Core/Util/Activation.php#L123-L133
* Remove all old PHP+JS code (https://github.com/google/site-kit-wp/blob/411fcd008334eafa286990f6523a75cc73816d2b/includes/Core/Util/Activation.php#L143) and replace with a `div` used to insert the `assets/js/googlesitekit-activation.js` code, eg. `<div id="js-googlesitekit-activation"></div>`

## Changelog entry

* Reduce maintenance by implementing dynamic activation notice in React.

**Comment by felixarntz** [comment]
@tofumatt 
> Some refactoring of `DashboardSplashApp` may need to be done as it determines which setup code path to load but also displays the entire setup app. It's likely the setup code should be refactored into its own component that could be used across the app.

I'd feel more comfortable creating a new `ActivationNoticeApp` or similar instead. Specific components inside `DashboardSplashApp` we should totally reuse, and we should also consider outsourcing certain pieces of `DashboardSplashApp` markup or functionality in separate child-components if needed. But I'd prefer not to intertwine the actual entry components.

> replace with a `div` used to insert the `assets/js/googlesitekit-activation.js` code, eg. `<div id="js-googlesitekit-activation"></div>`

See the ACs, it would be great if this could have a loading spinner that makes it show immediately before React logic is loaded, to prevent it from "suddenly" popping up.

**Comment by tofumatt** [comment]
Sounds good! I think that was largely what I meant, but I clarified the IB so it's clearer that I meant we should create a new setup component that can be shared between the components. That component should essentially contain the "Start setup" button and the "opt-in" checkbox for analytics, so it wouldn't be complicated.

**Comment by felixarntz** [comment]
IB ✅

**Comment by tofumatt** [comment]
QA'd this with a new site, reactivating a disabled plugin, and using the filter added for debugging/development. All worked as expected.

QA ✅
