### ISSUE TITLE
Unnecessary exception handling in health check code

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#9910]
## Bug Description

From the FPM bug bash.  [Asana ticket can be found here](https://app.asana.com/0/1208913171972144/1208990312120923/f). 

In `First_Party_Mode::is_endpoint_healthy()` , we are wrapping the call to `file_get_contents()` in a try / catch, but this appears to be unnecessary as `file_get_contents()` should not throw an exception.

We can remove this redundant exception handling.

![Image](https://github.com/user-attachments/assets/0f3184d3-3fd7-4494-ad74-230bf3622395)

See this [Slack thread](https://fueled10up.slack.com/archives/C077DB69US2/p1734449398049979) for a bit of extra context.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* [ ] 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by techanvil** [comment]
We should be able to close this issue, as the try/catch will be removed in https://github.com/google/site-kit-wp/pull/9929.

**Comment by techanvil** [comment]
Closing as this has now been addressed as per the above.
