### ISSUE TITLE
Problem with Wordpress Plugin

### ISSUE THREAD

**Issue by carloscortesp** [google/site-kit-wp#992]
## Bug Description

It does not allow to install the plugin because it shows an error: Prohibited
You do not have permission to access this resource.

## Steps to reproduce

When finalizing the process marks that error. I attached screenshot

## Screenshots

https://drive.google.com/open?id=1_r-6AlvQC9flNv6T9iOcg-cSceauJPNx

## Additional Context

 - PHP Version: 
 - Plugin Version [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
@carloscortesp Thanks for reporting. We have moved Site Kit support to the WordPress support forum. You can open a [new support topic](https://wordpress.org/support/plugin/google-site-kit/#new-post) there and we can assist. Please add as much relevant information to your support topic as is needed to assist with your issue.
