### ISSUE TITLE
Ensure stability and interoperability of JS dependencies by using Webpack bundles

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#993]
Site Kit's JS code relies on various 3P dependencies, such as React, some WordPress packages and other packages like `lodash`. Many of those packages are bundled by WordPress core, so our initial approach has been to use these dependencies directly, relying on the scripts, and more specifically the versions registered by it.

Using the WP-registered scripts directly as dependencies used to be the convention, however that only worked because core scripts used to be "always backward-compatible" and only change a little bit. Since Gutenberg the project has been including backward-incompatible changes quite regularly (which isn't necessarily bad and brings lots of benefits, but we need to adapt to it).

Relying on WP core-provided scripts directly is problematic for the following reasons:
* We can never be sure which version of e.g. React or `wp.element` is currently active.
* Modern WordPress JS dependencies include breaking changes regularly.
* We cannot move faster (or slower FWIW) than core, we have to always follow.
* We have to maintain a list of those dependencies in PHP and register them (related: #885, which will become invalid from this).
* We have to "polyfill"-bundle some dependencies which have been in WP only since 5.0, and conditionally register them in PHP with extra code.

All of this easily leads to bugs on certain environments, that we would be able to avoid if we only relied on exact dependency versions specified by us.

Let's use Webpack to actually bundle all necessary dependencies in our individual script files (`googlesitekit-*.js`) so that only these files need to be registered and enqueued. All dependencies should be scoped to our own scripts (e.g. we must not expose `React` or `wp.*` as globals). Potentially we might consider exposing some commonly used dependencies on our own global for future extensions of Site Kit, but that could also be discussed in a follow-up issue.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Site Kit should bundle its JS dependencies internally.
* Only our own JS files should be registered (and enqueued where applicable) in PHP.
* Dependencies in the script files should be scoped and must not be exposed globally.
* For the admin bar menu, only the loader file should be loaded initially (like before), the "heavier" full admin bar menu script should only be loaded from there on request, when the user hovers over the menu.
* No functionality should change. :)

## Implementation Brief

* Stop relying on any globals or injected global context. This means explicitly importing React in all components that use it (eg that use JSX). This point can be discussed but I think it's worthwhile to do.
* Remove all externals from `Assets.php` and `webpack.config.js`, instead bundling them into `sitekit-vendor`.
* Configure libraries like `@wordpress/api-fetch` to use the correct nonce middleware and root URL.
* Any other, as-of-yet-unknown changes to config/initialisation to ensure the code doesn't need en-masse updates (aside from the `import React from 'react';` bit above.

## Changelog entry

* Fully rely on Webpack for third-party dependencies and decouple from WordPress-shipped assets for more stability across all versions.

**Comment by felixarntz** [comment]
@tofumatt Let's discuss the implementation brief in our sync next week. We need to find a solution that does not get overly complex. Specifically, a PR for this could easily blow up, so let's try to find the minimum changes needed for an easy win - i.e. we should do as little actual JS code refactoring as possible.

**Comment by tofumatt** [comment]
Agreed! The plan here should be to make as few (preferably no) changes to most of the codebase but rather to change the Webpack config and PHP `enqueue_asset` calls. Time permitting, I'll have a brief look at this before the call to get a sense of what it would entail. 😄

**Comment by tofumatt** [comment]
Just an update here that adjusting the `apiFetch` calls to use the correct middleware as suggested by @aaemnnosttv doesn't seem to be doing the trick, so there's more investigation needed.

I'm realising that I should move this out of IB and flag work I'm doing as execution, so I've put this in IB Review with the understanding that the technical bits of the IB are to-be-determined. But at least the idea is expressed in the IB: aside from the proposed `import React from 'react';` changes the aim is not to have to change any code outside some initialisation that the WP libraries did.

**Comment by felixarntz** [comment]
IB ✅

**Comment by felixarntz** [comment]
As soon as this is closed, let's follow up on testing #939.

**Comment by cole10up** [comment]
Setting a reminder to followup testing #939 as its still assigned to myself.

**Comment by cole10up** [comment]
**Tested**

Ran a series of regression tests around setting up and tearing down services, configuring and adjusting settings, installing, resetting and uninstalling SK.

![image](https://user-images.githubusercontent.com/57115907/73817652-6438b980-47a0-11ea-9165-7867a975e7a8.png)

Passed QA ✅

@aaemnnosttv - Feel free to run engineering QA

**Comment by aaemnnosttv** [comment]
## ✅ TQA

* After building a release zip, all JS files are either entrypoints or webpack chunks  
    <details>
    <summary>JS Files</summary>

    ```
    google-site-kit/dist/assets/js/ads.js
    google-site-kit/dist/assets/js/chunk-googlesitekit-adminbar-5c25e291ec857fa5331f.js
    google-site-kit/dist/assets/js/chunk-googlesitekit-adminbar~chunk-googlesitekit-setup-wizard~chunk-googlesitekit-setup-wizard-proxy-87d7d1da8b50555acfd1.js
    google-site-kit/dist/assets/js/chunk-googlesitekit-setup-wizard-97bab0e93cfee02a4fb0.js
    google-site-kit/dist/assets/js/chunk-googlesitekit-setup-wizard-proxy-adc28b60cb7e7b1eed79.js
    google-site-kit/dist/assets/js/chunk-googlesitekit-setup-wrapper-abe35518b6bdc2eb12d3.js
    google-site-kit/dist/assets/js/googlesitekit-activation.js
    google-site-kit/dist/assets/js/googlesitekit-admin.js
    google-site-kit/dist/assets/js/googlesitekit-adminbar-loader.js
    google-site-kit/dist/assets/js/googlesitekit-api.js
    google-site-kit/dist/assets/js/googlesitekit-dashboard-details.js
    google-site-kit/dist/assets/js/googlesitekit-dashboard-splash.js
    google-site-kit/dist/assets/js/googlesitekit-dashboard.js
    google-site-kit/dist/assets/js/googlesitekit-data.js
    google-site-kit/dist/assets/js/googlesitekit-module.js
    google-site-kit/dist/assets/js/googlesitekit-settings.js
    google-site-kit/dist/assets/js/googlesitekit-wp-dashboard.js
    google-site-kit/dist/assets/js/vendors~chunk-googlesitekit-adminbar-65de1905d420da62416e.js
    google-site-kit/dist/assets/js/vendors~chunk-googlesitekit-setup-wizard-proxy-4ac729584cc1eb67165d.js
    ```
    </details>
* Chunk filenames are all hashed to ensure the latest data is always fresh in the browser
* Build does not include any test or supporting files for development
* All external assets/polyfills have been removed from `Assets` and webpack config
* JS does not touch globals anymore other than our own data objects (and select Google libraries such as Google Charts)

I noticed that each `scss` file is generating a corresponding `js` file in the root of the `dist` directory. This isn't specific to this issue and the extra files aren't included in the release zip so it isn't a problem, just something to clean up in the future.
