### ISSUE TITLE
Scaffold googlesitekit-data JS package

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#997]
## Feature Description

This should be a simple JS package exposing a Site Kit specific data store registry on a global `googlesitekit.data` (via `wp.data.createRegistry()`).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* There should be a JS file `googlesitekit-data.js` that is registered in PHP as `googlesitekit-data`.
* The script should simply expose an "empty" data store registry `googlesitekit.data`, using `@wordpress/data`.
* The script should not have any internal dependencies (e.g. not rely on `googlesitekit-api` for now) - only the minimum dependencies necessary.

## Implementation Brief

* Create an `assets/js/googlesitekit/data` folder for the new code to reside in. Place code in these files and make sure they can be imported within the project.
* `assets/js/googlesitekit/data` can start by being an empty module that doesn't export anything.
* In `assets/js/googlesitekit-data.js`, import `assets/js/googlesitekit/data` and expose it globally as `googlesitekit.data`. If the `googlesitekit` global isn't available, create an empty object and place `data` inside it as a property.
* Add webpack external for `'assets/]js/googlesitekit/data'` that resolves to `googlesitekit.data`
* Add an entry in `Assets.php` to allow `googlesitekit-data` to be loaded

## Changelog entry

* Introduce `googlesitekit.data` registry for JS datastores.

**Comment by felixarntz** [comment]
IB ✅

**Comment by cole10up** [comment]
**Tested**

Checked latest package and confirmed the following file exists:
![image](https://user-images.githubusercontent.com/57115907/73333516-d51b2700-421e-11ea-8dfc-dcce809d0012.png)

Content:
![image](https://user-images.githubusercontent.com/57115907/73333522-dc423500-421e-11ea-8f4b-8634b2e83b31.png)

Confirmed from a QA perspective.
