### ISSUE TITLE
Scaffold googlesitekit-site package and core/site store

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#999]
## Feature Description

Based on the `googlesitekit.data` store registry from #997, there should be a `core/site` store, registered by a separate JS asset `googlesitekit-site`.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* There should be a JS file `googlesitekit-site.js` that is registered in PHP as `googlesitekit-site`.
* The script should depend on `googlesitekit-data` and `googlesitekit-api`.
* The script should register a `core/site` store on `googlesitekit.data`.
* The store should (for this initial implementation) have the following selectors:
    * `getConnection()`: resolves to the `core/site/data/connection` route and "pass-through" its response
* The store should (for this initial implementation) have the following actions:
    * `reset()`: calls `core/site/data/reset` route

## Implementation Brief

* Create a new file in `assets/js/googlesitekit/site/index.js` that creates a new `'core/site'` store using `'googlesitekit-data'`'s `registerStore` .
* Add an asset entry in `Assets.php` to enqueue the file.
* Expose a `getConnection()` selector that uses a resolver to fetch data from the API
* Expose a `reset()` action that uses fetch to reset site data using the API
* Add jest coverage for these tests, likely requiring some bootstrapping of the jest environment for testing reducers. (This is largely the reason for the "large" size label on this issue; the actual implementation of this reducer is not complex.)

## Changelog entry

* Expose `googlesitekit.data` registry and register initial `core/site` store on it.

**Comment by felixarntz** [comment]
IB ✅ 

To make the API call to receive the connection info, can we use a resolver like [here](https://github.com/WordPress/gutenberg/blob/master/packages/core-data/src/resolvers.js)?

**Comment by tofumatt** [comment]
Yup! That sort of resolver pattern nicely mirrors Gutenberg's approach to stores and should mean the data is cached after the first request, which for data like the connection info is good. (That will be augmented by our own request caching, which for data like `connectionInfo()` can be reasonably aggressive, making these selectors rarely need network requests.

**Comment by aaemnnosttv** [comment]
## QA ✅ 

* [x] There should be a JS file `googlesitekit-site.js` that is registered in PHP as `googlesitekit-site`.  
Changed to `googlesitekit-datastore-site.js` and `googlesitekit-datastore-site`.
* [x] The script should depend on `googlesitekit-data` and `googlesitekit-api`.  
Depends on `googlesitekit-data` which depends on `googlesitekit-api`
* [x] The script should register a `core/site` store on `googlesitekit.data`.
* [x] The store should (for this initial implementation) have the following selectors:
    * `getConnection()`: resolves to the `core/site/data/connection` route and "pass-through" its response
* [x] The store should (for this initial implementation) have the following actions:
    * `reset()`: calls `core/site/data/reset` route
